// Generated by CIRCT firtool-1.62.0
module Branch(
  input  [3:0]  io_br_type,
  input  [31:0] io_src1,
                io_src2,
                io_pc_ex,
                io_imm_ex,
  input         io_predict_jump,
  input  [31:0] io_pred_npc,
  output        io_real_jump,
                io_predict_fail,
  output [31:0] io_branch_target
);

  wire        io_real_jump_0;
  wire [31:0] io_branch_target_0;
  wire        _GEN = io_br_type == 4'h6;
  wire        _GEN_0 = io_br_type == 4'h7;
  wire        _GEN_1 = io_br_type == 4'h8;
  wire        _GEN_2 = io_br_type == 4'h9;
  wire        _GEN_3 = io_br_type == 4'hA;
  wire        _GEN_4 = io_br_type == 4'hB;
  wire        _GEN_5 = io_br_type == 4'h3;
  assign io_branch_target_0 =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | ~_GEN_5
      ? 32'(io_pc_ex + io_imm_ex)
      : 32'(io_src1 + io_imm_ex);
  wire        _GEN_6 = io_br_type == 4'h4;
  wire        _GEN_7 = io_br_type == 4'h5;
  wire        _GEN_8 =
    _GEN_6
      ? ~io_predict_jump | (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_7 & (~io_predict_jump | (|(io_pred_npc ^ io_branch_target_0)));
  wire        _GEN_9 =
    _GEN_5 ? ~io_predict_jump | (|(io_pred_npc ^ io_branch_target_0)) : _GEN_8;
  wire        _GEN_10 =
    _GEN_4
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_9;
  wire        _GEN_11 =
    _GEN_3
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_10;
  wire        _GEN_12 =
    _GEN_2
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_11;
  wire        _GEN_13 =
    _GEN_1
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_12;
  wire        _GEN_14 =
    _GEN_0
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_13;
  wire        _GEN_15 = _GEN_4 ? io_src1 >= io_src2 : _GEN_5 | _GEN_6 | _GEN_7;
  wire        _GEN_16 = _GEN_3 ? io_src1 < io_src2 : _GEN_15;
  wire        _GEN_17 = _GEN_2 ? $signed(io_src1) >= $signed(io_src2) : _GEN_16;
  wire        _GEN_18 = _GEN_1 ? $signed(io_src1) < $signed(io_src2) : _GEN_17;
  wire        _GEN_19 = _GEN_0 ? io_src1 != io_src2 : _GEN_18;
  assign io_real_jump_0 = _GEN ? io_src1 == io_src2 : _GEN_19;
  assign io_real_jump = io_real_jump_0;
  assign io_predict_fail =
    _GEN
      ? io_real_jump_0 ^ io_predict_jump | io_predict_jump
        & (|(io_pred_npc ^ io_branch_target_0))
      : _GEN_14;
  assign io_branch_target = io_branch_target_0;
endmodule

