// Generated by CIRCT firtool-1.62.0
module Bypass_3(
  input  [5:0]  io_prd_wb_0,
                io_prd_wb_1,
                io_prd_wb_2,
                io_prj_ex_0,
                io_prj_ex_1,
                io_prj_ex_2,
                io_prk_ex_0,
                io_prk_ex_1,
                io_prk_ex_2,
  input  [31:0] io_prf_wdata_wb_0,
                io_prf_wdata_wb_1,
                io_prf_wdata_wb_2,
  input         io_rd_valid_wb_0,
                io_rd_valid_wb_1,
                io_rd_valid_wb_2,
  output        io_forward_prj_en_0,
                io_forward_prj_en_1,
                io_forward_prj_en_2,
                io_forward_prk_en_0,
                io_forward_prk_en_1,
                io_forward_prk_en_2,
  output [31:0] io_forward_prj_data_0,
                io_forward_prj_data_1,
                io_forward_prj_data_2,
                io_forward_prk_data_0,
                io_forward_prk_data_1,
                io_forward_prk_data_2
);

  wire [5:0]  _io_forward_prj_data_0_T = io_prd_wb_0 ^ io_prj_ex_0;
  wire [5:0]  _io_forward_prk_data_0_T = io_prd_wb_0 ^ io_prk_ex_0;
  wire [5:0]  _io_forward_prj_data_1_T = io_prd_wb_0 ^ io_prj_ex_1;
  wire [5:0]  _io_forward_prk_data_1_T = io_prd_wb_0 ^ io_prk_ex_1;
  wire [5:0]  _io_forward_prj_data_2_T = io_prd_wb_0 ^ io_prj_ex_2;
  wire [5:0]  _io_forward_prj_data_2_T_2 = io_prd_wb_1 ^ io_prj_ex_2;
  wire [5:0]  _io_forward_prk_data_2_T = io_prd_wb_0 ^ io_prk_ex_2;
  wire [5:0]  _io_forward_prk_data_2_T_2 = io_prd_wb_1 ^ io_prk_ex_2;
  wire [31:0] _io_forward_prj_data_2_T_4 =
    (|_io_forward_prj_data_2_T_2) ? io_prf_wdata_wb_2 : io_prf_wdata_wb_1;
  wire [31:0] _io_forward_prk_data_2_T_4 =
    (|_io_forward_prk_data_2_T_2) ? io_prf_wdata_wb_2 : io_prf_wdata_wb_1;
  assign io_forward_prj_en_0 =
    io_rd_valid_wb_0 & ~(|_io_forward_prj_data_0_T) | io_rd_valid_wb_1
    & (io_prd_wb_1 ^ io_prj_ex_0) == 6'h0;
  assign io_forward_prj_en_1 =
    io_rd_valid_wb_0 & ~(|_io_forward_prj_data_1_T) | io_rd_valid_wb_1
    & (io_prd_wb_1 ^ io_prj_ex_1) == 6'h0;
  assign io_forward_prj_en_2 =
    io_rd_valid_wb_0 & ~(|_io_forward_prj_data_2_T) | io_rd_valid_wb_1
    & ~(|_io_forward_prj_data_2_T_2) | io_rd_valid_wb_2
    & (io_prd_wb_2 ^ io_prj_ex_2) == 6'h0;
  assign io_forward_prk_en_0 =
    io_rd_valid_wb_0 & ~(|_io_forward_prk_data_0_T) | io_rd_valid_wb_1
    & (io_prd_wb_1 ^ io_prk_ex_0) == 6'h0;
  assign io_forward_prk_en_1 =
    io_rd_valid_wb_0 & ~(|_io_forward_prk_data_1_T) | io_rd_valid_wb_1
    & (io_prd_wb_1 ^ io_prk_ex_1) == 6'h0;
  assign io_forward_prk_en_2 =
    io_rd_valid_wb_0 & ~(|_io_forward_prk_data_2_T) | io_rd_valid_wb_1
    & ~(|_io_forward_prk_data_2_T_2) | io_rd_valid_wb_2
    & (io_prd_wb_2 ^ io_prk_ex_2) == 6'h0;
  assign io_forward_prj_data_0 =
    (|_io_forward_prj_data_0_T) ? io_prf_wdata_wb_1 : io_prf_wdata_wb_0;
  assign io_forward_prj_data_1 =
    (|_io_forward_prj_data_1_T) ? io_prf_wdata_wb_1 : io_prf_wdata_wb_0;
  assign io_forward_prj_data_2 =
    (|_io_forward_prj_data_2_T) ? _io_forward_prj_data_2_T_4 : io_prf_wdata_wb_0;
  assign io_forward_prk_data_0 =
    (|_io_forward_prk_data_0_T) ? io_prf_wdata_wb_1 : io_prf_wdata_wb_0;
  assign io_forward_prk_data_1 =
    (|_io_forward_prk_data_1_T) ? io_prf_wdata_wb_1 : io_prf_wdata_wb_0;
  assign io_forward_prk_data_2 =
    (|_io_forward_prk_data_2_T) ? _io_forward_prk_data_2_T_4 : io_prf_wdata_wb_0;
endmodule

