// Generated by CIRCT firtool-1.62.0
module DCache(
  input         clock,
                reset,
  input  [31:0] io_addr_RF,
  input  [4:0]  io_mem_type_RF,
  input  [31:0] io_wdata_RF,
  input         io_store_cmt_RF,
  input  [4:0]  io_rob_index_EX,
  input  [31:0] io_paddr_EX,
  input         io_uncache_EX,
  output        io_cache_miss_MEM_3,
                io_cache_miss_MEM_4,
  output [31:0] io_rdata_MEM,
  input         io_exception_MEM,
  output        io_cache_miss_iq_0,
                io_cache_miss_iq_1,
                io_cache_miss_iq_2,
  input  [4:0]  io_rob_index_CMT,
  input         io_cacop_en,
  input  [1:0]  io_cacop_op,
  input         io_flush,
  output [31:0] io_d_araddr,
  output        io_d_rvalid,
  input         io_d_rready,
  input  [31:0] io_d_rdata,
  input         io_d_rlast,
  output [2:0]  io_d_rsize,
  output [7:0]  io_d_rlen,
  output [31:0] io_d_awaddr,
                io_d_wdata,
  output        io_d_wvalid,
  input         io_d_wready,
  output        io_d_wlast,
  output [3:0]  io_d_wstrb,
  output [2:0]  io_d_wsize,
  output [7:0]  io_d_wlen,
  input         io_d_bvalid,
  output        io_d_bready
);

  wire            wrt_finish;
  wire            addr_sel;
  wire            data_sel;
  wire [4:0]      _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_addra;
  wire [255:0]    _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_doutb;
  wire [4:0]      _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_addra;
  wire [255:0]    _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_doutb;
  wire [4:0]      _xilinx_simple_dual_port_1_clock_ram_write_first_1_addra;
  wire            _xilinx_simple_dual_port_1_clock_ram_write_first_1_wea;
  wire [22:0]     _xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb;
  wire [4:0]      _xilinx_simple_dual_port_1_clock_ram_write_first_addra;
  wire            _xilinx_simple_dual_port_1_clock_ram_write_first_wea;
  wire [22:0]     _xilinx_simple_dual_port_1_clock_ram_write_first_doutb;
  reg  [31:0]     addr_reg_RF_EX;
  reg  [4:0]      mem_type_reg_RF_EX;
  reg  [31:0]     wdata_reg_RF_EX;
  reg             store_cmt_reg_RF_EX;
  reg             cacop_en_reg_RF_EX;
  reg  [1:0]      cacop_op_reg_RF_EX;
  reg             flush_RF_EX;
  reg  [31:0]     paddr_reg_EX_MEM;
  reg  [4:0]      mem_type_reg_EX_MEM;
  reg  [31:0]     wdata_reg_EX_MEM;
  reg             uncache_reg_EX_MEM;
  reg  [4:0]      rob_index_EX_MEM;
  reg  [1:0]      hit_reg_EX_MEM_0;
  reg  [1:0]      hit_reg_EX_MEM_1;
  reg  [1:0]      hit_reg_EX_MEM_2;
  reg  [1:0]      hit_reg_EX_MEM_3;
  reg  [1:0]      hit_reg_EX_MEM_4;
  reg  [21:0]     tag_reg_EX_MEM_0;
  reg  [21:0]     tag_reg_EX_MEM_1;
  reg             cacop_en_reg_EX_MEM;
  reg  [1:0]      cacop_op_reg_EX_MEM;
  reg             flush_EX_MEM;
  reg  [255:0]    cmem_rdata_reg_EX_MEM_0;
  reg  [255:0]    cmem_rdata_reg_EX_MEM_1;
  reg  [4:0]      mem_type_reg_EX_MEM_backup_0;
  reg  [4:0]      mem_type_reg_EX_MEM_backup_1;
  reg  [4:0]      mem_type_reg_EX_MEM_backup_2;
  reg  [4:0]      mem_type_reg_EX_MEM_backup_3;
  reg  [4:0]      mem_type_reg_EX_MEM_backup_4;
  reg             exception_MEM;
  reg             lru_mem_0;
  reg             lru_mem_1;
  reg             lru_mem_2;
  reg             lru_mem_3;
  reg             lru_mem_4;
  reg             lru_mem_5;
  reg             lru_mem_6;
  reg             lru_mem_7;
  reg             lru_mem_8;
  reg             lru_mem_9;
  reg             lru_mem_10;
  reg             lru_mem_11;
  reg             lru_mem_12;
  reg             lru_mem_13;
  reg             lru_mem_14;
  reg             lru_mem_15;
  reg             lru_mem_16;
  reg             lru_mem_17;
  reg             lru_mem_18;
  reg             lru_mem_19;
  reg             lru_mem_20;
  reg             lru_mem_21;
  reg             lru_mem_22;
  reg             lru_mem_23;
  reg             lru_mem_24;
  reg             lru_mem_25;
  reg             lru_mem_26;
  reg             lru_mem_27;
  reg             lru_mem_28;
  reg             lru_mem_29;
  reg             lru_mem_30;
  reg             lru_mem_31;
  reg  [255:0]    ret_buf;
  reg  [287:0]    wrt_buf;
  reg             dirty_table_0_0;
  reg             dirty_table_0_1;
  reg             dirty_table_0_2;
  reg             dirty_table_0_3;
  reg             dirty_table_0_4;
  reg             dirty_table_0_5;
  reg             dirty_table_0_6;
  reg             dirty_table_0_7;
  reg             dirty_table_0_8;
  reg             dirty_table_0_9;
  reg             dirty_table_0_10;
  reg             dirty_table_0_11;
  reg             dirty_table_0_12;
  reg             dirty_table_0_13;
  reg             dirty_table_0_14;
  reg             dirty_table_0_15;
  reg             dirty_table_0_16;
  reg             dirty_table_0_17;
  reg             dirty_table_0_18;
  reg             dirty_table_0_19;
  reg             dirty_table_0_20;
  reg             dirty_table_0_21;
  reg             dirty_table_0_22;
  reg             dirty_table_0_23;
  reg             dirty_table_0_24;
  reg             dirty_table_0_25;
  reg             dirty_table_0_26;
  reg             dirty_table_0_27;
  reg             dirty_table_0_28;
  reg             dirty_table_0_29;
  reg             dirty_table_0_30;
  reg             dirty_table_0_31;
  reg             dirty_table_1_0;
  reg             dirty_table_1_1;
  reg             dirty_table_1_2;
  reg             dirty_table_1_3;
  reg             dirty_table_1_4;
  reg             dirty_table_1_5;
  reg             dirty_table_1_6;
  reg             dirty_table_1_7;
  reg             dirty_table_1_8;
  reg             dirty_table_1_9;
  reg             dirty_table_1_10;
  reg             dirty_table_1_11;
  reg             dirty_table_1_12;
  reg             dirty_table_1_13;
  reg             dirty_table_1_14;
  reg             dirty_table_1_15;
  reg             dirty_table_1_16;
  reg             dirty_table_1_17;
  reg             dirty_table_1_18;
  reg             dirty_table_1_19;
  reg             dirty_table_1_20;
  reg             dirty_table_1_21;
  reg             dirty_table_1_22;
  reg             dirty_table_1_23;
  reg             dirty_table_1_24;
  reg             dirty_table_1_25;
  reg             dirty_table_1_26;
  reg             dirty_table_1_27;
  reg             dirty_table_1_28;
  reg             dirty_table_1_29;
  reg             dirty_table_1_30;
  reg             dirty_table_1_31;
  wire [4:0]      tagv_0_addrb = addr_sel ? addr_reg_RF_EX[9:5] : io_addr_RF[9:5];
  wire [22:0]     _tagv_1_dina_T = {1'h1, paddr_reg_EX_MEM[31:10]};
  wire [22:0]     tagv_0_dina = cacop_en_reg_EX_MEM ? 23'h0 : _tagv_1_dina_T;
  wire [4:0]      tagv_1_addrb = addr_sel ? addr_reg_RF_EX[9:5] : io_addr_RF[9:5];
  wire [22:0]     tagv_1_dina = cacop_en_reg_EX_MEM ? 23'h0 : _tagv_1_dina_T;
  wire [4:0]      cmem_0_addrb = addr_sel ? addr_reg_RF_EX[9:5] : io_addr_RF[9:5];
  wire [4:0]      cmem_1_addrb = addr_sel ? addr_reg_RF_EX[9:5] : io_addr_RF[9:5];
  wire            cacop_way_MEM =
    cacop_op_reg_EX_MEM[1] ? hit_reg_EX_MEM_1[1] : paddr_reg_EX_MEM[0];
  wire            cacop_exec_MEM = ~(cacop_op_reg_EX_MEM[1]) | (|hit_reg_EX_MEM_0);
  wire [255:0]    _GEN =
    hit_reg_EX_MEM_0[1] ? cmem_rdata_reg_EX_MEM_1 : cmem_rdata_reg_EX_MEM_0;
  wire [255:0]    _GEN_0 = {248'h0, paddr_reg_EX_MEM[4:0], 3'h0};
  wire [255:0]    _mem_rdata_MEM_T = _GEN >> _GEN_0;
  wire [255:0]    _rbuf_rdata_MEM_T_1 = ret_buf >> _GEN_0;
  wire [31:0]     rbuf_rdata_MEM =
    uncache_reg_EX_MEM ? ret_buf[255:224] : _rbuf_rdata_MEM_T_1[31:0];
  wire [31:0]     rdata_MEM_temp = data_sel ? rbuf_rdata_MEM : _mem_rdata_MEM_T[31:0];
  wire [3:0]      _GEN_1 = {2'h0, mem_type_reg_EX_MEM[1:0]};
  wire [127:0]    _highest_mask_T = 128'h1 << {121'h0, 4'h1 << _GEN_1, 3'h0};
  wire [31:0]     _highest_mask_T_2 = 32'(_highest_mask_T[31:0] - 32'h1);
  wire [510:0]    _GEN_2 = {503'h0, paddr_reg_EX_MEM[4:0], 3'h0};
  wire [510:0]    _wmask_T_2 = {479'h0, _highest_mask_T_2} << _GEN_2;
  wire [255:0]    wmask = mem_type_reg_EX_MEM[3] ? 256'h0 : _wmask_T_2[255:0];
  wire [510:0]    wdata_refill = {479'h0, wdata_reg_EX_MEM} << _GEN_2;
  wire [255:0]    cmem_1_dina = wmask & wdata_refill[255:0] | ~wmask & ret_buf;
  wire [31:0]     wmask_byte =
    {wmask[248],
     wmask[240],
     wmask[232],
     wmask[224],
     wmask[216],
     wmask[208],
     wmask[200],
     wmask[192],
     wmask[184],
     wmask[176],
     wmask[168],
     wmask[160],
     wmask[152],
     wmask[144],
     wmask[136],
     wmask[128],
     wmask[120],
     wmask[112],
     wmask[104],
     wmask[96],
     wmask[88],
     wmask[80],
     wmask[72],
     wmask[64],
     wmask[56],
     wmask[48],
     wmask[40],
     wmask[32],
     wmask[24],
     wmask[16],
     wmask[8],
     wmask[0]};
  wire [31:0]     _GEN_3 =
    {{lru_mem_31},
     {lru_mem_30},
     {lru_mem_29},
     {lru_mem_28},
     {lru_mem_27},
     {lru_mem_26},
     {lru_mem_25},
     {lru_mem_24},
     {lru_mem_23},
     {lru_mem_22},
     {lru_mem_21},
     {lru_mem_20},
     {lru_mem_19},
     {lru_mem_18},
     {lru_mem_17},
     {lru_mem_16},
     {lru_mem_15},
     {lru_mem_14},
     {lru_mem_13},
     {lru_mem_12},
     {lru_mem_11},
     {lru_mem_10},
     {lru_mem_9},
     {lru_mem_8},
     {lru_mem_7},
     {lru_mem_6},
     {lru_mem_5},
     {lru_mem_4},
     {lru_mem_3},
     {lru_mem_2},
     {lru_mem_1},
     {lru_mem_0}};
  wire            _GEN_4 = _GEN_3[paddr_reg_EX_MEM[9:5]];
  reg  [2:0]      state;
  reg  [2:0]      state_backup_3;
  reg  [2:0]      state_backup_4;
  wire            _GEN_5 = state == 3'h0;
  assign data_sel =
    ~_GEN_5 | cacop_en_reg_EX_MEM | ~(|(mem_type_reg_EX_MEM[4:3])) | uncache_reg_EX_MEM;
  wire            _cmem_we_MEM_T = mem_type_reg_EX_MEM[4] & (|hit_reg_EX_MEM_1);
  wire [31:0]     _GEN_6 =
    cacop_en_reg_EX_MEM | ~(|(mem_type_reg_EX_MEM[4:3])) | uncache_reg_EX_MEM
    | ~(~(hit_reg_EX_MEM_2[1]) & _cmem_we_MEM_T)
      ? 32'h0
      : wmask_byte;
  wire [31:0]     _GEN_7 =
    cacop_en_reg_EX_MEM | ~(|(mem_type_reg_EX_MEM[4:3])) | uncache_reg_EX_MEM
    | ~(hit_reg_EX_MEM_2[1] & _cmem_we_MEM_T)
      ? 32'h0
      : wmask_byte;
  wire            _GEN_8 =
    cacop_en_reg_EX_MEM
      ? cacop_exec_MEM
      : (|(mem_type_reg_EX_MEM[4:3])) & uncache_reg_EX_MEM;
  wire            _GEN_9 = state == 3'h1;
  wire            _GEN_10 = state == 3'h2;
  wire            tag_idx = cacop_en_reg_EX_MEM ? cacop_way_MEM : _GEN_4;
  wire            _GEN_11 = _GEN_5 | _GEN_9;
  wire            lru_miss_upd = ~_GEN_11 & _GEN_10 & ~cacop_en_reg_EX_MEM;
  wire [31:0]     _GEN_12 =
    _GEN_9 | ~(_GEN_10 & ~_GEN_4) | cacop_en_reg_EX_MEM ? 32'h0 : 32'hFFFFFFFF;
  wire [31:0]     cmem_we_MEM_0 = _GEN_5 ? _GEN_6 : _GEN_12;
  wire [31:0]     _GEN_13 =
    _GEN_9 | ~(_GEN_10 & _GEN_4) | cacop_en_reg_EX_MEM ? 32'h0 : 32'hFFFFFFFF;
  wire [31:0]     cmem_we_MEM_1 = _GEN_5 ? _GEN_7 : _GEN_13;
  wire            dirty_clean =
    ~_GEN_11 & _GEN_10 & (mem_type_reg_EX_MEM[3] | cacop_en_reg_EX_MEM);
  wire            _GEN_14 = state == 3'h3;
  wire            _GEN_15 = state == 3'h4;
  wire            _wbuf_we_T_1 = flush_EX_MEM | exception_MEM;
  wire            _GEN_16 = _GEN_14 ? ~wrt_finish : _GEN_15 & ~_wbuf_we_T_1;
  wire            _GEN_17 = _GEN_9 | _GEN_10;
  assign addr_sel = _GEN_5 ? _GEN_8 : _GEN_17 | _GEN_16;
  wire            _GEN_18 =
    cacop_en_reg_EX_MEM
      ? cacop_exec_MEM
      : (|(mem_type_reg_EX_MEM_backup_3[4:3]))
        & (uncache_reg_EX_MEM | ~(|hit_reg_EX_MEM_3));
  wire            _cache_miss_MEM_3_T_2 = flush_EX_MEM | exception_MEM;
  wire            _GEN_19 =
    state_backup_3 == 3'h3
      ? ~wrt_finish
      : state_backup_3 == 3'h4 & ~_cache_miss_MEM_3_T_2;
  wire            _GEN_20 =
    cacop_en_reg_EX_MEM
      ? cacop_exec_MEM
      : (|(mem_type_reg_EX_MEM_backup_4[4:3]))
        & (uncache_reg_EX_MEM | ~(|hit_reg_EX_MEM_4));
  wire            _cache_miss_MEM_4_T_2 = flush_EX_MEM | exception_MEM;
  wire            _GEN_21 =
    state_backup_4 == 3'h3
      ? ~wrt_finish
      : state_backup_4 == 3'h4 & ~_cache_miss_MEM_4_T_2;
  wire            cache_miss_MEM_4 =
    state_backup_4 == 3'h0
      ? _GEN_20
      : state_backup_4 == 3'h1 | state_backup_4 == 3'h2 | _GEN_21;
  reg  [7:0]      wrt_count;
  wire [2:0]      wrt_num = uncache_reg_EX_MEM ? 3'h0 : 3'h7;
  wire [7:0]      io_d_wlen_0 = {5'h0, wrt_num};
  reg  [1:0]      wrt_state;
  wire            _GEN_22 = wrt_state == 2'h0;
  wire            _GEN_23 = wrt_state == 2'h1;
  wire            d_wvalid = ~_GEN_22 & _GEN_23 & wrt_count != 8'hFF;
  assign wrt_finish = ~(_GEN_22 | _GEN_23) & wrt_state == 2'h2;
  wire [1:0]      _io_d_rsize_T_1 = uncache_reg_EX_MEM ? mem_type_reg_EX_MEM[1:0] : 2'h2;
  wire [15:0]     _io_d_wstrb_T_2 = 16'h1 << (4'h1 << _GEN_1);
  wire [1:0]      _io_d_wsize_T_1 = uncache_reg_EX_MEM ? mem_type_reg_EX_MEM[1:0] : 2'h2;
  wire            uncache_EX = ~store_cmt_reg_RF_EX & (flush_RF_EX | io_uncache_EX);
  wire [21:0]     tag_EX =
    store_cmt_reg_RF_EX ? addr_reg_RF_EX[31:10] : io_paddr_EX[31:10];
  wire [1:0]      hit_EX =
    {_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[22]
       & (_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[21:0]
          ^ tag_EX) == 22'h0,
     _xilinx_simple_dual_port_1_clock_ram_write_first_doutb[22]
       & (_xilinx_simple_dual_port_1_clock_ram_write_first_doutb[21:0]
          ^ tag_EX) == 22'h0};
  wire [21:0]     _GEN_24 = _GEN_4 ? tag_reg_EX_MEM_1 : tag_reg_EX_MEM_0;
  wire [255:0]    _GEN_25 = _GEN_4 ? cmem_rdata_reg_EX_MEM_1 : cmem_rdata_reg_EX_MEM_0;
  wire [287:0]    _GEN_26 =
    uncache_reg_EX_MEM
      ? {224'h0, wdata_reg_EX_MEM, paddr_reg_EX_MEM}
      : {_GEN_25, _GEN_24, paddr_reg_EX_MEM[9:5], 5'h0};
  wire            cmem_wb_idx =
    cacop_op_reg_EX_MEM[1] ? hit_reg_EX_MEM_3[1] : paddr_reg_EX_MEM[0];
  wire [255:0]    _GEN_27 =
    cmem_wb_idx ? cmem_rdata_reg_EX_MEM_1 : cmem_rdata_reg_EX_MEM_0;
  wire            write_way = (|hit_reg_EX_MEM_2) ? hit_reg_EX_MEM_2[1] : _GEN_4;
  wire            _GEN_28 = paddr_reg_EX_MEM[9:5] == 5'h0;
  wire            _GEN_29 = paddr_reg_EX_MEM[9:5] == 5'h1;
  wire            _GEN_30 = paddr_reg_EX_MEM[9:5] == 5'h2;
  wire            _GEN_31 = paddr_reg_EX_MEM[9:5] == 5'h3;
  wire            _GEN_32 = paddr_reg_EX_MEM[9:5] == 5'h4;
  wire            _GEN_33 = paddr_reg_EX_MEM[9:5] == 5'h5;
  wire            _GEN_34 = paddr_reg_EX_MEM[9:5] == 5'h6;
  wire            _GEN_35 = paddr_reg_EX_MEM[9:5] == 5'h7;
  wire            _GEN_36 = paddr_reg_EX_MEM[9:5] == 5'h8;
  wire            _GEN_37 = paddr_reg_EX_MEM[9:5] == 5'h9;
  wire            _GEN_38 = paddr_reg_EX_MEM[9:5] == 5'hA;
  wire            _GEN_39 = paddr_reg_EX_MEM[9:5] == 5'hB;
  wire            _GEN_40 = paddr_reg_EX_MEM[9:5] == 5'hC;
  wire            _GEN_41 = paddr_reg_EX_MEM[9:5] == 5'hD;
  wire            _GEN_42 = paddr_reg_EX_MEM[9:5] == 5'hE;
  wire            _GEN_43 = paddr_reg_EX_MEM[9:5] == 5'hF;
  wire            _GEN_44 = paddr_reg_EX_MEM[9:5] == 5'h10;
  wire            _GEN_45 = paddr_reg_EX_MEM[9:5] == 5'h11;
  wire            _GEN_46 = paddr_reg_EX_MEM[9:5] == 5'h12;
  wire            _GEN_47 = paddr_reg_EX_MEM[9:5] == 5'h13;
  wire            _GEN_48 = paddr_reg_EX_MEM[9:5] == 5'h14;
  wire            _GEN_49 = paddr_reg_EX_MEM[9:5] == 5'h15;
  wire            _GEN_50 = paddr_reg_EX_MEM[9:5] == 5'h16;
  wire            _GEN_51 = paddr_reg_EX_MEM[9:5] == 5'h17;
  wire            _GEN_52 = paddr_reg_EX_MEM[9:5] == 5'h18;
  wire            _GEN_53 = paddr_reg_EX_MEM[9:5] == 5'h19;
  wire            _GEN_54 = paddr_reg_EX_MEM[9:5] == 5'h1A;
  wire            _GEN_55 = paddr_reg_EX_MEM[9:5] == 5'h1B;
  wire            _GEN_56 = paddr_reg_EX_MEM[9:5] == 5'h1C;
  wire            _GEN_57 = paddr_reg_EX_MEM[9:5] == 5'h1D;
  wire            _GEN_58 = paddr_reg_EX_MEM[9:5] == 5'h1E;
  wire            confirm_exec = io_rob_index_CMT == rob_index_EX_MEM;
  wire            _GEN_59 = _GEN_9 | _GEN_10 | _GEN_14;
  wire            _GEN_60 =
    cacop_en_reg_EX_MEM
      ? cacop_exec_MEM
      : (|(mem_type_reg_EX_MEM[4:3])) & ~uncache_reg_EX_MEM & ~(|hit_reg_EX_MEM_3);
  wire            wfsm_en =
    _GEN_5 ? _GEN_60 : ~_GEN_59 & _GEN_15 & confirm_exec & ~_wbuf_we_T_1;
  wire [31:0]     _GEN_61 =
    _GEN_4
      ? {{dirty_table_1_31},
         {dirty_table_1_30},
         {dirty_table_1_29},
         {dirty_table_1_28},
         {dirty_table_1_27},
         {dirty_table_1_26},
         {dirty_table_1_25},
         {dirty_table_1_24},
         {dirty_table_1_23},
         {dirty_table_1_22},
         {dirty_table_1_21},
         {dirty_table_1_20},
         {dirty_table_1_19},
         {dirty_table_1_18},
         {dirty_table_1_17},
         {dirty_table_1_16},
         {dirty_table_1_15},
         {dirty_table_1_14},
         {dirty_table_1_13},
         {dirty_table_1_12},
         {dirty_table_1_11},
         {dirty_table_1_10},
         {dirty_table_1_9},
         {dirty_table_1_8},
         {dirty_table_1_7},
         {dirty_table_1_6},
         {dirty_table_1_5},
         {dirty_table_1_4},
         {dirty_table_1_3},
         {dirty_table_1_2},
         {dirty_table_1_1},
         {dirty_table_1_0}}
      : {{dirty_table_0_31},
         {dirty_table_0_30},
         {dirty_table_0_29},
         {dirty_table_0_28},
         {dirty_table_0_27},
         {dirty_table_0_26},
         {dirty_table_0_25},
         {dirty_table_0_24},
         {dirty_table_0_23},
         {dirty_table_0_22},
         {dirty_table_0_21},
         {dirty_table_0_20},
         {dirty_table_0_19},
         {dirty_table_0_18},
         {dirty_table_0_17},
         {dirty_table_0_16},
         {dirty_table_0_15},
         {dirty_table_0_14},
         {dirty_table_0_13},
         {dirty_table_0_12},
         {dirty_table_0_11},
         {dirty_table_0_10},
         {dirty_table_0_9},
         {dirty_table_0_8},
         {dirty_table_0_7},
         {dirty_table_0_6},
         {dirty_table_0_5},
         {dirty_table_0_4},
         {dirty_table_0_3},
         {dirty_table_0_2},
         {dirty_table_0_1},
         {dirty_table_0_0}};
  wire            _GEN_62 = _GEN_61[paddr_reg_EX_MEM[9:5]];
  wire            _GEN_63 =
    cacop_en_reg_EX_MEM
      ? cacop_exec_MEM
      : (|(mem_type_reg_EX_MEM[4:3])) & ~uncache_reg_EX_MEM & ~(|hit_reg_EX_MEM_2);
  wire            wbuf_we =
    _GEN_5 ? _GEN_63 : ~_GEN_59 & _GEN_15 & confirm_exec & ~_wbuf_we_T_1;
  wire            dirty_we =
    _GEN_5
      ? ~cacop_en_reg_EX_MEM & (|(mem_type_reg_EX_MEM[4:3])) & ~uncache_reg_EX_MEM
        & mem_type_reg_EX_MEM[4]
      : ~_GEN_9 & _GEN_10 & mem_type_reg_EX_MEM[4];
  wire [2:0]      _state_T_8 = confirm_exec ? {1'h0, mem_type_reg_EX_MEM[4], 1'h1} : 3'h4;
  wire [2:0]      _state_T_9 = _wbuf_we_T_1 ? 3'h0 : _state_T_8;
  wire [2:0]      _state_T_5 = wrt_finish ? 3'h0 : 3'h3;
  wire [2:0]      _state_T_4 =
    io_d_rready & io_d_rlast ? {2'h1, uncache_reg_EX_MEM} : 3'h1;
  wire [2:0]      _GEN_64 = uncache_reg_EX_MEM ? 3'h4 : {2'h0, ~(|hit_reg_EX_MEM_0)};
  wire [2:0]      _GEN_65 = (|(mem_type_reg_EX_MEM[4:3])) ? _GEN_64 : state;
  wire [2:0]      _GEN_66 = cacop_en_reg_EX_MEM ? {1'h0, cacop_exec_MEM, 1'h0} : _GEN_65;
  wire [7:0][2:0] _GEN_67 =
    {{state},
     {state},
     {state},
     {_state_T_9},
     {_state_T_5},
     {3'h3},
     {_state_T_4},
     {_GEN_66}};
  wire [2:0]      _state_backup_3_T_8 =
    io_rob_index_CMT == rob_index_EX_MEM ? {1'h0, mem_type_reg_EX_MEM[4], 1'h1} : 3'h4;
  wire [2:0]      _state_backup_3_T_9 =
    _cache_miss_MEM_3_T_2 ? 3'h0 : _state_backup_3_T_8;
  wire [2:0]      _state_backup_3_T_5 = wrt_finish ? 3'h0 : 3'h3;
  wire [2:0]      _state_backup_3_T_4 =
    io_d_rready & io_d_rlast ? {2'h1, uncache_reg_EX_MEM} : 3'h1;
  wire [2:0]      _GEN_68 = uncache_reg_EX_MEM ? 3'h4 : {2'h0, ~(|hit_reg_EX_MEM_3)};
  wire [2:0]      _GEN_69 =
    (|(mem_type_reg_EX_MEM_backup_3[4:3])) ? _GEN_68 : state_backup_3;
  wire [2:0]      _GEN_70 = cacop_en_reg_EX_MEM ? {1'h0, cacop_exec_MEM, 1'h0} : _GEN_69;
  wire [7:0][2:0] _GEN_71 =
    {{state_backup_3},
     {state_backup_3},
     {state_backup_3},
     {_state_backup_3_T_9},
     {_state_backup_3_T_5},
     {3'h3},
     {_state_backup_3_T_4},
     {_GEN_70}};
  wire [2:0]      _state_backup_4_T_8 =
    io_rob_index_CMT == rob_index_EX_MEM ? {1'h0, mem_type_reg_EX_MEM[4], 1'h1} : 3'h4;
  wire [2:0]      _state_backup_4_T_9 =
    _cache_miss_MEM_4_T_2 ? 3'h0 : _state_backup_4_T_8;
  wire [2:0]      _state_backup_4_T_5 = wrt_finish ? 3'h0 : 3'h3;
  wire [2:0]      _state_backup_4_T_4 =
    io_d_rready & io_d_rlast ? {2'h1, uncache_reg_EX_MEM} : 3'h1;
  wire [2:0]      _GEN_72 = uncache_reg_EX_MEM ? 3'h4 : {2'h0, ~(|hit_reg_EX_MEM_4)};
  wire [2:0]      _GEN_73 =
    (|(mem_type_reg_EX_MEM_backup_4[4:3])) ? _GEN_72 : state_backup_4;
  wire [2:0]      _GEN_74 = cacop_en_reg_EX_MEM ? {1'h0, cacop_exec_MEM, 1'h0} : _GEN_73;
  wire [7:0][2:0] _GEN_75 =
    {{state_backup_4},
     {state_backup_4},
     {state_backup_4},
     {_state_backup_4_T_9},
     {_state_backup_4_T_5},
     {3'h3},
     {_state_backup_4_T_4},
     {_GEN_74}};
  wire [1:0]      _wrt_state_T_5 = io_d_bvalid ? 2'h2 : 2'h1;
  wire            _GEN_76 = uncache_reg_EX_MEM ? mem_type_reg_EX_MEM[4] : _GEN_62;
  wire [1:0]      _GEN_77 = _GEN_76 ? 2'h1 : 2'h2;
  wire [1:0]      _wrt_state_T_2 = cacop_op_reg_EX_MEM == 2'h0 | ~_GEN_62 ? 2'h2 : 2'h1;
  wire [1:0]      _GEN_78 = cacop_en_reg_EX_MEM ? _wrt_state_T_2 : _GEN_77;
  wire [1:0]      _GEN_79 = wfsm_en ? _GEN_78 : wrt_state;
  wire [3:0][1:0] _GEN_80 =
    {{wrt_state},
     {{~(~(_GEN_5 | _GEN_17) & (_GEN_14 | _GEN_15 & _wbuf_we_T_1)), 1'h0}},
     {_wrt_state_T_5},
     {_GEN_79}};
  always @(posedge clock) begin
    if (~cache_miss_MEM_4) begin
      addr_reg_RF_EX <= io_addr_RF;
      mem_type_reg_RF_EX <= io_mem_type_RF;
      wdata_reg_RF_EX <= io_wdata_RF;
      store_cmt_reg_RF_EX <= io_store_cmt_RF;
      cacop_en_reg_RF_EX <= io_cacop_en;
      cacop_op_reg_RF_EX <= io_cacop_op;
      paddr_reg_EX_MEM <=
        store_cmt_reg_RF_EX | flush_RF_EX ? addr_reg_RF_EX : io_paddr_EX;
      mem_type_reg_EX_MEM <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
      wdata_reg_EX_MEM <= wdata_reg_RF_EX;
      uncache_reg_EX_MEM <= uncache_EX;
      rob_index_EX_MEM <= io_rob_index_EX;
      hit_reg_EX_MEM_0 <= hit_EX;
      hit_reg_EX_MEM_1 <= hit_EX;
      hit_reg_EX_MEM_2 <= hit_EX;
      hit_reg_EX_MEM_3 <= hit_EX;
      hit_reg_EX_MEM_4 <= hit_EX;
      tag_reg_EX_MEM_0 <= _xilinx_simple_dual_port_1_clock_ram_write_first_doutb[21:0];
      tag_reg_EX_MEM_1 <= _xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[21:0];
      cacop_en_reg_EX_MEM <= cacop_en_reg_RF_EX;
      cacop_op_reg_EX_MEM <= cacop_op_reg_RF_EX;
      cmem_rdata_reg_EX_MEM_0 <=
        _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_doutb;
      cmem_rdata_reg_EX_MEM_1 <=
        _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_doutb;
      mem_type_reg_EX_MEM_backup_0 <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
      mem_type_reg_EX_MEM_backup_1 <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
      mem_type_reg_EX_MEM_backup_2 <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
      mem_type_reg_EX_MEM_backup_3 <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
      mem_type_reg_EX_MEM_backup_4 <=
        mem_type_reg_RF_EX[3] | uncache_EX | store_cmt_reg_RF_EX
          ? mem_type_reg_RF_EX
          : 5'h0;
    end
    if (~cache_miss_MEM_4 | io_flush)
      flush_RF_EX <= io_flush;
    if (~cache_miss_MEM_4 | io_flush)
      flush_EX_MEM <= io_flush ? io_flush : flush_RF_EX;
    exception_MEM <= io_exception_MEM;
    if (reset) begin
      lru_mem_0 <= 1'h0;
      lru_mem_1 <= 1'h0;
      lru_mem_2 <= 1'h0;
      lru_mem_3 <= 1'h0;
      lru_mem_4 <= 1'h0;
      lru_mem_5 <= 1'h0;
      lru_mem_6 <= 1'h0;
      lru_mem_7 <= 1'h0;
      lru_mem_8 <= 1'h0;
      lru_mem_9 <= 1'h0;
      lru_mem_10 <= 1'h0;
      lru_mem_11 <= 1'h0;
      lru_mem_12 <= 1'h0;
      lru_mem_13 <= 1'h0;
      lru_mem_14 <= 1'h0;
      lru_mem_15 <= 1'h0;
      lru_mem_16 <= 1'h0;
      lru_mem_17 <= 1'h0;
      lru_mem_18 <= 1'h0;
      lru_mem_19 <= 1'h0;
      lru_mem_20 <= 1'h0;
      lru_mem_21 <= 1'h0;
      lru_mem_22 <= 1'h0;
      lru_mem_23 <= 1'h0;
      lru_mem_24 <= 1'h0;
      lru_mem_25 <= 1'h0;
      lru_mem_26 <= 1'h0;
      lru_mem_27 <= 1'h0;
      lru_mem_28 <= 1'h0;
      lru_mem_29 <= 1'h0;
      lru_mem_30 <= 1'h0;
      lru_mem_31 <= 1'h0;
      ret_buf <= 256'h0;
      wrt_buf <= 288'h0;
      dirty_table_0_0 <= 1'h0;
      dirty_table_0_1 <= 1'h0;
      dirty_table_0_2 <= 1'h0;
      dirty_table_0_3 <= 1'h0;
      dirty_table_0_4 <= 1'h0;
      dirty_table_0_5 <= 1'h0;
      dirty_table_0_6 <= 1'h0;
      dirty_table_0_7 <= 1'h0;
      dirty_table_0_8 <= 1'h0;
      dirty_table_0_9 <= 1'h0;
      dirty_table_0_10 <= 1'h0;
      dirty_table_0_11 <= 1'h0;
      dirty_table_0_12 <= 1'h0;
      dirty_table_0_13 <= 1'h0;
      dirty_table_0_14 <= 1'h0;
      dirty_table_0_15 <= 1'h0;
      dirty_table_0_16 <= 1'h0;
      dirty_table_0_17 <= 1'h0;
      dirty_table_0_18 <= 1'h0;
      dirty_table_0_19 <= 1'h0;
      dirty_table_0_20 <= 1'h0;
      dirty_table_0_21 <= 1'h0;
      dirty_table_0_22 <= 1'h0;
      dirty_table_0_23 <= 1'h0;
      dirty_table_0_24 <= 1'h0;
      dirty_table_0_25 <= 1'h0;
      dirty_table_0_26 <= 1'h0;
      dirty_table_0_27 <= 1'h0;
      dirty_table_0_28 <= 1'h0;
      dirty_table_0_29 <= 1'h0;
      dirty_table_0_30 <= 1'h0;
      dirty_table_0_31 <= 1'h0;
      dirty_table_1_0 <= 1'h0;
      dirty_table_1_1 <= 1'h0;
      dirty_table_1_2 <= 1'h0;
      dirty_table_1_3 <= 1'h0;
      dirty_table_1_4 <= 1'h0;
      dirty_table_1_5 <= 1'h0;
      dirty_table_1_6 <= 1'h0;
      dirty_table_1_7 <= 1'h0;
      dirty_table_1_8 <= 1'h0;
      dirty_table_1_9 <= 1'h0;
      dirty_table_1_10 <= 1'h0;
      dirty_table_1_11 <= 1'h0;
      dirty_table_1_12 <= 1'h0;
      dirty_table_1_13 <= 1'h0;
      dirty_table_1_14 <= 1'h0;
      dirty_table_1_15 <= 1'h0;
      dirty_table_1_16 <= 1'h0;
      dirty_table_1_17 <= 1'h0;
      dirty_table_1_18 <= 1'h0;
      dirty_table_1_19 <= 1'h0;
      dirty_table_1_20 <= 1'h0;
      dirty_table_1_21 <= 1'h0;
      dirty_table_1_22 <= 1'h0;
      dirty_table_1_23 <= 1'h0;
      dirty_table_1_24 <= 1'h0;
      dirty_table_1_25 <= 1'h0;
      dirty_table_1_26 <= 1'h0;
      dirty_table_1_27 <= 1'h0;
      dirty_table_1_28 <= 1'h0;
      dirty_table_1_29 <= 1'h0;
      dirty_table_1_30 <= 1'h0;
      dirty_table_1_31 <= 1'h0;
      state <= 3'h0;
      state_backup_3 <= 3'h0;
      state_backup_4 <= 3'h0;
      wrt_count <= 8'h0;
      wrt_state <= 2'h0;
    end
    else begin
      if (_GEN_5 & ~cacop_en_reg_EX_MEM & (|(mem_type_reg_EX_MEM[4:3]))
          & ~uncache_reg_EX_MEM & (|hit_reg_EX_MEM_1)) begin
        if (_GEN_28)
          lru_mem_0 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_29)
          lru_mem_1 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_30)
          lru_mem_2 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_31)
          lru_mem_3 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_32)
          lru_mem_4 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_33)
          lru_mem_5 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_34)
          lru_mem_6 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_35)
          lru_mem_7 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_36)
          lru_mem_8 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_37)
          lru_mem_9 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_38)
          lru_mem_10 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_39)
          lru_mem_11 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_40)
          lru_mem_12 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_41)
          lru_mem_13 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_42)
          lru_mem_14 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_43)
          lru_mem_15 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_44)
          lru_mem_16 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_45)
          lru_mem_17 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_46)
          lru_mem_18 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_47)
          lru_mem_19 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_48)
          lru_mem_20 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_49)
          lru_mem_21 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_50)
          lru_mem_22 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_51)
          lru_mem_23 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_52)
          lru_mem_24 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_53)
          lru_mem_25 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_54)
          lru_mem_26 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_55)
          lru_mem_27 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_56)
          lru_mem_28 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_57)
          lru_mem_29 <= ~(hit_reg_EX_MEM_1[1]);
        if (_GEN_58)
          lru_mem_30 <= ~(hit_reg_EX_MEM_1[1]);
        if (&(paddr_reg_EX_MEM[9:5]))
          lru_mem_31 <= ~(hit_reg_EX_MEM_1[1]);
      end
      else begin
        if (lru_miss_upd & _GEN_28)
          lru_mem_0 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_29)
          lru_mem_1 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_30)
          lru_mem_2 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_31)
          lru_mem_3 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_32)
          lru_mem_4 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_33)
          lru_mem_5 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_34)
          lru_mem_6 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_35)
          lru_mem_7 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_36)
          lru_mem_8 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_37)
          lru_mem_9 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_38)
          lru_mem_10 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_39)
          lru_mem_11 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_40)
          lru_mem_12 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_41)
          lru_mem_13 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_42)
          lru_mem_14 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_43)
          lru_mem_15 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_44)
          lru_mem_16 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_45)
          lru_mem_17 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_46)
          lru_mem_18 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_47)
          lru_mem_19 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_48)
          lru_mem_20 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_49)
          lru_mem_21 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_50)
          lru_mem_22 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_51)
          lru_mem_23 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_52)
          lru_mem_24 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_53)
          lru_mem_25 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_54)
          lru_mem_26 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_55)
          lru_mem_27 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_56)
          lru_mem_28 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_57)
          lru_mem_29 <= ~_GEN_4;
        if (lru_miss_upd & _GEN_58)
          lru_mem_30 <= ~_GEN_4;
        if (lru_miss_upd & (&(paddr_reg_EX_MEM[9:5])))
          lru_mem_31 <= ~_GEN_4;
      end
      if (io_d_rready)
        ret_buf <= {io_d_rdata, ret_buf[255:32]};
      if (wbuf_we)
        wrt_buf <= cacop_en_reg_EX_MEM ? {_GEN_27, paddr_reg_EX_MEM} : _GEN_26;
      else if (io_d_wready & d_wvalid)
        wrt_buf <= {32'h0, wrt_buf[287:64], wrt_buf[31:0]};
      if (dirty_we) begin
        dirty_table_0_0 <= ~write_way & _GEN_28 | dirty_table_0_0;
        dirty_table_0_1 <= ~write_way & _GEN_29 | dirty_table_0_1;
        dirty_table_0_2 <= ~write_way & _GEN_30 | dirty_table_0_2;
        dirty_table_0_3 <= ~write_way & _GEN_31 | dirty_table_0_3;
        dirty_table_0_4 <= ~write_way & _GEN_32 | dirty_table_0_4;
        dirty_table_0_5 <= ~write_way & _GEN_33 | dirty_table_0_5;
        dirty_table_0_6 <= ~write_way & _GEN_34 | dirty_table_0_6;
        dirty_table_0_7 <= ~write_way & _GEN_35 | dirty_table_0_7;
        dirty_table_0_8 <= ~write_way & _GEN_36 | dirty_table_0_8;
        dirty_table_0_9 <= ~write_way & _GEN_37 | dirty_table_0_9;
        dirty_table_0_10 <= ~write_way & _GEN_38 | dirty_table_0_10;
        dirty_table_0_11 <= ~write_way & _GEN_39 | dirty_table_0_11;
        dirty_table_0_12 <= ~write_way & _GEN_40 | dirty_table_0_12;
        dirty_table_0_13 <= ~write_way & _GEN_41 | dirty_table_0_13;
        dirty_table_0_14 <= ~write_way & _GEN_42 | dirty_table_0_14;
        dirty_table_0_15 <= ~write_way & _GEN_43 | dirty_table_0_15;
        dirty_table_0_16 <= ~write_way & _GEN_44 | dirty_table_0_16;
        dirty_table_0_17 <= ~write_way & _GEN_45 | dirty_table_0_17;
        dirty_table_0_18 <= ~write_way & _GEN_46 | dirty_table_0_18;
        dirty_table_0_19 <= ~write_way & _GEN_47 | dirty_table_0_19;
        dirty_table_0_20 <= ~write_way & _GEN_48 | dirty_table_0_20;
        dirty_table_0_21 <= ~write_way & _GEN_49 | dirty_table_0_21;
        dirty_table_0_22 <= ~write_way & _GEN_50 | dirty_table_0_22;
        dirty_table_0_23 <= ~write_way & _GEN_51 | dirty_table_0_23;
        dirty_table_0_24 <= ~write_way & _GEN_52 | dirty_table_0_24;
        dirty_table_0_25 <= ~write_way & _GEN_53 | dirty_table_0_25;
        dirty_table_0_26 <= ~write_way & _GEN_54 | dirty_table_0_26;
        dirty_table_0_27 <= ~write_way & _GEN_55 | dirty_table_0_27;
        dirty_table_0_28 <= ~write_way & _GEN_56 | dirty_table_0_28;
        dirty_table_0_29 <= ~write_way & _GEN_57 | dirty_table_0_29;
        dirty_table_0_30 <= ~write_way & _GEN_58 | dirty_table_0_30;
        dirty_table_0_31 <= ~write_way & (&(paddr_reg_EX_MEM[9:5])) | dirty_table_0_31;
        dirty_table_1_0 <= write_way & _GEN_28 | dirty_table_1_0;
        dirty_table_1_1 <= write_way & _GEN_29 | dirty_table_1_1;
        dirty_table_1_2 <= write_way & _GEN_30 | dirty_table_1_2;
        dirty_table_1_3 <= write_way & _GEN_31 | dirty_table_1_3;
        dirty_table_1_4 <= write_way & _GEN_32 | dirty_table_1_4;
        dirty_table_1_5 <= write_way & _GEN_33 | dirty_table_1_5;
        dirty_table_1_6 <= write_way & _GEN_34 | dirty_table_1_6;
        dirty_table_1_7 <= write_way & _GEN_35 | dirty_table_1_7;
        dirty_table_1_8 <= write_way & _GEN_36 | dirty_table_1_8;
        dirty_table_1_9 <= write_way & _GEN_37 | dirty_table_1_9;
        dirty_table_1_10 <= write_way & _GEN_38 | dirty_table_1_10;
        dirty_table_1_11 <= write_way & _GEN_39 | dirty_table_1_11;
        dirty_table_1_12 <= write_way & _GEN_40 | dirty_table_1_12;
        dirty_table_1_13 <= write_way & _GEN_41 | dirty_table_1_13;
        dirty_table_1_14 <= write_way & _GEN_42 | dirty_table_1_14;
        dirty_table_1_15 <= write_way & _GEN_43 | dirty_table_1_15;
        dirty_table_1_16 <= write_way & _GEN_44 | dirty_table_1_16;
        dirty_table_1_17 <= write_way & _GEN_45 | dirty_table_1_17;
        dirty_table_1_18 <= write_way & _GEN_46 | dirty_table_1_18;
        dirty_table_1_19 <= write_way & _GEN_47 | dirty_table_1_19;
        dirty_table_1_20 <= write_way & _GEN_48 | dirty_table_1_20;
        dirty_table_1_21 <= write_way & _GEN_49 | dirty_table_1_21;
        dirty_table_1_22 <= write_way & _GEN_50 | dirty_table_1_22;
        dirty_table_1_23 <= write_way & _GEN_51 | dirty_table_1_23;
        dirty_table_1_24 <= write_way & _GEN_52 | dirty_table_1_24;
        dirty_table_1_25 <= write_way & _GEN_53 | dirty_table_1_25;
        dirty_table_1_26 <= write_way & _GEN_54 | dirty_table_1_26;
        dirty_table_1_27 <= write_way & _GEN_55 | dirty_table_1_27;
        dirty_table_1_28 <= write_way & _GEN_56 | dirty_table_1_28;
        dirty_table_1_29 <= write_way & _GEN_57 | dirty_table_1_29;
        dirty_table_1_30 <= write_way & _GEN_58 | dirty_table_1_30;
        dirty_table_1_31 <= write_way & (&(paddr_reg_EX_MEM[9:5])) | dirty_table_1_31;
      end
      else begin
        dirty_table_0_0 <= ~(dirty_clean & ~_GEN_4 & _GEN_28) & dirty_table_0_0;
        dirty_table_0_1 <= ~(dirty_clean & ~_GEN_4 & _GEN_29) & dirty_table_0_1;
        dirty_table_0_2 <= ~(dirty_clean & ~_GEN_4 & _GEN_30) & dirty_table_0_2;
        dirty_table_0_3 <= ~(dirty_clean & ~_GEN_4 & _GEN_31) & dirty_table_0_3;
        dirty_table_0_4 <= ~(dirty_clean & ~_GEN_4 & _GEN_32) & dirty_table_0_4;
        dirty_table_0_5 <= ~(dirty_clean & ~_GEN_4 & _GEN_33) & dirty_table_0_5;
        dirty_table_0_6 <= ~(dirty_clean & ~_GEN_4 & _GEN_34) & dirty_table_0_6;
        dirty_table_0_7 <= ~(dirty_clean & ~_GEN_4 & _GEN_35) & dirty_table_0_7;
        dirty_table_0_8 <= ~(dirty_clean & ~_GEN_4 & _GEN_36) & dirty_table_0_8;
        dirty_table_0_9 <= ~(dirty_clean & ~_GEN_4 & _GEN_37) & dirty_table_0_9;
        dirty_table_0_10 <= ~(dirty_clean & ~_GEN_4 & _GEN_38) & dirty_table_0_10;
        dirty_table_0_11 <= ~(dirty_clean & ~_GEN_4 & _GEN_39) & dirty_table_0_11;
        dirty_table_0_12 <= ~(dirty_clean & ~_GEN_4 & _GEN_40) & dirty_table_0_12;
        dirty_table_0_13 <= ~(dirty_clean & ~_GEN_4 & _GEN_41) & dirty_table_0_13;
        dirty_table_0_14 <= ~(dirty_clean & ~_GEN_4 & _GEN_42) & dirty_table_0_14;
        dirty_table_0_15 <= ~(dirty_clean & ~_GEN_4 & _GEN_43) & dirty_table_0_15;
        dirty_table_0_16 <= ~(dirty_clean & ~_GEN_4 & _GEN_44) & dirty_table_0_16;
        dirty_table_0_17 <= ~(dirty_clean & ~_GEN_4 & _GEN_45) & dirty_table_0_17;
        dirty_table_0_18 <= ~(dirty_clean & ~_GEN_4 & _GEN_46) & dirty_table_0_18;
        dirty_table_0_19 <= ~(dirty_clean & ~_GEN_4 & _GEN_47) & dirty_table_0_19;
        dirty_table_0_20 <= ~(dirty_clean & ~_GEN_4 & _GEN_48) & dirty_table_0_20;
        dirty_table_0_21 <= ~(dirty_clean & ~_GEN_4 & _GEN_49) & dirty_table_0_21;
        dirty_table_0_22 <= ~(dirty_clean & ~_GEN_4 & _GEN_50) & dirty_table_0_22;
        dirty_table_0_23 <= ~(dirty_clean & ~_GEN_4 & _GEN_51) & dirty_table_0_23;
        dirty_table_0_24 <= ~(dirty_clean & ~_GEN_4 & _GEN_52) & dirty_table_0_24;
        dirty_table_0_25 <= ~(dirty_clean & ~_GEN_4 & _GEN_53) & dirty_table_0_25;
        dirty_table_0_26 <= ~(dirty_clean & ~_GEN_4 & _GEN_54) & dirty_table_0_26;
        dirty_table_0_27 <= ~(dirty_clean & ~_GEN_4 & _GEN_55) & dirty_table_0_27;
        dirty_table_0_28 <= ~(dirty_clean & ~_GEN_4 & _GEN_56) & dirty_table_0_28;
        dirty_table_0_29 <= ~(dirty_clean & ~_GEN_4 & _GEN_57) & dirty_table_0_29;
        dirty_table_0_30 <= ~(dirty_clean & ~_GEN_4 & _GEN_58) & dirty_table_0_30;
        dirty_table_0_31 <=
          ~(dirty_clean & ~_GEN_4 & (&(paddr_reg_EX_MEM[9:5]))) & dirty_table_0_31;
        dirty_table_1_0 <= ~(dirty_clean & _GEN_4 & _GEN_28) & dirty_table_1_0;
        dirty_table_1_1 <= ~(dirty_clean & _GEN_4 & _GEN_29) & dirty_table_1_1;
        dirty_table_1_2 <= ~(dirty_clean & _GEN_4 & _GEN_30) & dirty_table_1_2;
        dirty_table_1_3 <= ~(dirty_clean & _GEN_4 & _GEN_31) & dirty_table_1_3;
        dirty_table_1_4 <= ~(dirty_clean & _GEN_4 & _GEN_32) & dirty_table_1_4;
        dirty_table_1_5 <= ~(dirty_clean & _GEN_4 & _GEN_33) & dirty_table_1_5;
        dirty_table_1_6 <= ~(dirty_clean & _GEN_4 & _GEN_34) & dirty_table_1_6;
        dirty_table_1_7 <= ~(dirty_clean & _GEN_4 & _GEN_35) & dirty_table_1_7;
        dirty_table_1_8 <= ~(dirty_clean & _GEN_4 & _GEN_36) & dirty_table_1_8;
        dirty_table_1_9 <= ~(dirty_clean & _GEN_4 & _GEN_37) & dirty_table_1_9;
        dirty_table_1_10 <= ~(dirty_clean & _GEN_4 & _GEN_38) & dirty_table_1_10;
        dirty_table_1_11 <= ~(dirty_clean & _GEN_4 & _GEN_39) & dirty_table_1_11;
        dirty_table_1_12 <= ~(dirty_clean & _GEN_4 & _GEN_40) & dirty_table_1_12;
        dirty_table_1_13 <= ~(dirty_clean & _GEN_4 & _GEN_41) & dirty_table_1_13;
        dirty_table_1_14 <= ~(dirty_clean & _GEN_4 & _GEN_42) & dirty_table_1_14;
        dirty_table_1_15 <= ~(dirty_clean & _GEN_4 & _GEN_43) & dirty_table_1_15;
        dirty_table_1_16 <= ~(dirty_clean & _GEN_4 & _GEN_44) & dirty_table_1_16;
        dirty_table_1_17 <= ~(dirty_clean & _GEN_4 & _GEN_45) & dirty_table_1_17;
        dirty_table_1_18 <= ~(dirty_clean & _GEN_4 & _GEN_46) & dirty_table_1_18;
        dirty_table_1_19 <= ~(dirty_clean & _GEN_4 & _GEN_47) & dirty_table_1_19;
        dirty_table_1_20 <= ~(dirty_clean & _GEN_4 & _GEN_48) & dirty_table_1_20;
        dirty_table_1_21 <= ~(dirty_clean & _GEN_4 & _GEN_49) & dirty_table_1_21;
        dirty_table_1_22 <= ~(dirty_clean & _GEN_4 & _GEN_50) & dirty_table_1_22;
        dirty_table_1_23 <= ~(dirty_clean & _GEN_4 & _GEN_51) & dirty_table_1_23;
        dirty_table_1_24 <= ~(dirty_clean & _GEN_4 & _GEN_52) & dirty_table_1_24;
        dirty_table_1_25 <= ~(dirty_clean & _GEN_4 & _GEN_53) & dirty_table_1_25;
        dirty_table_1_26 <= ~(dirty_clean & _GEN_4 & _GEN_54) & dirty_table_1_26;
        dirty_table_1_27 <= ~(dirty_clean & _GEN_4 & _GEN_55) & dirty_table_1_27;
        dirty_table_1_28 <= ~(dirty_clean & _GEN_4 & _GEN_56) & dirty_table_1_28;
        dirty_table_1_29 <= ~(dirty_clean & _GEN_4 & _GEN_57) & dirty_table_1_29;
        dirty_table_1_30 <= ~(dirty_clean & _GEN_4 & _GEN_58) & dirty_table_1_30;
        dirty_table_1_31 <=
          ~(dirty_clean & _GEN_4 & (&(paddr_reg_EX_MEM[9:5]))) & dirty_table_1_31;
      end
      state <= _GEN_67[state];
      state_backup_3 <= _GEN_71[state_backup_3];
      state_backup_4 <= _GEN_75[state_backup_4];
      if (_GEN_22 & wfsm_en)
        wrt_count <= io_d_wlen_0;
      else if (d_wvalid & io_d_wready)
        wrt_count <= 8'(wrt_count - 8'h1);
      wrt_state <= _GEN_80[wrt_state];
    end
  end // always @(posedge)
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_addra = paddr_reg_EX_MEM[9:5];
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_wea =
    ~_GEN_11 & _GEN_10 & ~tag_idx;
  xilinx_simple_dual_port_1_clock_ram_write_first #(
    .RAM_DEPTH(32),
    .RAM_WIDTH(23)
  ) xilinx_simple_dual_port_1_clock_ram_write_first (
    .addra (_xilinx_simple_dual_port_1_clock_ram_write_first_addra),
    .addrb (tagv_0_addrb),
    .dina  (tagv_0_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_write_first_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_write_first_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_1_addra = paddr_reg_EX_MEM[9:5];
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_1_wea =
    ~_GEN_11 & _GEN_10 & tag_idx;
  xilinx_simple_dual_port_1_clock_ram_write_first #(
    .RAM_DEPTH(32),
    .RAM_WIDTH(23)
  ) xilinx_simple_dual_port_1_clock_ram_write_first_1 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_write_first_1_addra),
    .addrb (tagv_1_addrb),
    .dina  (tagv_1_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_write_first_1_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb)
  );
  assign _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_addra =
    paddr_reg_EX_MEM[9:5];
  xilinx_simple_dual_port_byte_write_1_clock_ram_write_first #(
    .COL_WIDTH(8),
    .NB_COL(32),
    .RAM_DEPTH(32)
  ) xilinx_simple_dual_port_byte_write_1_clock_ram_write_first (
    .addra (_xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_addra),
    .addrb (cmem_0_addrb),
    .dina  (cmem_1_dina),
    .clka  (clock),
    .wea   (cmem_we_MEM_0),
    .doutb (_xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_doutb)
  );
  assign _xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_addra =
    paddr_reg_EX_MEM[9:5];
  xilinx_simple_dual_port_byte_write_1_clock_ram_write_first #(
    .COL_WIDTH(8),
    .NB_COL(32),
    .RAM_DEPTH(32)
  ) xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1 (
    .addra (_xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_addra),
    .addrb (cmem_1_addrb),
    .dina  (cmem_1_dina),
    .clka  (clock),
    .wea   (cmem_we_MEM_1),
    .doutb (_xilinx_simple_dual_port_byte_write_1_clock_ram_write_first_1_doutb)
  );
  assign io_cache_miss_MEM_3 =
    state_backup_3 == 3'h0
      ? _GEN_18
      : state_backup_3 == 3'h1 | state_backup_3 == 3'h2 | _GEN_19;
  assign io_cache_miss_MEM_4 = cache_miss_MEM_4;
  assign io_rdata_MEM = _highest_mask_T_2 & rdata_MEM_temp;
  assign io_cache_miss_iq_0 =
    cacop_en_reg_EX_MEM | (|(mem_type_reg_EX_MEM_backup_0[4:3]))
    & (uncache_reg_EX_MEM | ~(|hit_reg_EX_MEM_0));
  assign io_cache_miss_iq_1 =
    cacop_en_reg_EX_MEM | (|(mem_type_reg_EX_MEM_backup_1[4:3]))
    & (uncache_reg_EX_MEM | ~(|hit_reg_EX_MEM_1));
  assign io_cache_miss_iq_2 =
    cacop_en_reg_EX_MEM | (|(mem_type_reg_EX_MEM_backup_2[4:3]))
    & (uncache_reg_EX_MEM | ~(|hit_reg_EX_MEM_2));
  assign io_d_araddr =
    uncache_reg_EX_MEM ? paddr_reg_EX_MEM : {paddr_reg_EX_MEM[31:5], 5'h0};
  assign io_d_rvalid = ~_GEN_5 & _GEN_9;
  assign io_d_rsize = {1'h0, _io_d_rsize_T_1};
  assign io_d_rlen = io_d_wlen_0;
  assign io_d_awaddr = wrt_buf[31:0];
  assign io_d_wdata = wrt_buf[63:32];
  assign io_d_wvalid = d_wvalid;
  assign io_d_wlast = ~_GEN_22 & _GEN_23 & wrt_count == 8'h0;
  assign io_d_wstrb = uncache_reg_EX_MEM ? 4'(_io_d_wstrb_T_2[3:0] - 4'h1) : 4'hF;
  assign io_d_wsize = {1'h0, _io_d_wsize_T_1};
  assign io_d_wlen = io_d_wlen_0;
  assign io_d_bready = ~_GEN_22 & _GEN_23;
endmodule

