// Generated by CIRCT firtool-1.62.0
module Decode(
  input  [31:0] io_inst,
  output [4:0]  io_rj,
                io_rk,
                io_rd,
  output        io_rd_valid,
  output [31:0] io_imm,
  output [4:0]  io_alu_op,
  output        io_alu_rs1_sel,
  output [1:0]  io_alu_rs2_sel,
  output [3:0]  io_br_type,
  output [4:0]  io_mem_type,
  output [12:0] io_priv_vec,
  output [2:0]  io_fu_id,
  output [7:0]  io_exception
);

  wire              _ctrl_T_1 = {io_inst[31:10], io_inst[4:0]} == 27'h300;
  wire              _ctrl_T_3 = io_inst[31:5] == 27'h300;
  wire              _ctrl_T_5 = io_inst[31:5] == 27'h320;
  wire              _ctrl_T_7 = io_inst[31:15] == 17'h20;
  wire              _ctrl_T_9 = io_inst[31:15] == 17'h22;
  wire              _ctrl_T_11 = io_inst[31:15] == 17'h24;
  wire              _ctrl_T_13 = io_inst[31:15] == 17'h25;
  wire              _ctrl_T_15 = io_inst[31:15] == 17'h28;
  wire              _ctrl_T_17 = io_inst[31:15] == 17'h29;
  wire              _ctrl_T_19 = io_inst[31:15] == 17'h2A;
  wire              _ctrl_T_21 = io_inst[31:15] == 17'h2B;
  wire              _ctrl_T_23 = io_inst[31:15] == 17'h2E;
  wire              _ctrl_T_25 = io_inst[31:15] == 17'h2F;
  wire              _ctrl_T_27 = io_inst[31:15] == 17'h30;
  wire              _ctrl_T_29 = io_inst[31:15] == 17'h38;
  wire              _ctrl_T_31 = io_inst[31:15] == 17'h39;
  wire              _ctrl_T_33 = io_inst[31:15] == 17'h3A;
  wire              _ctrl_T_35 = io_inst[31:15] == 17'h40;
  wire              _ctrl_T_37 = io_inst[31:15] == 17'h41;
  wire              _ctrl_T_39 = io_inst[31:15] == 17'h42;
  wire              _ctrl_T_41 = io_inst[31:15] == 17'h43;
  wire              _ctrl_T_43 = io_inst[31:15] == 17'h54;
  wire              _ctrl_T_45 = io_inst[31:15] == 17'h56;
  wire              _ctrl_T_47 = io_inst[31:15] == 17'h81;
  wire              _ctrl_T_49 = io_inst[31:15] == 17'h89;
  wire              _ctrl_T_51 = io_inst[31:15] == 17'h91;
  wire              _ctrl_T_53 = io_inst[31:22] == 10'h8;
  wire              _ctrl_T_55 = io_inst[31:22] == 10'h9;
  wire              _ctrl_T_57 = io_inst[31:22] == 10'hA;
  wire              _ctrl_T_59 = io_inst[31:22] == 10'hD;
  wire              _ctrl_T_61 = io_inst[31:22] == 10'hE;
  wire              _ctrl_T_63 = io_inst[31:22] == 10'hF;
  wire [12:0]       _GEN = {io_inst[31:24], io_inst[9:5]};
  wire              _ctrl_T_65 = _GEN == 13'h80;
  wire              _ctrl_T_67 = _GEN == 13'h81;
  wire              _ctrl_T_69 = io_inst[31:24] == 8'h4;
  wire              _ctrl_T_71 = io_inst[31:22] == 10'h18;
  wire              _ctrl_T_73 = io_inst == 32'h6482800;
  wire              _ctrl_T_75 = io_inst == 32'h6482C00;
  wire              _ctrl_T_77 = io_inst == 32'h6483000;
  wire              _ctrl_T_79 = io_inst == 32'h6483400;
  wire              _ctrl_T_81 = io_inst == 32'h6483800;
  wire              _ctrl_T_83 = io_inst[31:15] == 17'hC91;
  wire              _ctrl_T_85 = io_inst[31:15] == 17'hC93;
  wire              _ctrl_T_87 = io_inst[31:25] == 7'hA;
  wire              _ctrl_T_89 = io_inst[31:25] == 7'hE;
  wire              _ctrl_T_91 = io_inst[31:24] == 8'h20;
  wire              _ctrl_T_93 = io_inst[31:24] == 8'h21;
  wire              _ctrl_T_95 = io_inst[31:22] == 10'hA0;
  wire              _ctrl_T_97 = io_inst[31:22] == 10'hA1;
  wire              _ctrl_T_99 = io_inst[31:22] == 10'hA2;
  wire              _ctrl_T_101 = io_inst[31:22] == 10'hA4;
  wire              _ctrl_T_103 = io_inst[31:22] == 10'hA5;
  wire              _ctrl_T_105 = io_inst[31:22] == 10'hA6;
  wire              _ctrl_T_107 = io_inst[31:22] == 10'hA8;
  wire              _ctrl_T_109 = io_inst[31:22] == 10'hA9;
  wire              _ctrl_T_111 = io_inst[31:26] == 6'h13;
  wire              _ctrl_T_113 = io_inst[31:26] == 6'h14;
  wire              _ctrl_T_386 = io_inst[31:26] == 6'h15;
  wire              _ctrl_T_117 = io_inst[31:26] == 6'h16;
  wire              _ctrl_T_119 = io_inst[31:26] == 6'h17;
  wire              _ctrl_T_121 = io_inst[31:26] == 6'h18;
  wire              _ctrl_T_123 = io_inst[31:26] == 6'h19;
  wire              _ctrl_T_125 = io_inst[31:26] == 6'h1A;
  wire              _ctrl_T_191 = io_inst[31:26] == 6'h1B;
  wire              _GEN_0 =
    _ctrl_T_117 | _ctrl_T_119 | _ctrl_T_121 | _ctrl_T_123 | _ctrl_T_125;
  wire              _GEN_1 = _ctrl_T_113 | _ctrl_T_386;
  wire              _GEN_2 = _ctrl_T_107 | _ctrl_T_109 | _ctrl_T_111;
  wire              _GEN_3 = _ctrl_T_87 | _ctrl_T_89;
  wire              _GEN_4 = _ctrl_T_81 | _ctrl_T_83;
  wire              _GEN_5 = _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79;
  wire              _GEN_6 = _ctrl_T_73 | _GEN_5;
  wire              _GEN_7 = _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63;
  wire              _GEN_8 =
    _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 | _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57 | _GEN_7;
  wire              _GEN_9 = _ctrl_T_43 | _ctrl_T_45;
  wire              _GEN_10 =
    _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13 | _ctrl_T_15 | _ctrl_T_17 | _ctrl_T_19
    | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25 | _ctrl_T_27 | _ctrl_T_29 | _ctrl_T_31
    | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37 | _ctrl_T_39 | _ctrl_T_41;
  wire              _GEN_11 = _ctrl_T_3 | _ctrl_T_5;
  wire              _GEN_12 = _ctrl_T_1 | _GEN_11;
  wire              _GEN_13 = _ctrl_T_107 | _ctrl_T_109 | _ctrl_T_111 | _GEN_1;
  wire              _GEN_14 = _ctrl_T_101 | _ctrl_T_103 | _ctrl_T_105;
  wire              _GEN_15 = _ctrl_T_95 | _ctrl_T_97 | _ctrl_T_99;
  wire              _GEN_16 = _ctrl_T_87 | _ctrl_T_89 | _ctrl_T_91;
  wire              _GEN_17 = _ctrl_T_67 | _ctrl_T_69;
  wire              _GEN_18 = _ctrl_T_81 | _ctrl_T_83 | _ctrl_T_85;
  wire              _GEN_19 = _ctrl_T_65 | _GEN_17;
  wire              _GEN_20 =
    _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 | _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57
    | _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63 | _GEN_19;
  wire              _GEN_21 = _ctrl_T_3 | _ctrl_T_5 | _GEN_10;
  wire              _GEN_22 = _ctrl_T_1 | _GEN_21;
  wire [3:0]        _ctrl_T_349 = _ctrl_T_63 ? 4'h7 : 4'h0;
  wire [3:0]        _ctrl_T_350 = _ctrl_T_61 ? 4'h6 : _ctrl_T_349;
  wire [3:0]        _ctrl_T_351 = _ctrl_T_59 ? 4'h5 : _ctrl_T_350;
  wire [3:0]        _ctrl_T_352 = _ctrl_T_57 ? 4'h0 : _ctrl_T_351;
  wire [3:0]        _ctrl_T_353 = _ctrl_T_55 ? 4'h3 : _ctrl_T_352;
  wire [3:0]        _ctrl_T_354 = _ctrl_T_53 ? 4'h2 : _ctrl_T_353;
  wire [3:0]        _ctrl_T_355 = _ctrl_T_51 ? 4'hA : _ctrl_T_354;
  wire [3:0]        _ctrl_T_356 = _ctrl_T_49 ? 4'h9 : _ctrl_T_355;
  wire [3:0]        _ctrl_T_357 = _ctrl_T_47 ? 4'h8 : _ctrl_T_356;
  wire [3:0]        _ctrl_T_359 = _GEN_9 ? 4'h0 : _ctrl_T_357;
  wire [3:0]        _ctrl_T_360 = _ctrl_T_41 ? 4'h7 : _ctrl_T_359;
  wire [3:0]        _ctrl_T_361 = _ctrl_T_39 ? 4'h6 : _ctrl_T_360;
  wire [3:0]        _ctrl_T_362 = _ctrl_T_37 ? 4'h5 : _ctrl_T_361;
  wire [3:0]        _ctrl_T_363 = _ctrl_T_35 ? 4'h4 : _ctrl_T_362;
  wire [3:0]        _ctrl_T_364 = _ctrl_T_33 ? 4'h2 : _ctrl_T_363;
  wire [3:0]        _ctrl_T_365 = _ctrl_T_31 ? 4'h1 : _ctrl_T_364;
  wire [3:0]        _ctrl_T_366 = _ctrl_T_29 ? 4'h0 : _ctrl_T_365;
  wire [3:0]        _ctrl_T_367 = _ctrl_T_27 ? 4'hA : _ctrl_T_366;
  wire [3:0]        _ctrl_T_368 = _ctrl_T_25 ? 4'h9 : _ctrl_T_367;
  wire [3:0]        _ctrl_T_369 = _ctrl_T_23 ? 4'h8 : _ctrl_T_368;
  wire [3:0]        _ctrl_T_370 = _ctrl_T_21 ? 4'h7 : _ctrl_T_369;
  wire [3:0]        _ctrl_T_371 = _ctrl_T_19 ? 4'h6 : _ctrl_T_370;
  wire [3:0]        _ctrl_T_372 = _ctrl_T_17 ? 4'h5 : _ctrl_T_371;
  wire [3:0]        _ctrl_T_373 = _ctrl_T_15 ? 4'h4 : _ctrl_T_372;
  wire [3:0]        _ctrl_T_374 = _ctrl_T_13 ? 4'h3 : _ctrl_T_373;
  wire [3:0]        _ctrl_T_375 = _ctrl_T_11 ? 4'h2 : _ctrl_T_374;
  wire [3:0]        _ctrl_T_376 = _ctrl_T_9 ? 4'h1 : _ctrl_T_375;
  wire [3:0]        ctrl_3 =
    _ctrl_T_1 | _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 ? 4'h0 : _ctrl_T_376;
  wire              _GEN_23 =
    _ctrl_T_95 | _ctrl_T_97 | _ctrl_T_99 | _ctrl_T_101 | _ctrl_T_103 | _ctrl_T_105
    | _ctrl_T_107 | _ctrl_T_109;
  wire              _GEN_24 = _ctrl_T_91 | _ctrl_T_93 | _GEN_23;
  wire              _GEN_25 =
    _ctrl_T_43 | _ctrl_T_45 | _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 | _ctrl_T_53
    | _ctrl_T_55 | _ctrl_T_57 | _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63 | _ctrl_T_65
    | _ctrl_T_67 | _ctrl_T_69 | _ctrl_T_71 | _ctrl_T_73 | _ctrl_T_75 | _ctrl_T_77
    | _ctrl_T_79 | _ctrl_T_81 | _ctrl_T_83 | _ctrl_T_85 | _ctrl_T_87 | _ctrl_T_89
    | _GEN_24;
  wire [1:0]        _ctrl_T_485 =
    _GEN_25 | ~(_ctrl_T_111 | ~(_ctrl_T_113 | ~_ctrl_T_386)) ? 2'h1 : 2'h2;
  wire [1:0]        _ctrl_T_503 = _GEN_10 ? 2'h0 : _ctrl_T_485;
  wire [1:0]        _ctrl_T_504 = _ctrl_T_5 ? 2'h2 : _ctrl_T_503;
  wire [1:0]        _ctrl_T_505 = _ctrl_T_3 ? 2'h3 : _ctrl_T_504;
  wire [3:0]        _ctrl_T_506 = _ctrl_T_191 ? 4'hB : 4'h0;
  wire [3:0]        _ctrl_T_507 = _ctrl_T_125 ? 4'hA : _ctrl_T_506;
  wire [3:0]        _ctrl_T_508 = _ctrl_T_123 ? 4'h9 : _ctrl_T_507;
  wire [3:0]        _ctrl_T_509 = _ctrl_T_121 ? 4'h8 : _ctrl_T_508;
  wire [3:0]        _ctrl_T_510 = _ctrl_T_119 ? 4'h7 : _ctrl_T_509;
  wire [3:0]        _ctrl_T_511 = _ctrl_T_117 ? 4'h6 : _ctrl_T_510;
  wire [3:0]        _ctrl_T_512 = _ctrl_T_386 ? 4'h5 : _ctrl_T_511;
  wire [3:0]        _ctrl_T_513 = _ctrl_T_113 ? 4'h4 : _ctrl_T_512;
  wire [3:0]        _ctrl_T_514 = _ctrl_T_111 ? 4'h3 : _ctrl_T_513;
  wire [4:0]        _ctrl_T_578 = _ctrl_T_109 ? 5'hD : 5'h0;
  wire [4:0]        _ctrl_T_579 = _ctrl_T_107 ? 5'hC : _ctrl_T_578;
  wire [4:0]        _ctrl_T_580 = _ctrl_T_105 ? 5'h12 : _ctrl_T_579;
  wire [4:0]        _ctrl_T_581 = _ctrl_T_103 ? 5'h11 : _ctrl_T_580;
  wire [4:0]        _ctrl_T_582 = _ctrl_T_101 ? 5'h10 : _ctrl_T_581;
  wire [4:0]        _ctrl_T_583 = _ctrl_T_99 ? 5'hA : _ctrl_T_582;
  wire [4:0]        _ctrl_T_584 = _ctrl_T_97 ? 5'h9 : _ctrl_T_583;
  wire [4:0]        _ctrl_T_585 = _ctrl_T_95 ? 5'h8 : _ctrl_T_584;
  wire [4:0]        _ctrl_T_586 = _ctrl_T_93 ? 5'h12 : _ctrl_T_585;
  wire [4:0]        _ctrl_T_587 = _ctrl_T_91 ? 5'hA : _ctrl_T_586;
  wire [4:0]        _ctrl_T_596 =
    _ctrl_T_73 | _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79 | _ctrl_T_81 | _ctrl_T_83
    | _ctrl_T_85 | _GEN_3
      ? 5'h0
      : _ctrl_T_587;
  wire [4:0]        _ctrl_T_597 = _ctrl_T_71 ? 5'h8 : _ctrl_T_596;
  wire              _GEN_26 =
    _ctrl_T_117 | _ctrl_T_119 | _ctrl_T_121 | _ctrl_T_123 | _ctrl_T_125 | _ctrl_T_191;
  wire              _GEN_27 = _ctrl_T_111 | _ctrl_T_113 | _ctrl_T_386 | _GEN_26;
  wire [2:0]        _ctrl_T_640 = _GEN_27 ? 3'h1 : 3'h2;
  wire [2:0]        _ctrl_T_650 = _GEN_24 ? 3'h3 : _ctrl_T_640;
  wire [2:0]        _ctrl_T_652 = _GEN_3 ? 3'h4 : _ctrl_T_650;
  wire [2:0]        _ctrl_T_659 =
    _ctrl_T_73 | _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79 | _GEN_18 ? 3'h2 : _ctrl_T_652;
  wire [2:0]        _ctrl_T_660 = _ctrl_T_71 ? 3'h3 : _ctrl_T_659;
  wire [2:0]        _ctrl_T_663 = _GEN_19 ? 3'h2 : _ctrl_T_660;
  wire [2:0]        _ctrl_T_672 = _GEN_8 ? 3'h4 : _ctrl_T_663;
  wire              _GEN_28 =
    _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37 | _ctrl_T_39
    | _ctrl_T_41 | _GEN_9;
  wire [2:0]        _ctrl_T_681 = _GEN_28 ? 3'h2 : _ctrl_T_672;
  wire [2:0]        _ctrl_T_692 =
    _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13 | _ctrl_T_15 | _ctrl_T_17 | _ctrl_T_19
    | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25 | _ctrl_T_27
      ? 3'h4
      : _ctrl_T_681;
  wire [2:0]        _ctrl_T_694 = _GEN_11 ? 3'h0 : _ctrl_T_692;
  wire [1:0]        _ctrl_T_820 =
    _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13 | _ctrl_T_15
    | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25 | _ctrl_T_27
    | _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37 | _ctrl_T_39
    | _ctrl_T_41 | _ctrl_T_43 | _ctrl_T_45 | _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51
    | _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57 | _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63
    | _ctrl_T_65 | _ctrl_T_67 | _ctrl_T_69 | _ctrl_T_71 | _ctrl_T_73 | _ctrl_T_75
    | _ctrl_T_77 | _ctrl_T_79 | _ctrl_T_81 | _ctrl_T_83 | _ctrl_T_85 | _ctrl_T_87
    | _ctrl_T_89 | _ctrl_T_91 | _ctrl_T_93 | _ctrl_T_95 | _ctrl_T_97 | _ctrl_T_99
    | _ctrl_T_101 | _ctrl_T_103 | _ctrl_T_105 | _ctrl_T_107 | _ctrl_T_109 | _ctrl_T_111
    | _ctrl_T_113
      ? 2'h0
      : {1'h0, _ctrl_T_386};
  wire [1:0]        ctrl_10 = _ctrl_T_1 ? 2'h2 : _ctrl_T_820;
  wire [3:0]        _ctrl_T_828 = _GEN_1 ? 4'h6 : {1'h0, _GEN_26, 2'h0};
  wire [3:0]        _ctrl_T_829 = _ctrl_T_111 ? 4'h4 : _ctrl_T_828;
  wire [3:0]        _ctrl_T_837 = _GEN_23 ? 4'h3 : _ctrl_T_829;
  wire [3:0]        _ctrl_T_839 = _ctrl_T_91 | _ctrl_T_93 ? 4'hB : _ctrl_T_837;
  wire [3:0]        _ctrl_T_841 = _GEN_3 ? 4'h5 : _ctrl_T_839;
  wire [3:0]        _ctrl_T_842 = _ctrl_T_85 ? 4'hA : _ctrl_T_841;
  wire [3:0]        _ctrl_T_843 = _ctrl_T_83 ? 4'h0 : _ctrl_T_842;
  wire [3:0]        _ctrl_T_844 = _ctrl_T_81 ? 4'h9 : _ctrl_T_843;
  wire [3:0]        _ctrl_T_847 = _GEN_5 ? 4'h0 : _ctrl_T_844;
  wire [3:0]        _ctrl_T_848 = _ctrl_T_73 ? 4'h8 : _ctrl_T_847;
  wire [3:0]        _ctrl_T_849 = _ctrl_T_71 ? 4'hA : _ctrl_T_848;
  wire [3:0]        _ctrl_T_852 = _GEN_19 ? 4'h7 : _ctrl_T_849;
  wire [3:0]        _ctrl_T_855 = _GEN_7 ? 4'h2 : _ctrl_T_852;
  wire [3:0]        _ctrl_T_858 =
    _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57 ? 4'h3 : _ctrl_T_855;
  wire [3:0]        _ctrl_T_861 =
    _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 ? 4'h1 : _ctrl_T_858;
  wire [3:0]        _ctrl_T_883 =
    _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13 | _ctrl_T_15
    | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25 | _ctrl_T_27
    | _GEN_28
      ? 4'h0
      : _ctrl_T_861;
  wire [3:0]        ctrl_11 = _ctrl_T_1 ? 4'h8 : _ctrl_T_883;
  wire [12:0]       _ctrl_T_901 = _ctrl_T_93 ? 13'h1001 : 13'h0;
  wire [12:0]       _ctrl_T_902 = _ctrl_T_91 ? 13'h801 : _ctrl_T_901;
  wire [12:0]       _ctrl_T_904 = _GEN_3 ? 13'h0 : _ctrl_T_902;
  wire [12:0]       _ctrl_T_905 = _ctrl_T_85 ? 13'h101 : _ctrl_T_904;
  wire [12:0]       _ctrl_T_906 = _ctrl_T_83 ? 13'h201 : _ctrl_T_905;
  wire [12:0]       _ctrl_T_907 = _ctrl_T_81 ? 13'h9 : _ctrl_T_906;
  wire [12:0]       _ctrl_T_908 = _ctrl_T_79 ? 13'h41 : _ctrl_T_907;
  wire [12:0]       _ctrl_T_909 = _ctrl_T_77 ? 13'h21 : _ctrl_T_908;
  wire [12:0]       _ctrl_T_910 = _ctrl_T_75 ? 13'h11 : _ctrl_T_909;
  wire [12:0]       _ctrl_T_911 = _ctrl_T_73 ? 13'h81 : _ctrl_T_910;
  wire [12:0]       _ctrl_T_912 = _ctrl_T_71 ? 13'h401 : _ctrl_T_911;
  wire [12:0]       _ctrl_T_913 = _ctrl_T_69 ? 13'h5 : _ctrl_T_912;
  wire [12:0]       _ctrl_T_914 = _ctrl_T_67 ? 13'h3 : _ctrl_T_913;
  wire [12:0]       _ctrl_T_915 = _ctrl_T_65 ? 13'h1 : _ctrl_T_914;
  wire [12:0]       _ctrl_T_946 =
    _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13 | _ctrl_T_15
    | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25 | _ctrl_T_27
    | _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37 | _ctrl_T_39
    | _ctrl_T_41 | _ctrl_T_43 | _ctrl_T_45 | _GEN_8
      ? 13'h0
      : _ctrl_T_915;
  wire [12:0]       ctrl_12 = _ctrl_T_1 ? 13'h1 : _ctrl_T_946;
  wire [7:0]        _ctrl_T_987 =
    _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 | _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57
    | _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63 | _ctrl_T_65 | _ctrl_T_67 | _ctrl_T_69
    | _ctrl_T_71 | _ctrl_T_73 | _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79 | _ctrl_T_81
    | _ctrl_T_83 | _ctrl_T_85 | _ctrl_T_87 | _ctrl_T_89 | _ctrl_T_91 | _ctrl_T_93
    | _ctrl_T_95 | _ctrl_T_97 | _ctrl_T_99 | _ctrl_T_101 | _ctrl_T_103 | _ctrl_T_105
    | _ctrl_T_107 | _ctrl_T_109 | _GEN_27
      ? 8'h0
      : 8'h8D;
  wire [7:0]        _ctrl_T_988 = _ctrl_T_45 ? 8'h8B : _ctrl_T_987;
  wire [7:0]        _ctrl_T_989 = _ctrl_T_43 ? 8'h8C : _ctrl_T_988;
  wire [7:0]        ctrl_13 = _GEN_22 ? 8'h0 : _ctrl_T_989;
  wire [4:0]        _io_rk_T_3 =
    ~_ctrl_T_1
    & (_GEN_21 | ~_GEN_9
       & (_GEN_8 | ~_GEN_19
          & (_ctrl_T_71 | ~(_ctrl_T_73 | _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79 | _GEN_4)
             & (_ctrl_T_85 | _GEN_16 | ~_ctrl_T_93
                & (_GEN_15 | ~_GEN_14 & (_GEN_13 | ~_GEN_26))))))
      ? io_inst[14:10]
      : io_inst[4:0];
  wire [4:0]        _io_rd_T_6 = ctrl_10 == 2'h1 ? 5'h1 : io_inst[4:0];
  wire [4:0]        io_rd_0 = ctrl_10 == 2'h2 ? io_inst[9:5] : _io_rd_T_6;
  wire [31:0]       _io_imm_imm_T_29 = {{15{io_inst[21]}}, io_inst[21:10], io_inst[4:0]};
  wire [15:0][31:0] _GEN_29 =
    {{_io_imm_imm_T_29},
     {_io_imm_imm_T_29},
     {_io_imm_imm_T_29},
     {_io_imm_imm_T_29},
     {{{18{io_inst[21]}}, io_inst[21:10], 2'h0}},
     {_io_imm_imm_T_29},
     {32'h6},
     {32'h40},
     {{18'h0, io_inst[23:10]}},
     {{{4{io_inst[9]}}, io_inst[9:0], io_inst[25:10], 2'h0}},
     {{io_inst[24:5], 12'h0}},
     {{{14{io_inst[25]}}, io_inst[25:10], 2'h0}},
     {{{20{io_inst[21]}}, io_inst[21:10]}},
     {{20'h0, io_inst[21:10]}},
     {{27'h0, io_inst[14:10]}},
     {32'h0}};
  assign io_rj =
    ~_GEN_12
    & (_GEN_10 | ~_GEN_9
       & (_GEN_8 | ~(_ctrl_T_65 | _ctrl_T_67)
          & (_ctrl_T_69 | _ctrl_T_71 | _GEN_6 | ~_GEN_4
             & (_ctrl_T_85 | ~_GEN_3
                & (_ctrl_T_91 | _ctrl_T_93 | _ctrl_T_95 | _ctrl_T_97 | _ctrl_T_99
                   | _ctrl_T_101 | _ctrl_T_103 | _ctrl_T_105 | _GEN_2 | ~_GEN_1
                   & (_GEN_0 | _ctrl_T_191))))))
      ? io_inst[9:5]
      : 5'h0;
  assign io_rk =
    ~_GEN_12
    & (_GEN_10
       | ~(_ctrl_T_43 | _ctrl_T_45 | _ctrl_T_47 | _ctrl_T_49 | _ctrl_T_51 | _ctrl_T_53
           | _ctrl_T_55 | _ctrl_T_57 | _ctrl_T_59 | _ctrl_T_61 | _ctrl_T_63 | _ctrl_T_65)
       & (_GEN_17 | ~_ctrl_T_71
          & (_GEN_6 | ~_GEN_4
             & (_ctrl_T_85 | ~_GEN_16
                & (_ctrl_T_93 | ~_GEN_15
                   & (_GEN_14 | ~_GEN_13 & (_GEN_0 | _ctrl_T_191)))))))
      ? _io_rk_T_3
      : 5'h0;
  assign io_rd = io_rd_0;
  assign io_rd_valid =
    (_GEN_22 | ~_GEN_9
     & (_GEN_20 | ~_ctrl_T_71
        & (_GEN_6 | ~_GEN_18
           & (_ctrl_T_87 | _ctrl_T_89 | _ctrl_T_91 | _ctrl_T_93 | _GEN_15 | ~_GEN_14
              & (_GEN_2 | ~_ctrl_T_113 & _ctrl_T_386))))) & (|io_rd_0);
  assign io_imm = _GEN_29[ctrl_11];
  assign io_alu_op = {1'h0, ctrl_3};
  assign io_alu_rs1_sel =
    ~(_ctrl_T_1 | _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13
      | _ctrl_T_15 | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25
      | _ctrl_T_27 | _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37
      | _ctrl_T_39 | _ctrl_T_41 | _ctrl_T_43 | _ctrl_T_45 | _ctrl_T_47 | _ctrl_T_49
      | _ctrl_T_51 | _ctrl_T_53 | _ctrl_T_55 | _ctrl_T_57 | _ctrl_T_59 | _ctrl_T_61
      | _ctrl_T_63 | _ctrl_T_65 | _ctrl_T_67 | _ctrl_T_69 | _ctrl_T_71 | _ctrl_T_73
      | _ctrl_T_75 | _ctrl_T_77 | _ctrl_T_79 | _ctrl_T_81 | _ctrl_T_83 | _ctrl_T_85
      | _ctrl_T_87)
    & (_ctrl_T_89 | ~_GEN_24 & (_ctrl_T_111 | ~_ctrl_T_113 & _ctrl_T_386));
  assign io_alu_rs2_sel = _ctrl_T_1 ? 2'h1 : _ctrl_T_505;
  assign io_br_type =
    _ctrl_T_1 | _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13
    | _ctrl_T_15 | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25
    | _ctrl_T_27 | _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37
    | _ctrl_T_39 | _ctrl_T_41 | _GEN_25
      ? 4'h0
      : _ctrl_T_514;
  assign io_mem_type =
    _ctrl_T_1 | _ctrl_T_3 | _ctrl_T_5 | _ctrl_T_7 | _ctrl_T_9 | _ctrl_T_11 | _ctrl_T_13
    | _ctrl_T_15 | _ctrl_T_17 | _ctrl_T_19 | _ctrl_T_21 | _ctrl_T_23 | _ctrl_T_25
    | _ctrl_T_27 | _ctrl_T_29 | _ctrl_T_31 | _ctrl_T_33 | _ctrl_T_35 | _ctrl_T_37
    | _ctrl_T_39 | _ctrl_T_41 | _ctrl_T_43 | _ctrl_T_45 | _GEN_20
      ? 5'h0
      : _ctrl_T_597;
  assign io_priv_vec = ctrl_12;
  assign io_fu_id = _ctrl_T_1 ? 3'h2 : _ctrl_T_694;
  assign io_exception = ctrl_12[8] & io_inst[4:0] > 5'h6 ? 8'h8D : ctrl_13;
endmodule

