// Generated by CIRCT firtool-1.62.0
module Dispatch(
  input        io_inst_packs_0_inst_valid,
  input  [2:0] io_inst_packs_0_fu_id,
  input        io_inst_packs_1_inst_valid,
  input  [2:0] io_inst_packs_1_fu_id,
  input  [3:0] io_elem_num_0,
               io_elem_num_1,
  output       io_insts_disp_index_0_0,
               io_insts_disp_index_1_0,
               io_insts_disp_index_2_0,
               io_insts_disp_index_3_0,
               io_insts_disp_valid_0_0,
               io_insts_disp_valid_0_1,
               io_insts_disp_valid_1_0,
               io_insts_disp_valid_1_1,
               io_insts_disp_valid_2_0,
               io_insts_disp_valid_2_1,
               io_insts_disp_valid_3_0,
               io_insts_disp_valid_3_1
);

  wire [2:0] _GEN = {2'h0, io_elem_num_0 > io_elem_num_1};
  wire [2:0] _queue_id_hit_0_T_1 =
    io_inst_packs_0_fu_id == 3'h4 ? _GEN : io_inst_packs_0_fu_id;
  wire [7:0] _queue_id_hit_0_T_2 = 8'h1 << _queue_id_hit_0_T_1;
  wire [3:0] queue_id_hit_0 = _queue_id_hit_0_T_2[3:0] & {4{io_inst_packs_0_inst_valid}};
  wire [2:0] _queue_id_hit_1_T_1 =
    io_inst_packs_1_fu_id == 3'h4 ? _GEN : io_inst_packs_1_fu_id;
  wire [7:0] _queue_id_hit_1_T_2 = 8'h1 << _queue_id_hit_1_T_1;
  wire [3:0] queue_id_hit_1 = _queue_id_hit_1_T_2[3:0] & {4{io_inst_packs_1_inst_valid}};
  assign io_insts_disp_index_0_0 = ~(queue_id_hit_0[0]);
  assign io_insts_disp_index_1_0 = ~(queue_id_hit_0[1]);
  assign io_insts_disp_index_2_0 = ~(queue_id_hit_0[2]);
  assign io_insts_disp_index_3_0 = ~(queue_id_hit_0[3]);
  assign io_insts_disp_valid_0_0 =
    queue_id_hit_0[0] ? queue_id_hit_0[0] : queue_id_hit_1[0];
  assign io_insts_disp_valid_0_1 = queue_id_hit_0[0] & queue_id_hit_1[0];
  assign io_insts_disp_valid_1_0 =
    queue_id_hit_0[1] ? queue_id_hit_0[1] : queue_id_hit_1[1];
  assign io_insts_disp_valid_1_1 = queue_id_hit_0[1] & queue_id_hit_1[1];
  assign io_insts_disp_valid_2_0 =
    queue_id_hit_0[2] ? queue_id_hit_0[2] : queue_id_hit_1[2];
  assign io_insts_disp_valid_2_1 = queue_id_hit_0[2] & queue_id_hit_1[2];
  assign io_insts_disp_valid_3_0 =
    queue_id_hit_0[3] ? queue_id_hit_0[3] : queue_id_hit_1[3];
  assign io_insts_disp_valid_3_1 = queue_id_hit_0[3] & queue_id_hit_1[3];
endmodule

