// Generated by CIRCT firtool-1.62.0
module Divide(
  input         clock,
                reset,
  input  [31:0] io_src1,
                io_src2,
  input  [4:0]  io_op,
  output [31:0] io_res,
  output        io_busy_6,
                io_busy_7,
                io_busy_8,
                io_busy_9,
                io_busy_10,
                io_busy_11,
                io_busy_12,
                io_busy_13,
                io_busy_14,
                io_busy_15,
                io_busy_16,
                io_busy_17,
                io_busy_18,
                io_busy_19,
                io_busy_20
);

  reg  [5:0]  cnt_0;
  reg  [5:0]  cnt_1;
  reg  [5:0]  cnt_2;
  reg  [5:0]  cnt_3;
  reg  [5:0]  cnt_4;
  reg  [5:0]  cnt_5;
  reg  [5:0]  cnt_6;
  reg  [5:0]  cnt_7;
  reg  [5:0]  cnt_8;
  reg  [5:0]  cnt_9;
  reg  [5:0]  cnt_10;
  reg  [5:0]  cnt_11;
  reg  [5:0]  cnt_12;
  reg  [5:0]  cnt_13;
  reg  [5:0]  cnt_14;
  reg  [5:0]  cnt_15;
  reg  [5:0]  cnt_16;
  reg  [5:0]  cnt_17;
  reg  [5:0]  cnt_18;
  reg  [5:0]  cnt_19;
  reg  [5:0]  cnt_20;
  reg  [31:0] src1_reg1;
  reg  [31:0] src2_reg1;
  reg  [4:0]  op_reg1;
  reg         res_sign_reg1;
  reg         en_reg1;
  reg  [4:0]  high_rev_reg1;
  reg  [31:0] src2_reg2;
  reg  [4:0]  op_reg2;
  reg         res_sign_reg2;
  reg  [64:0] quo_rem;
  wire [31:0] _io_res_T_5 = res_sign_reg2 ? 32'(~(quo_rem[31:0]) + 32'h1) : quo_rem[31:0];
  wire [31:0] _io_res_T_12 =
    res_sign_reg2 ? 32'(~(quo_rem[64:33]) + 32'h1) : quo_rem[64:33];
  wire [31:0] _io_res_T_15 = op_reg2 == 5'h4 ? _io_res_T_5 : 32'h0;
  wire [31:0] _io_res_T_17 = op_reg2 == 5'h6 ? quo_rem[31:0] : _io_res_T_15;
  wire [31:0] _io_res_T_19 = op_reg2 == 5'h5 ? _io_res_T_12 : _io_res_T_17;
  wire [95:0] _quo_rem_T_9 = {64'h0, src1_reg1} << high_rev_reg1;
  wire [5:0]  _GEN = {1'h0, high_rev_reg1};
  wire        _src2_T = io_op == 5'h4;
  wire        _src2_T_1 = io_op == 5'h5;
  wire [31:0] src1 =
    (_src2_T | _src2_T_1) & io_src1[31] ? 32'(~io_src1 + 32'h1) : io_src1;
  wire        _res_sign_T_9 =
    io_op == 5'h5
      ? io_src1[31]
      : io_op != 5'h6 & io_op == 5'h4 & (io_src1[31] ^ io_src2[31]);
  wire [7:0]  _GEN_0 =
    {{src1[11:8], src1[15:14]} & 6'h33, 2'h0} | {src1[15:12], src1[19:16]} & 8'h33;
  wire [18:0] _GEN_1 =
    {src1[5:4], src1[7:6], src1[9:8], _GEN_0, src1[19:18], src1[21:20], src1[23]}
    & 19'h55555;
  wire [3:0]  _GEN_2 = _GEN_1[18:15] | {src1[7:6], src1[9:8]} & 4'h5;
  wire [7:0]  _GEN_3 = _GEN_1[14:7] | _GEN_0 & 8'h55;
  wire [3:0]  _GEN_4 = {_GEN_1[2:0], 1'h0} | {src1[23:22], src1[25:24]} & 4'h5;
  wire [4:0]  _high_rev_T_82 = src1[2] ? 5'h1D : {4'hF, ~(src1[1])};
  wire [4:0]  _high_rev_T_83 = src1[3] ? 5'h1C : _high_rev_T_82;
  wire [4:0]  _high_rev_T_84 = src1[4] ? 5'h1B : _high_rev_T_83;
  wire [4:0]  _high_rev_T_85 = _GEN_2[3] ? 5'h1A : _high_rev_T_84;
  wire [4:0]  _high_rev_T_86 = _GEN_2[2] ? 5'h19 : _high_rev_T_85;
  wire [4:0]  _high_rev_T_87 = _GEN_2[1] ? 5'h18 : _high_rev_T_86;
  wire [4:0]  _high_rev_T_88 = _GEN_2[0] ? 5'h17 : _high_rev_T_87;
  wire [4:0]  _high_rev_T_89 = _GEN_3[7] ? 5'h16 : _high_rev_T_88;
  wire [4:0]  _high_rev_T_90 = _GEN_3[6] ? 5'h15 : _high_rev_T_89;
  wire [4:0]  _high_rev_T_91 = _GEN_3[5] ? 5'h14 : _high_rev_T_90;
  wire [4:0]  _high_rev_T_92 = _GEN_3[4] ? 5'h13 : _high_rev_T_91;
  wire [4:0]  _high_rev_T_93 = _GEN_3[3] ? 5'h12 : _high_rev_T_92;
  wire [4:0]  _high_rev_T_94 = _GEN_3[2] ? 5'h11 : _high_rev_T_93;
  wire [4:0]  _high_rev_T_95 = _GEN_3[1] ? 5'h10 : _high_rev_T_94;
  wire [4:0]  _high_rev_T_96 = _GEN_3[0] ? 5'hF : _high_rev_T_95;
  wire [4:0]  _high_rev_T_97 = _GEN_0[1] ? 5'hE : _high_rev_T_96;
  wire [4:0]  _high_rev_T_98 = _GEN_1[5] | src1[18] ? 5'hD : _high_rev_T_97;
  wire [4:0]  _high_rev_T_99 = src1[19] ? 5'hC : _high_rev_T_98;
  wire [4:0]  _high_rev_T_100 = src1[20] ? 5'hB : _high_rev_T_99;
  wire [4:0]  _high_rev_T_101 = _GEN_4[3] ? 5'hA : _high_rev_T_100;
  wire [4:0]  _high_rev_T_102 = _GEN_4[2] ? 5'h9 : _high_rev_T_101;
  wire [4:0]  _high_rev_T_103 = _GEN_4[1] ? 5'h8 : _high_rev_T_102;
  wire [4:0]  _high_rev_T_104 = _GEN_4[0] ? 5'h7 : _high_rev_T_103;
  wire [4:0]  _high_rev_T_105 = src1[25] ? 5'h6 : _high_rev_T_104;
  wire [4:0]  _high_rev_T_106 = src1[26] ? 5'h5 : _high_rev_T_105;
  wire [4:0]  _high_rev_T_107 = src1[27] ? 5'h4 : _high_rev_T_106;
  wire [4:0]  _high_rev_T_108 = src1[28] ? 5'h3 : _high_rev_T_107;
  wire [4:0]  _high_rev_T_109 = src1[29] ? 5'h2 : _high_rev_T_108;
  wire [4:0]  _high_rev_T_110 = src1[30] ? 5'h1 : _high_rev_T_109;
  always @(posedge clock) begin
    if (reset) begin
      cnt_0 <= 6'h0;
      cnt_1 <= 6'h0;
      cnt_2 <= 6'h0;
      cnt_3 <= 6'h0;
      cnt_4 <= 6'h0;
      cnt_5 <= 6'h0;
      cnt_6 <= 6'h0;
      cnt_7 <= 6'h0;
      cnt_8 <= 6'h0;
      cnt_9 <= 6'h0;
      cnt_10 <= 6'h0;
      cnt_11 <= 6'h0;
      cnt_12 <= 6'h0;
      cnt_13 <= 6'h0;
      cnt_14 <= 6'h0;
      cnt_15 <= 6'h0;
      cnt_16 <= 6'h0;
      cnt_17 <= 6'h0;
      cnt_18 <= 6'h0;
      cnt_19 <= 6'h0;
      cnt_20 <= 6'h0;
      src2_reg2 <= 32'h0;
      op_reg2 <= 5'h0;
      res_sign_reg2 <= 1'h0;
      quo_rem <= 65'h0;
    end
    else begin
      if (|cnt_0)
        cnt_0 <= 6'(cnt_0 - 6'h1);
      else if (en_reg1)
        cnt_0 <= 6'(6'h21 - _GEN);
      if (|cnt_1)
        cnt_1 <= 6'(cnt_1 - 6'h1);
      else if (en_reg1)
        cnt_1 <= 6'(6'h21 - _GEN);
      if (|cnt_2)
        cnt_2 <= 6'(cnt_2 - 6'h1);
      else if (en_reg1)
        cnt_2 <= 6'(6'h21 - _GEN);
      if (|cnt_3)
        cnt_3 <= 6'(cnt_3 - 6'h1);
      else if (en_reg1)
        cnt_3 <= 6'(6'h21 - _GEN);
      if (|cnt_4)
        cnt_4 <= 6'(cnt_4 - 6'h1);
      else if (en_reg1)
        cnt_4 <= 6'(6'h21 - _GEN);
      if (|cnt_5) begin
        cnt_5 <= 6'(cnt_5 - 6'h1);
        if (quo_rem[63:32] >= src2_reg2)
          quo_rem <= {32'(quo_rem[63:32] - src2_reg2), quo_rem[31:0], 1'h1};
        else
          quo_rem <= {quo_rem[63:0], 1'h0};
      end
      else if (en_reg1) begin
        cnt_5 <= 6'(6'h21 - _GEN);
        quo_rem <= _quo_rem_T_9[64:0];
      end
      if (|cnt_6)
        cnt_6 <= 6'(cnt_6 - 6'h1);
      else if (en_reg1)
        cnt_6 <= 6'(6'h21 - _GEN);
      if (|cnt_7)
        cnt_7 <= 6'(cnt_7 - 6'h1);
      else if (en_reg1)
        cnt_7 <= 6'(6'h21 - _GEN);
      if (|cnt_8)
        cnt_8 <= 6'(cnt_8 - 6'h1);
      else if (en_reg1)
        cnt_8 <= 6'(6'h21 - _GEN);
      if (|cnt_9)
        cnt_9 <= 6'(cnt_9 - 6'h1);
      else if (en_reg1)
        cnt_9 <= 6'(6'h21 - _GEN);
      if (|cnt_10)
        cnt_10 <= 6'(cnt_10 - 6'h1);
      else if (en_reg1)
        cnt_10 <= 6'(6'h21 - _GEN);
      if (|cnt_11)
        cnt_11 <= 6'(cnt_11 - 6'h1);
      else if (en_reg1)
        cnt_11 <= 6'(6'h21 - _GEN);
      if (|cnt_12)
        cnt_12 <= 6'(cnt_12 - 6'h1);
      else if (en_reg1)
        cnt_12 <= 6'(6'h21 - _GEN);
      if (|cnt_13)
        cnt_13 <= 6'(cnt_13 - 6'h1);
      else if (en_reg1)
        cnt_13 <= 6'(6'h21 - _GEN);
      if (|cnt_14)
        cnt_14 <= 6'(cnt_14 - 6'h1);
      else if (en_reg1)
        cnt_14 <= 6'(6'h21 - _GEN);
      if (|cnt_15)
        cnt_15 <= 6'(cnt_15 - 6'h1);
      else if (en_reg1)
        cnt_15 <= 6'(6'h21 - _GEN);
      if (|cnt_16)
        cnt_16 <= 6'(cnt_16 - 6'h1);
      else if (en_reg1)
        cnt_16 <= 6'(6'h21 - _GEN);
      if (|cnt_17)
        cnt_17 <= 6'(cnt_17 - 6'h1);
      else if (en_reg1)
        cnt_17 <= 6'(6'h21 - _GEN);
      if (|cnt_18)
        cnt_18 <= 6'(cnt_18 - 6'h1);
      else if (en_reg1)
        cnt_18 <= 6'(6'h21 - _GEN);
      if (|cnt_19)
        cnt_19 <= 6'(cnt_19 - 6'h1);
      else if (en_reg1)
        cnt_19 <= 6'(6'h21 - _GEN);
      if (|cnt_20)
        cnt_20 <= 6'(cnt_20 - 6'h1);
      else if (en_reg1)
        cnt_20 <= 6'(6'h21 - _GEN);
      if (en_reg1 & ~(|cnt_4)) begin
        src2_reg2 <= src2_reg1;
        op_reg2 <= op_reg1;
        res_sign_reg2 <= res_sign_reg1;
      end
    end
    if (~(|cnt_0))
      src1_reg1 <= src1;
    if (~(|cnt_1))
      src2_reg1 <= (_src2_T | _src2_T_1) & io_src2[31] ? 32'(~io_src2 + 32'h1) : io_src2;
    if (~(|cnt_2)) begin
      op_reg1 <= io_op;
      res_sign_reg1 <= io_op != 5'h7 & _res_sign_T_9;
      en_reg1 <= io_op[2];
    end
    if (~(|cnt_3))
      high_rev_reg1 <= src1[31] ? 5'h0 : _high_rev_T_110;
  end // always @(posedge)
  assign io_res = op_reg2 == 5'h7 ? quo_rem[64:33] : _io_res_T_19;
  assign io_busy_6 = |cnt_6;
  assign io_busy_7 = |cnt_7;
  assign io_busy_8 = |cnt_8;
  assign io_busy_9 = |cnt_9;
  assign io_busy_10 = |cnt_10;
  assign io_busy_11 = |cnt_11;
  assign io_busy_12 = |cnt_12;
  assign io_busy_13 = |cnt_13;
  assign io_busy_14 = |cnt_14;
  assign io_busy_15 = |cnt_15;
  assign io_busy_16 = |cnt_16;
  assign io_busy_17 = |cnt_17;
  assign io_busy_18 = |cnt_18;
  assign io_busy_19 = |cnt_19;
  assign io_busy_20 = |cnt_20;
endmodule

