// Generated by CIRCT firtool-1.62.0
module Fetch_Queue(
  input         clock,
                reset,
  input  [31:0] io_insts_pack_0_pc,
                io_insts_pack_0_inst,
  input         io_insts_pack_0_inst_valid,
                io_insts_pack_0_predict_jump,
  input  [31:0] io_insts_pack_0_pred_npc,
  input  [7:0]  io_insts_pack_0_exception,
  input  [31:0] io_insts_pack_1_pc,
                io_insts_pack_1_inst,
  input         io_insts_pack_1_inst_valid,
                io_insts_pack_1_predict_jump,
  input  [31:0] io_insts_pack_1_pred_npc,
  input  [7:0]  io_insts_pack_1_exception,
  input         io_next_ready,
  output        io_insts_valid_decode_0,
                io_insts_valid_decode_1,
  output [31:0] io_insts_pack_id_0_pc,
                io_insts_pack_id_0_inst,
  output        io_insts_pack_id_0_predict_jump,
  output [31:0] io_insts_pack_id_0_pred_npc,
  output [7:0]  io_insts_pack_id_0_exception,
  output [31:0] io_insts_pack_id_1_pc,
                io_insts_pack_id_1_inst,
  output        io_insts_pack_id_1_predict_jump,
  output [31:0] io_insts_pack_id_1_pred_npc,
  output [7:0]  io_insts_pack_id_1_exception,
  output        io_full,
  input         io_flush
);

  reg  [31:0] queue_0_0_pc;
  reg  [31:0] queue_0_0_inst;
  reg         queue_0_0_predict_jump;
  reg  [31:0] queue_0_0_pred_npc;
  reg  [7:0]  queue_0_0_exception;
  reg  [31:0] queue_0_1_pc;
  reg  [31:0] queue_0_1_inst;
  reg         queue_0_1_predict_jump;
  reg  [31:0] queue_0_1_pred_npc;
  reg  [7:0]  queue_0_1_exception;
  reg  [31:0] queue_0_2_pc;
  reg  [31:0] queue_0_2_inst;
  reg         queue_0_2_predict_jump;
  reg  [31:0] queue_0_2_pred_npc;
  reg  [7:0]  queue_0_2_exception;
  reg  [31:0] queue_0_3_pc;
  reg  [31:0] queue_0_3_inst;
  reg         queue_0_3_predict_jump;
  reg  [31:0] queue_0_3_pred_npc;
  reg  [7:0]  queue_0_3_exception;
  reg  [31:0] queue_1_0_pc;
  reg  [31:0] queue_1_0_inst;
  reg         queue_1_0_predict_jump;
  reg  [31:0] queue_1_0_pred_npc;
  reg  [7:0]  queue_1_0_exception;
  reg  [31:0] queue_1_1_pc;
  reg  [31:0] queue_1_1_inst;
  reg         queue_1_1_predict_jump;
  reg  [31:0] queue_1_1_pred_npc;
  reg  [7:0]  queue_1_1_exception;
  reg  [31:0] queue_1_2_pc;
  reg  [31:0] queue_1_2_inst;
  reg         queue_1_2_predict_jump;
  reg  [31:0] queue_1_2_pred_npc;
  reg  [7:0]  queue_1_2_exception;
  reg  [31:0] queue_1_3_pc;
  reg  [31:0] queue_1_3_inst;
  reg         queue_1_3_predict_jump;
  reg  [31:0] queue_1_3_pred_npc;
  reg  [7:0]  queue_1_3_exception;
  reg  [3:0]  head;
  reg  [7:0]  tail;
  wire [3:0]  tail_even = {tail[6], tail[4], tail[2], tail[0]};
  wire [3:0]  tail_for_compare = {tail[7], tail[5], tail[3], tail[1]} | tail_even;
  wire [3:0]  _full_T_3 = head & {tail_for_compare[2:0], tail_for_compare[3]};
  wire [7:0]  _io_insts_pack_id_0_T_4 = head[0] ? queue_0_0_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_5 = head[1] ? queue_0_1_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_6 = head[2] ? queue_0_2_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_0_T_7 = head[3] ? queue_0_3_exception : 8'h0;
  wire [31:0] _io_insts_pack_id_0_T_11 = head[0] ? queue_0_0_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_12 = head[1] ? queue_0_1_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_13 = head[2] ? queue_0_2_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_14 = head[3] ? queue_0_3_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_32 = head[0] ? queue_0_0_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_33 = head[1] ? queue_0_1_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_34 = head[2] ? queue_0_2_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_35 = head[3] ? queue_0_3_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_39 = head[0] ? queue_0_0_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_40 = head[1] ? queue_0_1_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_41 = head[2] ? queue_0_2_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_0_T_42 = head[3] ? queue_0_3_pc : 32'h0;
  wire        io_insts_valid_decode_1_0 = (head & tail_for_compare) == 4'h0;
  wire [7:0]  _io_insts_pack_id_1_T_4 = head[0] ? queue_1_0_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_5 = head[1] ? queue_1_1_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_6 = head[2] ? queue_1_2_exception : 8'h0;
  wire [7:0]  _io_insts_pack_id_1_T_7 = head[3] ? queue_1_3_exception : 8'h0;
  wire [31:0] _io_insts_pack_id_1_T_11 = head[0] ? queue_1_0_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_12 = head[1] ? queue_1_1_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_13 = head[2] ? queue_1_2_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_14 = head[3] ? queue_1_3_pred_npc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_32 = head[0] ? queue_1_0_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_33 = head[1] ? queue_1_1_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_34 = head[2] ? queue_1_2_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_35 = head[3] ? queue_1_3_inst : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_39 = head[0] ? queue_1_0_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_40 = head[1] ? queue_1_1_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_41 = head[2] ? queue_1_2_pc : 32'h0;
  wire [31:0] _io_insts_pack_id_1_T_42 = head[3] ? queue_1_3_pc : 32'h0;
  wire [7:0]  write_mask =
    tail & {8{io_insts_pack_0_inst_valid}} | {tail[6:0], tail[7]}
    & {8{io_insts_pack_1_inst_valid}};
  wire [31:0] write_data_even_pc = (|tail_even) ? io_insts_pack_0_pc : io_insts_pack_1_pc;
  wire [31:0] write_data_even_inst =
    (|tail_even) ? io_insts_pack_0_inst : io_insts_pack_1_inst;
  wire        write_data_even_predict_jump =
    (|tail_even) ? io_insts_pack_0_predict_jump : io_insts_pack_1_predict_jump;
  wire [31:0] write_data_even_pred_npc =
    (|tail_even) ? io_insts_pack_0_pred_npc : io_insts_pack_1_pred_npc;
  wire [7:0]  write_data_even_exception =
    (|tail_even) ? io_insts_pack_0_exception : io_insts_pack_1_exception;
  wire [31:0] write_data_odd_pc = (|tail_even) ? io_insts_pack_1_pc : io_insts_pack_0_pc;
  wire [31:0] write_data_odd_inst =
    (|tail_even) ? io_insts_pack_1_inst : io_insts_pack_0_inst;
  wire        write_data_odd_predict_jump =
    (|tail_even) ? io_insts_pack_1_predict_jump : io_insts_pack_0_predict_jump;
  wire [31:0] write_data_odd_pred_npc =
    (|tail_even) ? io_insts_pack_1_pred_npc : io_insts_pack_0_pred_npc;
  wire [7:0]  write_data_odd_exception =
    (|tail_even) ? io_insts_pack_1_exception : io_insts_pack_0_exception;
  always @(posedge clock) begin
    if (reset) begin
      queue_0_0_pc <= 32'h0;
      queue_0_0_inst <= 32'h0;
      queue_0_0_predict_jump <= 1'h0;
      queue_0_0_pred_npc <= 32'h0;
      queue_0_0_exception <= 8'h0;
      queue_0_1_pc <= 32'h0;
      queue_0_1_inst <= 32'h0;
      queue_0_1_predict_jump <= 1'h0;
      queue_0_1_pred_npc <= 32'h0;
      queue_0_1_exception <= 8'h0;
      queue_0_2_pc <= 32'h0;
      queue_0_2_inst <= 32'h0;
      queue_0_2_predict_jump <= 1'h0;
      queue_0_2_pred_npc <= 32'h0;
      queue_0_2_exception <= 8'h0;
      queue_0_3_pc <= 32'h0;
      queue_0_3_inst <= 32'h0;
      queue_0_3_predict_jump <= 1'h0;
      queue_0_3_pred_npc <= 32'h0;
      queue_0_3_exception <= 8'h0;
      queue_1_0_pc <= 32'h0;
      queue_1_0_inst <= 32'h0;
      queue_1_0_predict_jump <= 1'h0;
      queue_1_0_pred_npc <= 32'h0;
      queue_1_0_exception <= 8'h0;
      queue_1_1_pc <= 32'h0;
      queue_1_1_inst <= 32'h0;
      queue_1_1_predict_jump <= 1'h0;
      queue_1_1_pred_npc <= 32'h0;
      queue_1_1_exception <= 8'h0;
      queue_1_2_pc <= 32'h0;
      queue_1_2_inst <= 32'h0;
      queue_1_2_predict_jump <= 1'h0;
      queue_1_2_pred_npc <= 32'h0;
      queue_1_2_exception <= 8'h0;
      queue_1_3_pc <= 32'h0;
      queue_1_3_inst <= 32'h0;
      queue_1_3_predict_jump <= 1'h0;
      queue_1_3_pred_npc <= 32'h0;
      queue_1_3_exception <= 8'h0;
      head <= 4'h1;
      tail <= 8'h1;
    end
    else begin
      if (~(|_full_T_3) & write_mask[0]) begin
        queue_0_0_pc <= write_data_even_pc;
        queue_0_0_inst <= write_data_even_inst;
        queue_0_0_predict_jump <= write_data_even_predict_jump;
        queue_0_0_pred_npc <= write_data_even_pred_npc;
        queue_0_0_exception <= write_data_even_exception;
      end
      if (~(|_full_T_3) & write_mask[2]) begin
        queue_0_1_pc <= write_data_even_pc;
        queue_0_1_inst <= write_data_even_inst;
        queue_0_1_predict_jump <= write_data_even_predict_jump;
        queue_0_1_pred_npc <= write_data_even_pred_npc;
        queue_0_1_exception <= write_data_even_exception;
      end
      if (~(|_full_T_3) & write_mask[4]) begin
        queue_0_2_pc <= write_data_even_pc;
        queue_0_2_inst <= write_data_even_inst;
        queue_0_2_predict_jump <= write_data_even_predict_jump;
        queue_0_2_pred_npc <= write_data_even_pred_npc;
        queue_0_2_exception <= write_data_even_exception;
      end
      if (~(|_full_T_3) & write_mask[6]) begin
        queue_0_3_pc <= write_data_even_pc;
        queue_0_3_inst <= write_data_even_inst;
        queue_0_3_predict_jump <= write_data_even_predict_jump;
        queue_0_3_pred_npc <= write_data_even_pred_npc;
        queue_0_3_exception <= write_data_even_exception;
      end
      if (~(|_full_T_3) & write_mask[1]) begin
        queue_1_0_pc <= write_data_odd_pc;
        queue_1_0_inst <= write_data_odd_inst;
        queue_1_0_predict_jump <= write_data_odd_predict_jump;
        queue_1_0_pred_npc <= write_data_odd_pred_npc;
        queue_1_0_exception <= write_data_odd_exception;
      end
      if (~(|_full_T_3) & write_mask[3]) begin
        queue_1_1_pc <= write_data_odd_pc;
        queue_1_1_inst <= write_data_odd_inst;
        queue_1_1_predict_jump <= write_data_odd_predict_jump;
        queue_1_1_pred_npc <= write_data_odd_pred_npc;
        queue_1_1_exception <= write_data_odd_exception;
      end
      if (~(|_full_T_3) & write_mask[5]) begin
        queue_1_2_pc <= write_data_odd_pc;
        queue_1_2_inst <= write_data_odd_inst;
        queue_1_2_predict_jump <= write_data_odd_predict_jump;
        queue_1_2_pred_npc <= write_data_odd_pred_npc;
        queue_1_2_exception <= write_data_odd_exception;
      end
      if (~(|_full_T_3) & write_mask[7]) begin
        queue_1_3_pc <= write_data_odd_pc;
        queue_1_3_inst <= write_data_odd_inst;
        queue_1_3_predict_jump <= write_data_odd_predict_jump;
        queue_1_3_pred_npc <= write_data_odd_pred_npc;
        queue_1_3_exception <= write_data_odd_exception;
      end
      if (io_flush) begin
        head <= 4'h1;
        tail <= 8'h1;
      end
      else begin
        if (io_next_ready & io_insts_valid_decode_1_0)
          head <= {head[2:0], head[3]};
        if (~(|_full_T_3) & io_insts_pack_0_inst_valid) begin
          if (io_insts_pack_1_inst_valid)
            tail <= {tail[5:0], tail[7:6]};
          else
            tail <= {tail[6:0], tail[7]};
        end
      end
    end
  end // always @(posedge)
  assign io_insts_valid_decode_0 = io_insts_valid_decode_1_0;
  assign io_insts_valid_decode_1 = io_insts_valid_decode_1_0;
  assign io_insts_pack_id_0_pc =
    _io_insts_pack_id_0_T_39 | _io_insts_pack_id_0_T_40 | _io_insts_pack_id_0_T_41
    | _io_insts_pack_id_0_T_42;
  assign io_insts_pack_id_0_inst =
    _io_insts_pack_id_0_T_32 | _io_insts_pack_id_0_T_33 | _io_insts_pack_id_0_T_34
    | _io_insts_pack_id_0_T_35;
  assign io_insts_pack_id_0_predict_jump =
    head[0] & queue_0_0_predict_jump | head[1] & queue_0_1_predict_jump | head[2]
    & queue_0_2_predict_jump | head[3] & queue_0_3_predict_jump;
  assign io_insts_pack_id_0_pred_npc =
    _io_insts_pack_id_0_T_11 | _io_insts_pack_id_0_T_12 | _io_insts_pack_id_0_T_13
    | _io_insts_pack_id_0_T_14;
  assign io_insts_pack_id_0_exception =
    _io_insts_pack_id_0_T_4 | _io_insts_pack_id_0_T_5 | _io_insts_pack_id_0_T_6
    | _io_insts_pack_id_0_T_7;
  assign io_insts_pack_id_1_pc =
    _io_insts_pack_id_1_T_39 | _io_insts_pack_id_1_T_40 | _io_insts_pack_id_1_T_41
    | _io_insts_pack_id_1_T_42;
  assign io_insts_pack_id_1_inst =
    _io_insts_pack_id_1_T_32 | _io_insts_pack_id_1_T_33 | _io_insts_pack_id_1_T_34
    | _io_insts_pack_id_1_T_35;
  assign io_insts_pack_id_1_predict_jump =
    head[0] & queue_1_0_predict_jump | head[1] & queue_1_1_predict_jump | head[2]
    & queue_1_2_predict_jump | head[3] & queue_1_3_predict_jump;
  assign io_insts_pack_id_1_pred_npc =
    _io_insts_pack_id_1_T_11 | _io_insts_pack_id_1_T_12 | _io_insts_pack_id_1_T_13
    | _io_insts_pack_id_1_T_14;
  assign io_insts_pack_id_1_exception =
    _io_insts_pack_id_1_T_4 | _io_insts_pack_id_1_T_5 | _io_insts_pack_id_1_T_6
    | _io_insts_pack_id_1_T_7;
  assign io_full = |_full_T_3;
endmodule

