// Generated by CIRCT firtool-1.62.0
module Free_List(
  input        clock,
               reset,
               io_rd_valid_0,
               io_rd_valid_1,
               io_rename_en_0,
               io_rename_en_1,
  output [5:0] io_alloc_preg_0,
               io_alloc_preg_1,
  output       io_empty,
  input        io_commit_en_0,
               io_commit_en_1,
               io_commit_pprd_valid_0,
               io_commit_pprd_valid_1,
  input  [5:0] io_commit_pprd_0,
               io_commit_pprd_1,
  input        io_predict_fail,
  input  [5:0] io_head_arch
);

  reg  [5:0]  free_list_0;
  reg  [5:0]  free_list_1;
  reg  [5:0]  free_list_2;
  reg  [5:0]  free_list_3;
  reg  [5:0]  free_list_4;
  reg  [5:0]  free_list_5;
  reg  [5:0]  free_list_6;
  reg  [5:0]  free_list_7;
  reg  [5:0]  free_list_8;
  reg  [5:0]  free_list_9;
  reg  [5:0]  free_list_10;
  reg  [5:0]  free_list_11;
  reg  [5:0]  free_list_12;
  reg  [5:0]  free_list_13;
  reg  [5:0]  free_list_14;
  reg  [5:0]  free_list_15;
  reg  [5:0]  free_list_16;
  reg  [5:0]  free_list_17;
  reg  [5:0]  free_list_18;
  reg  [5:0]  free_list_19;
  reg  [5:0]  free_list_20;
  reg  [5:0]  free_list_21;
  reg  [5:0]  free_list_22;
  reg  [5:0]  free_list_23;
  reg  [5:0]  free_list_24;
  reg  [5:0]  free_list_25;
  reg  [5:0]  free_list_26;
  reg  [5:0]  free_list_27;
  reg  [5:0]  free_list_28;
  reg  [5:0]  free_list_29;
  reg  [5:0]  free_list_30;
  reg  [5:0]  free_list_31;
  reg  [5:0]  free_list_32;
  reg  [5:0]  free_list_33;
  reg  [5:0]  free_list_34;
  reg  [5:0]  free_list_35;
  reg  [5:0]  free_list_36;
  reg  [5:0]  free_list_37;
  reg  [5:0]  free_list_38;
  reg  [5:0]  free_list_39;
  reg  [5:0]  free_list_40;
  reg  [5:0]  free_list_41;
  reg  [5:0]  free_list_42;
  reg  [5:0]  free_list_43;
  reg  [5:0]  free_list_44;
  reg  [5:0]  free_list_45;
  reg  [5:0]  free_list_46;
  reg  [5:0]  free_list_47;
  reg  [5:0]  free_list_48;
  reg  [5:0]  free_list_49;
  reg  [5:0]  free_list_50;
  reg  [5:0]  free_list_51;
  reg  [5:0]  free_list_52;
  reg  [5:0]  free_list_53;
  reg  [53:0] head;
  reg  [53:0] tail;
  wire [1:0]  _io_empty_T_4 = {|({head[52:0], head[53]} & tail), |(head & tail)};
  wire        _GEN = io_rd_valid_0 & io_rename_en_0 & ~(|_io_empty_T_4);
  wire [53:0] _GEN_0 = {head[52:0], head[53]};
  wire [53:0] head_idx_1 = _GEN ? _GEN_0 : head;
  wire [5:0]  _io_alloc_preg_0_T_54 = head[0] ? free_list_0 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_55 = head[1] ? free_list_1 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_56 = head[2] ? free_list_2 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_57 = head[3] ? free_list_3 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_58 = head[4] ? free_list_4 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_59 = head[5] ? free_list_5 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_60 = head[6] ? free_list_6 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_61 = head[7] ? free_list_7 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_62 = head[8] ? free_list_8 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_63 = head[9] ? free_list_9 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_64 = head[10] ? free_list_10 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_65 = head[11] ? free_list_11 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_66 = head[12] ? free_list_12 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_67 = head[13] ? free_list_13 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_68 = head[14] ? free_list_14 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_69 = head[15] ? free_list_15 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_70 = head[16] ? free_list_16 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_71 = head[17] ? free_list_17 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_72 = head[18] ? free_list_18 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_73 = head[19] ? free_list_19 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_74 = head[20] ? free_list_20 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_75 = head[21] ? free_list_21 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_76 = head[22] ? free_list_22 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_77 = head[23] ? free_list_23 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_78 = head[24] ? free_list_24 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_79 = head[25] ? free_list_25 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_80 = head[26] ? free_list_26 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_81 = head[27] ? free_list_27 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_82 = head[28] ? free_list_28 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_83 = head[29] ? free_list_29 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_84 = head[30] ? free_list_30 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_85 = head[31] ? free_list_31 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_86 = head[32] ? free_list_32 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_87 = head[33] ? free_list_33 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_88 = head[34] ? free_list_34 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_89 = head[35] ? free_list_35 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_90 = head[36] ? free_list_36 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_91 = head[37] ? free_list_37 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_92 = head[38] ? free_list_38 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_93 = head[39] ? free_list_39 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_94 = head[40] ? free_list_40 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_95 = head[41] ? free_list_41 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_96 = head[42] ? free_list_42 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_97 = head[43] ? free_list_43 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_98 = head[44] ? free_list_44 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_99 = head[45] ? free_list_45 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_100 = head[46] ? free_list_46 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_101 = head[47] ? free_list_47 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_102 = head[48] ? free_list_48 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_103 = head[49] ? free_list_49 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_104 = head[50] ? free_list_50 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_105 = head[51] ? free_list_51 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_106 = head[52] ? free_list_52 : 6'h0;
  wire [5:0]  _io_alloc_preg_0_T_107 = head[53] ? free_list_53 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_54 = head_idx_1[0] ? free_list_0 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_55 = head_idx_1[1] ? free_list_1 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_56 = head_idx_1[2] ? free_list_2 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_57 = head_idx_1[3] ? free_list_3 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_58 = head_idx_1[4] ? free_list_4 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_59 = head_idx_1[5] ? free_list_5 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_60 = head_idx_1[6] ? free_list_6 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_61 = head_idx_1[7] ? free_list_7 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_62 = head_idx_1[8] ? free_list_8 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_63 = head_idx_1[9] ? free_list_9 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_64 = head_idx_1[10] ? free_list_10 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_65 = head_idx_1[11] ? free_list_11 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_66 = head_idx_1[12] ? free_list_12 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_67 = head_idx_1[13] ? free_list_13 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_68 = head_idx_1[14] ? free_list_14 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_69 = head_idx_1[15] ? free_list_15 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_70 = head_idx_1[16] ? free_list_16 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_71 = head_idx_1[17] ? free_list_17 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_72 = head_idx_1[18] ? free_list_18 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_73 = head_idx_1[19] ? free_list_19 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_74 = head_idx_1[20] ? free_list_20 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_75 = head_idx_1[21] ? free_list_21 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_76 = head_idx_1[22] ? free_list_22 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_77 = head_idx_1[23] ? free_list_23 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_78 = head_idx_1[24] ? free_list_24 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_79 = head_idx_1[25] ? free_list_25 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_80 = head_idx_1[26] ? free_list_26 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_81 = head_idx_1[27] ? free_list_27 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_82 = head_idx_1[28] ? free_list_28 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_83 = head_idx_1[29] ? free_list_29 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_84 = head_idx_1[30] ? free_list_30 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_85 = head_idx_1[31] ? free_list_31 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_86 = head_idx_1[32] ? free_list_32 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_87 = head_idx_1[33] ? free_list_33 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_88 = head_idx_1[34] ? free_list_34 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_89 = head_idx_1[35] ? free_list_35 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_90 = head_idx_1[36] ? free_list_36 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_91 = head_idx_1[37] ? free_list_37 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_92 = head_idx_1[38] ? free_list_38 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_93 = head_idx_1[39] ? free_list_39 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_94 = head_idx_1[40] ? free_list_40 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_95 = head_idx_1[41] ? free_list_41 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_96 = head_idx_1[42] ? free_list_42 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_97 = head_idx_1[43] ? free_list_43 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_98 = head_idx_1[44] ? free_list_44 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_99 = head_idx_1[45] ? free_list_45 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_100 = head_idx_1[46] ? free_list_46 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_101 = head_idx_1[47] ? free_list_47 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_102 = head_idx_1[48] ? free_list_48 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_103 = head_idx_1[49] ? free_list_49 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_104 = head_idx_1[50] ? free_list_50 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_105 = head_idx_1[51] ? free_list_51 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_106 = head_idx_1[52] ? free_list_52 : 6'h0;
  wire [5:0]  _io_alloc_preg_1_T_107 = head_idx_1[53] ? free_list_53 : 6'h0;
  wire [63:0] _head_T = 64'h1 << io_head_arch;
  wire        _GEN_1 = io_commit_en_0 & io_commit_pprd_valid_0;
  wire [53:0] _GEN_2 = {tail[52:0], tail[53]};
  wire [53:0] tail_idx_1 = _GEN_1 ? _GEN_2 : tail;
  wire [30:0] _GEN_3 = {10'h0, tail[53:33]} | tail[31:1];
  wire [14:0] _GEN_4 = _GEN_3[30:16] | _GEN_3[14:0];
  wire [6:0]  _GEN_5 = _GEN_4[14:8] | _GEN_4[6:0];
  wire [2:0]  _GEN_6 = _GEN_5[6:4] | _GEN_5[2:0];
  wire [5:0]  _GEN_7 =
    {|(tail[53:32]),
     |(_GEN_3[30:15]),
     |(_GEN_4[14:7]),
     |(_GEN_5[6:3]),
     |(_GEN_6[2:1]),
     _GEN_6[2] | _GEN_6[0]};
  wire        _GEN_8 = io_commit_en_1 & io_commit_pprd_valid_1;
  wire [30:0] _GEN_9 = {10'h0, tail_idx_1[53:33]} | tail_idx_1[31:1];
  wire [14:0] _GEN_10 = _GEN_9[30:16] | _GEN_9[14:0];
  wire [6:0]  _GEN_11 = _GEN_10[14:8] | _GEN_10[6:0];
  wire [2:0]  _GEN_12 = _GEN_11[6:4] | _GEN_11[2:0];
  wire [5:0]  _GEN_13 =
    {|(tail_idx_1[53:32]),
     |(_GEN_9[30:15]),
     |(_GEN_10[14:7]),
     |(_GEN_11[6:3]),
     |(_GEN_12[2:1]),
     _GEN_12[2] | _GEN_12[0]};
  always @(posedge clock) begin
    if (reset) begin
      free_list_0 <= 6'h1;
      free_list_1 <= 6'h2;
      free_list_2 <= 6'h3;
      free_list_3 <= 6'h4;
      free_list_4 <= 6'h5;
      free_list_5 <= 6'h6;
      free_list_6 <= 6'h7;
      free_list_7 <= 6'h8;
      free_list_8 <= 6'h9;
      free_list_9 <= 6'hA;
      free_list_10 <= 6'hB;
      free_list_11 <= 6'hC;
      free_list_12 <= 6'hD;
      free_list_13 <= 6'hE;
      free_list_14 <= 6'hF;
      free_list_15 <= 6'h10;
      free_list_16 <= 6'h11;
      free_list_17 <= 6'h12;
      free_list_18 <= 6'h13;
      free_list_19 <= 6'h14;
      free_list_20 <= 6'h15;
      free_list_21 <= 6'h16;
      free_list_22 <= 6'h17;
      free_list_23 <= 6'h18;
      free_list_24 <= 6'h19;
      free_list_25 <= 6'h1A;
      free_list_26 <= 6'h1B;
      free_list_27 <= 6'h1C;
      free_list_28 <= 6'h1D;
      free_list_29 <= 6'h1E;
      free_list_30 <= 6'h1F;
      free_list_31 <= 6'h20;
      free_list_32 <= 6'h21;
      free_list_33 <= 6'h22;
      free_list_34 <= 6'h23;
      free_list_35 <= 6'h24;
      free_list_36 <= 6'h25;
      free_list_37 <= 6'h26;
      free_list_38 <= 6'h27;
      free_list_39 <= 6'h28;
      free_list_40 <= 6'h29;
      free_list_41 <= 6'h2A;
      free_list_42 <= 6'h2B;
      free_list_43 <= 6'h2C;
      free_list_44 <= 6'h2D;
      free_list_45 <= 6'h2E;
      free_list_46 <= 6'h2F;
      free_list_47 <= 6'h30;
      free_list_48 <= 6'h31;
      free_list_49 <= 6'h32;
      free_list_50 <= 6'h33;
      free_list_51 <= 6'h34;
      free_list_52 <= 6'h35;
      free_list_53 <= 6'h36;
      head <= 54'h1;
      tail <= 54'h20000000000000;
    end
    else begin
      if (_GEN_8 & _GEN_13 == 6'h0)
        free_list_0 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h0)
        free_list_0 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1)
        free_list_1 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1)
        free_list_1 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2)
        free_list_2 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2)
        free_list_2 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h3)
        free_list_3 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h3)
        free_list_3 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h4)
        free_list_4 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h4)
        free_list_4 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h5)
        free_list_5 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h5)
        free_list_5 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h6)
        free_list_6 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h6)
        free_list_6 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h7)
        free_list_7 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h7)
        free_list_7 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h8)
        free_list_8 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h8)
        free_list_8 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h9)
        free_list_9 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h9)
        free_list_9 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hA)
        free_list_10 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hA)
        free_list_10 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hB)
        free_list_11 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hB)
        free_list_11 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hC)
        free_list_12 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hC)
        free_list_12 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hD)
        free_list_13 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hD)
        free_list_13 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hE)
        free_list_14 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hE)
        free_list_14 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'hF)
        free_list_15 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'hF)
        free_list_15 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h10)
        free_list_16 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h10)
        free_list_16 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h11)
        free_list_17 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h11)
        free_list_17 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h12)
        free_list_18 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h12)
        free_list_18 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h13)
        free_list_19 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h13)
        free_list_19 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h14)
        free_list_20 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h14)
        free_list_20 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h15)
        free_list_21 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h15)
        free_list_21 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h16)
        free_list_22 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h16)
        free_list_22 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h17)
        free_list_23 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h17)
        free_list_23 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h18)
        free_list_24 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h18)
        free_list_24 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h19)
        free_list_25 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h19)
        free_list_25 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1A)
        free_list_26 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1A)
        free_list_26 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1B)
        free_list_27 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1B)
        free_list_27 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1C)
        free_list_28 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1C)
        free_list_28 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1D)
        free_list_29 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1D)
        free_list_29 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1E)
        free_list_30 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1E)
        free_list_30 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h1F)
        free_list_31 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h1F)
        free_list_31 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h20)
        free_list_32 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h20)
        free_list_32 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h21)
        free_list_33 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h21)
        free_list_33 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h22)
        free_list_34 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h22)
        free_list_34 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h23)
        free_list_35 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h23)
        free_list_35 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h24)
        free_list_36 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h24)
        free_list_36 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h25)
        free_list_37 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h25)
        free_list_37 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h26)
        free_list_38 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h26)
        free_list_38 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h27)
        free_list_39 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h27)
        free_list_39 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h28)
        free_list_40 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h28)
        free_list_40 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h29)
        free_list_41 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h29)
        free_list_41 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2A)
        free_list_42 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2A)
        free_list_42 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2B)
        free_list_43 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2B)
        free_list_43 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2C)
        free_list_44 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2C)
        free_list_44 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2D)
        free_list_45 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2D)
        free_list_45 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2E)
        free_list_46 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2E)
        free_list_46 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h2F)
        free_list_47 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h2F)
        free_list_47 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h30)
        free_list_48 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h30)
        free_list_48 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h31)
        free_list_49 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h31)
        free_list_49 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h32)
        free_list_50 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h32)
        free_list_50 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h33)
        free_list_51 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h33)
        free_list_51 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h34)
        free_list_52 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h34)
        free_list_52 <= io_commit_pprd_0;
      if (_GEN_8 & _GEN_13 == 6'h35)
        free_list_53 <= io_commit_pprd_1;
      else if (_GEN_1 & _GEN_7 == 6'h35)
        free_list_53 <= io_commit_pprd_0;
      if (io_predict_fail)
        head <= _head_T[53:0];
      else if (io_rd_valid_1 & io_rename_en_1 & ~(|_io_empty_T_4))
        head <= {head_idx_1[52:0], head_idx_1[53]};
      else if (_GEN)
        head <= _GEN_0;
      if (_GEN_8)
        tail <= {tail_idx_1[52:0], tail_idx_1[53]};
      else if (_GEN_1)
        tail <= _GEN_2;
    end
  end // always @(posedge)
  assign io_alloc_preg_0 =
    _io_alloc_preg_0_T_54 | _io_alloc_preg_0_T_55 | _io_alloc_preg_0_T_56
    | _io_alloc_preg_0_T_57 | _io_alloc_preg_0_T_58 | _io_alloc_preg_0_T_59
    | _io_alloc_preg_0_T_60 | _io_alloc_preg_0_T_61 | _io_alloc_preg_0_T_62
    | _io_alloc_preg_0_T_63 | _io_alloc_preg_0_T_64 | _io_alloc_preg_0_T_65
    | _io_alloc_preg_0_T_66 | _io_alloc_preg_0_T_67 | _io_alloc_preg_0_T_68
    | _io_alloc_preg_0_T_69 | _io_alloc_preg_0_T_70 | _io_alloc_preg_0_T_71
    | _io_alloc_preg_0_T_72 | _io_alloc_preg_0_T_73 | _io_alloc_preg_0_T_74
    | _io_alloc_preg_0_T_75 | _io_alloc_preg_0_T_76 | _io_alloc_preg_0_T_77
    | _io_alloc_preg_0_T_78 | _io_alloc_preg_0_T_79 | _io_alloc_preg_0_T_80
    | _io_alloc_preg_0_T_81 | _io_alloc_preg_0_T_82 | _io_alloc_preg_0_T_83
    | _io_alloc_preg_0_T_84 | _io_alloc_preg_0_T_85 | _io_alloc_preg_0_T_86
    | _io_alloc_preg_0_T_87 | _io_alloc_preg_0_T_88 | _io_alloc_preg_0_T_89
    | _io_alloc_preg_0_T_90 | _io_alloc_preg_0_T_91 | _io_alloc_preg_0_T_92
    | _io_alloc_preg_0_T_93 | _io_alloc_preg_0_T_94 | _io_alloc_preg_0_T_95
    | _io_alloc_preg_0_T_96 | _io_alloc_preg_0_T_97 | _io_alloc_preg_0_T_98
    | _io_alloc_preg_0_T_99 | _io_alloc_preg_0_T_100 | _io_alloc_preg_0_T_101
    | _io_alloc_preg_0_T_102 | _io_alloc_preg_0_T_103 | _io_alloc_preg_0_T_104
    | _io_alloc_preg_0_T_105 | _io_alloc_preg_0_T_106 | _io_alloc_preg_0_T_107;
  assign io_alloc_preg_1 =
    _io_alloc_preg_1_T_54 | _io_alloc_preg_1_T_55 | _io_alloc_preg_1_T_56
    | _io_alloc_preg_1_T_57 | _io_alloc_preg_1_T_58 | _io_alloc_preg_1_T_59
    | _io_alloc_preg_1_T_60 | _io_alloc_preg_1_T_61 | _io_alloc_preg_1_T_62
    | _io_alloc_preg_1_T_63 | _io_alloc_preg_1_T_64 | _io_alloc_preg_1_T_65
    | _io_alloc_preg_1_T_66 | _io_alloc_preg_1_T_67 | _io_alloc_preg_1_T_68
    | _io_alloc_preg_1_T_69 | _io_alloc_preg_1_T_70 | _io_alloc_preg_1_T_71
    | _io_alloc_preg_1_T_72 | _io_alloc_preg_1_T_73 | _io_alloc_preg_1_T_74
    | _io_alloc_preg_1_T_75 | _io_alloc_preg_1_T_76 | _io_alloc_preg_1_T_77
    | _io_alloc_preg_1_T_78 | _io_alloc_preg_1_T_79 | _io_alloc_preg_1_T_80
    | _io_alloc_preg_1_T_81 | _io_alloc_preg_1_T_82 | _io_alloc_preg_1_T_83
    | _io_alloc_preg_1_T_84 | _io_alloc_preg_1_T_85 | _io_alloc_preg_1_T_86
    | _io_alloc_preg_1_T_87 | _io_alloc_preg_1_T_88 | _io_alloc_preg_1_T_89
    | _io_alloc_preg_1_T_90 | _io_alloc_preg_1_T_91 | _io_alloc_preg_1_T_92
    | _io_alloc_preg_1_T_93 | _io_alloc_preg_1_T_94 | _io_alloc_preg_1_T_95
    | _io_alloc_preg_1_T_96 | _io_alloc_preg_1_T_97 | _io_alloc_preg_1_T_98
    | _io_alloc_preg_1_T_99 | _io_alloc_preg_1_T_100 | _io_alloc_preg_1_T_101
    | _io_alloc_preg_1_T_102 | _io_alloc_preg_1_T_103 | _io_alloc_preg_1_T_104
    | _io_alloc_preg_1_T_105 | _io_alloc_preg_1_T_106 | _io_alloc_preg_1_T_107;
  assign io_empty = |_io_empty_T_4;
endmodule

