// Generated by CIRCT firtool-1.62.0
module ICache(
  input         clock,
                reset,
  input  [31:0] io_addr_IF,
                io_paddr_IF,
  input         io_rvalid_IF,
                io_uncache_IF,
  output        io_has_cacop_IF,
                io_cache_miss_RM,
  output [31:0] io_rdata_RM_0,
                io_rdata_RM_1,
  output [1:0]  io_pc_sign_RM_0,
                io_pc_sign_RM_1,
  input         io_exception_RM,
                io_stall,
  output [31:0] io_i_araddr,
  output        io_i_rvalid,
  input         io_i_rready,
  input  [31:0] io_i_rdata,
  input         io_i_rlast,
  output [7:0]  io_i_rlen,
  input         io_cacop_en,
  input  [1:0]  io_cacop_op
);

  wire [31:0]       io_i_araddr_0;
  wire              addr_sel;
  wire              data_sel;
  wire [31:0]       _xilinx_single_port_ram_write_first_5_douta;
  wire [31:0]       _xilinx_single_port_ram_write_first_4_douta;
  wire [511:0]      _xilinx_single_port_ram_write_first_3_douta;
  wire [511:0]      _xilinx_single_port_ram_write_first_2_douta;
  wire              _xilinx_single_port_ram_write_first_1_wea;
  wire [19:0]       _xilinx_single_port_ram_write_first_1_douta;
  wire              _xilinx_single_port_ram_write_first_wea;
  wire [19:0]       _xilinx_single_port_ram_write_first_douta;
  wire [31:0]       _ir_io_pc;
  wire [31:0]       _ir_io_icache_wdata_inst;
  wire [1:0]        _ir_io_icache_wdata_pc_sign;
  reg               cacop_en_IF;
  reg  [1:0]        cacop_op_IF;
  reg  [31:0]       cacop_addr_IF;
  reg  [31:0]       paddr_reg_IF_RM;
  reg               rvalid_reg_IF_RM;
  reg               uncache_reg_IF_RM;
  reg               cacop_en_reg_IF_RM;
  reg  [1:0]        cacop_op_reg_IF_RM;
  reg               lru_mem_0;
  reg               lru_mem_1;
  reg               lru_mem_2;
  reg               lru_mem_3;
  reg               lru_mem_4;
  reg               lru_mem_5;
  reg               lru_mem_6;
  reg               lru_mem_7;
  reg               lru_mem_8;
  reg               lru_mem_9;
  reg               lru_mem_10;
  reg               lru_mem_11;
  reg               lru_mem_12;
  reg               lru_mem_13;
  reg               lru_mem_14;
  reg               lru_mem_15;
  reg               lru_mem_16;
  reg               lru_mem_17;
  reg               lru_mem_18;
  reg               lru_mem_19;
  reg               lru_mem_20;
  reg               lru_mem_21;
  reg               lru_mem_22;
  reg               lru_mem_23;
  reg               lru_mem_24;
  reg               lru_mem_25;
  reg               lru_mem_26;
  reg               lru_mem_27;
  reg               lru_mem_28;
  reg               lru_mem_29;
  reg               lru_mem_30;
  reg               lru_mem_31;
  reg               lru_mem_32;
  reg               lru_mem_33;
  reg               lru_mem_34;
  reg               lru_mem_35;
  reg               lru_mem_36;
  reg               lru_mem_37;
  reg               lru_mem_38;
  reg               lru_mem_39;
  reg               lru_mem_40;
  reg               lru_mem_41;
  reg               lru_mem_42;
  reg               lru_mem_43;
  reg               lru_mem_44;
  reg               lru_mem_45;
  reg               lru_mem_46;
  reg               lru_mem_47;
  reg               lru_mem_48;
  reg               lru_mem_49;
  reg               lru_mem_50;
  reg               lru_mem_51;
  reg               lru_mem_52;
  reg               lru_mem_53;
  reg               lru_mem_54;
  reg               lru_mem_55;
  reg               lru_mem_56;
  reg               lru_mem_57;
  reg               lru_mem_58;
  reg               lru_mem_59;
  reg               lru_mem_60;
  reg               lru_mem_61;
  reg               lru_mem_62;
  reg               lru_mem_63;
  reg               lru_mem_64;
  reg               lru_mem_65;
  reg               lru_mem_66;
  reg               lru_mem_67;
  reg               lru_mem_68;
  reg               lru_mem_69;
  reg               lru_mem_70;
  reg               lru_mem_71;
  reg               lru_mem_72;
  reg               lru_mem_73;
  reg               lru_mem_74;
  reg               lru_mem_75;
  reg               lru_mem_76;
  reg               lru_mem_77;
  reg               lru_mem_78;
  reg               lru_mem_79;
  reg               lru_mem_80;
  reg               lru_mem_81;
  reg               lru_mem_82;
  reg               lru_mem_83;
  reg               lru_mem_84;
  reg               lru_mem_85;
  reg               lru_mem_86;
  reg               lru_mem_87;
  reg               lru_mem_88;
  reg               lru_mem_89;
  reg               lru_mem_90;
  reg               lru_mem_91;
  reg               lru_mem_92;
  reg               lru_mem_93;
  reg               lru_mem_94;
  reg               lru_mem_95;
  reg               lru_mem_96;
  reg               lru_mem_97;
  reg               lru_mem_98;
  reg               lru_mem_99;
  reg               lru_mem_100;
  reg               lru_mem_101;
  reg               lru_mem_102;
  reg               lru_mem_103;
  reg               lru_mem_104;
  reg               lru_mem_105;
  reg               lru_mem_106;
  reg               lru_mem_107;
  reg               lru_mem_108;
  reg               lru_mem_109;
  reg               lru_mem_110;
  reg               lru_mem_111;
  reg               lru_mem_112;
  reg               lru_mem_113;
  reg               lru_mem_114;
  reg               lru_mem_115;
  reg               lru_mem_116;
  reg               lru_mem_117;
  reg               lru_mem_118;
  reg               lru_mem_119;
  reg               lru_mem_120;
  reg               lru_mem_121;
  reg               lru_mem_122;
  reg               lru_mem_123;
  reg               lru_mem_124;
  reg               lru_mem_125;
  reg               lru_mem_126;
  reg               lru_mem_127;
  reg  [511:0]      ret_buf;
  reg  [31:0]       inst_temp_buf;
  reg  [31:0]       pc_sign_buf;
  reg  [3:0]        rd_cnt;
  wire [6:0]        tagv_0_addra = addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire [19:0]       _tagv_1_dina_T = {1'h1, paddr_reg_IF_RM[31:13]};
  wire [19:0]       tagv_0_dina = cacop_en_reg_IF_RM ? 20'h0 : _tagv_1_dina_T;
  wire [6:0]        tagv_1_addra = addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire [19:0]       tagv_1_dina = cacop_en_reg_IF_RM ? 20'h0 : _tagv_1_dina_T;
  wire [6:0]        cmem_0_addra = addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire [6:0]        cmem_1_addra = addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire [6:0]        pc_sign_mem_0_addra =
    addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire [6:0]        pc_sign_mem_1_addra =
    addr_sel ? paddr_reg_IF_RM[12:6] : io_addr_IF[12:6];
  wire              hit_RM_0 =
    _xilinx_single_port_ram_write_first_douta[19]
    & (_xilinx_single_port_ram_write_first_douta[18:0] ^ paddr_reg_IF_RM[31:13]) == 19'h0;
  wire              hit_RM_1 =
    _xilinx_single_port_ram_write_first_1_douta[19]
    & (_xilinx_single_port_ram_write_first_1_douta[18:0]
       ^ paddr_reg_IF_RM[31:13]) == 19'h0;
  wire [1:0]        _cache_hit_RM_T = {hit_RM_1, hit_RM_0};
  wire              cacop_way_RM = cacop_op_reg_IF_RM[1] ? hit_RM_1 : paddr_reg_IF_RM[0];
  wire              cacop_exec_RM = ~(cacop_op_reg_IF_RM[1]) | (|_cache_hit_RM_T);
  wire [511:0]      _cmem_hit_line_T =
    hit_RM_0 ? _xilinx_single_port_ram_write_first_2_douta : 512'h0;
  wire [511:0]      _cmem_hit_line_T_1 =
    hit_RM_1 ? _xilinx_single_port_ram_write_first_3_douta : 512'h0;
  wire [511:0]      cmem_hit_line = _cmem_hit_line_T | _cmem_hit_line_T_1;
  wire [15:0][63:0] _GEN =
    {{{32'h0, ret_buf[511:480]}},
     {ret_buf[511:448]},
     {ret_buf[479:416]},
     {ret_buf[447:384]},
     {ret_buf[415:352]},
     {ret_buf[383:320]},
     {ret_buf[351:288]},
     {ret_buf[319:256]},
     {ret_buf[287:224]},
     {ret_buf[255:192]},
     {ret_buf[223:160]},
     {ret_buf[191:128]},
     {ret_buf[159:96]},
     {ret_buf[127:64]},
     {ret_buf[95:32]},
     {ret_buf[63:0]}};
  wire [63:0]       rbuf_rdata_RM =
    uncache_reg_IF_RM ? ret_buf[511:448] : _GEN[paddr_reg_IF_RM[5:2]];
  wire [15:0][63:0] _GEN_0 =
    {{{32'h0, cmem_hit_line[511:480]}},
     {cmem_hit_line[511:448]},
     {cmem_hit_line[479:416]},
     {cmem_hit_line[447:384]},
     {cmem_hit_line[415:352]},
     {cmem_hit_line[383:320]},
     {cmem_hit_line[351:288]},
     {cmem_hit_line[319:256]},
     {cmem_hit_line[287:224]},
     {cmem_hit_line[255:192]},
     {cmem_hit_line[223:160]},
     {cmem_hit_line[191:128]},
     {cmem_hit_line[159:96]},
     {cmem_hit_line[127:64]},
     {cmem_hit_line[95:32]},
     {cmem_hit_line[63:0]}};
  wire [63:0]       _GEN_1 = _GEN_0[paddr_reg_IF_RM[5:2]];
  wire [31:0]       _pmem_hit_line_T =
    hit_RM_0 ? _xilinx_single_port_ram_write_first_4_douta : 32'h0;
  wire [31:0]       _pmem_hit_line_T_1 =
    hit_RM_1 ? _xilinx_single_port_ram_write_first_5_douta : 32'h0;
  wire [31:0]       pmem_hit_line = _pmem_hit_line_T | _pmem_hit_line_T_1;
  wire [15:0][3:0]  _GEN_2 =
    {{{2'h0, pc_sign_buf[31:30]}},
     {pc_sign_buf[31:28]},
     {pc_sign_buf[29:26]},
     {pc_sign_buf[27:24]},
     {pc_sign_buf[25:22]},
     {pc_sign_buf[23:20]},
     {pc_sign_buf[21:18]},
     {pc_sign_buf[19:16]},
     {pc_sign_buf[17:14]},
     {pc_sign_buf[15:12]},
     {pc_sign_buf[13:10]},
     {pc_sign_buf[11:8]},
     {pc_sign_buf[9:6]},
     {pc_sign_buf[7:4]},
     {pc_sign_buf[5:2]},
     {pc_sign_buf[3:0]}};
  wire [3:0]        pbuf_rdata_RM =
    uncache_reg_IF_RM ? pc_sign_buf[31:28] : _GEN_2[paddr_reg_IF_RM[5:2]];
  wire [15:0][3:0]  _GEN_3 =
    {{{2'h0, pmem_hit_line[31:30]}},
     {pmem_hit_line[31:28]},
     {pmem_hit_line[29:26]},
     {pmem_hit_line[27:24]},
     {pmem_hit_line[25:22]},
     {pmem_hit_line[23:20]},
     {pmem_hit_line[21:18]},
     {pmem_hit_line[19:16]},
     {pmem_hit_line[17:14]},
     {pmem_hit_line[15:12]},
     {pmem_hit_line[13:10]},
     {pmem_hit_line[11:8]},
     {pmem_hit_line[9:6]},
     {pmem_hit_line[7:4]},
     {pmem_hit_line[5:2]},
     {pmem_hit_line[3:0]}};
  wire [3:0]        _GEN_4 = _GEN_3[paddr_reg_IF_RM[5:2]];
  reg               i_rready;
  wire [127:0]      _GEN_5 =
    {{lru_mem_127},
     {lru_mem_126},
     {lru_mem_125},
     {lru_mem_124},
     {lru_mem_123},
     {lru_mem_122},
     {lru_mem_121},
     {lru_mem_120},
     {lru_mem_119},
     {lru_mem_118},
     {lru_mem_117},
     {lru_mem_116},
     {lru_mem_115},
     {lru_mem_114},
     {lru_mem_113},
     {lru_mem_112},
     {lru_mem_111},
     {lru_mem_110},
     {lru_mem_109},
     {lru_mem_108},
     {lru_mem_107},
     {lru_mem_106},
     {lru_mem_105},
     {lru_mem_104},
     {lru_mem_103},
     {lru_mem_102},
     {lru_mem_101},
     {lru_mem_100},
     {lru_mem_99},
     {lru_mem_98},
     {lru_mem_97},
     {lru_mem_96},
     {lru_mem_95},
     {lru_mem_94},
     {lru_mem_93},
     {lru_mem_92},
     {lru_mem_91},
     {lru_mem_90},
     {lru_mem_89},
     {lru_mem_88},
     {lru_mem_87},
     {lru_mem_86},
     {lru_mem_85},
     {lru_mem_84},
     {lru_mem_83},
     {lru_mem_82},
     {lru_mem_81},
     {lru_mem_80},
     {lru_mem_79},
     {lru_mem_78},
     {lru_mem_77},
     {lru_mem_76},
     {lru_mem_75},
     {lru_mem_74},
     {lru_mem_73},
     {lru_mem_72},
     {lru_mem_71},
     {lru_mem_70},
     {lru_mem_69},
     {lru_mem_68},
     {lru_mem_67},
     {lru_mem_66},
     {lru_mem_65},
     {lru_mem_64},
     {lru_mem_63},
     {lru_mem_62},
     {lru_mem_61},
     {lru_mem_60},
     {lru_mem_59},
     {lru_mem_58},
     {lru_mem_57},
     {lru_mem_56},
     {lru_mem_55},
     {lru_mem_54},
     {lru_mem_53},
     {lru_mem_52},
     {lru_mem_51},
     {lru_mem_50},
     {lru_mem_49},
     {lru_mem_48},
     {lru_mem_47},
     {lru_mem_46},
     {lru_mem_45},
     {lru_mem_44},
     {lru_mem_43},
     {lru_mem_42},
     {lru_mem_41},
     {lru_mem_40},
     {lru_mem_39},
     {lru_mem_38},
     {lru_mem_37},
     {lru_mem_36},
     {lru_mem_35},
     {lru_mem_34},
     {lru_mem_33},
     {lru_mem_32},
     {lru_mem_31},
     {lru_mem_30},
     {lru_mem_29},
     {lru_mem_28},
     {lru_mem_27},
     {lru_mem_26},
     {lru_mem_25},
     {lru_mem_24},
     {lru_mem_23},
     {lru_mem_22},
     {lru_mem_21},
     {lru_mem_20},
     {lru_mem_19},
     {lru_mem_18},
     {lru_mem_17},
     {lru_mem_16},
     {lru_mem_15},
     {lru_mem_14},
     {lru_mem_13},
     {lru_mem_12},
     {lru_mem_11},
     {lru_mem_10},
     {lru_mem_9},
     {lru_mem_8},
     {lru_mem_7},
     {lru_mem_6},
     {lru_mem_5},
     {lru_mem_4},
     {lru_mem_3},
     {lru_mem_2},
     {lru_mem_1},
     {lru_mem_0}};
  wire              _GEN_6 = _GEN_5[paddr_reg_IF_RM[12:6]];
  reg               read_finish;
  reg  [1:0]        state;
  wire              _GEN_7 = io_exception_RM | cacop_en_reg_IF_RM;
  wire              _GEN_8 =
    cacop_en_reg_IF_RM
      ? cacop_exec_RM
      : rvalid_reg_IF_RM & (uncache_reg_IF_RM | ~(|_cache_hit_RM_T));
  assign data_sel = (|state) | _GEN_7 | ~rvalid_reg_IF_RM | uncache_reg_IF_RM;
  wire              _GEN_9 =
    cacop_en_reg_IF_RM
      ? cacop_exec_RM
      : rvalid_reg_IF_RM & (uncache_reg_IF_RM | io_stall);
  wire              _GEN_10 = state == 2'h1;
  wire              _GEN_11 = state == 2'h2;
  wire              tag_idx = cacop_en_reg_IF_RM ? cacop_way_RM : _GEN_6;
  wire              _GEN_12 = ~(|state) | _GEN_10;
  wire              lru_miss_upd = ~_GEN_12 & _GEN_11 & ~cacop_en_reg_IF_RM;
  wire              cmem_we_RM_0 = ~_GEN_12 & _GEN_11 & ~_GEN_6 & ~cacop_en_reg_IF_RM;
  wire              cmem_we_RM_1 = ~_GEN_12 & _GEN_11 & _GEN_6 & ~cacop_en_reg_IF_RM;
  assign addr_sel = (|state) ? ~_GEN_10 & _GEN_11 : ~io_exception_RM & _GEN_9;
  wire              cache_miss_RM =
    (|state) ? _GEN_10 | _GEN_11 : ~io_exception_RM & _GEN_8;
  assign io_i_araddr_0 =
    uncache_reg_IF_RM ? paddr_reg_IF_RM : {paddr_reg_IF_RM[31:6], 6'h0};
  wire [3:0]        _io_i_rlen_T = uncache_reg_IF_RM ? 4'h1 : 4'hF;
  wire [1:0]        _state_T_3 = read_finish ? {1'h1, uncache_reg_IF_RM} : 2'h1;
  wire [3:0][1:0]   _GEN_13 = {{{2{io_stall}}}, {2'h3}, {_state_T_3}, {state}};
  wire              _GEN_14 = io_stall | cache_miss_RM;
  wire              _GEN_15 = paddr_reg_IF_RM[12:6] == 7'h0;
  wire              _GEN_16 = paddr_reg_IF_RM[12:6] == 7'h1;
  wire              _GEN_17 = paddr_reg_IF_RM[12:6] == 7'h2;
  wire              _GEN_18 = paddr_reg_IF_RM[12:6] == 7'h3;
  wire              _GEN_19 = paddr_reg_IF_RM[12:6] == 7'h4;
  wire              _GEN_20 = paddr_reg_IF_RM[12:6] == 7'h5;
  wire              _GEN_21 = paddr_reg_IF_RM[12:6] == 7'h6;
  wire              _GEN_22 = paddr_reg_IF_RM[12:6] == 7'h7;
  wire              _GEN_23 = paddr_reg_IF_RM[12:6] == 7'h8;
  wire              _GEN_24 = paddr_reg_IF_RM[12:6] == 7'h9;
  wire              _GEN_25 = paddr_reg_IF_RM[12:6] == 7'hA;
  wire              _GEN_26 = paddr_reg_IF_RM[12:6] == 7'hB;
  wire              _GEN_27 = paddr_reg_IF_RM[12:6] == 7'hC;
  wire              _GEN_28 = paddr_reg_IF_RM[12:6] == 7'hD;
  wire              _GEN_29 = paddr_reg_IF_RM[12:6] == 7'hE;
  wire              _GEN_30 = paddr_reg_IF_RM[12:6] == 7'hF;
  wire              _GEN_31 = paddr_reg_IF_RM[12:6] == 7'h10;
  wire              _GEN_32 = paddr_reg_IF_RM[12:6] == 7'h11;
  wire              _GEN_33 = paddr_reg_IF_RM[12:6] == 7'h12;
  wire              _GEN_34 = paddr_reg_IF_RM[12:6] == 7'h13;
  wire              _GEN_35 = paddr_reg_IF_RM[12:6] == 7'h14;
  wire              _GEN_36 = paddr_reg_IF_RM[12:6] == 7'h15;
  wire              _GEN_37 = paddr_reg_IF_RM[12:6] == 7'h16;
  wire              _GEN_38 = paddr_reg_IF_RM[12:6] == 7'h17;
  wire              _GEN_39 = paddr_reg_IF_RM[12:6] == 7'h18;
  wire              _GEN_40 = paddr_reg_IF_RM[12:6] == 7'h19;
  wire              _GEN_41 = paddr_reg_IF_RM[12:6] == 7'h1A;
  wire              _GEN_42 = paddr_reg_IF_RM[12:6] == 7'h1B;
  wire              _GEN_43 = paddr_reg_IF_RM[12:6] == 7'h1C;
  wire              _GEN_44 = paddr_reg_IF_RM[12:6] == 7'h1D;
  wire              _GEN_45 = paddr_reg_IF_RM[12:6] == 7'h1E;
  wire              _GEN_46 = paddr_reg_IF_RM[12:6] == 7'h1F;
  wire              _GEN_47 = paddr_reg_IF_RM[12:6] == 7'h20;
  wire              _GEN_48 = paddr_reg_IF_RM[12:6] == 7'h21;
  wire              _GEN_49 = paddr_reg_IF_RM[12:6] == 7'h22;
  wire              _GEN_50 = paddr_reg_IF_RM[12:6] == 7'h23;
  wire              _GEN_51 = paddr_reg_IF_RM[12:6] == 7'h24;
  wire              _GEN_52 = paddr_reg_IF_RM[12:6] == 7'h25;
  wire              _GEN_53 = paddr_reg_IF_RM[12:6] == 7'h26;
  wire              _GEN_54 = paddr_reg_IF_RM[12:6] == 7'h27;
  wire              _GEN_55 = paddr_reg_IF_RM[12:6] == 7'h28;
  wire              _GEN_56 = paddr_reg_IF_RM[12:6] == 7'h29;
  wire              _GEN_57 = paddr_reg_IF_RM[12:6] == 7'h2A;
  wire              _GEN_58 = paddr_reg_IF_RM[12:6] == 7'h2B;
  wire              _GEN_59 = paddr_reg_IF_RM[12:6] == 7'h2C;
  wire              _GEN_60 = paddr_reg_IF_RM[12:6] == 7'h2D;
  wire              _GEN_61 = paddr_reg_IF_RM[12:6] == 7'h2E;
  wire              _GEN_62 = paddr_reg_IF_RM[12:6] == 7'h2F;
  wire              _GEN_63 = paddr_reg_IF_RM[12:6] == 7'h30;
  wire              _GEN_64 = paddr_reg_IF_RM[12:6] == 7'h31;
  wire              _GEN_65 = paddr_reg_IF_RM[12:6] == 7'h32;
  wire              _GEN_66 = paddr_reg_IF_RM[12:6] == 7'h33;
  wire              _GEN_67 = paddr_reg_IF_RM[12:6] == 7'h34;
  wire              _GEN_68 = paddr_reg_IF_RM[12:6] == 7'h35;
  wire              _GEN_69 = paddr_reg_IF_RM[12:6] == 7'h36;
  wire              _GEN_70 = paddr_reg_IF_RM[12:6] == 7'h37;
  wire              _GEN_71 = paddr_reg_IF_RM[12:6] == 7'h38;
  wire              _GEN_72 = paddr_reg_IF_RM[12:6] == 7'h39;
  wire              _GEN_73 = paddr_reg_IF_RM[12:6] == 7'h3A;
  wire              _GEN_74 = paddr_reg_IF_RM[12:6] == 7'h3B;
  wire              _GEN_75 = paddr_reg_IF_RM[12:6] == 7'h3C;
  wire              _GEN_76 = paddr_reg_IF_RM[12:6] == 7'h3D;
  wire              _GEN_77 = paddr_reg_IF_RM[12:6] == 7'h3E;
  wire              _GEN_78 = paddr_reg_IF_RM[12:6] == 7'h3F;
  wire              _GEN_79 = paddr_reg_IF_RM[12:6] == 7'h40;
  wire              _GEN_80 = paddr_reg_IF_RM[12:6] == 7'h41;
  wire              _GEN_81 = paddr_reg_IF_RM[12:6] == 7'h42;
  wire              _GEN_82 = paddr_reg_IF_RM[12:6] == 7'h43;
  wire              _GEN_83 = paddr_reg_IF_RM[12:6] == 7'h44;
  wire              _GEN_84 = paddr_reg_IF_RM[12:6] == 7'h45;
  wire              _GEN_85 = paddr_reg_IF_RM[12:6] == 7'h46;
  wire              _GEN_86 = paddr_reg_IF_RM[12:6] == 7'h47;
  wire              _GEN_87 = paddr_reg_IF_RM[12:6] == 7'h48;
  wire              _GEN_88 = paddr_reg_IF_RM[12:6] == 7'h49;
  wire              _GEN_89 = paddr_reg_IF_RM[12:6] == 7'h4A;
  wire              _GEN_90 = paddr_reg_IF_RM[12:6] == 7'h4B;
  wire              _GEN_91 = paddr_reg_IF_RM[12:6] == 7'h4C;
  wire              _GEN_92 = paddr_reg_IF_RM[12:6] == 7'h4D;
  wire              _GEN_93 = paddr_reg_IF_RM[12:6] == 7'h4E;
  wire              _GEN_94 = paddr_reg_IF_RM[12:6] == 7'h4F;
  wire              _GEN_95 = paddr_reg_IF_RM[12:6] == 7'h50;
  wire              _GEN_96 = paddr_reg_IF_RM[12:6] == 7'h51;
  wire              _GEN_97 = paddr_reg_IF_RM[12:6] == 7'h52;
  wire              _GEN_98 = paddr_reg_IF_RM[12:6] == 7'h53;
  wire              _GEN_99 = paddr_reg_IF_RM[12:6] == 7'h54;
  wire              _GEN_100 = paddr_reg_IF_RM[12:6] == 7'h55;
  wire              _GEN_101 = paddr_reg_IF_RM[12:6] == 7'h56;
  wire              _GEN_102 = paddr_reg_IF_RM[12:6] == 7'h57;
  wire              _GEN_103 = paddr_reg_IF_RM[12:6] == 7'h58;
  wire              _GEN_104 = paddr_reg_IF_RM[12:6] == 7'h59;
  wire              _GEN_105 = paddr_reg_IF_RM[12:6] == 7'h5A;
  wire              _GEN_106 = paddr_reg_IF_RM[12:6] == 7'h5B;
  wire              _GEN_107 = paddr_reg_IF_RM[12:6] == 7'h5C;
  wire              _GEN_108 = paddr_reg_IF_RM[12:6] == 7'h5D;
  wire              _GEN_109 = paddr_reg_IF_RM[12:6] == 7'h5E;
  wire              _GEN_110 = paddr_reg_IF_RM[12:6] == 7'h5F;
  wire              _GEN_111 = paddr_reg_IF_RM[12:6] == 7'h60;
  wire              _GEN_112 = paddr_reg_IF_RM[12:6] == 7'h61;
  wire              _GEN_113 = paddr_reg_IF_RM[12:6] == 7'h62;
  wire              _GEN_114 = paddr_reg_IF_RM[12:6] == 7'h63;
  wire              _GEN_115 = paddr_reg_IF_RM[12:6] == 7'h64;
  wire              _GEN_116 = paddr_reg_IF_RM[12:6] == 7'h65;
  wire              _GEN_117 = paddr_reg_IF_RM[12:6] == 7'h66;
  wire              _GEN_118 = paddr_reg_IF_RM[12:6] == 7'h67;
  wire              _GEN_119 = paddr_reg_IF_RM[12:6] == 7'h68;
  wire              _GEN_120 = paddr_reg_IF_RM[12:6] == 7'h69;
  wire              _GEN_121 = paddr_reg_IF_RM[12:6] == 7'h6A;
  wire              _GEN_122 = paddr_reg_IF_RM[12:6] == 7'h6B;
  wire              _GEN_123 = paddr_reg_IF_RM[12:6] == 7'h6C;
  wire              _GEN_124 = paddr_reg_IF_RM[12:6] == 7'h6D;
  wire              _GEN_125 = paddr_reg_IF_RM[12:6] == 7'h6E;
  wire              _GEN_126 = paddr_reg_IF_RM[12:6] == 7'h6F;
  wire              _GEN_127 = paddr_reg_IF_RM[12:6] == 7'h70;
  wire              _GEN_128 = paddr_reg_IF_RM[12:6] == 7'h71;
  wire              _GEN_129 = paddr_reg_IF_RM[12:6] == 7'h72;
  wire              _GEN_130 = paddr_reg_IF_RM[12:6] == 7'h73;
  wire              _GEN_131 = paddr_reg_IF_RM[12:6] == 7'h74;
  wire              _GEN_132 = paddr_reg_IF_RM[12:6] == 7'h75;
  wire              _GEN_133 = paddr_reg_IF_RM[12:6] == 7'h76;
  wire              _GEN_134 = paddr_reg_IF_RM[12:6] == 7'h77;
  wire              _GEN_135 = paddr_reg_IF_RM[12:6] == 7'h78;
  wire              _GEN_136 = paddr_reg_IF_RM[12:6] == 7'h79;
  wire              _GEN_137 = paddr_reg_IF_RM[12:6] == 7'h7A;
  wire              _GEN_138 = paddr_reg_IF_RM[12:6] == 7'h7B;
  wire              _GEN_139 = paddr_reg_IF_RM[12:6] == 7'h7C;
  wire              _GEN_140 = paddr_reg_IF_RM[12:6] == 7'h7D;
  wire              _GEN_141 = paddr_reg_IF_RM[12:6] == 7'h7E;
  always @(posedge clock) begin
    if (reset) begin
      cacop_en_IF <= 1'h0;
      cacop_op_IF <= 2'h0;
      cacop_addr_IF <= 32'h0;
      paddr_reg_IF_RM <= 32'h0;
      rvalid_reg_IF_RM <= 1'h0;
      uncache_reg_IF_RM <= 1'h0;
      cacop_en_reg_IF_RM <= 1'h0;
      cacop_op_reg_IF_RM <= 2'h0;
      lru_mem_0 <= 1'h0;
      lru_mem_1 <= 1'h0;
      lru_mem_2 <= 1'h0;
      lru_mem_3 <= 1'h0;
      lru_mem_4 <= 1'h0;
      lru_mem_5 <= 1'h0;
      lru_mem_6 <= 1'h0;
      lru_mem_7 <= 1'h0;
      lru_mem_8 <= 1'h0;
      lru_mem_9 <= 1'h0;
      lru_mem_10 <= 1'h0;
      lru_mem_11 <= 1'h0;
      lru_mem_12 <= 1'h0;
      lru_mem_13 <= 1'h0;
      lru_mem_14 <= 1'h0;
      lru_mem_15 <= 1'h0;
      lru_mem_16 <= 1'h0;
      lru_mem_17 <= 1'h0;
      lru_mem_18 <= 1'h0;
      lru_mem_19 <= 1'h0;
      lru_mem_20 <= 1'h0;
      lru_mem_21 <= 1'h0;
      lru_mem_22 <= 1'h0;
      lru_mem_23 <= 1'h0;
      lru_mem_24 <= 1'h0;
      lru_mem_25 <= 1'h0;
      lru_mem_26 <= 1'h0;
      lru_mem_27 <= 1'h0;
      lru_mem_28 <= 1'h0;
      lru_mem_29 <= 1'h0;
      lru_mem_30 <= 1'h0;
      lru_mem_31 <= 1'h0;
      lru_mem_32 <= 1'h0;
      lru_mem_33 <= 1'h0;
      lru_mem_34 <= 1'h0;
      lru_mem_35 <= 1'h0;
      lru_mem_36 <= 1'h0;
      lru_mem_37 <= 1'h0;
      lru_mem_38 <= 1'h0;
      lru_mem_39 <= 1'h0;
      lru_mem_40 <= 1'h0;
      lru_mem_41 <= 1'h0;
      lru_mem_42 <= 1'h0;
      lru_mem_43 <= 1'h0;
      lru_mem_44 <= 1'h0;
      lru_mem_45 <= 1'h0;
      lru_mem_46 <= 1'h0;
      lru_mem_47 <= 1'h0;
      lru_mem_48 <= 1'h0;
      lru_mem_49 <= 1'h0;
      lru_mem_50 <= 1'h0;
      lru_mem_51 <= 1'h0;
      lru_mem_52 <= 1'h0;
      lru_mem_53 <= 1'h0;
      lru_mem_54 <= 1'h0;
      lru_mem_55 <= 1'h0;
      lru_mem_56 <= 1'h0;
      lru_mem_57 <= 1'h0;
      lru_mem_58 <= 1'h0;
      lru_mem_59 <= 1'h0;
      lru_mem_60 <= 1'h0;
      lru_mem_61 <= 1'h0;
      lru_mem_62 <= 1'h0;
      lru_mem_63 <= 1'h0;
      lru_mem_64 <= 1'h0;
      lru_mem_65 <= 1'h0;
      lru_mem_66 <= 1'h0;
      lru_mem_67 <= 1'h0;
      lru_mem_68 <= 1'h0;
      lru_mem_69 <= 1'h0;
      lru_mem_70 <= 1'h0;
      lru_mem_71 <= 1'h0;
      lru_mem_72 <= 1'h0;
      lru_mem_73 <= 1'h0;
      lru_mem_74 <= 1'h0;
      lru_mem_75 <= 1'h0;
      lru_mem_76 <= 1'h0;
      lru_mem_77 <= 1'h0;
      lru_mem_78 <= 1'h0;
      lru_mem_79 <= 1'h0;
      lru_mem_80 <= 1'h0;
      lru_mem_81 <= 1'h0;
      lru_mem_82 <= 1'h0;
      lru_mem_83 <= 1'h0;
      lru_mem_84 <= 1'h0;
      lru_mem_85 <= 1'h0;
      lru_mem_86 <= 1'h0;
      lru_mem_87 <= 1'h0;
      lru_mem_88 <= 1'h0;
      lru_mem_89 <= 1'h0;
      lru_mem_90 <= 1'h0;
      lru_mem_91 <= 1'h0;
      lru_mem_92 <= 1'h0;
      lru_mem_93 <= 1'h0;
      lru_mem_94 <= 1'h0;
      lru_mem_95 <= 1'h0;
      lru_mem_96 <= 1'h0;
      lru_mem_97 <= 1'h0;
      lru_mem_98 <= 1'h0;
      lru_mem_99 <= 1'h0;
      lru_mem_100 <= 1'h0;
      lru_mem_101 <= 1'h0;
      lru_mem_102 <= 1'h0;
      lru_mem_103 <= 1'h0;
      lru_mem_104 <= 1'h0;
      lru_mem_105 <= 1'h0;
      lru_mem_106 <= 1'h0;
      lru_mem_107 <= 1'h0;
      lru_mem_108 <= 1'h0;
      lru_mem_109 <= 1'h0;
      lru_mem_110 <= 1'h0;
      lru_mem_111 <= 1'h0;
      lru_mem_112 <= 1'h0;
      lru_mem_113 <= 1'h0;
      lru_mem_114 <= 1'h0;
      lru_mem_115 <= 1'h0;
      lru_mem_116 <= 1'h0;
      lru_mem_117 <= 1'h0;
      lru_mem_118 <= 1'h0;
      lru_mem_119 <= 1'h0;
      lru_mem_120 <= 1'h0;
      lru_mem_121 <= 1'h0;
      lru_mem_122 <= 1'h0;
      lru_mem_123 <= 1'h0;
      lru_mem_124 <= 1'h0;
      lru_mem_125 <= 1'h0;
      lru_mem_126 <= 1'h0;
      lru_mem_127 <= 1'h0;
      ret_buf <= 512'h0;
      inst_temp_buf <= 32'h0;
      pc_sign_buf <= 32'h0;
      rd_cnt <= 4'h0;
      state <= 2'h0;
    end
    else begin
      if (cacop_en_IF)
        cacop_en_IF <= _GEN_14 & cacop_en_IF;
      else begin
        cacop_en_IF <= io_cacop_en;
        cacop_op_IF <= io_cacop_op;
        cacop_addr_IF <= io_paddr_IF;
      end
      if (~_GEN_14) begin
        paddr_reg_IF_RM <= cacop_en_IF ? cacop_addr_IF : io_paddr_IF;
        rvalid_reg_IF_RM <= io_rvalid_IF;
        uncache_reg_IF_RM <= io_uncache_IF;
        cacop_en_reg_IF_RM <= cacop_en_IF;
        cacop_op_reg_IF_RM <= cacop_op_IF;
      end
      if (~(|state) & ~_GEN_7 & rvalid_reg_IF_RM & ~uncache_reg_IF_RM
          & (|_cache_hit_RM_T)) begin
        if (_GEN_15)
          lru_mem_0 <= ~hit_RM_1;
        if (_GEN_16)
          lru_mem_1 <= ~hit_RM_1;
        if (_GEN_17)
          lru_mem_2 <= ~hit_RM_1;
        if (_GEN_18)
          lru_mem_3 <= ~hit_RM_1;
        if (_GEN_19)
          lru_mem_4 <= ~hit_RM_1;
        if (_GEN_20)
          lru_mem_5 <= ~hit_RM_1;
        if (_GEN_21)
          lru_mem_6 <= ~hit_RM_1;
        if (_GEN_22)
          lru_mem_7 <= ~hit_RM_1;
        if (_GEN_23)
          lru_mem_8 <= ~hit_RM_1;
        if (_GEN_24)
          lru_mem_9 <= ~hit_RM_1;
        if (_GEN_25)
          lru_mem_10 <= ~hit_RM_1;
        if (_GEN_26)
          lru_mem_11 <= ~hit_RM_1;
        if (_GEN_27)
          lru_mem_12 <= ~hit_RM_1;
        if (_GEN_28)
          lru_mem_13 <= ~hit_RM_1;
        if (_GEN_29)
          lru_mem_14 <= ~hit_RM_1;
        if (_GEN_30)
          lru_mem_15 <= ~hit_RM_1;
        if (_GEN_31)
          lru_mem_16 <= ~hit_RM_1;
        if (_GEN_32)
          lru_mem_17 <= ~hit_RM_1;
        if (_GEN_33)
          lru_mem_18 <= ~hit_RM_1;
        if (_GEN_34)
          lru_mem_19 <= ~hit_RM_1;
        if (_GEN_35)
          lru_mem_20 <= ~hit_RM_1;
        if (_GEN_36)
          lru_mem_21 <= ~hit_RM_1;
        if (_GEN_37)
          lru_mem_22 <= ~hit_RM_1;
        if (_GEN_38)
          lru_mem_23 <= ~hit_RM_1;
        if (_GEN_39)
          lru_mem_24 <= ~hit_RM_1;
        if (_GEN_40)
          lru_mem_25 <= ~hit_RM_1;
        if (_GEN_41)
          lru_mem_26 <= ~hit_RM_1;
        if (_GEN_42)
          lru_mem_27 <= ~hit_RM_1;
        if (_GEN_43)
          lru_mem_28 <= ~hit_RM_1;
        if (_GEN_44)
          lru_mem_29 <= ~hit_RM_1;
        if (_GEN_45)
          lru_mem_30 <= ~hit_RM_1;
        if (_GEN_46)
          lru_mem_31 <= ~hit_RM_1;
        if (_GEN_47)
          lru_mem_32 <= ~hit_RM_1;
        if (_GEN_48)
          lru_mem_33 <= ~hit_RM_1;
        if (_GEN_49)
          lru_mem_34 <= ~hit_RM_1;
        if (_GEN_50)
          lru_mem_35 <= ~hit_RM_1;
        if (_GEN_51)
          lru_mem_36 <= ~hit_RM_1;
        if (_GEN_52)
          lru_mem_37 <= ~hit_RM_1;
        if (_GEN_53)
          lru_mem_38 <= ~hit_RM_1;
        if (_GEN_54)
          lru_mem_39 <= ~hit_RM_1;
        if (_GEN_55)
          lru_mem_40 <= ~hit_RM_1;
        if (_GEN_56)
          lru_mem_41 <= ~hit_RM_1;
        if (_GEN_57)
          lru_mem_42 <= ~hit_RM_1;
        if (_GEN_58)
          lru_mem_43 <= ~hit_RM_1;
        if (_GEN_59)
          lru_mem_44 <= ~hit_RM_1;
        if (_GEN_60)
          lru_mem_45 <= ~hit_RM_1;
        if (_GEN_61)
          lru_mem_46 <= ~hit_RM_1;
        if (_GEN_62)
          lru_mem_47 <= ~hit_RM_1;
        if (_GEN_63)
          lru_mem_48 <= ~hit_RM_1;
        if (_GEN_64)
          lru_mem_49 <= ~hit_RM_1;
        if (_GEN_65)
          lru_mem_50 <= ~hit_RM_1;
        if (_GEN_66)
          lru_mem_51 <= ~hit_RM_1;
        if (_GEN_67)
          lru_mem_52 <= ~hit_RM_1;
        if (_GEN_68)
          lru_mem_53 <= ~hit_RM_1;
        if (_GEN_69)
          lru_mem_54 <= ~hit_RM_1;
        if (_GEN_70)
          lru_mem_55 <= ~hit_RM_1;
        if (_GEN_71)
          lru_mem_56 <= ~hit_RM_1;
        if (_GEN_72)
          lru_mem_57 <= ~hit_RM_1;
        if (_GEN_73)
          lru_mem_58 <= ~hit_RM_1;
        if (_GEN_74)
          lru_mem_59 <= ~hit_RM_1;
        if (_GEN_75)
          lru_mem_60 <= ~hit_RM_1;
        if (_GEN_76)
          lru_mem_61 <= ~hit_RM_1;
        if (_GEN_77)
          lru_mem_62 <= ~hit_RM_1;
        if (_GEN_78)
          lru_mem_63 <= ~hit_RM_1;
        if (_GEN_79)
          lru_mem_64 <= ~hit_RM_1;
        if (_GEN_80)
          lru_mem_65 <= ~hit_RM_1;
        if (_GEN_81)
          lru_mem_66 <= ~hit_RM_1;
        if (_GEN_82)
          lru_mem_67 <= ~hit_RM_1;
        if (_GEN_83)
          lru_mem_68 <= ~hit_RM_1;
        if (_GEN_84)
          lru_mem_69 <= ~hit_RM_1;
        if (_GEN_85)
          lru_mem_70 <= ~hit_RM_1;
        if (_GEN_86)
          lru_mem_71 <= ~hit_RM_1;
        if (_GEN_87)
          lru_mem_72 <= ~hit_RM_1;
        if (_GEN_88)
          lru_mem_73 <= ~hit_RM_1;
        if (_GEN_89)
          lru_mem_74 <= ~hit_RM_1;
        if (_GEN_90)
          lru_mem_75 <= ~hit_RM_1;
        if (_GEN_91)
          lru_mem_76 <= ~hit_RM_1;
        if (_GEN_92)
          lru_mem_77 <= ~hit_RM_1;
        if (_GEN_93)
          lru_mem_78 <= ~hit_RM_1;
        if (_GEN_94)
          lru_mem_79 <= ~hit_RM_1;
        if (_GEN_95)
          lru_mem_80 <= ~hit_RM_1;
        if (_GEN_96)
          lru_mem_81 <= ~hit_RM_1;
        if (_GEN_97)
          lru_mem_82 <= ~hit_RM_1;
        if (_GEN_98)
          lru_mem_83 <= ~hit_RM_1;
        if (_GEN_99)
          lru_mem_84 <= ~hit_RM_1;
        if (_GEN_100)
          lru_mem_85 <= ~hit_RM_1;
        if (_GEN_101)
          lru_mem_86 <= ~hit_RM_1;
        if (_GEN_102)
          lru_mem_87 <= ~hit_RM_1;
        if (_GEN_103)
          lru_mem_88 <= ~hit_RM_1;
        if (_GEN_104)
          lru_mem_89 <= ~hit_RM_1;
        if (_GEN_105)
          lru_mem_90 <= ~hit_RM_1;
        if (_GEN_106)
          lru_mem_91 <= ~hit_RM_1;
        if (_GEN_107)
          lru_mem_92 <= ~hit_RM_1;
        if (_GEN_108)
          lru_mem_93 <= ~hit_RM_1;
        if (_GEN_109)
          lru_mem_94 <= ~hit_RM_1;
        if (_GEN_110)
          lru_mem_95 <= ~hit_RM_1;
        if (_GEN_111)
          lru_mem_96 <= ~hit_RM_1;
        if (_GEN_112)
          lru_mem_97 <= ~hit_RM_1;
        if (_GEN_113)
          lru_mem_98 <= ~hit_RM_1;
        if (_GEN_114)
          lru_mem_99 <= ~hit_RM_1;
        if (_GEN_115)
          lru_mem_100 <= ~hit_RM_1;
        if (_GEN_116)
          lru_mem_101 <= ~hit_RM_1;
        if (_GEN_117)
          lru_mem_102 <= ~hit_RM_1;
        if (_GEN_118)
          lru_mem_103 <= ~hit_RM_1;
        if (_GEN_119)
          lru_mem_104 <= ~hit_RM_1;
        if (_GEN_120)
          lru_mem_105 <= ~hit_RM_1;
        if (_GEN_121)
          lru_mem_106 <= ~hit_RM_1;
        if (_GEN_122)
          lru_mem_107 <= ~hit_RM_1;
        if (_GEN_123)
          lru_mem_108 <= ~hit_RM_1;
        if (_GEN_124)
          lru_mem_109 <= ~hit_RM_1;
        if (_GEN_125)
          lru_mem_110 <= ~hit_RM_1;
        if (_GEN_126)
          lru_mem_111 <= ~hit_RM_1;
        if (_GEN_127)
          lru_mem_112 <= ~hit_RM_1;
        if (_GEN_128)
          lru_mem_113 <= ~hit_RM_1;
        if (_GEN_129)
          lru_mem_114 <= ~hit_RM_1;
        if (_GEN_130)
          lru_mem_115 <= ~hit_RM_1;
        if (_GEN_131)
          lru_mem_116 <= ~hit_RM_1;
        if (_GEN_132)
          lru_mem_117 <= ~hit_RM_1;
        if (_GEN_133)
          lru_mem_118 <= ~hit_RM_1;
        if (_GEN_134)
          lru_mem_119 <= ~hit_RM_1;
        if (_GEN_135)
          lru_mem_120 <= ~hit_RM_1;
        if (_GEN_136)
          lru_mem_121 <= ~hit_RM_1;
        if (_GEN_137)
          lru_mem_122 <= ~hit_RM_1;
        if (_GEN_138)
          lru_mem_123 <= ~hit_RM_1;
        if (_GEN_139)
          lru_mem_124 <= ~hit_RM_1;
        if (_GEN_140)
          lru_mem_125 <= ~hit_RM_1;
        if (_GEN_141)
          lru_mem_126 <= ~hit_RM_1;
        if (&(paddr_reg_IF_RM[12:6]))
          lru_mem_127 <= ~hit_RM_1;
      end
      else begin
        if (lru_miss_upd & _GEN_15)
          lru_mem_0 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_16)
          lru_mem_1 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_17)
          lru_mem_2 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_18)
          lru_mem_3 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_19)
          lru_mem_4 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_20)
          lru_mem_5 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_21)
          lru_mem_6 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_22)
          lru_mem_7 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_23)
          lru_mem_8 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_24)
          lru_mem_9 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_25)
          lru_mem_10 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_26)
          lru_mem_11 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_27)
          lru_mem_12 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_28)
          lru_mem_13 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_29)
          lru_mem_14 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_30)
          lru_mem_15 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_31)
          lru_mem_16 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_32)
          lru_mem_17 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_33)
          lru_mem_18 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_34)
          lru_mem_19 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_35)
          lru_mem_20 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_36)
          lru_mem_21 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_37)
          lru_mem_22 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_38)
          lru_mem_23 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_39)
          lru_mem_24 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_40)
          lru_mem_25 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_41)
          lru_mem_26 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_42)
          lru_mem_27 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_43)
          lru_mem_28 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_44)
          lru_mem_29 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_45)
          lru_mem_30 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_46)
          lru_mem_31 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_47)
          lru_mem_32 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_48)
          lru_mem_33 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_49)
          lru_mem_34 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_50)
          lru_mem_35 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_51)
          lru_mem_36 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_52)
          lru_mem_37 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_53)
          lru_mem_38 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_54)
          lru_mem_39 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_55)
          lru_mem_40 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_56)
          lru_mem_41 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_57)
          lru_mem_42 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_58)
          lru_mem_43 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_59)
          lru_mem_44 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_60)
          lru_mem_45 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_61)
          lru_mem_46 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_62)
          lru_mem_47 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_63)
          lru_mem_48 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_64)
          lru_mem_49 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_65)
          lru_mem_50 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_66)
          lru_mem_51 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_67)
          lru_mem_52 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_68)
          lru_mem_53 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_69)
          lru_mem_54 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_70)
          lru_mem_55 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_71)
          lru_mem_56 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_72)
          lru_mem_57 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_73)
          lru_mem_58 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_74)
          lru_mem_59 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_75)
          lru_mem_60 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_76)
          lru_mem_61 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_77)
          lru_mem_62 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_78)
          lru_mem_63 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_79)
          lru_mem_64 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_80)
          lru_mem_65 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_81)
          lru_mem_66 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_82)
          lru_mem_67 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_83)
          lru_mem_68 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_84)
          lru_mem_69 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_85)
          lru_mem_70 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_86)
          lru_mem_71 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_87)
          lru_mem_72 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_88)
          lru_mem_73 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_89)
          lru_mem_74 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_90)
          lru_mem_75 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_91)
          lru_mem_76 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_92)
          lru_mem_77 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_93)
          lru_mem_78 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_94)
          lru_mem_79 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_95)
          lru_mem_80 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_96)
          lru_mem_81 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_97)
          lru_mem_82 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_98)
          lru_mem_83 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_99)
          lru_mem_84 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_100)
          lru_mem_85 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_101)
          lru_mem_86 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_102)
          lru_mem_87 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_103)
          lru_mem_88 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_104)
          lru_mem_89 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_105)
          lru_mem_90 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_106)
          lru_mem_91 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_107)
          lru_mem_92 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_108)
          lru_mem_93 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_109)
          lru_mem_94 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_110)
          lru_mem_95 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_111)
          lru_mem_96 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_112)
          lru_mem_97 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_113)
          lru_mem_98 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_114)
          lru_mem_99 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_115)
          lru_mem_100 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_116)
          lru_mem_101 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_117)
          lru_mem_102 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_118)
          lru_mem_103 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_119)
          lru_mem_104 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_120)
          lru_mem_105 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_121)
          lru_mem_106 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_122)
          lru_mem_107 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_123)
          lru_mem_108 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_124)
          lru_mem_109 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_125)
          lru_mem_110 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_126)
          lru_mem_111 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_127)
          lru_mem_112 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_128)
          lru_mem_113 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_129)
          lru_mem_114 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_130)
          lru_mem_115 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_131)
          lru_mem_116 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_132)
          lru_mem_117 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_133)
          lru_mem_118 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_134)
          lru_mem_119 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_135)
          lru_mem_120 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_136)
          lru_mem_121 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_137)
          lru_mem_122 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_138)
          lru_mem_123 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_139)
          lru_mem_124 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_140)
          lru_mem_125 <= ~_GEN_6;
        if (lru_miss_upd & _GEN_141)
          lru_mem_126 <= ~_GEN_6;
        if (lru_miss_upd & (&(paddr_reg_IF_RM[12:6])))
          lru_mem_127 <= ~_GEN_6;
      end
      if (i_rready) begin
        ret_buf <= {_ir_io_icache_wdata_inst, ret_buf[511:32]};
        pc_sign_buf <= {_ir_io_icache_wdata_pc_sign, pc_sign_buf[31:2]};
      end
      if (io_i_rready)
        inst_temp_buf <= io_i_rdata;
      if (|state) begin
        if (i_rready)
          rd_cnt <= 4'(rd_cnt + 4'h1);
        state <= _GEN_13[state];
      end
      else begin
        rd_cnt <= 4'h0;
        if (io_exception_RM)
          state <= 2'h0;
        else if (cacop_en_reg_IF_RM)
          state <= {cacop_exec_RM, 1'h0};
        else if (rvalid_reg_IF_RM)
          state <= uncache_reg_IF_RM ? 2'h1 : {1'h0, ~(|_cache_hit_RM_T)};
      end
    end
    i_rready <= io_i_rready;
    read_finish <= io_i_rlast & i_rready;
  end // always @(posedge)
  assign _ir_io_pc = 32'({26'h0, rd_cnt, 2'h0} + io_i_araddr_0);
  Inst_Replace ir (
    .io_inst_raw             (inst_temp_buf),
    .io_pc                   (_ir_io_pc),
    .io_icache_wdata_inst    (_ir_io_icache_wdata_inst),
    .io_icache_wdata_pc_sign (_ir_io_icache_wdata_pc_sign)
  );
  assign _xilinx_single_port_ram_write_first_wea = ~_GEN_12 & _GEN_11 & ~tag_idx;
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(20)
  ) xilinx_single_port_ram_write_first (
    .addra (tagv_0_addra),
    .dina  (tagv_0_dina),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_write_first_wea),
    .douta (_xilinx_single_port_ram_write_first_douta)
  );
  assign _xilinx_single_port_ram_write_first_1_wea = ~_GEN_12 & _GEN_11 & tag_idx;
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(20)
  ) xilinx_single_port_ram_write_first_1 (
    .addra (tagv_1_addra),
    .dina  (tagv_1_dina),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_write_first_1_wea),
    .douta (_xilinx_single_port_ram_write_first_1_douta)
  );
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(512)
  ) xilinx_single_port_ram_write_first_2 (
    .addra (cmem_0_addra),
    .dina  (ret_buf),
    .clka  (clock),
    .wea   (cmem_we_RM_0),
    .douta (_xilinx_single_port_ram_write_first_2_douta)
  );
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(512)
  ) xilinx_single_port_ram_write_first_3 (
    .addra (cmem_1_addra),
    .dina  (ret_buf),
    .clka  (clock),
    .wea   (cmem_we_RM_1),
    .douta (_xilinx_single_port_ram_write_first_3_douta)
  );
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(32)
  ) xilinx_single_port_ram_write_first_4 (
    .addra (pc_sign_mem_0_addra),
    .dina  (pc_sign_buf),
    .clka  (clock),
    .wea   (cmem_we_RM_0),
    .douta (_xilinx_single_port_ram_write_first_4_douta)
  );
  xilinx_single_port_ram_write_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(32)
  ) xilinx_single_port_ram_write_first_5 (
    .addra (pc_sign_mem_1_addra),
    .dina  (pc_sign_buf),
    .clka  (clock),
    .wea   (cmem_we_RM_1),
    .douta (_xilinx_single_port_ram_write_first_5_douta)
  );
  assign io_has_cacop_IF = cacop_en_IF;
  assign io_cache_miss_RM = cache_miss_RM;
  assign io_rdata_RM_0 = data_sel ? rbuf_rdata_RM[31:0] : _GEN_1[31:0];
  assign io_rdata_RM_1 = data_sel ? rbuf_rdata_RM[63:32] : _GEN_1[63:32];
  assign io_pc_sign_RM_0 = data_sel ? pbuf_rdata_RM[1:0] : _GEN_4[1:0];
  assign io_pc_sign_RM_1 = data_sel ? pbuf_rdata_RM[3:2] : _GEN_4[3:2];
  assign io_i_araddr = io_i_araddr_0;
  assign io_i_rvalid = (|state) & _GEN_10 & ~read_finish;
  assign io_i_rlen = {4'h0, _io_i_rlen_T};
endmodule

