// Generated by CIRCT firtool-1.62.0
module Inst_Replace(
  input  [31:0] io_inst_raw,
                io_pc,
  output [31:0] io_icache_wdata_inst,
  output [1:0]  io_icache_wdata_pc_sign
);

  wire [1:0]  _GEN =
    io_inst_raw[29:26] == 4'h4 | io_inst_raw[29:26] == 4'h5
      ? 2'h1
      : {io_inst_raw[29:26] != 4'h3, 1'h0};
  wire [1:0]  br_type = io_inst_raw[31:30] == 2'h1 ? _GEN : 2'h0;
  wire [19:0] _pc_add_imm16_T_4 =
    20'(io_pc[19:0] + {{2{io_inst_raw[25]}}, io_inst_raw[25:10], 2'h0});
  wire [29:0] _pc_add_imm26_T_5 =
    30'(io_pc[29:0] + {{2{io_inst_raw[9]}}, io_inst_raw[9:0], io_inst_raw[25:10], 2'h0});
  wire        _GEN_0 = br_type == 2'h1;
  wire        _GEN_1 = br_type == 2'h2;
  wire [31:0] _GEN_2 =
    _GEN_1
      ? {io_inst_raw[31:26], _pc_add_imm16_T_4[17:2], io_inst_raw[9:0]}
      : io_inst_raw;
  wire [1:0]  _GEN_3 = _GEN_1 ? 2'(_pc_add_imm16_T_4[19:18] - io_pc[19:18]) : 2'h0;
  assign io_icache_wdata_inst =
    _GEN_0
      ? {io_inst_raw[31:26], _pc_add_imm26_T_5[17:2], _pc_add_imm26_T_5[27:18]}
      : _GEN_2;
  assign io_icache_wdata_pc_sign =
    _GEN_0 ? 2'(_pc_add_imm26_T_5[29:28] - io_pc[29:28]) : _GEN_3;
endmodule

