// Generated by CIRCT firtool-1.62.0
module MDU(
  input         clock,
                reset,
  input  [31:0] io_src1,
                io_src2,
  input  [4:0]  io_md_op,
  output [31:0] io_mul_out,
                io_div_out,
  output        io_busy_16,
                io_busy_17,
                io_busy_18,
                io_busy_19,
                io_busy_20
);

  wire _mul_io_busy_6;
  wire _mul_io_busy_7;
  wire _mul_io_busy_8;
  wire _mul_io_busy_9;
  wire _mul_io_busy_10;
  wire _mul_io_busy_11;
  wire _mul_io_busy_12;
  wire _mul_io_busy_13;
  wire _mul_io_busy_14;
  wire _mul_io_busy_15;
  Multiply mul (
    .clock      (clock),
    .io_src1    (io_src1),
    .io_src2    (io_src2),
    .io_op      (io_md_op),
    .io_busy_6  (_mul_io_busy_6),
    .io_busy_7  (_mul_io_busy_7),
    .io_busy_8  (_mul_io_busy_8),
    .io_busy_9  (_mul_io_busy_9),
    .io_busy_10 (_mul_io_busy_10),
    .io_busy_11 (_mul_io_busy_11),
    .io_busy_12 (_mul_io_busy_12),
    .io_busy_13 (_mul_io_busy_13),
    .io_busy_14 (_mul_io_busy_14),
    .io_busy_15 (_mul_io_busy_15),
    .io_res     (io_mul_out)
  );
  Divide div (
    .clock      (clock),
    .reset      (reset),
    .io_src1    (io_src1),
    .io_src2    (io_src2),
    .io_op      (io_md_op),
    .io_res     (io_div_out),
    .io_busy_6  (_mul_io_busy_6),
    .io_busy_7  (_mul_io_busy_7),
    .io_busy_8  (_mul_io_busy_8),
    .io_busy_9  (_mul_io_busy_9),
    .io_busy_10 (_mul_io_busy_10),
    .io_busy_11 (_mul_io_busy_11),
    .io_busy_12 (_mul_io_busy_12),
    .io_busy_13 (_mul_io_busy_13),
    .io_busy_14 (_mul_io_busy_14),
    .io_busy_15 (_mul_io_busy_15),
    .io_busy_16 (io_busy_16),
    .io_busy_17 (io_busy_17),
    .io_busy_18 (io_busy_18),
    .io_busy_19 (io_busy_19),
    .io_busy_20 (io_busy_20)
  );
endmodule

