// Generated by CIRCT firtool-1.62.0
module Multiply(
  input         clock,
  input  [31:0] io_src1,
                io_src2,
  input  [4:0]  io_op,
  input         io_busy_6,
                io_busy_7,
                io_busy_8,
                io_busy_9,
                io_busy_10,
                io_busy_11,
                io_busy_12,
                io_busy_13,
                io_busy_14,
                io_busy_15,
  output [31:0] io_res
);

  reg  [65:0] booth_reg1_0;
  reg  [65:0] booth_reg1_1;
  reg  [65:0] booth_reg1_2;
  reg  [65:0] booth_reg1_3;
  reg  [65:0] booth_reg1_4;
  reg  [65:0] booth_reg2_0;
  reg  [65:0] booth_reg2_1;
  reg  [65:0] booth_reg2_2;
  reg  [65:0] booth_reg2_3;
  reg  [65:0] booth_reg2_4;
  reg  [65:0] booth_reg3_0;
  reg  [65:0] booth_reg3_1;
  reg  [65:0] booth_reg3_2;
  reg  [65:0] booth_reg3_3;
  reg  [65:0] booth_reg3_4;
  reg  [65:0] booth_reg4_0;
  reg  [65:0] booth_reg4_1;
  reg  [65:0] booth_reg4_2;
  reg  [65:0] booth_reg4_3;
  reg  [65:0] booth_reg4_4;
  reg  [65:0] booth_reg5_0;
  reg  [65:0] booth_reg5_1;
  reg  [65:0] booth_reg5_2;
  reg  [65:0] booth_reg5_3;
  reg  [65:0] booth_reg5_4;
  reg  [65:0] booth_reg6_0;
  reg  [65:0] booth_reg6_1;
  reg  [65:0] booth_reg6_2;
  reg  [65:0] booth_reg6_3;
  reg  [65:0] booth_reg6_4;
  reg  [65:0] booth_reg7_0;
  reg  [65:0] booth_reg7_1;
  reg  [65:0] booth_reg7_2;
  reg  [63:0] adder_src1;
  reg  [63:0] adder_src2;
  reg  [4:0]  op_reg1;
  reg  [4:0]  op_reg2;
  wire [63:0] _res_T = 64'(adder_src1 + adder_src2);
  wire        _src2_T = io_op == 5'h2;
  wire [33:0] _GEN = _src2_T ? 34'h0 : {34{io_src1[31]}};
  wire [33:0] _GEN_0 = _src2_T ? 34'h0 : {34{io_src2[31]}};
  wire [63:0] level1_x_xor_y = booth_reg1_0[63:0] ^ booth_reg1_1[63:0];
  wire [63:0] level1_res1 = level1_x_xor_y ^ booth_reg1_2[63:0];
  wire [62:0] _level1_res2_T_2 =
    booth_reg1_0[62:0] & booth_reg1_1[62:0] | booth_reg1_2[62:0] & level1_x_xor_y[62:0];
  wire [63:0] level1_x_xor_y_1 = booth_reg1_3[63:0] ^ booth_reg1_4[63:0];
  wire [63:0] level1_res1_1 = level1_x_xor_y_1 ^ booth_reg2_0[63:0];
  wire [62:0] _level1_res2_T_7 =
    booth_reg1_3[62:0] & booth_reg1_4[62:0] | booth_reg2_0[62:0] & level1_x_xor_y_1[62:0];
  wire [63:0] level1_x_xor_y_2 = booth_reg2_1[63:0] ^ booth_reg2_2[63:0];
  wire [63:0] level1_res1_2 = level1_x_xor_y_2 ^ booth_reg2_3[63:0];
  wire [62:0] _level1_res2_T_12 =
    booth_reg2_1[62:0] & booth_reg2_2[62:0] | booth_reg2_3[62:0] & level1_x_xor_y_2[62:0];
  wire [63:0] level1_x_xor_y_3 = booth_reg2_4[63:0] ^ booth_reg3_0[63:0];
  wire [63:0] level1_res1_3 = level1_x_xor_y_3 ^ booth_reg3_1[63:0];
  wire [62:0] _level1_res2_T_17 =
    booth_reg2_4[62:0] & booth_reg3_0[62:0] | booth_reg3_1[62:0] & level1_x_xor_y_3[62:0];
  wire [63:0] level1_x_xor_y_4 = booth_reg3_2[63:0] ^ booth_reg3_3[63:0];
  wire [63:0] level1_res1_4 = level1_x_xor_y_4 ^ booth_reg3_4[63:0];
  wire [62:0] _level1_res2_T_22 =
    booth_reg3_2[62:0] & booth_reg3_3[62:0] | booth_reg3_4[62:0] & level1_x_xor_y_4[62:0];
  wire [63:0] level1_x_xor_y_5 = booth_reg4_0[63:0] ^ booth_reg4_1[63:0];
  wire [63:0] level1_res1_5 = level1_x_xor_y_5 ^ booth_reg4_2[63:0];
  wire [62:0] _level1_res2_T_27 =
    booth_reg4_0[62:0] & booth_reg4_1[62:0] | booth_reg4_2[62:0] & level1_x_xor_y_5[62:0];
  wire [63:0] level1_x_xor_y_6 = booth_reg4_3[63:0] ^ booth_reg4_4[63:0];
  wire [63:0] level1_res1_6 = level1_x_xor_y_6 ^ booth_reg5_0[63:0];
  wire [62:0] _level1_res2_T_32 =
    booth_reg4_3[62:0] & booth_reg4_4[62:0] | booth_reg5_0[62:0] & level1_x_xor_y_6[62:0];
  wire [63:0] level1_x_xor_y_7 = booth_reg5_1[63:0] ^ booth_reg5_2[63:0];
  wire [63:0] level1_res1_7 = level1_x_xor_y_7 ^ booth_reg5_3[63:0];
  wire [62:0] _level1_res2_T_37 =
    booth_reg5_1[62:0] & booth_reg5_2[62:0] | booth_reg5_3[62:0] & level1_x_xor_y_7[62:0];
  wire [63:0] level1_x_xor_y_8 = booth_reg5_4[63:0] ^ booth_reg6_0[63:0];
  wire [63:0] level1_res1_8 = level1_x_xor_y_8 ^ booth_reg6_1[63:0];
  wire [62:0] _level1_res2_T_42 =
    booth_reg5_4[62:0] & booth_reg6_0[62:0] | booth_reg6_1[62:0] & level1_x_xor_y_8[62:0];
  wire [63:0] level1_x_xor_y_9 = booth_reg6_2[63:0] ^ booth_reg6_3[63:0];
  wire [63:0] level1_res1_9 = level1_x_xor_y_9 ^ booth_reg6_4[63:0];
  wire [62:0] _level1_res2_T_47 =
    booth_reg6_2[62:0] & booth_reg6_3[62:0] | booth_reg6_4[62:0] & level1_x_xor_y_9[62:0];
  wire [63:0] level1_x_xor_y_10 = booth_reg7_0[63:0] ^ booth_reg7_1[63:0];
  wire [63:0] level1_res1_10 = level1_x_xor_y_10 ^ booth_reg7_2[63:0];
  wire [62:0] _level1_res2_T_52 =
    booth_reg7_0[62:0] & booth_reg7_1[62:0] | booth_reg7_2[62:0]
    & level1_x_xor_y_10[62:0];
  wire [63:0] level2_x_xor_y = level1_res1 ^ {_level1_res2_T_2, 1'h0};
  wire [63:0] level2_res1 = level2_x_xor_y ^ level1_res1_1;
  wire [62:0] _level2_res2_T_2 =
    level1_res1[62:0] & {_level1_res2_T_2[61:0], 1'h0} | level1_res1_1[62:0]
    & level2_x_xor_y[62:0];
  wire [63:0] level2_x_xor_y_1 = {_level1_res2_T_7, 1'h0} ^ level1_res1_2;
  wire [63:0] level2_res1_1 = level2_x_xor_y_1 ^ {_level1_res2_T_12, 1'h0};
  wire [62:0] _level2_res2_T_7 =
    {_level1_res2_T_7[61:0], 1'h0} & level1_res1_2[62:0] | {_level1_res2_T_12[61:0], 1'h0}
    & level2_x_xor_y_1[62:0];
  wire [63:0] level2_x_xor_y_2 = level1_res1_3 ^ {_level1_res2_T_17, 1'h0};
  wire [63:0] level2_res1_2 = level2_x_xor_y_2 ^ level1_res1_4;
  wire [62:0] _level2_res2_T_12 =
    level1_res1_3[62:0] & {_level1_res2_T_17[61:0], 1'h0} | level1_res1_4[62:0]
    & level2_x_xor_y_2[62:0];
  wire [63:0] level2_x_xor_y_3 = {_level1_res2_T_22, 1'h0} ^ level1_res1_5;
  wire [63:0] level2_res1_3 = level2_x_xor_y_3 ^ {_level1_res2_T_27, 1'h0};
  wire [62:0] _level2_res2_T_17 =
    {_level1_res2_T_22[61:0], 1'h0} & level1_res1_5[62:0]
    | {_level1_res2_T_27[61:0], 1'h0} & level2_x_xor_y_3[62:0];
  wire [63:0] level2_x_xor_y_4 = level1_res1_6 ^ {_level1_res2_T_32, 1'h0};
  wire [63:0] level2_res1_4 = level2_x_xor_y_4 ^ level1_res1_7;
  wire [62:0] _level2_res2_T_22 =
    level1_res1_6[62:0] & {_level1_res2_T_32[61:0], 1'h0} | level1_res1_7[62:0]
    & level2_x_xor_y_4[62:0];
  wire [63:0] level2_x_xor_y_5 = {_level1_res2_T_37, 1'h0} ^ level1_res1_8;
  wire [63:0] level2_res1_5 = level2_x_xor_y_5 ^ {_level1_res2_T_42, 1'h0};
  wire [62:0] _level2_res2_T_27 =
    {_level1_res2_T_37[61:0], 1'h0} & level1_res1_8[62:0]
    | {_level1_res2_T_42[61:0], 1'h0} & level2_x_xor_y_5[62:0];
  wire [63:0] level2_x_xor_y_6 = level1_res1_9 ^ {_level1_res2_T_47, 1'h0};
  wire [63:0] level2_res1_6 = level2_x_xor_y_6 ^ level1_res1_10;
  wire [62:0] _level2_res2_T_32 =
    level1_res1_9[62:0] & {_level1_res2_T_47[61:0], 1'h0} | level1_res1_10[62:0]
    & level2_x_xor_y_6[62:0];
  wire [63:0] level3_x_xor_y = level2_res1 ^ {_level2_res2_T_2, 1'h0};
  wire [63:0] level3_res1 = level3_x_xor_y ^ level2_res1_1;
  wire [62:0] _level3_res2_T_2 =
    level2_res1[62:0] & {_level2_res2_T_2[61:0], 1'h0} | level2_res1_1[62:0]
    & level3_x_xor_y[62:0];
  wire [63:0] level3_x_xor_y_1 = {_level2_res2_T_7, 1'h0} ^ level2_res1_2;
  wire [63:0] level3_res1_1 = level3_x_xor_y_1 ^ {_level2_res2_T_12, 1'h0};
  wire [62:0] _level3_res2_T_7 =
    {_level2_res2_T_7[61:0], 1'h0} & level2_res1_2[62:0] | {_level2_res2_T_12[61:0], 1'h0}
    & level3_x_xor_y_1[62:0];
  wire [63:0] level3_x_xor_y_2 = level2_res1_3 ^ {_level2_res2_T_17, 1'h0};
  wire [63:0] level3_res1_2 = level3_x_xor_y_2 ^ level2_res1_4;
  wire [62:0] _level3_res2_T_12 =
    level2_res1_3[62:0] & {_level2_res2_T_17[61:0], 1'h0} | level2_res1_4[62:0]
    & level3_x_xor_y_2[62:0];
  wire [63:0] level3_x_xor_y_3 = {_level2_res2_T_22, 1'h0} ^ level2_res1_5;
  wire [63:0] level3_res1_3 = level3_x_xor_y_3 ^ {_level2_res2_T_27, 1'h0};
  wire [62:0] _level3_res2_T_17 =
    {_level2_res2_T_22[61:0], 1'h0} & level2_res1_5[62:0]
    | {_level2_res2_T_27[61:0], 1'h0} & level3_x_xor_y_3[62:0];
  wire [63:0] level3_x_xor_y_4 = level2_res1_6 ^ {_level2_res2_T_32, 1'h0};
  wire [63:0] level3_res1_4 = level3_x_xor_y_4 ^ {_level1_res2_T_52, 1'h0};
  wire [62:0] _level3_res2_T_22 =
    level2_res1_6[62:0] & {_level2_res2_T_32[61:0], 1'h0}
    | {_level1_res2_T_52[61:0], 1'h0} & level3_x_xor_y_4[62:0];
  wire [63:0] level4_x_xor_y = level3_res1 ^ {_level3_res2_T_2, 1'h0};
  wire [63:0] level4_res1 = level4_x_xor_y ^ level3_res1_1;
  wire [62:0] _level4_res2_T_2 =
    level3_res1[62:0] & {_level3_res2_T_2[61:0], 1'h0} | level3_res1_1[62:0]
    & level4_x_xor_y[62:0];
  wire [63:0] level4_x_xor_y_1 = {_level3_res2_T_7, 1'h0} ^ level3_res1_2;
  wire [63:0] level4_res1_1 = level4_x_xor_y_1 ^ {_level3_res2_T_12, 1'h0};
  wire [62:0] _level4_res2_T_7 =
    {_level3_res2_T_7[61:0], 1'h0} & level3_res1_2[62:0] | {_level3_res2_T_12[61:0], 1'h0}
    & level4_x_xor_y_1[62:0];
  wire [63:0] level4_x_xor_y_2 = level3_res1_3 ^ {_level3_res2_T_17, 1'h0};
  wire [63:0] level4_res1_2 = level4_x_xor_y_2 ^ level3_res1_4;
  wire [62:0] _level4_res2_T_12 =
    level3_res1_3[62:0] & {_level3_res2_T_17[61:0], 1'h0} | level3_res1_4[62:0]
    & level4_x_xor_y_2[62:0];
  wire [63:0] level5_x_xor_y = level4_res1 ^ {_level4_res2_T_2, 1'h0};
  wire [63:0] level5_res1 = level5_x_xor_y ^ level4_res1_1;
  wire [62:0] _level5_res2_T_2 =
    level4_res1[62:0] & {_level4_res2_T_2[61:0], 1'h0} | level4_res1_1[62:0]
    & level5_x_xor_y[62:0];
  wire [63:0] level5_x_xor_y_1 = {_level4_res2_T_7, 1'h0} ^ level4_res1_2;
  wire [63:0] level5_res1_1 = level5_x_xor_y_1 ^ {_level4_res2_T_12, 1'h0};
  wire [62:0] _level5_res2_T_7 =
    {_level4_res2_T_7[61:0], 1'h0} & level4_res1_2[62:0] | {_level4_res2_T_12[61:0], 1'h0}
    & level5_x_xor_y_1[62:0];
  wire [63:0] level6_x_xor_y = level5_res1 ^ {_level5_res2_T_2, 1'h0};
  wire [63:0] level6_res1 = level6_x_xor_y ^ level5_res1_1;
  wire [62:0] _level6_res2_T_2 =
    level5_res1[62:0] & {_level5_res2_T_2[61:0], 1'h0} | level5_res1_1[62:0]
    & level6_x_xor_y[62:0];
  wire [63:0] level7_x_xor_y = level6_res1 ^ {_level6_res2_T_2, 1'h0};
  wire [63:0] level7_res1 = level7_x_xor_y ^ {_level5_res2_T_7, 1'h0};
  wire [62:0] _level7_res2_T_2 =
    level6_res1[62:0] & {_level6_res2_T_2[61:0], 1'h0} | {_level5_res2_T_7[61:0], 1'h0}
    & level7_x_xor_y[62:0];
  wire [63:0] level8_x_xor_y = level7_res1 ^ {_level7_res2_T_2, 1'h0};
  wire [65:0] _GEN_1 =
    io_src2[1:0] == 2'h2 ? {_GEN[32:0], io_src1, 1'h0} : {_GEN, io_src1};
  wire [65:0] booth_res = io_src2[1:0] == 2'h0 ? 66'h0 : _GEN_1;
  wire [65:0] _GEN_2 = (&(io_src2[3:1])) ? 66'h0 : {_GEN[31:0], io_src1, 2'h0};
  wire [65:0] _GEN_3 = io_src2[3:1] == 3'h4 ? {_GEN[30:0], io_src1, 3'h0} : _GEN_2;
  wire [65:0] _GEN_4 = io_src2[3:1] == 3'h3 ? {_GEN[30:0], io_src1, 3'h0} : _GEN_3;
  wire [65:0] booth_res_1 = io_src2[3:1] == 3'h0 ? 66'h0 : _GEN_4;
  wire [65:0] _GEN_5 = (&(io_src2[5:3])) ? 66'h0 : {_GEN[29:0], io_src1, 4'h0};
  wire [65:0] _GEN_6 = io_src2[5:3] == 3'h4 ? {_GEN[28:0], io_src1, 5'h0} : _GEN_5;
  wire [65:0] _GEN_7 = io_src2[5:3] == 3'h3 ? {_GEN[28:0], io_src1, 5'h0} : _GEN_6;
  wire [65:0] booth_res_2 = io_src2[5:3] == 3'h0 ? 66'h0 : _GEN_7;
  wire [65:0] _GEN_8 = (&(io_src2[7:5])) ? 66'h0 : {_GEN[27:0], io_src1, 6'h0};
  wire [65:0] _GEN_9 = io_src2[7:5] == 3'h4 ? {_GEN[26:0], io_src1, 7'h0} : _GEN_8;
  wire [65:0] _GEN_10 = io_src2[7:5] == 3'h3 ? {_GEN[26:0], io_src1, 7'h0} : _GEN_9;
  wire [65:0] booth_res_3 = io_src2[7:5] == 3'h0 ? 66'h0 : _GEN_10;
  wire [65:0] _GEN_11 = (&(io_src2[9:7])) ? 66'h0 : {_GEN[25:0], io_src1, 8'h0};
  wire [65:0] _GEN_12 = io_src2[9:7] == 3'h4 ? {_GEN[24:0], io_src1, 9'h0} : _GEN_11;
  wire [65:0] _GEN_13 = io_src2[9:7] == 3'h3 ? {_GEN[24:0], io_src1, 9'h0} : _GEN_12;
  wire [65:0] booth_res_4 = io_src2[9:7] == 3'h0 ? 66'h0 : _GEN_13;
  wire [65:0] _GEN_14 = (&(io_src2[11:9])) ? 66'h0 : {_GEN[23:0], io_src1, 10'h0};
  wire [65:0] _GEN_15 = io_src2[11:9] == 3'h4 ? {_GEN[22:0], io_src1, 11'h0} : _GEN_14;
  wire [65:0] _GEN_16 = io_src2[11:9] == 3'h3 ? {_GEN[22:0], io_src1, 11'h0} : _GEN_15;
  wire [65:0] booth_res_5 = io_src2[11:9] == 3'h0 ? 66'h0 : _GEN_16;
  wire [65:0] _GEN_17 = (&(io_src2[13:11])) ? 66'h0 : {_GEN[21:0], io_src1, 12'h0};
  wire [65:0] _GEN_18 = io_src2[13:11] == 3'h4 ? {_GEN[20:0], io_src1, 13'h0} : _GEN_17;
  wire [65:0] _GEN_19 = io_src2[13:11] == 3'h3 ? {_GEN[20:0], io_src1, 13'h0} : _GEN_18;
  wire [65:0] booth_res_6 = io_src2[13:11] == 3'h0 ? 66'h0 : _GEN_19;
  wire [65:0] _GEN_20 = (&(io_src2[15:13])) ? 66'h0 : {_GEN[19:0], io_src1, 14'h0};
  wire [65:0] _GEN_21 = io_src2[15:13] == 3'h4 ? {_GEN[18:0], io_src1, 15'h0} : _GEN_20;
  wire [65:0] _GEN_22 = io_src2[15:13] == 3'h3 ? {_GEN[18:0], io_src1, 15'h0} : _GEN_21;
  wire [65:0] booth_res_7 = io_src2[15:13] == 3'h0 ? 66'h0 : _GEN_22;
  wire [65:0] _GEN_23 = (&(io_src2[17:15])) ? 66'h0 : {_GEN[17:0], io_src1, 16'h0};
  wire [65:0] _GEN_24 = io_src2[17:15] == 3'h4 ? {_GEN[16:0], io_src1, 17'h0} : _GEN_23;
  wire [65:0] _GEN_25 = io_src2[17:15] == 3'h3 ? {_GEN[16:0], io_src1, 17'h0} : _GEN_24;
  wire [65:0] booth_res_8 = io_src2[17:15] == 3'h0 ? 66'h0 : _GEN_25;
  wire [65:0] _GEN_26 = (&(io_src2[19:17])) ? 66'h0 : {_GEN[15:0], io_src1, 18'h0};
  wire [65:0] _GEN_27 = io_src2[19:17] == 3'h4 ? {_GEN[14:0], io_src1, 19'h0} : _GEN_26;
  wire [65:0] _GEN_28 = io_src2[19:17] == 3'h3 ? {_GEN[14:0], io_src1, 19'h0} : _GEN_27;
  wire [65:0] booth_res_9 = io_src2[19:17] == 3'h0 ? 66'h0 : _GEN_28;
  wire [65:0] _GEN_29 = (&(io_src2[21:19])) ? 66'h0 : {_GEN[13:0], io_src1, 20'h0};
  wire [65:0] _GEN_30 = io_src2[21:19] == 3'h4 ? {_GEN[12:0], io_src1, 21'h0} : _GEN_29;
  wire [65:0] _GEN_31 = io_src2[21:19] == 3'h3 ? {_GEN[12:0], io_src1, 21'h0} : _GEN_30;
  wire [65:0] booth_res_10 = io_src2[21:19] == 3'h0 ? 66'h0 : _GEN_31;
  wire [65:0] _GEN_32 = (&(io_src2[23:21])) ? 66'h0 : {_GEN[11:0], io_src1, 22'h0};
  wire [65:0] _GEN_33 = io_src2[23:21] == 3'h4 ? {_GEN[10:0], io_src1, 23'h0} : _GEN_32;
  wire [65:0] _GEN_34 = io_src2[23:21] == 3'h3 ? {_GEN[10:0], io_src1, 23'h0} : _GEN_33;
  wire [65:0] booth_res_11 = io_src2[23:21] == 3'h0 ? 66'h0 : _GEN_34;
  wire [65:0] _GEN_35 = (&(io_src2[25:23])) ? 66'h0 : {_GEN[9:0], io_src1, 24'h0};
  wire [65:0] _GEN_36 = io_src2[25:23] == 3'h4 ? {_GEN[8:0], io_src1, 25'h0} : _GEN_35;
  wire [65:0] _GEN_37 = io_src2[25:23] == 3'h3 ? {_GEN[8:0], io_src1, 25'h0} : _GEN_36;
  wire [65:0] booth_res_12 = io_src2[25:23] == 3'h0 ? 66'h0 : _GEN_37;
  wire [65:0] _GEN_38 = (&(io_src2[27:25])) ? 66'h0 : {_GEN[7:0], io_src1, 26'h0};
  wire [65:0] _GEN_39 = io_src2[27:25] == 3'h4 ? {_GEN[6:0], io_src1, 27'h0} : _GEN_38;
  wire [65:0] _GEN_40 = io_src2[27:25] == 3'h3 ? {_GEN[6:0], io_src1, 27'h0} : _GEN_39;
  wire [65:0] booth_res_13 = io_src2[27:25] == 3'h0 ? 66'h0 : _GEN_40;
  wire [65:0] _GEN_41 = (&(io_src2[29:27])) ? 66'h0 : {_GEN[5:0], io_src1, 28'h0};
  wire [65:0] _GEN_42 = io_src2[29:27] == 3'h4 ? {_GEN[4:0], io_src1, 29'h0} : _GEN_41;
  wire [65:0] _GEN_43 = io_src2[29:27] == 3'h3 ? {_GEN[4:0], io_src1, 29'h0} : _GEN_42;
  wire [65:0] booth_res_14 = io_src2[29:27] == 3'h0 ? 66'h0 : _GEN_43;
  wire [65:0] _GEN_44 = (&(io_src2[31:29])) ? 66'h0 : {_GEN[3:0], io_src1, 30'h0};
  wire [65:0] _GEN_45 = io_src2[31:29] == 3'h4 ? {_GEN[2:0], io_src1, 31'h0} : _GEN_44;
  wire [65:0] _GEN_46 = io_src2[31:29] == 3'h3 ? {_GEN[2:0], io_src1, 31'h0} : _GEN_45;
  wire [65:0] booth_res_15 = io_src2[31:29] == 3'h0 ? 66'h0 : _GEN_46;
  wire [2:0]  _booth_T_179 = {_GEN_0[1:0], io_src2[31]};
  wire [65:0] _GEN_47 = (&_booth_T_179) ? 66'h0 : {_GEN[1:0], io_src1, 32'h0};
  wire [65:0] _GEN_48 = _booth_T_179 == 3'h4 ? {_GEN[0], io_src1, 33'h0} : _GEN_47;
  wire [65:0] _GEN_49 = _booth_T_179 == 3'h3 ? {_GEN[0], io_src1, 33'h0} : _GEN_48;
  wire [65:0] booth_res_16 = _booth_T_179 == 3'h0 ? 66'h0 : _GEN_49;
  wire [65:0] _GEN_50 = (&(_GEN_0[3:1])) ? 66'h0 : {io_src1, 34'h0};
  wire [65:0] _GEN_51 = _GEN_0[3:1] == 3'h4 ? {io_src1[30:0], 35'h0} : _GEN_50;
  wire [65:0] _GEN_52 = _GEN_0[3:1] == 3'h3 ? {io_src1[30:0], 35'h0} : _GEN_51;
  wire [65:0] booth_res_17 = _GEN_0[3:1] == 3'h0 ? 66'h0 : _GEN_52;
  wire [65:0] _GEN_53 = (&(_GEN_0[5:3])) ? 66'h0 : {io_src1[29:0], 36'h0};
  wire [65:0] _GEN_54 = _GEN_0[5:3] == 3'h4 ? {io_src1[28:0], 37'h0} : _GEN_53;
  wire [65:0] _GEN_55 = _GEN_0[5:3] == 3'h3 ? {io_src1[28:0], 37'h0} : _GEN_54;
  wire [65:0] booth_res_18 = _GEN_0[5:3] == 3'h0 ? 66'h0 : _GEN_55;
  wire [65:0] _GEN_56 = (&(_GEN_0[7:5])) ? 66'h0 : {io_src1[27:0], 38'h0};
  wire [65:0] _GEN_57 = _GEN_0[7:5] == 3'h4 ? {io_src1[26:0], 39'h0} : _GEN_56;
  wire [65:0] _GEN_58 = _GEN_0[7:5] == 3'h3 ? {io_src1[26:0], 39'h0} : _GEN_57;
  wire [65:0] booth_res_19 = _GEN_0[7:5] == 3'h0 ? 66'h0 : _GEN_58;
  wire [65:0] _GEN_59 = (&(_GEN_0[9:7])) ? 66'h0 : {io_src1[25:0], 40'h0};
  wire [65:0] _GEN_60 = _GEN_0[9:7] == 3'h4 ? {io_src1[24:0], 41'h0} : _GEN_59;
  wire [65:0] _GEN_61 = _GEN_0[9:7] == 3'h3 ? {io_src1[24:0], 41'h0} : _GEN_60;
  wire [65:0] booth_res_20 = _GEN_0[9:7] == 3'h0 ? 66'h0 : _GEN_61;
  wire [65:0] _GEN_62 = (&(_GEN_0[11:9])) ? 66'h0 : {io_src1[23:0], 42'h0};
  wire [65:0] _GEN_63 = _GEN_0[11:9] == 3'h4 ? {io_src1[22:0], 43'h0} : _GEN_62;
  wire [65:0] _GEN_64 = _GEN_0[11:9] == 3'h3 ? {io_src1[22:0], 43'h0} : _GEN_63;
  wire [65:0] booth_res_21 = _GEN_0[11:9] == 3'h0 ? 66'h0 : _GEN_64;
  wire [65:0] _GEN_65 = (&(_GEN_0[13:11])) ? 66'h0 : {io_src1[21:0], 44'h0};
  wire [65:0] _GEN_66 = _GEN_0[13:11] == 3'h4 ? {io_src1[20:0], 45'h0} : _GEN_65;
  wire [65:0] _GEN_67 = _GEN_0[13:11] == 3'h3 ? {io_src1[20:0], 45'h0} : _GEN_66;
  wire [65:0] booth_res_22 = _GEN_0[13:11] == 3'h0 ? 66'h0 : _GEN_67;
  wire [65:0] _GEN_68 = (&(_GEN_0[15:13])) ? 66'h0 : {io_src1[19:0], 46'h0};
  wire [65:0] _GEN_69 = _GEN_0[15:13] == 3'h4 ? {io_src1[18:0], 47'h0} : _GEN_68;
  wire [65:0] _GEN_70 = _GEN_0[15:13] == 3'h3 ? {io_src1[18:0], 47'h0} : _GEN_69;
  wire [65:0] booth_res_23 = _GEN_0[15:13] == 3'h0 ? 66'h0 : _GEN_70;
  wire [65:0] _GEN_71 = (&(_GEN_0[17:15])) ? 66'h0 : {io_src1[17:0], 48'h0};
  wire [65:0] _GEN_72 = _GEN_0[17:15] == 3'h4 ? {io_src1[16:0], 49'h0} : _GEN_71;
  wire [65:0] _GEN_73 = _GEN_0[17:15] == 3'h3 ? {io_src1[16:0], 49'h0} : _GEN_72;
  wire [65:0] booth_res_24 = _GEN_0[17:15] == 3'h0 ? 66'h0 : _GEN_73;
  wire [65:0] _GEN_74 = (&(_GEN_0[19:17])) ? 66'h0 : {io_src1[15:0], 50'h0};
  wire [65:0] _GEN_75 = _GEN_0[19:17] == 3'h4 ? {io_src1[14:0], 51'h0} : _GEN_74;
  wire [65:0] _GEN_76 = _GEN_0[19:17] == 3'h3 ? {io_src1[14:0], 51'h0} : _GEN_75;
  wire [65:0] booth_res_25 = _GEN_0[19:17] == 3'h0 ? 66'h0 : _GEN_76;
  wire [65:0] _GEN_77 = (&(_GEN_0[21:19])) ? 66'h0 : {io_src1[13:0], 52'h0};
  wire [65:0] _GEN_78 = _GEN_0[21:19] == 3'h4 ? {io_src1[12:0], 53'h0} : _GEN_77;
  wire [65:0] _GEN_79 = _GEN_0[21:19] == 3'h3 ? {io_src1[12:0], 53'h0} : _GEN_78;
  wire [65:0] booth_res_26 = _GEN_0[21:19] == 3'h0 ? 66'h0 : _GEN_79;
  wire [65:0] _GEN_80 = (&(_GEN_0[23:21])) ? 66'h0 : {io_src1[11:0], 54'h0};
  wire [65:0] _GEN_81 = _GEN_0[23:21] == 3'h4 ? {io_src1[10:0], 55'h0} : _GEN_80;
  wire [65:0] _GEN_82 = _GEN_0[23:21] == 3'h3 ? {io_src1[10:0], 55'h0} : _GEN_81;
  wire [65:0] booth_res_27 = _GEN_0[23:21] == 3'h0 ? 66'h0 : _GEN_82;
  wire [65:0] _GEN_83 = (&(_GEN_0[25:23])) ? 66'h0 : {io_src1[9:0], 56'h0};
  wire [65:0] _GEN_84 = _GEN_0[25:23] == 3'h4 ? {io_src1[8:0], 57'h0} : _GEN_83;
  wire [65:0] _GEN_85 = _GEN_0[25:23] == 3'h3 ? {io_src1[8:0], 57'h0} : _GEN_84;
  wire [65:0] booth_res_28 = _GEN_0[25:23] == 3'h0 ? 66'h0 : _GEN_85;
  wire [65:0] _GEN_86 = (&(_GEN_0[27:25])) ? 66'h0 : {io_src1[7:0], 58'h0};
  wire [65:0] _GEN_87 = _GEN_0[27:25] == 3'h4 ? {io_src1[6:0], 59'h0} : _GEN_86;
  wire [65:0] _GEN_88 = _GEN_0[27:25] == 3'h3 ? {io_src1[6:0], 59'h0} : _GEN_87;
  wire [65:0] booth_res_29 = _GEN_0[27:25] == 3'h0 ? 66'h0 : _GEN_88;
  wire [65:0] _GEN_89 = (&(_GEN_0[29:27])) ? 66'h0 : {io_src1[5:0], 60'h0};
  wire [65:0] _GEN_90 = _GEN_0[29:27] == 3'h4 ? {io_src1[4:0], 61'h0} : _GEN_89;
  wire [65:0] _GEN_91 = _GEN_0[29:27] == 3'h3 ? {io_src1[4:0], 61'h0} : _GEN_90;
  wire [65:0] booth_res_30 = _GEN_0[29:27] == 3'h0 ? 66'h0 : _GEN_91;
  wire [65:0] _GEN_92 = (&(_GEN_0[31:29])) ? 66'h0 : {io_src1[3:0], 62'h0};
  wire [65:0] _GEN_93 = _GEN_0[31:29] == 3'h4 ? {io_src1[2:0], 63'h0} : _GEN_92;
  wire [65:0] _GEN_94 = _GEN_0[31:29] == 3'h3 ? {io_src1[2:0], 63'h0} : _GEN_93;
  wire [65:0] booth_res_31 = _GEN_0[31:29] == 3'h0 ? 66'h0 : _GEN_94;
  wire [65:0] _GEN_95 = (&(_GEN_0[33:31])) ? 66'h0 : {io_src1[1:0], 64'h0};
  wire [65:0] _GEN_96 = _GEN_0[33:31] == 3'h4 ? {io_src1[0], 65'h0} : _GEN_95;
  wire [65:0] _GEN_97 = _GEN_0[33:31] == 3'h3 ? {io_src1[0], 65'h0} : _GEN_96;
  wire [65:0] booth_res_32 = _GEN_0[33:31] == 3'h0 ? 66'h0 : _GEN_97;
  always @(posedge clock) begin
    if (io_busy_6) begin
    end
    else begin
      booth_reg1_0 <= io_src2[1] ? 66'(~booth_res + 66'h1) : booth_res;
      booth_reg1_1 <= io_src2[3] ? 66'(~booth_res_1 + 66'h1) : booth_res_1;
      booth_reg1_2 <= io_src2[5] ? 66'(~booth_res_2 + 66'h1) : booth_res_2;
      booth_reg1_3 <= io_src2[7] ? 66'(~booth_res_3 + 66'h1) : booth_res_3;
      booth_reg1_4 <= io_src2[9] ? 66'(~booth_res_4 + 66'h1) : booth_res_4;
    end
    if (io_busy_7) begin
    end
    else begin
      booth_reg2_0 <= io_src2[11] ? 66'(~booth_res_5 + 66'h1) : booth_res_5;
      booth_reg2_1 <= io_src2[13] ? 66'(~booth_res_6 + 66'h1) : booth_res_6;
      booth_reg2_2 <= io_src2[15] ? 66'(~booth_res_7 + 66'h1) : booth_res_7;
      booth_reg2_3 <= io_src2[17] ? 66'(~booth_res_8 + 66'h1) : booth_res_8;
      booth_reg2_4 <= io_src2[19] ? 66'(~booth_res_9 + 66'h1) : booth_res_9;
    end
    if (io_busy_8) begin
    end
    else begin
      booth_reg3_0 <= io_src2[21] ? 66'(~booth_res_10 + 66'h1) : booth_res_10;
      booth_reg3_1 <= io_src2[23] ? 66'(~booth_res_11 + 66'h1) : booth_res_11;
      booth_reg3_2 <= io_src2[25] ? 66'(~booth_res_12 + 66'h1) : booth_res_12;
      booth_reg3_3 <= io_src2[27] ? 66'(~booth_res_13 + 66'h1) : booth_res_13;
      booth_reg3_4 <= io_src2[29] ? 66'(~booth_res_14 + 66'h1) : booth_res_14;
    end
    if (io_busy_9) begin
    end
    else begin
      booth_reg4_0 <= io_src2[31] ? 66'(~booth_res_15 + 66'h1) : booth_res_15;
      booth_reg4_1 <= _GEN_0[1] ? 66'(~booth_res_16 + 66'h1) : booth_res_16;
      booth_reg4_2 <= _GEN_0[3] ? 66'(~booth_res_17 + 66'h1) : booth_res_17;
      booth_reg4_3 <= _GEN_0[5] ? 66'(~booth_res_18 + 66'h1) : booth_res_18;
      booth_reg4_4 <= _GEN_0[7] ? 66'(~booth_res_19 + 66'h1) : booth_res_19;
    end
    if (io_busy_10) begin
    end
    else begin
      booth_reg5_0 <= _GEN_0[9] ? 66'(~booth_res_20 + 66'h1) : booth_res_20;
      booth_reg5_1 <= _GEN_0[11] ? 66'(~booth_res_21 + 66'h1) : booth_res_21;
      booth_reg5_2 <= _GEN_0[13] ? 66'(~booth_res_22 + 66'h1) : booth_res_22;
      booth_reg5_3 <= _GEN_0[15] ? 66'(~booth_res_23 + 66'h1) : booth_res_23;
      booth_reg5_4 <= _GEN_0[17] ? 66'(~booth_res_24 + 66'h1) : booth_res_24;
    end
    if (io_busy_11) begin
    end
    else begin
      booth_reg6_0 <= _GEN_0[19] ? 66'(~booth_res_25 + 66'h1) : booth_res_25;
      booth_reg6_1 <= _GEN_0[21] ? 66'(~booth_res_26 + 66'h1) : booth_res_26;
      booth_reg6_2 <= _GEN_0[23] ? 66'(~booth_res_27 + 66'h1) : booth_res_27;
      booth_reg6_3 <= _GEN_0[25] ? 66'(~booth_res_28 + 66'h1) : booth_res_28;
      booth_reg6_4 <= _GEN_0[27] ? 66'(~booth_res_29 + 66'h1) : booth_res_29;
    end
    if (io_busy_12) begin
    end
    else begin
      booth_reg7_0 <= _GEN_0[29] ? 66'(~booth_res_30 + 66'h1) : booth_res_30;
      booth_reg7_1 <= _GEN_0[31] ? 66'(~booth_res_31 + 66'h1) : booth_res_31;
      booth_reg7_2 <= _GEN_0[33] ? 66'(~booth_res_32 + 66'h1) : booth_res_32;
    end
    if (io_busy_13) begin
    end
    else
      adder_src1 <= level8_x_xor_y ^ {_level3_res2_T_22, 1'h0};
    if (io_busy_14) begin
    end
    else
      adder_src2 <=
        {level7_res1[62:0] & {_level7_res2_T_2[61:0], 1'h0}
           | {_level3_res2_T_22[61:0], 1'h0} & level8_x_xor_y[62:0],
         1'h0};
    if (io_busy_15) begin
    end
    else begin
      op_reg1 <= io_op;
      op_reg2 <= op_reg1;
    end
  end // always @(posedge)
  assign io_res = op_reg2 == 5'h0 ? _res_T[31:0] : _res_T[63:32];
endmodule

