// Generated by CIRCT firtool-1.62.0
module Order_Issue_Queue_1(
  input         clock,
                reset,
                io_insts_disp_index_0,
                io_insts_disp_valid_0,
                io_insts_disp_valid_1,
  input  [5:0]  io_insts_dispatch_0_prj,
                io_insts_dispatch_0_prk,
  input         io_insts_dispatch_0_rd_valid,
  input  [5:0]  io_insts_dispatch_0_prd,
  input  [31:0] io_insts_dispatch_0_imm,
  input  [4:0]  io_insts_dispatch_0_rob_index,
                io_insts_dispatch_0_mem_type,
  input  [2:0]  io_insts_dispatch_0_priv_vec,
  input  [5:0]  io_insts_dispatch_1_prj,
                io_insts_dispatch_1_prk,
  input         io_insts_dispatch_1_rd_valid,
  input  [5:0]  io_insts_dispatch_1_prd,
  input  [31:0] io_insts_dispatch_1_imm,
  input  [4:0]  io_insts_dispatch_1_rob_index,
                io_insts_dispatch_1_mem_type,
  input  [2:0]  io_insts_dispatch_1_priv_vec,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prk_ready_0,
                io_prk_ready_1,
  input  [5:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
  input  [1:0]  io_is_store_cmt_num,
  input  [4:0]  io_rob_index_cmt,
  input         io_issue_ack,
  output [5:0]  io_insts_issue_inst_prj,
                io_insts_issue_inst_prk,
  output        io_insts_issue_inst_rd_valid,
  output [5:0]  io_insts_issue_inst_prd,
  output [31:0] io_insts_issue_inst_imm,
  output [4:0]  io_insts_issue_inst_rob_index,
                io_insts_issue_inst_mem_type,
  output [2:0]  io_insts_issue_inst_priv_vec,
  output        io_issue_req,
                io_full,
  input         io_stall,
                io_flush
);

  reg  [5:0]  queue_0_inst_prj;
  reg  [5:0]  queue_0_inst_prk;
  reg         queue_0_inst_rd_valid;
  reg  [5:0]  queue_0_inst_prd;
  reg  [31:0] queue_0_inst_imm;
  reg  [4:0]  queue_0_inst_rob_index;
  reg  [4:0]  queue_0_inst_mem_type;
  reg  [2:0]  queue_0_inst_priv_vec;
  reg         queue_0_prj_waked;
  reg         queue_0_prk_waked;
  reg  [5:0]  queue_1_inst_prj;
  reg  [5:0]  queue_1_inst_prk;
  reg         queue_1_inst_rd_valid;
  reg  [5:0]  queue_1_inst_prd;
  reg  [31:0] queue_1_inst_imm;
  reg  [4:0]  queue_1_inst_rob_index;
  reg  [4:0]  queue_1_inst_mem_type;
  reg  [2:0]  queue_1_inst_priv_vec;
  reg         queue_1_prj_waked;
  reg         queue_1_prk_waked;
  reg  [5:0]  queue_2_inst_prj;
  reg  [5:0]  queue_2_inst_prk;
  reg         queue_2_inst_rd_valid;
  reg  [5:0]  queue_2_inst_prd;
  reg  [31:0] queue_2_inst_imm;
  reg  [4:0]  queue_2_inst_rob_index;
  reg  [4:0]  queue_2_inst_mem_type;
  reg  [2:0]  queue_2_inst_priv_vec;
  reg         queue_2_prj_waked;
  reg         queue_2_prk_waked;
  reg  [5:0]  queue_3_inst_prj;
  reg  [5:0]  queue_3_inst_prk;
  reg         queue_3_inst_rd_valid;
  reg  [5:0]  queue_3_inst_prd;
  reg  [31:0] queue_3_inst_imm;
  reg  [4:0]  queue_3_inst_rob_index;
  reg  [4:0]  queue_3_inst_mem_type;
  reg  [2:0]  queue_3_inst_priv_vec;
  reg         queue_3_prj_waked;
  reg         queue_3_prk_waked;
  reg  [5:0]  queue_4_inst_prj;
  reg  [5:0]  queue_4_inst_prk;
  reg         queue_4_inst_rd_valid;
  reg  [5:0]  queue_4_inst_prd;
  reg  [31:0] queue_4_inst_imm;
  reg  [4:0]  queue_4_inst_rob_index;
  reg  [4:0]  queue_4_inst_mem_type;
  reg  [2:0]  queue_4_inst_priv_vec;
  reg         queue_4_prj_waked;
  reg         queue_4_prk_waked;
  reg  [5:0]  queue_5_inst_prj;
  reg  [5:0]  queue_5_inst_prk;
  reg         queue_5_inst_rd_valid;
  reg  [5:0]  queue_5_inst_prd;
  reg  [31:0] queue_5_inst_imm;
  reg  [4:0]  queue_5_inst_rob_index;
  reg  [4:0]  queue_5_inst_mem_type;
  reg  [2:0]  queue_5_inst_priv_vec;
  reg         queue_5_prj_waked;
  reg         queue_5_prk_waked;
  reg  [5:0]  queue_6_inst_prj;
  reg  [5:0]  queue_6_inst_prk;
  reg         queue_6_inst_rd_valid;
  reg  [5:0]  queue_6_inst_prd;
  reg  [31:0] queue_6_inst_imm;
  reg  [4:0]  queue_6_inst_rob_index;
  reg  [4:0]  queue_6_inst_mem_type;
  reg  [2:0]  queue_6_inst_priv_vec;
  reg         queue_6_prj_waked;
  reg         queue_6_prk_waked;
  reg  [5:0]  queue_7_inst_prj;
  reg  [5:0]  queue_7_inst_prk;
  reg         queue_7_inst_rd_valid;
  reg  [5:0]  queue_7_inst_prd;
  reg  [31:0] queue_7_inst_imm;
  reg  [4:0]  queue_7_inst_rob_index;
  reg  [4:0]  queue_7_inst_mem_type;
  reg  [2:0]  queue_7_inst_priv_vec;
  reg         queue_7_prj_waked;
  reg         queue_7_prk_waked;
  reg  [3:0]  tail;
  reg  [7:0]  qmask;
  reg  [1:0]  store_num;
  wire [1:0]  insert_num =
    2'({1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1});
  wire [1:0]  _tail_T = qmask[6] ? 2'h0 : insert_num;
  wire [7:0]  _qmask_pop_T_1 = {1'h0, qmask[7:1]};
  wire [7:0]  qmask_pop = io_issue_ack ? _qmask_pop_T_1 : qmask;
  wire [3:0]  _tail_pop_T = 4'(tail - {3'h0, io_issue_ack});
  wire        _GEN = 1'(1'h0 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_0 = _GEN ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_1 = _GEN ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_inst_prj = io_issue_ack ? queue_1_inst_prj : queue_0_inst_prj;
  wire [5:0]  queue_next_inst_prj = qmask_pop[0] ? _queue_next_T_inst_prj : _GEN_0;
  wire [5:0]  _queue_next_T_inst_prk = io_issue_ack ? queue_1_inst_prk : queue_0_inst_prk;
  wire [5:0]  queue_next_inst_prk = qmask_pop[0] ? _queue_next_T_inst_prk : _GEN_1;
  wire        _GEN_2 = 1'(1'h1 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_3 = _GEN_2 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_4 = _GEN_2 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_1_inst_prj =
    io_issue_ack ? queue_2_inst_prj : queue_1_inst_prj;
  wire [5:0]  queue_next_1_inst_prj = qmask_pop[1] ? _queue_next_T_1_inst_prj : _GEN_3;
  wire [5:0]  _queue_next_T_1_inst_prk =
    io_issue_ack ? queue_2_inst_prk : queue_1_inst_prk;
  wire [5:0]  queue_next_1_inst_prk = qmask_pop[1] ? _queue_next_T_1_inst_prk : _GEN_4;
  wire        _GEN_5 = 1'(1'h0 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_6 = _GEN_5 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_7 = _GEN_5 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_2_inst_prj =
    io_issue_ack ? queue_3_inst_prj : queue_2_inst_prj;
  wire [5:0]  queue_next_2_inst_prj = qmask_pop[2] ? _queue_next_T_2_inst_prj : _GEN_6;
  wire [5:0]  _queue_next_T_2_inst_prk =
    io_issue_ack ? queue_3_inst_prk : queue_2_inst_prk;
  wire [5:0]  queue_next_2_inst_prk = qmask_pop[2] ? _queue_next_T_2_inst_prk : _GEN_7;
  wire        _GEN_8 = 1'(1'h1 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_9 = _GEN_8 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_10 = _GEN_8 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_3_inst_prj =
    io_issue_ack ? queue_4_inst_prj : queue_3_inst_prj;
  wire [5:0]  queue_next_3_inst_prj = qmask_pop[3] ? _queue_next_T_3_inst_prj : _GEN_9;
  wire [5:0]  _queue_next_T_3_inst_prk =
    io_issue_ack ? queue_4_inst_prk : queue_3_inst_prk;
  wire [5:0]  queue_next_3_inst_prk = qmask_pop[3] ? _queue_next_T_3_inst_prk : _GEN_10;
  wire        _GEN_11 = 1'(1'h0 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_12 = _GEN_11 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_13 = _GEN_11 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_4_inst_prj =
    io_issue_ack ? queue_5_inst_prj : queue_4_inst_prj;
  wire [5:0]  queue_next_4_inst_prj = qmask_pop[4] ? _queue_next_T_4_inst_prj : _GEN_12;
  wire [5:0]  _queue_next_T_4_inst_prk =
    io_issue_ack ? queue_5_inst_prk : queue_4_inst_prk;
  wire [5:0]  queue_next_4_inst_prk = qmask_pop[4] ? _queue_next_T_4_inst_prk : _GEN_13;
  wire        _GEN_14 = 1'(1'h1 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_15 = _GEN_14 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_16 = _GEN_14 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_5_inst_prj =
    io_issue_ack ? queue_6_inst_prj : queue_5_inst_prj;
  wire [5:0]  queue_next_5_inst_prj = qmask_pop[5] ? _queue_next_T_5_inst_prj : _GEN_15;
  wire [5:0]  _queue_next_T_5_inst_prk =
    io_issue_ack ? queue_6_inst_prk : queue_5_inst_prk;
  wire [5:0]  queue_next_5_inst_prk = qmask_pop[5] ? _queue_next_T_5_inst_prk : _GEN_16;
  wire        _GEN_17 = 1'(1'h0 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_18 = _GEN_17 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_19 = _GEN_17 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_6_inst_prj =
    io_issue_ack ? queue_7_inst_prj : queue_6_inst_prj;
  wire [5:0]  queue_next_6_inst_prj = qmask_pop[6] ? _queue_next_T_6_inst_prj : _GEN_18;
  wire [5:0]  _queue_next_T_6_inst_prk =
    io_issue_ack ? queue_7_inst_prk : queue_6_inst_prk;
  wire [5:0]  queue_next_6_inst_prk = qmask_pop[6] ? _queue_next_T_6_inst_prk : _GEN_19;
  wire        _GEN_20 = 1'(1'h1 - _tail_pop_T[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_21 = _GEN_20 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_22 = _GEN_20 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  queue_next_7_inst_prj = qmask_pop[7] ? queue_7_inst_prj : _GEN_21;
  wire [5:0]  queue_next_7_inst_prk = qmask_pop[7] ? queue_7_inst_prk : _GEN_22;
  wire        _GEN_23 = _GEN ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_prj_waked =
    io_issue_ack ? queue_1_prj_waked : queue_0_prj_waked;
  wire        queue_next_prj_waked = qmask_pop[0] ? _queue_next_T_prj_waked : _GEN_23;
  wire        _GEN_24 = _GEN ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_prk_waked =
    io_issue_ack ? queue_1_prk_waked : queue_0_prk_waked;
  wire        queue_next_prk_waked = qmask_pop[0] ? _queue_next_T_prk_waked : _GEN_24;
  wire        _GEN_25 = _GEN_2 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_1_prj_waked =
    io_issue_ack ? queue_2_prj_waked : queue_1_prj_waked;
  wire        queue_next_1_prj_waked = qmask_pop[1] ? _queue_next_T_1_prj_waked : _GEN_25;
  wire        _GEN_26 = _GEN_2 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_1_prk_waked =
    io_issue_ack ? queue_2_prk_waked : queue_1_prk_waked;
  wire        queue_next_1_prk_waked = qmask_pop[1] ? _queue_next_T_1_prk_waked : _GEN_26;
  wire        _GEN_27 = _GEN_5 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_2_prj_waked =
    io_issue_ack ? queue_3_prj_waked : queue_2_prj_waked;
  wire        queue_next_2_prj_waked = qmask_pop[2] ? _queue_next_T_2_prj_waked : _GEN_27;
  wire        _GEN_28 = _GEN_5 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_2_prk_waked =
    io_issue_ack ? queue_3_prk_waked : queue_2_prk_waked;
  wire        queue_next_2_prk_waked = qmask_pop[2] ? _queue_next_T_2_prk_waked : _GEN_28;
  wire        _GEN_29 = _GEN_8 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_3_prj_waked =
    io_issue_ack ? queue_4_prj_waked : queue_3_prj_waked;
  wire        queue_next_3_prj_waked = qmask_pop[3] ? _queue_next_T_3_prj_waked : _GEN_29;
  wire        _GEN_30 = _GEN_8 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_3_prk_waked =
    io_issue_ack ? queue_4_prk_waked : queue_3_prk_waked;
  wire        queue_next_3_prk_waked = qmask_pop[3] ? _queue_next_T_3_prk_waked : _GEN_30;
  wire        _GEN_31 = _GEN_11 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_4_prj_waked =
    io_issue_ack ? queue_5_prj_waked : queue_4_prj_waked;
  wire        queue_next_4_prj_waked = qmask_pop[4] ? _queue_next_T_4_prj_waked : _GEN_31;
  wire        _GEN_32 = _GEN_11 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_4_prk_waked =
    io_issue_ack ? queue_5_prk_waked : queue_4_prk_waked;
  wire        queue_next_4_prk_waked = qmask_pop[4] ? _queue_next_T_4_prk_waked : _GEN_32;
  wire        _GEN_33 = _GEN_14 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_5_prj_waked =
    io_issue_ack ? queue_6_prj_waked : queue_5_prj_waked;
  wire        queue_next_5_prj_waked = qmask_pop[5] ? _queue_next_T_5_prj_waked : _GEN_33;
  wire        _GEN_34 = _GEN_14 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_5_prk_waked =
    io_issue_ack ? queue_6_prk_waked : queue_5_prk_waked;
  wire        queue_next_5_prk_waked = qmask_pop[5] ? _queue_next_T_5_prk_waked : _GEN_34;
  wire        _GEN_35 = _GEN_17 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_6_prj_waked =
    io_issue_ack ? queue_7_prj_waked : queue_6_prj_waked;
  wire        queue_next_6_prj_waked = qmask_pop[6] ? _queue_next_T_6_prj_waked : _GEN_35;
  wire        _GEN_36 = _GEN_17 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_6_prk_waked =
    io_issue_ack ? queue_7_prk_waked : queue_6_prk_waked;
  wire        queue_next_6_prk_waked = qmask_pop[6] ? _queue_next_T_6_prk_waked : _GEN_36;
  wire        _GEN_37 = _GEN_20 ? io_prj_ready_1 : io_prj_ready_0;
  wire        queue_next_7_prj_waked = qmask_pop[7] ? queue_7_prj_waked : _GEN_37;
  wire        _GEN_38 = _GEN_20 ? io_prk_ready_1 : io_prk_ready_0;
  wire        queue_next_7_prk_waked = qmask_pop[7] ? queue_7_prk_waked : _GEN_38;
  always @(posedge clock) begin
    if (reset) begin
      queue_0_inst_prj <= 6'h0;
      queue_0_inst_prk <= 6'h0;
      queue_0_inst_rd_valid <= 1'h0;
      queue_0_inst_prd <= 6'h0;
      queue_0_inst_imm <= 32'h0;
      queue_0_inst_rob_index <= 5'h0;
      queue_0_inst_mem_type <= 5'h0;
      queue_0_inst_priv_vec <= 3'h0;
      queue_0_prj_waked <= 1'h0;
      queue_0_prk_waked <= 1'h0;
      queue_1_inst_prj <= 6'h0;
      queue_1_inst_prk <= 6'h0;
      queue_1_inst_rd_valid <= 1'h0;
      queue_1_inst_prd <= 6'h0;
      queue_1_inst_imm <= 32'h0;
      queue_1_inst_rob_index <= 5'h0;
      queue_1_inst_mem_type <= 5'h0;
      queue_1_inst_priv_vec <= 3'h0;
      queue_1_prj_waked <= 1'h0;
      queue_1_prk_waked <= 1'h0;
      queue_2_inst_prj <= 6'h0;
      queue_2_inst_prk <= 6'h0;
      queue_2_inst_rd_valid <= 1'h0;
      queue_2_inst_prd <= 6'h0;
      queue_2_inst_imm <= 32'h0;
      queue_2_inst_rob_index <= 5'h0;
      queue_2_inst_mem_type <= 5'h0;
      queue_2_inst_priv_vec <= 3'h0;
      queue_2_prj_waked <= 1'h0;
      queue_2_prk_waked <= 1'h0;
      queue_3_inst_prj <= 6'h0;
      queue_3_inst_prk <= 6'h0;
      queue_3_inst_rd_valid <= 1'h0;
      queue_3_inst_prd <= 6'h0;
      queue_3_inst_imm <= 32'h0;
      queue_3_inst_rob_index <= 5'h0;
      queue_3_inst_mem_type <= 5'h0;
      queue_3_inst_priv_vec <= 3'h0;
      queue_3_prj_waked <= 1'h0;
      queue_3_prk_waked <= 1'h0;
      queue_4_inst_prj <= 6'h0;
      queue_4_inst_prk <= 6'h0;
      queue_4_inst_rd_valid <= 1'h0;
      queue_4_inst_prd <= 6'h0;
      queue_4_inst_imm <= 32'h0;
      queue_4_inst_rob_index <= 5'h0;
      queue_4_inst_mem_type <= 5'h0;
      queue_4_inst_priv_vec <= 3'h0;
      queue_4_prj_waked <= 1'h0;
      queue_4_prk_waked <= 1'h0;
      queue_5_inst_prj <= 6'h0;
      queue_5_inst_prk <= 6'h0;
      queue_5_inst_rd_valid <= 1'h0;
      queue_5_inst_prd <= 6'h0;
      queue_5_inst_imm <= 32'h0;
      queue_5_inst_rob_index <= 5'h0;
      queue_5_inst_mem_type <= 5'h0;
      queue_5_inst_priv_vec <= 3'h0;
      queue_5_prj_waked <= 1'h0;
      queue_5_prk_waked <= 1'h0;
      queue_6_inst_prj <= 6'h0;
      queue_6_inst_prk <= 6'h0;
      queue_6_inst_rd_valid <= 1'h0;
      queue_6_inst_prd <= 6'h0;
      queue_6_inst_imm <= 32'h0;
      queue_6_inst_rob_index <= 5'h0;
      queue_6_inst_mem_type <= 5'h0;
      queue_6_inst_priv_vec <= 3'h0;
      queue_6_prj_waked <= 1'h0;
      queue_6_prk_waked <= 1'h0;
      queue_7_inst_prj <= 6'h0;
      queue_7_inst_prk <= 6'h0;
      queue_7_inst_rd_valid <= 1'h0;
      queue_7_inst_prd <= 6'h0;
      queue_7_inst_imm <= 32'h0;
      queue_7_inst_rob_index <= 5'h0;
      queue_7_inst_mem_type <= 5'h0;
      queue_7_inst_priv_vec <= 3'h0;
      queue_7_prj_waked <= 1'h0;
      queue_7_prk_waked <= 1'h0;
      tail <= 4'h0;
      qmask <= 8'h0;
      store_num <= 2'h0;
    end
    else begin
      if (qmask_pop[0]) begin
        if (io_issue_ack) begin
          queue_0_inst_prj <= queue_1_inst_prj;
          queue_0_inst_prk <= queue_1_inst_prk;
          queue_0_inst_rd_valid <= queue_1_inst_rd_valid;
          queue_0_inst_prd <= queue_1_inst_prd;
          queue_0_inst_imm <= queue_1_inst_imm;
          queue_0_inst_rob_index <= queue_1_inst_rob_index;
          queue_0_inst_mem_type <= queue_1_inst_mem_type;
          queue_0_inst_priv_vec <= queue_1_inst_priv_vec;
        end
      end
      else begin
        queue_0_inst_prj <= _GEN_0;
        queue_0_inst_prk <= _GEN_1;
        queue_0_inst_rd_valid <=
          _GEN ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_0_inst_prd <= _GEN ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_0_inst_imm <= _GEN ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_0_inst_rob_index <=
          _GEN ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_0_inst_mem_type <=
          _GEN ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_0_inst_priv_vec <=
          _GEN ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_0_prj_waked <=
        queue_next_prj_waked
        | (|{(queue_next_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_0_prk_waked <=
        queue_next_prk_waked
        | (|{(queue_next_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[1]) begin
        if (io_issue_ack) begin
          queue_1_inst_prj <= queue_2_inst_prj;
          queue_1_inst_prk <= queue_2_inst_prk;
          queue_1_inst_rd_valid <= queue_2_inst_rd_valid;
          queue_1_inst_prd <= queue_2_inst_prd;
          queue_1_inst_imm <= queue_2_inst_imm;
          queue_1_inst_rob_index <= queue_2_inst_rob_index;
          queue_1_inst_mem_type <= queue_2_inst_mem_type;
          queue_1_inst_priv_vec <= queue_2_inst_priv_vec;
        end
      end
      else begin
        queue_1_inst_prj <= _GEN_3;
        queue_1_inst_prk <= _GEN_4;
        queue_1_inst_rd_valid <=
          _GEN_2 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_1_inst_prd <= _GEN_2 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_1_inst_imm <= _GEN_2 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_1_inst_rob_index <=
          _GEN_2 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_1_inst_mem_type <=
          _GEN_2 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_1_inst_priv_vec <=
          _GEN_2 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_1_prj_waked <=
        queue_next_1_prj_waked
        | (|{(queue_next_1_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_1_prk_waked <=
        queue_next_1_prk_waked
        | (|{(queue_next_1_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[2]) begin
        if (io_issue_ack) begin
          queue_2_inst_prj <= queue_3_inst_prj;
          queue_2_inst_prk <= queue_3_inst_prk;
          queue_2_inst_rd_valid <= queue_3_inst_rd_valid;
          queue_2_inst_prd <= queue_3_inst_prd;
          queue_2_inst_imm <= queue_3_inst_imm;
          queue_2_inst_rob_index <= queue_3_inst_rob_index;
          queue_2_inst_mem_type <= queue_3_inst_mem_type;
          queue_2_inst_priv_vec <= queue_3_inst_priv_vec;
        end
      end
      else begin
        queue_2_inst_prj <= _GEN_6;
        queue_2_inst_prk <= _GEN_7;
        queue_2_inst_rd_valid <=
          _GEN_5 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_2_inst_prd <= _GEN_5 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_2_inst_imm <= _GEN_5 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_2_inst_rob_index <=
          _GEN_5 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_2_inst_mem_type <=
          _GEN_5 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_2_inst_priv_vec <=
          _GEN_5 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_2_prj_waked <=
        queue_next_2_prj_waked
        | (|{(queue_next_2_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_2_prk_waked <=
        queue_next_2_prk_waked
        | (|{(queue_next_2_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[3]) begin
        if (io_issue_ack) begin
          queue_3_inst_prj <= queue_4_inst_prj;
          queue_3_inst_prk <= queue_4_inst_prk;
          queue_3_inst_rd_valid <= queue_4_inst_rd_valid;
          queue_3_inst_prd <= queue_4_inst_prd;
          queue_3_inst_imm <= queue_4_inst_imm;
          queue_3_inst_rob_index <= queue_4_inst_rob_index;
          queue_3_inst_mem_type <= queue_4_inst_mem_type;
          queue_3_inst_priv_vec <= queue_4_inst_priv_vec;
        end
      end
      else begin
        queue_3_inst_prj <= _GEN_9;
        queue_3_inst_prk <= _GEN_10;
        queue_3_inst_rd_valid <=
          _GEN_8 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_3_inst_prd <= _GEN_8 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_3_inst_imm <= _GEN_8 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_3_inst_rob_index <=
          _GEN_8 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_3_inst_mem_type <=
          _GEN_8 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_3_inst_priv_vec <=
          _GEN_8 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_3_prj_waked <=
        queue_next_3_prj_waked
        | (|{(queue_next_3_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_3_prk_waked <=
        queue_next_3_prk_waked
        | (|{(queue_next_3_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[4]) begin
        if (io_issue_ack) begin
          queue_4_inst_prj <= queue_5_inst_prj;
          queue_4_inst_prk <= queue_5_inst_prk;
          queue_4_inst_rd_valid <= queue_5_inst_rd_valid;
          queue_4_inst_prd <= queue_5_inst_prd;
          queue_4_inst_imm <= queue_5_inst_imm;
          queue_4_inst_rob_index <= queue_5_inst_rob_index;
          queue_4_inst_mem_type <= queue_5_inst_mem_type;
          queue_4_inst_priv_vec <= queue_5_inst_priv_vec;
        end
      end
      else begin
        queue_4_inst_prj <= _GEN_12;
        queue_4_inst_prk <= _GEN_13;
        queue_4_inst_rd_valid <=
          _GEN_11 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_4_inst_prd <= _GEN_11 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_4_inst_imm <= _GEN_11 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_4_inst_rob_index <=
          _GEN_11 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_4_inst_mem_type <=
          _GEN_11 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_4_inst_priv_vec <=
          _GEN_11 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_4_prj_waked <=
        queue_next_4_prj_waked
        | (|{(queue_next_4_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_4_prk_waked <=
        queue_next_4_prk_waked
        | (|{(queue_next_4_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[5]) begin
        if (io_issue_ack) begin
          queue_5_inst_prj <= queue_6_inst_prj;
          queue_5_inst_prk <= queue_6_inst_prk;
          queue_5_inst_rd_valid <= queue_6_inst_rd_valid;
          queue_5_inst_prd <= queue_6_inst_prd;
          queue_5_inst_imm <= queue_6_inst_imm;
          queue_5_inst_rob_index <= queue_6_inst_rob_index;
          queue_5_inst_mem_type <= queue_6_inst_mem_type;
          queue_5_inst_priv_vec <= queue_6_inst_priv_vec;
        end
      end
      else begin
        queue_5_inst_prj <= _GEN_15;
        queue_5_inst_prk <= _GEN_16;
        queue_5_inst_rd_valid <=
          _GEN_14 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_5_inst_prd <= _GEN_14 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_5_inst_imm <= _GEN_14 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_5_inst_rob_index <=
          _GEN_14 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_5_inst_mem_type <=
          _GEN_14 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_5_inst_priv_vec <=
          _GEN_14 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_5_prj_waked <=
        queue_next_5_prj_waked
        | (|{(queue_next_5_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_5_prk_waked <=
        queue_next_5_prk_waked
        | (|{(queue_next_5_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[6]) begin
        if (io_issue_ack) begin
          queue_6_inst_prj <= queue_7_inst_prj;
          queue_6_inst_prk <= queue_7_inst_prk;
          queue_6_inst_rd_valid <= queue_7_inst_rd_valid;
          queue_6_inst_prd <= queue_7_inst_prd;
          queue_6_inst_imm <= queue_7_inst_imm;
          queue_6_inst_rob_index <= queue_7_inst_rob_index;
          queue_6_inst_mem_type <= queue_7_inst_mem_type;
          queue_6_inst_priv_vec <= queue_7_inst_priv_vec;
        end
      end
      else begin
        queue_6_inst_prj <= _GEN_18;
        queue_6_inst_prk <= _GEN_19;
        queue_6_inst_rd_valid <=
          _GEN_17 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_6_inst_prd <= _GEN_17 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_6_inst_imm <= _GEN_17 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_6_inst_rob_index <=
          _GEN_17 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_6_inst_mem_type <=
          _GEN_17 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_6_inst_priv_vec <=
          _GEN_17 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_6_prj_waked <=
        queue_next_6_prj_waked
        | (|{(queue_next_6_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_6_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_6_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_6_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_6_prk_waked <=
        queue_next_6_prk_waked
        | (|{(queue_next_6_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_6_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_6_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_6_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (qmask_pop[7]) begin
      end
      else begin
        queue_7_inst_prj <= _GEN_21;
        queue_7_inst_prk <= _GEN_22;
        queue_7_inst_rd_valid <=
          _GEN_20 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_7_inst_prd <= _GEN_20 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_7_inst_imm <= _GEN_20 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_7_inst_rob_index <=
          _GEN_20 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_7_inst_mem_type <=
          _GEN_20 ? io_insts_dispatch_1_mem_type : io_insts_dispatch_0_mem_type;
        queue_7_inst_priv_vec <=
          _GEN_20 ? io_insts_dispatch_1_priv_vec : io_insts_dispatch_0_priv_vec;
      end
      queue_7_prj_waked <=
        queue_next_7_prj_waked
        | (|{(queue_next_7_inst_prj ^ io_wake_preg_3) == 6'h0,
             (queue_next_7_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_7_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_7_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_7_prk_waked <=
        queue_next_7_prk_waked
        | (|{(queue_next_7_inst_prk ^ io_wake_preg_3) == 6'h0,
             (queue_next_7_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_7_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_7_inst_prk ^ io_wake_preg_0) == 6'h0});
      if (io_flush) begin
        tail <= 4'h0;
        qmask <= 8'h0;
        store_num <= 2'h0;
      end
      else begin
        if (io_stall) begin
          tail <= _tail_pop_T;
          if (io_issue_ack)
            qmask <= _qmask_pop_T_1;
        end
        else begin
          tail <= 4'(_tail_pop_T + {2'h0, _tail_T});
          if (insert_num == 2'h2)
            qmask <= {qmask_pop[5:0], 2'h3};
          else if (insert_num == 2'h1)
            qmask <= {qmask_pop[6:0], 1'h1};
          else if (io_issue_ack)
            qmask <= _qmask_pop_T_1;
        end
        store_num <=
          2'(2'(store_num + {1'h0, io_issue_ack & queue_0_inst_mem_type[4]})
             - io_is_store_cmt_num);
      end
    end
  end // always @(posedge)
  assign io_insts_issue_inst_prj = queue_0_inst_prj;
  assign io_insts_issue_inst_prk = queue_0_inst_prk;
  assign io_insts_issue_inst_rd_valid = queue_0_inst_rd_valid;
  assign io_insts_issue_inst_prd = queue_0_inst_prd;
  assign io_insts_issue_inst_imm = queue_0_inst_imm;
  assign io_insts_issue_inst_rob_index = queue_0_inst_rob_index;
  assign io_insts_issue_inst_mem_type = queue_0_inst_mem_type;
  assign io_insts_issue_inst_priv_vec = queue_0_inst_priv_vec;
  assign io_issue_req =
    qmask[0] & queue_0_prj_waked & queue_0_prk_waked
    & ~(queue_0_inst_priv_vec[0]
        & ((|store_num) | queue_0_inst_rob_index != io_rob_index_cmt));
  assign io_full = qmask[6];
endmodule

