// Generated by CIRCT firtool-1.62.0
module Order_Select_1(
  input  [5:0]  io_insts_issue_inst_prj,
                io_insts_issue_inst_prk,
  input         io_insts_issue_inst_rd_valid,
  input  [5:0]  io_insts_issue_inst_prd,
  input  [31:0] io_insts_issue_inst_imm,
  input  [4:0]  io_insts_issue_inst_rob_index,
                io_insts_issue_inst_mem_type,
  input  [2:0]  io_insts_issue_inst_priv_vec,
  input         io_issue_req,
                io_stall,
  output        io_issue_ack,
  output [5:0]  io_inst_issue_inst_prj,
                io_inst_issue_inst_prk,
  output        io_inst_issue_inst_rd_valid,
  output [5:0]  io_inst_issue_inst_prd,
  output [31:0] io_inst_issue_inst_imm,
  output [4:0]  io_inst_issue_inst_rob_index,
                io_inst_issue_inst_mem_type,
  output [2:0]  io_inst_issue_inst_priv_vec,
  output        io_inst_issue_valid
);

  wire io_issue_ack_0 = ~io_stall & io_issue_req;
  assign io_issue_ack = io_issue_ack_0;
  assign io_inst_issue_inst_prj = io_issue_ack_0 ? io_insts_issue_inst_prj : 6'h0;
  assign io_inst_issue_inst_prk = io_issue_ack_0 ? io_insts_issue_inst_prk : 6'h0;
  assign io_inst_issue_inst_rd_valid = io_issue_ack_0 & io_insts_issue_inst_rd_valid;
  assign io_inst_issue_inst_prd = io_issue_ack_0 ? io_insts_issue_inst_prd : 6'h0;
  assign io_inst_issue_inst_imm = io_issue_ack_0 ? io_insts_issue_inst_imm : 32'h0;
  assign io_inst_issue_inst_rob_index =
    io_issue_ack_0 ? io_insts_issue_inst_rob_index : 5'h0;
  assign io_inst_issue_inst_mem_type =
    io_issue_ack_0 ? io_insts_issue_inst_mem_type : 5'h0;
  assign io_inst_issue_inst_priv_vec =
    io_issue_ack_0 ? io_insts_issue_inst_priv_vec : 3'h0;
  assign io_inst_issue_valid = io_issue_ack_0;
endmodule

