// Generated by CIRCT firtool-1.62.0
module Predict(
  input         clock,
                reset,
  input  [31:0] io_npc_0,
                io_npc_1,
                io_pc_0,
                io_pc_1,
                io_pc_2,
                io_pc_3,
                io_pc_4,
                io_pc_5,
                io_pc_6,
  output        io_predict_jump_0,
                io_predict_jump_1,
  output [31:0] io_pred_npc,
  output        io_pred_valid_0,
                io_pred_valid_1,
  input  [31:0] io_pc_cmt,
  input         io_real_jump,
  input  [31:0] io_branch_target,
  input         io_update_en,
  input  [1:0]  io_br_type,
  input  [2:0]  io_top_arch,
  input  [31:0] io_ras_arch_0,
                io_ras_arch_1,
                io_ras_arch_2,
                io_ras_arch_3,
                io_ras_arch_4,
                io_ras_arch_5,
                io_ras_arch_6,
                io_ras_arch_7,
  input         io_predict_fail,
                io_pd_pred_fix,
                io_pd_pred_fix_is_bl,
  input  [31:0] io_pd_pc_plus_4
);

  wire [1:0]       btb_rdata_1_typ;
  wire [29:0]      btb_rdata_1_target;
  wire [1:0]       btb_rdata_0_typ;
  wire [29:0]      btb_rdata_0_target;
  wire [20:0]      btb_rdata_1_tag;
  wire             btb_rdata_1_valid;
  wire [20:0]      btb_rdata_0_tag;
  wire             btb_rdata_0_valid;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_3_addra;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_3_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_3_wea;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_2_addra;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_2_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_2_wea;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_1_addra;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_1_addrb;
  wire [21:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_1_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_1_wea;
  wire [21:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_addra;
  wire [6:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_addrb;
  wire [21:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_wea;
  wire [21:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_doutb;
  reg  [3:0]       bht_0_0;
  reg  [3:0]       bht_0_1;
  reg  [3:0]       bht_0_2;
  reg  [3:0]       bht_0_3;
  reg  [3:0]       bht_0_4;
  reg  [3:0]       bht_0_5;
  reg  [3:0]       bht_0_6;
  reg  [3:0]       bht_0_7;
  reg  [3:0]       bht_0_8;
  reg  [3:0]       bht_0_9;
  reg  [3:0]       bht_0_10;
  reg  [3:0]       bht_0_11;
  reg  [3:0]       bht_0_12;
  reg  [3:0]       bht_0_13;
  reg  [3:0]       bht_0_14;
  reg  [3:0]       bht_0_15;
  reg  [3:0]       bht_0_16;
  reg  [3:0]       bht_0_17;
  reg  [3:0]       bht_0_18;
  reg  [3:0]       bht_0_19;
  reg  [3:0]       bht_0_20;
  reg  [3:0]       bht_0_21;
  reg  [3:0]       bht_0_22;
  reg  [3:0]       bht_0_23;
  reg  [3:0]       bht_0_24;
  reg  [3:0]       bht_0_25;
  reg  [3:0]       bht_0_26;
  reg  [3:0]       bht_0_27;
  reg  [3:0]       bht_0_28;
  reg  [3:0]       bht_0_29;
  reg  [3:0]       bht_0_30;
  reg  [3:0]       bht_0_31;
  reg  [3:0]       bht_0_32;
  reg  [3:0]       bht_0_33;
  reg  [3:0]       bht_0_34;
  reg  [3:0]       bht_0_35;
  reg  [3:0]       bht_0_36;
  reg  [3:0]       bht_0_37;
  reg  [3:0]       bht_0_38;
  reg  [3:0]       bht_0_39;
  reg  [3:0]       bht_0_40;
  reg  [3:0]       bht_0_41;
  reg  [3:0]       bht_0_42;
  reg  [3:0]       bht_0_43;
  reg  [3:0]       bht_0_44;
  reg  [3:0]       bht_0_45;
  reg  [3:0]       bht_0_46;
  reg  [3:0]       bht_0_47;
  reg  [3:0]       bht_0_48;
  reg  [3:0]       bht_0_49;
  reg  [3:0]       bht_0_50;
  reg  [3:0]       bht_0_51;
  reg  [3:0]       bht_0_52;
  reg  [3:0]       bht_0_53;
  reg  [3:0]       bht_0_54;
  reg  [3:0]       bht_0_55;
  reg  [3:0]       bht_0_56;
  reg  [3:0]       bht_0_57;
  reg  [3:0]       bht_0_58;
  reg  [3:0]       bht_0_59;
  reg  [3:0]       bht_0_60;
  reg  [3:0]       bht_0_61;
  reg  [3:0]       bht_0_62;
  reg  [3:0]       bht_0_63;
  reg  [3:0]       bht_1_0;
  reg  [3:0]       bht_1_1;
  reg  [3:0]       bht_1_2;
  reg  [3:0]       bht_1_3;
  reg  [3:0]       bht_1_4;
  reg  [3:0]       bht_1_5;
  reg  [3:0]       bht_1_6;
  reg  [3:0]       bht_1_7;
  reg  [3:0]       bht_1_8;
  reg  [3:0]       bht_1_9;
  reg  [3:0]       bht_1_10;
  reg  [3:0]       bht_1_11;
  reg  [3:0]       bht_1_12;
  reg  [3:0]       bht_1_13;
  reg  [3:0]       bht_1_14;
  reg  [3:0]       bht_1_15;
  reg  [3:0]       bht_1_16;
  reg  [3:0]       bht_1_17;
  reg  [3:0]       bht_1_18;
  reg  [3:0]       bht_1_19;
  reg  [3:0]       bht_1_20;
  reg  [3:0]       bht_1_21;
  reg  [3:0]       bht_1_22;
  reg  [3:0]       bht_1_23;
  reg  [3:0]       bht_1_24;
  reg  [3:0]       bht_1_25;
  reg  [3:0]       bht_1_26;
  reg  [3:0]       bht_1_27;
  reg  [3:0]       bht_1_28;
  reg  [3:0]       bht_1_29;
  reg  [3:0]       bht_1_30;
  reg  [3:0]       bht_1_31;
  reg  [3:0]       bht_1_32;
  reg  [3:0]       bht_1_33;
  reg  [3:0]       bht_1_34;
  reg  [3:0]       bht_1_35;
  reg  [3:0]       bht_1_36;
  reg  [3:0]       bht_1_37;
  reg  [3:0]       bht_1_38;
  reg  [3:0]       bht_1_39;
  reg  [3:0]       bht_1_40;
  reg  [3:0]       bht_1_41;
  reg  [3:0]       bht_1_42;
  reg  [3:0]       bht_1_43;
  reg  [3:0]       bht_1_44;
  reg  [3:0]       bht_1_45;
  reg  [3:0]       bht_1_46;
  reg  [3:0]       bht_1_47;
  reg  [3:0]       bht_1_48;
  reg  [3:0]       bht_1_49;
  reg  [3:0]       bht_1_50;
  reg  [3:0]       bht_1_51;
  reg  [3:0]       bht_1_52;
  reg  [3:0]       bht_1_53;
  reg  [3:0]       bht_1_54;
  reg  [3:0]       bht_1_55;
  reg  [3:0]       bht_1_56;
  reg  [3:0]       bht_1_57;
  reg  [3:0]       bht_1_58;
  reg  [3:0]       bht_1_59;
  reg  [3:0]       bht_1_60;
  reg  [3:0]       bht_1_61;
  reg  [3:0]       bht_1_62;
  reg  [3:0]       bht_1_63;
  reg  [1:0]       pht_0_0;
  reg  [1:0]       pht_0_1;
  reg  [1:0]       pht_0_2;
  reg  [1:0]       pht_0_3;
  reg  [1:0]       pht_0_4;
  reg  [1:0]       pht_0_5;
  reg  [1:0]       pht_0_6;
  reg  [1:0]       pht_0_7;
  reg  [1:0]       pht_0_8;
  reg  [1:0]       pht_0_9;
  reg  [1:0]       pht_0_10;
  reg  [1:0]       pht_0_11;
  reg  [1:0]       pht_0_12;
  reg  [1:0]       pht_0_13;
  reg  [1:0]       pht_0_14;
  reg  [1:0]       pht_0_15;
  reg  [1:0]       pht_0_16;
  reg  [1:0]       pht_0_17;
  reg  [1:0]       pht_0_18;
  reg  [1:0]       pht_0_19;
  reg  [1:0]       pht_0_20;
  reg  [1:0]       pht_0_21;
  reg  [1:0]       pht_0_22;
  reg  [1:0]       pht_0_23;
  reg  [1:0]       pht_0_24;
  reg  [1:0]       pht_0_25;
  reg  [1:0]       pht_0_26;
  reg  [1:0]       pht_0_27;
  reg  [1:0]       pht_0_28;
  reg  [1:0]       pht_0_29;
  reg  [1:0]       pht_0_30;
  reg  [1:0]       pht_0_31;
  reg  [1:0]       pht_0_32;
  reg  [1:0]       pht_0_33;
  reg  [1:0]       pht_0_34;
  reg  [1:0]       pht_0_35;
  reg  [1:0]       pht_0_36;
  reg  [1:0]       pht_0_37;
  reg  [1:0]       pht_0_38;
  reg  [1:0]       pht_0_39;
  reg  [1:0]       pht_0_40;
  reg  [1:0]       pht_0_41;
  reg  [1:0]       pht_0_42;
  reg  [1:0]       pht_0_43;
  reg  [1:0]       pht_0_44;
  reg  [1:0]       pht_0_45;
  reg  [1:0]       pht_0_46;
  reg  [1:0]       pht_0_47;
  reg  [1:0]       pht_0_48;
  reg  [1:0]       pht_0_49;
  reg  [1:0]       pht_0_50;
  reg  [1:0]       pht_0_51;
  reg  [1:0]       pht_0_52;
  reg  [1:0]       pht_0_53;
  reg  [1:0]       pht_0_54;
  reg  [1:0]       pht_0_55;
  reg  [1:0]       pht_0_56;
  reg  [1:0]       pht_0_57;
  reg  [1:0]       pht_0_58;
  reg  [1:0]       pht_0_59;
  reg  [1:0]       pht_0_60;
  reg  [1:0]       pht_0_61;
  reg  [1:0]       pht_0_62;
  reg  [1:0]       pht_0_63;
  reg  [1:0]       pht_1_0;
  reg  [1:0]       pht_1_1;
  reg  [1:0]       pht_1_2;
  reg  [1:0]       pht_1_3;
  reg  [1:0]       pht_1_4;
  reg  [1:0]       pht_1_5;
  reg  [1:0]       pht_1_6;
  reg  [1:0]       pht_1_7;
  reg  [1:0]       pht_1_8;
  reg  [1:0]       pht_1_9;
  reg  [1:0]       pht_1_10;
  reg  [1:0]       pht_1_11;
  reg  [1:0]       pht_1_12;
  reg  [1:0]       pht_1_13;
  reg  [1:0]       pht_1_14;
  reg  [1:0]       pht_1_15;
  reg  [1:0]       pht_1_16;
  reg  [1:0]       pht_1_17;
  reg  [1:0]       pht_1_18;
  reg  [1:0]       pht_1_19;
  reg  [1:0]       pht_1_20;
  reg  [1:0]       pht_1_21;
  reg  [1:0]       pht_1_22;
  reg  [1:0]       pht_1_23;
  reg  [1:0]       pht_1_24;
  reg  [1:0]       pht_1_25;
  reg  [1:0]       pht_1_26;
  reg  [1:0]       pht_1_27;
  reg  [1:0]       pht_1_28;
  reg  [1:0]       pht_1_29;
  reg  [1:0]       pht_1_30;
  reg  [1:0]       pht_1_31;
  reg  [1:0]       pht_1_32;
  reg  [1:0]       pht_1_33;
  reg  [1:0]       pht_1_34;
  reg  [1:0]       pht_1_35;
  reg  [1:0]       pht_1_36;
  reg  [1:0]       pht_1_37;
  reg  [1:0]       pht_1_38;
  reg  [1:0]       pht_1_39;
  reg  [1:0]       pht_1_40;
  reg  [1:0]       pht_1_41;
  reg  [1:0]       pht_1_42;
  reg  [1:0]       pht_1_43;
  reg  [1:0]       pht_1_44;
  reg  [1:0]       pht_1_45;
  reg  [1:0]       pht_1_46;
  reg  [1:0]       pht_1_47;
  reg  [1:0]       pht_1_48;
  reg  [1:0]       pht_1_49;
  reg  [1:0]       pht_1_50;
  reg  [1:0]       pht_1_51;
  reg  [1:0]       pht_1_52;
  reg  [1:0]       pht_1_53;
  reg  [1:0]       pht_1_54;
  reg  [1:0]       pht_1_55;
  reg  [1:0]       pht_1_56;
  reg  [1:0]       pht_1_57;
  reg  [1:0]       pht_1_58;
  reg  [1:0]       pht_1_59;
  reg  [1:0]       pht_1_60;
  reg  [1:0]       pht_1_61;
  reg  [1:0]       pht_1_62;
  reg  [1:0]       pht_1_63;
  reg  [31:0]      ras_0;
  reg  [31:0]      ras_1;
  reg  [31:0]      ras_2;
  reg  [31:0]      ras_3;
  reg  [31:0]      ras_4;
  reg  [31:0]      ras_5;
  reg  [31:0]      ras_6;
  reg  [31:0]      ras_7;
  reg  [2:0]       top;
  wire [63:0][3:0] _GEN =
    {{bht_0_63},
     {bht_0_62},
     {bht_0_61},
     {bht_0_60},
     {bht_0_59},
     {bht_0_58},
     {bht_0_57},
     {bht_0_56},
     {bht_0_55},
     {bht_0_54},
     {bht_0_53},
     {bht_0_52},
     {bht_0_51},
     {bht_0_50},
     {bht_0_49},
     {bht_0_48},
     {bht_0_47},
     {bht_0_46},
     {bht_0_45},
     {bht_0_44},
     {bht_0_43},
     {bht_0_42},
     {bht_0_41},
     {bht_0_40},
     {bht_0_39},
     {bht_0_38},
     {bht_0_37},
     {bht_0_36},
     {bht_0_35},
     {bht_0_34},
     {bht_0_33},
     {bht_0_32},
     {bht_0_31},
     {bht_0_30},
     {bht_0_29},
     {bht_0_28},
     {bht_0_27},
     {bht_0_26},
     {bht_0_25},
     {bht_0_24},
     {bht_0_23},
     {bht_0_22},
     {bht_0_21},
     {bht_0_20},
     {bht_0_19},
     {bht_0_18},
     {bht_0_17},
     {bht_0_16},
     {bht_0_15},
     {bht_0_14},
     {bht_0_13},
     {bht_0_12},
     {bht_0_11},
     {bht_0_10},
     {bht_0_9},
     {bht_0_8},
     {bht_0_7},
     {bht_0_6},
     {bht_0_5},
     {bht_0_4},
     {bht_0_3},
     {bht_0_2},
     {bht_0_1},
     {bht_0_0}};
  wire [3:0]       bht_rdata_0 = _GEN[io_pc_0[8:3]];
  wire [63:0][3:0] _GEN_0 =
    {{bht_1_63},
     {bht_1_62},
     {bht_1_61},
     {bht_1_60},
     {bht_1_59},
     {bht_1_58},
     {bht_1_57},
     {bht_1_56},
     {bht_1_55},
     {bht_1_54},
     {bht_1_53},
     {bht_1_52},
     {bht_1_51},
     {bht_1_50},
     {bht_1_49},
     {bht_1_48},
     {bht_1_47},
     {bht_1_46},
     {bht_1_45},
     {bht_1_44},
     {bht_1_43},
     {bht_1_42},
     {bht_1_41},
     {bht_1_40},
     {bht_1_39},
     {bht_1_38},
     {bht_1_37},
     {bht_1_36},
     {bht_1_35},
     {bht_1_34},
     {bht_1_33},
     {bht_1_32},
     {bht_1_31},
     {bht_1_30},
     {bht_1_29},
     {bht_1_28},
     {bht_1_27},
     {bht_1_26},
     {bht_1_25},
     {bht_1_24},
     {bht_1_23},
     {bht_1_22},
     {bht_1_21},
     {bht_1_20},
     {bht_1_19},
     {bht_1_18},
     {bht_1_17},
     {bht_1_16},
     {bht_1_15},
     {bht_1_14},
     {bht_1_13},
     {bht_1_12},
     {bht_1_11},
     {bht_1_10},
     {bht_1_9},
     {bht_1_8},
     {bht_1_7},
     {bht_1_6},
     {bht_1_5},
     {bht_1_4},
     {bht_1_3},
     {bht_1_2},
     {bht_1_1},
     {bht_1_0}};
  wire [3:0]       bht_rdata_1 = _GEN_0[io_pc_1[8:3]];
  wire [63:0][1:0] _GEN_1 =
    {{pht_0_63},
     {pht_0_62},
     {pht_0_61},
     {pht_0_60},
     {pht_0_59},
     {pht_0_58},
     {pht_0_57},
     {pht_0_56},
     {pht_0_55},
     {pht_0_54},
     {pht_0_53},
     {pht_0_52},
     {pht_0_51},
     {pht_0_50},
     {pht_0_49},
     {pht_0_48},
     {pht_0_47},
     {pht_0_46},
     {pht_0_45},
     {pht_0_44},
     {pht_0_43},
     {pht_0_42},
     {pht_0_41},
     {pht_0_40},
     {pht_0_39},
     {pht_0_38},
     {pht_0_37},
     {pht_0_36},
     {pht_0_35},
     {pht_0_34},
     {pht_0_33},
     {pht_0_32},
     {pht_0_31},
     {pht_0_30},
     {pht_0_29},
     {pht_0_28},
     {pht_0_27},
     {pht_0_26},
     {pht_0_25},
     {pht_0_24},
     {pht_0_23},
     {pht_0_22},
     {pht_0_21},
     {pht_0_20},
     {pht_0_19},
     {pht_0_18},
     {pht_0_17},
     {pht_0_16},
     {pht_0_15},
     {pht_0_14},
     {pht_0_13},
     {pht_0_12},
     {pht_0_11},
     {pht_0_10},
     {pht_0_9},
     {pht_0_8},
     {pht_0_7},
     {pht_0_6},
     {pht_0_5},
     {pht_0_4},
     {pht_0_3},
     {pht_0_2},
     {pht_0_1},
     {pht_0_0}};
  wire [63:0][1:0] _GEN_2 =
    {{pht_1_63},
     {pht_1_62},
     {pht_1_61},
     {pht_1_60},
     {pht_1_59},
     {pht_1_58},
     {pht_1_57},
     {pht_1_56},
     {pht_1_55},
     {pht_1_54},
     {pht_1_53},
     {pht_1_52},
     {pht_1_51},
     {pht_1_50},
     {pht_1_49},
     {pht_1_48},
     {pht_1_47},
     {pht_1_46},
     {pht_1_45},
     {pht_1_44},
     {pht_1_43},
     {pht_1_42},
     {pht_1_41},
     {pht_1_40},
     {pht_1_39},
     {pht_1_38},
     {pht_1_37},
     {pht_1_36},
     {pht_1_35},
     {pht_1_34},
     {pht_1_33},
     {pht_1_32},
     {pht_1_31},
     {pht_1_30},
     {pht_1_29},
     {pht_1_28},
     {pht_1_27},
     {pht_1_26},
     {pht_1_25},
     {pht_1_24},
     {pht_1_23},
     {pht_1_22},
     {pht_1_21},
     {pht_1_20},
     {pht_1_19},
     {pht_1_18},
     {pht_1_17},
     {pht_1_16},
     {pht_1_15},
     {pht_1_14},
     {pht_1_13},
     {pht_1_12},
     {pht_1_11},
     {pht_1_10},
     {pht_1_9},
     {pht_1_8},
     {pht_1_7},
     {pht_1_6},
     {pht_1_5},
     {pht_1_4},
     {pht_1_3},
     {pht_1_2},
     {pht_1_1},
     {pht_1_0}};
  wire             predict_valid_0 =
    btb_rdata_0_valid & (btb_rdata_0_tag ^ io_pc_4[31:11]) == 21'h0;
  wire             predict_valid_1 =
    btb_rdata_1_valid & (btb_rdata_1_tag ^ io_pc_5[31:11]) == 21'h0;
  wire             pred_hit_1 =
    _GEN_2[{bht_rdata_1[3:2], bht_rdata_1[1:0] ^ io_pc_3[6:5], io_pc_3[4:3]}][1]
    & predict_valid_1;
  wire             pred_hit_0 =
    _GEN_1[{bht_rdata_0[3:2], bht_rdata_0[1:0] ^ io_pc_2[6:5], io_pc_2[4:3]}][1]
    & predict_valid_0 & ~(io_pc_6[2]);
  wire             pred_valid_hit_0 = predict_valid_0 & ~(io_pc_6[2]);
  wire [29:0]      _GEN_3 = pred_hit_0 ? btb_rdata_0_target : btb_rdata_1_target;
  wire [1:0]       _GEN_4 = pred_hit_0 ? btb_rdata_0_typ : btb_rdata_1_typ;
  wire             _io_pred_npc_T = _GEN_4 == 2'h1;
  wire [2:0]       _top_T_4 = 3'(top - 3'h1);
  wire [7:0][31:0] _GEN_5 =
    {{ras_7}, {ras_6}, {ras_5}, {ras_4}, {ras_3}, {ras_2}, {ras_1}, {ras_0}};
  assign btb_rdata_0_valid = _xilinx_simple_dual_port_1_clock_ram_read_first_doutb[21];
  assign btb_rdata_0_tag = _xilinx_simple_dual_port_1_clock_ram_read_first_doutb[20:0];
  assign btb_rdata_1_valid = _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb[21];
  assign btb_rdata_1_tag = _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb[20:0];
  assign btb_rdata_0_target =
    _xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb[31:2];
  assign btb_rdata_0_typ = _xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb[1:0];
  assign btb_rdata_1_target =
    _xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb[31:2];
  assign btb_rdata_1_typ = _xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb[1:0];
  wire [2:0]       _top_T = 3'(top + 3'h1);
  wire             _GEN_6 = pred_hit_0 ? pred_valid_hit_0 : predict_valid_1;
  wire             _GEN_7 = _GEN_4[1] & _GEN_6;
  wire [2:0]       _top_T_2 = 3'(top + 3'h1);
  wire [31:0]      _ras_T_2 = {io_pc_6[31:3], ~pred_hit_0, 2'h0};
  wire [63:0][3:0] _GEN_8 = io_pc_cmt[2] ? _GEN_0 : _GEN;
  wire [3:0]       _GEN_9 = _GEN_8[io_pc_cmt[8:3]];
  wire [3:0]       _bht_T_1 = {io_real_jump, _GEN_9[3:1]};
  wire             _GEN_10 = io_pc_cmt[8:3] == 6'h0;
  wire             _GEN_11 = io_pc_cmt[8:3] == 6'h1;
  wire             _GEN_12 = io_pc_cmt[8:3] == 6'h2;
  wire             _GEN_13 = io_pc_cmt[8:3] == 6'h3;
  wire             _GEN_14 = io_pc_cmt[8:3] == 6'h4;
  wire             _GEN_15 = io_pc_cmt[8:3] == 6'h5;
  wire             _GEN_16 = io_pc_cmt[8:3] == 6'h6;
  wire             _GEN_17 = io_pc_cmt[8:3] == 6'h7;
  wire             _GEN_18 = io_pc_cmt[8:3] == 6'h8;
  wire             _GEN_19 = io_pc_cmt[8:3] == 6'h9;
  wire             _GEN_20 = io_pc_cmt[8:3] == 6'hA;
  wire             _GEN_21 = io_pc_cmt[8:3] == 6'hB;
  wire             _GEN_22 = io_pc_cmt[8:3] == 6'hC;
  wire             _GEN_23 = io_pc_cmt[8:3] == 6'hD;
  wire             _GEN_24 = io_pc_cmt[8:3] == 6'hE;
  wire             _GEN_25 = io_pc_cmt[8:3] == 6'hF;
  wire             _GEN_26 = io_pc_cmt[8:3] == 6'h10;
  wire             _GEN_27 = io_pc_cmt[8:3] == 6'h11;
  wire             _GEN_28 = io_pc_cmt[8:3] == 6'h12;
  wire             _GEN_29 = io_pc_cmt[8:3] == 6'h13;
  wire             _GEN_30 = io_pc_cmt[8:3] == 6'h14;
  wire             _GEN_31 = io_pc_cmt[8:3] == 6'h15;
  wire             _GEN_32 = io_pc_cmt[8:3] == 6'h16;
  wire             _GEN_33 = io_pc_cmt[8:3] == 6'h17;
  wire             _GEN_34 = io_pc_cmt[8:3] == 6'h18;
  wire             _GEN_35 = io_pc_cmt[8:3] == 6'h19;
  wire             _GEN_36 = io_pc_cmt[8:3] == 6'h1A;
  wire             _GEN_37 = io_pc_cmt[8:3] == 6'h1B;
  wire             _GEN_38 = io_pc_cmt[8:3] == 6'h1C;
  wire             _GEN_39 = io_pc_cmt[8:3] == 6'h1D;
  wire             _GEN_40 = io_pc_cmt[8:3] == 6'h1E;
  wire             _GEN_41 = io_pc_cmt[8:3] == 6'h1F;
  wire             _GEN_42 = io_pc_cmt[8:3] == 6'h20;
  wire             _GEN_43 = io_pc_cmt[8:3] == 6'h21;
  wire             _GEN_44 = io_pc_cmt[8:3] == 6'h22;
  wire             _GEN_45 = io_pc_cmt[8:3] == 6'h23;
  wire             _GEN_46 = io_pc_cmt[8:3] == 6'h24;
  wire             _GEN_47 = io_pc_cmt[8:3] == 6'h25;
  wire             _GEN_48 = io_pc_cmt[8:3] == 6'h26;
  wire             _GEN_49 = io_pc_cmt[8:3] == 6'h27;
  wire             _GEN_50 = io_pc_cmt[8:3] == 6'h28;
  wire             _GEN_51 = io_pc_cmt[8:3] == 6'h29;
  wire             _GEN_52 = io_pc_cmt[8:3] == 6'h2A;
  wire             _GEN_53 = io_pc_cmt[8:3] == 6'h2B;
  wire             _GEN_54 = io_pc_cmt[8:3] == 6'h2C;
  wire             _GEN_55 = io_pc_cmt[8:3] == 6'h2D;
  wire             _GEN_56 = io_pc_cmt[8:3] == 6'h2E;
  wire             _GEN_57 = io_pc_cmt[8:3] == 6'h2F;
  wire             _GEN_58 = io_pc_cmt[8:3] == 6'h30;
  wire             _GEN_59 = io_pc_cmt[8:3] == 6'h31;
  wire             _GEN_60 = io_pc_cmt[8:3] == 6'h32;
  wire             _GEN_61 = io_pc_cmt[8:3] == 6'h33;
  wire             _GEN_62 = io_pc_cmt[8:3] == 6'h34;
  wire             _GEN_63 = io_pc_cmt[8:3] == 6'h35;
  wire             _GEN_64 = io_pc_cmt[8:3] == 6'h36;
  wire             _GEN_65 = io_pc_cmt[8:3] == 6'h37;
  wire             _GEN_66 = io_pc_cmt[8:3] == 6'h38;
  wire             _GEN_67 = io_pc_cmt[8:3] == 6'h39;
  wire             _GEN_68 = io_pc_cmt[8:3] == 6'h3A;
  wire             _GEN_69 = io_pc_cmt[8:3] == 6'h3B;
  wire             _GEN_70 = io_pc_cmt[8:3] == 6'h3C;
  wire             _GEN_71 = io_pc_cmt[8:3] == 6'h3D;
  wire             _GEN_72 = io_pc_cmt[8:3] == 6'h3E;
  wire [5:0]       pht_windex =
    {_GEN_9[3:2], _GEN_9[1:0] ^ io_pc_cmt[6:5], io_pc_cmt[4:3]};
  wire [63:0][1:0] _GEN_73 = io_pc_cmt[2] ? _GEN_2 : _GEN_1;
  wire [1:0]       _pht_T_1 =
    2'(_GEN_73[pht_windex] + {1'h0, _GEN_73[pht_windex] != 2'h3});
  wire [1:0]       _pht_T_4 = 2'(_GEN_73[pht_windex] - {1'h0, |_GEN_73[pht_windex]});
  wire             _GEN_74 = pht_windex == 6'h0;
  wire             _GEN_75 = pht_windex == 6'h1;
  wire             _GEN_76 = pht_windex == 6'h2;
  wire             _GEN_77 = pht_windex == 6'h3;
  wire             _GEN_78 = pht_windex == 6'h4;
  wire             _GEN_79 = pht_windex == 6'h5;
  wire             _GEN_80 = pht_windex == 6'h6;
  wire             _GEN_81 = pht_windex == 6'h7;
  wire             _GEN_82 = pht_windex == 6'h8;
  wire             _GEN_83 = pht_windex == 6'h9;
  wire             _GEN_84 = pht_windex == 6'hA;
  wire             _GEN_85 = pht_windex == 6'hB;
  wire             _GEN_86 = pht_windex == 6'hC;
  wire             _GEN_87 = pht_windex == 6'hD;
  wire             _GEN_88 = pht_windex == 6'hE;
  wire             _GEN_89 = pht_windex == 6'hF;
  wire             _GEN_90 = pht_windex == 6'h10;
  wire             _GEN_91 = pht_windex == 6'h11;
  wire             _GEN_92 = pht_windex == 6'h12;
  wire             _GEN_93 = pht_windex == 6'h13;
  wire             _GEN_94 = pht_windex == 6'h14;
  wire             _GEN_95 = pht_windex == 6'h15;
  wire             _GEN_96 = pht_windex == 6'h16;
  wire             _GEN_97 = pht_windex == 6'h17;
  wire             _GEN_98 = pht_windex == 6'h18;
  wire             _GEN_99 = pht_windex == 6'h19;
  wire             _GEN_100 = pht_windex == 6'h1A;
  wire             _GEN_101 = pht_windex == 6'h1B;
  wire             _GEN_102 = pht_windex == 6'h1C;
  wire             _GEN_103 = pht_windex == 6'h1D;
  wire             _GEN_104 = pht_windex == 6'h1E;
  wire             _GEN_105 = pht_windex == 6'h1F;
  wire             _GEN_106 = pht_windex == 6'h20;
  wire             _GEN_107 = pht_windex == 6'h21;
  wire             _GEN_108 = pht_windex == 6'h22;
  wire             _GEN_109 = pht_windex == 6'h23;
  wire             _GEN_110 = pht_windex == 6'h24;
  wire             _GEN_111 = pht_windex == 6'h25;
  wire             _GEN_112 = pht_windex == 6'h26;
  wire             _GEN_113 = pht_windex == 6'h27;
  wire             _GEN_114 = pht_windex == 6'h28;
  wire             _GEN_115 = pht_windex == 6'h29;
  wire             _GEN_116 = pht_windex == 6'h2A;
  wire             _GEN_117 = pht_windex == 6'h2B;
  wire             _GEN_118 = pht_windex == 6'h2C;
  wire             _GEN_119 = pht_windex == 6'h2D;
  wire             _GEN_120 = pht_windex == 6'h2E;
  wire             _GEN_121 = pht_windex == 6'h2F;
  wire             _GEN_122 = pht_windex == 6'h30;
  wire             _GEN_123 = pht_windex == 6'h31;
  wire             _GEN_124 = pht_windex == 6'h32;
  wire             _GEN_125 = pht_windex == 6'h33;
  wire             _GEN_126 = pht_windex == 6'h34;
  wire             _GEN_127 = pht_windex == 6'h35;
  wire             _GEN_128 = pht_windex == 6'h36;
  wire             _GEN_129 = pht_windex == 6'h37;
  wire             _GEN_130 = pht_windex == 6'h38;
  wire             _GEN_131 = pht_windex == 6'h39;
  wire             _GEN_132 = pht_windex == 6'h3A;
  wire             _GEN_133 = pht_windex == 6'h3B;
  wire             _GEN_134 = pht_windex == 6'h3C;
  wire             _GEN_135 = pht_windex == 6'h3D;
  wire             _GEN_136 = pht_windex == 6'h3E;
  always @(posedge clock) begin
    if (reset) begin
      bht_0_0 <= 4'h0;
      bht_0_1 <= 4'h0;
      bht_0_2 <= 4'h0;
      bht_0_3 <= 4'h0;
      bht_0_4 <= 4'h0;
      bht_0_5 <= 4'h0;
      bht_0_6 <= 4'h0;
      bht_0_7 <= 4'h0;
      bht_0_8 <= 4'h0;
      bht_0_9 <= 4'h0;
      bht_0_10 <= 4'h0;
      bht_0_11 <= 4'h0;
      bht_0_12 <= 4'h0;
      bht_0_13 <= 4'h0;
      bht_0_14 <= 4'h0;
      bht_0_15 <= 4'h0;
      bht_0_16 <= 4'h0;
      bht_0_17 <= 4'h0;
      bht_0_18 <= 4'h0;
      bht_0_19 <= 4'h0;
      bht_0_20 <= 4'h0;
      bht_0_21 <= 4'h0;
      bht_0_22 <= 4'h0;
      bht_0_23 <= 4'h0;
      bht_0_24 <= 4'h0;
      bht_0_25 <= 4'h0;
      bht_0_26 <= 4'h0;
      bht_0_27 <= 4'h0;
      bht_0_28 <= 4'h0;
      bht_0_29 <= 4'h0;
      bht_0_30 <= 4'h0;
      bht_0_31 <= 4'h0;
      bht_0_32 <= 4'h0;
      bht_0_33 <= 4'h0;
      bht_0_34 <= 4'h0;
      bht_0_35 <= 4'h0;
      bht_0_36 <= 4'h0;
      bht_0_37 <= 4'h0;
      bht_0_38 <= 4'h0;
      bht_0_39 <= 4'h0;
      bht_0_40 <= 4'h0;
      bht_0_41 <= 4'h0;
      bht_0_42 <= 4'h0;
      bht_0_43 <= 4'h0;
      bht_0_44 <= 4'h0;
      bht_0_45 <= 4'h0;
      bht_0_46 <= 4'h0;
      bht_0_47 <= 4'h0;
      bht_0_48 <= 4'h0;
      bht_0_49 <= 4'h0;
      bht_0_50 <= 4'h0;
      bht_0_51 <= 4'h0;
      bht_0_52 <= 4'h0;
      bht_0_53 <= 4'h0;
      bht_0_54 <= 4'h0;
      bht_0_55 <= 4'h0;
      bht_0_56 <= 4'h0;
      bht_0_57 <= 4'h0;
      bht_0_58 <= 4'h0;
      bht_0_59 <= 4'h0;
      bht_0_60 <= 4'h0;
      bht_0_61 <= 4'h0;
      bht_0_62 <= 4'h0;
      bht_0_63 <= 4'h0;
      bht_1_0 <= 4'h0;
      bht_1_1 <= 4'h0;
      bht_1_2 <= 4'h0;
      bht_1_3 <= 4'h0;
      bht_1_4 <= 4'h0;
      bht_1_5 <= 4'h0;
      bht_1_6 <= 4'h0;
      bht_1_7 <= 4'h0;
      bht_1_8 <= 4'h0;
      bht_1_9 <= 4'h0;
      bht_1_10 <= 4'h0;
      bht_1_11 <= 4'h0;
      bht_1_12 <= 4'h0;
      bht_1_13 <= 4'h0;
      bht_1_14 <= 4'h0;
      bht_1_15 <= 4'h0;
      bht_1_16 <= 4'h0;
      bht_1_17 <= 4'h0;
      bht_1_18 <= 4'h0;
      bht_1_19 <= 4'h0;
      bht_1_20 <= 4'h0;
      bht_1_21 <= 4'h0;
      bht_1_22 <= 4'h0;
      bht_1_23 <= 4'h0;
      bht_1_24 <= 4'h0;
      bht_1_25 <= 4'h0;
      bht_1_26 <= 4'h0;
      bht_1_27 <= 4'h0;
      bht_1_28 <= 4'h0;
      bht_1_29 <= 4'h0;
      bht_1_30 <= 4'h0;
      bht_1_31 <= 4'h0;
      bht_1_32 <= 4'h0;
      bht_1_33 <= 4'h0;
      bht_1_34 <= 4'h0;
      bht_1_35 <= 4'h0;
      bht_1_36 <= 4'h0;
      bht_1_37 <= 4'h0;
      bht_1_38 <= 4'h0;
      bht_1_39 <= 4'h0;
      bht_1_40 <= 4'h0;
      bht_1_41 <= 4'h0;
      bht_1_42 <= 4'h0;
      bht_1_43 <= 4'h0;
      bht_1_44 <= 4'h0;
      bht_1_45 <= 4'h0;
      bht_1_46 <= 4'h0;
      bht_1_47 <= 4'h0;
      bht_1_48 <= 4'h0;
      bht_1_49 <= 4'h0;
      bht_1_50 <= 4'h0;
      bht_1_51 <= 4'h0;
      bht_1_52 <= 4'h0;
      bht_1_53 <= 4'h0;
      bht_1_54 <= 4'h0;
      bht_1_55 <= 4'h0;
      bht_1_56 <= 4'h0;
      bht_1_57 <= 4'h0;
      bht_1_58 <= 4'h0;
      bht_1_59 <= 4'h0;
      bht_1_60 <= 4'h0;
      bht_1_61 <= 4'h0;
      bht_1_62 <= 4'h0;
      bht_1_63 <= 4'h0;
      pht_0_0 <= 2'h2;
      pht_0_1 <= 2'h2;
      pht_0_2 <= 2'h2;
      pht_0_3 <= 2'h2;
      pht_0_4 <= 2'h2;
      pht_0_5 <= 2'h2;
      pht_0_6 <= 2'h2;
      pht_0_7 <= 2'h2;
      pht_0_8 <= 2'h2;
      pht_0_9 <= 2'h2;
      pht_0_10 <= 2'h2;
      pht_0_11 <= 2'h2;
      pht_0_12 <= 2'h2;
      pht_0_13 <= 2'h2;
      pht_0_14 <= 2'h2;
      pht_0_15 <= 2'h2;
      pht_0_16 <= 2'h2;
      pht_0_17 <= 2'h2;
      pht_0_18 <= 2'h2;
      pht_0_19 <= 2'h2;
      pht_0_20 <= 2'h2;
      pht_0_21 <= 2'h2;
      pht_0_22 <= 2'h2;
      pht_0_23 <= 2'h2;
      pht_0_24 <= 2'h2;
      pht_0_25 <= 2'h2;
      pht_0_26 <= 2'h2;
      pht_0_27 <= 2'h2;
      pht_0_28 <= 2'h2;
      pht_0_29 <= 2'h2;
      pht_0_30 <= 2'h2;
      pht_0_31 <= 2'h2;
      pht_0_32 <= 2'h2;
      pht_0_33 <= 2'h2;
      pht_0_34 <= 2'h2;
      pht_0_35 <= 2'h2;
      pht_0_36 <= 2'h2;
      pht_0_37 <= 2'h2;
      pht_0_38 <= 2'h2;
      pht_0_39 <= 2'h2;
      pht_0_40 <= 2'h2;
      pht_0_41 <= 2'h2;
      pht_0_42 <= 2'h2;
      pht_0_43 <= 2'h2;
      pht_0_44 <= 2'h2;
      pht_0_45 <= 2'h2;
      pht_0_46 <= 2'h2;
      pht_0_47 <= 2'h2;
      pht_0_48 <= 2'h2;
      pht_0_49 <= 2'h2;
      pht_0_50 <= 2'h2;
      pht_0_51 <= 2'h2;
      pht_0_52 <= 2'h2;
      pht_0_53 <= 2'h2;
      pht_0_54 <= 2'h2;
      pht_0_55 <= 2'h2;
      pht_0_56 <= 2'h2;
      pht_0_57 <= 2'h2;
      pht_0_58 <= 2'h2;
      pht_0_59 <= 2'h2;
      pht_0_60 <= 2'h2;
      pht_0_61 <= 2'h2;
      pht_0_62 <= 2'h2;
      pht_0_63 <= 2'h2;
      pht_1_0 <= 2'h2;
      pht_1_1 <= 2'h2;
      pht_1_2 <= 2'h2;
      pht_1_3 <= 2'h2;
      pht_1_4 <= 2'h2;
      pht_1_5 <= 2'h2;
      pht_1_6 <= 2'h2;
      pht_1_7 <= 2'h2;
      pht_1_8 <= 2'h2;
      pht_1_9 <= 2'h2;
      pht_1_10 <= 2'h2;
      pht_1_11 <= 2'h2;
      pht_1_12 <= 2'h2;
      pht_1_13 <= 2'h2;
      pht_1_14 <= 2'h2;
      pht_1_15 <= 2'h2;
      pht_1_16 <= 2'h2;
      pht_1_17 <= 2'h2;
      pht_1_18 <= 2'h2;
      pht_1_19 <= 2'h2;
      pht_1_20 <= 2'h2;
      pht_1_21 <= 2'h2;
      pht_1_22 <= 2'h2;
      pht_1_23 <= 2'h2;
      pht_1_24 <= 2'h2;
      pht_1_25 <= 2'h2;
      pht_1_26 <= 2'h2;
      pht_1_27 <= 2'h2;
      pht_1_28 <= 2'h2;
      pht_1_29 <= 2'h2;
      pht_1_30 <= 2'h2;
      pht_1_31 <= 2'h2;
      pht_1_32 <= 2'h2;
      pht_1_33 <= 2'h2;
      pht_1_34 <= 2'h2;
      pht_1_35 <= 2'h2;
      pht_1_36 <= 2'h2;
      pht_1_37 <= 2'h2;
      pht_1_38 <= 2'h2;
      pht_1_39 <= 2'h2;
      pht_1_40 <= 2'h2;
      pht_1_41 <= 2'h2;
      pht_1_42 <= 2'h2;
      pht_1_43 <= 2'h2;
      pht_1_44 <= 2'h2;
      pht_1_45 <= 2'h2;
      pht_1_46 <= 2'h2;
      pht_1_47 <= 2'h2;
      pht_1_48 <= 2'h2;
      pht_1_49 <= 2'h2;
      pht_1_50 <= 2'h2;
      pht_1_51 <= 2'h2;
      pht_1_52 <= 2'h2;
      pht_1_53 <= 2'h2;
      pht_1_54 <= 2'h2;
      pht_1_55 <= 2'h2;
      pht_1_56 <= 2'h2;
      pht_1_57 <= 2'h2;
      pht_1_58 <= 2'h2;
      pht_1_59 <= 2'h2;
      pht_1_60 <= 2'h2;
      pht_1_61 <= 2'h2;
      pht_1_62 <= 2'h2;
      pht_1_63 <= 2'h2;
      ras_0 <= 32'h1C000000;
      ras_1 <= 32'h1C000000;
      ras_2 <= 32'h1C000000;
      ras_3 <= 32'h1C000000;
      ras_4 <= 32'h1C000000;
      ras_5 <= 32'h1C000000;
      ras_6 <= 32'h1C000000;
      ras_7 <= 32'h1C000000;
      top <= 3'h7;
    end
    else begin
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_10)
        bht_0_0 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_11)
        bht_0_1 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_12)
        bht_0_2 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_13)
        bht_0_3 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_14)
        bht_0_4 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_15)
        bht_0_5 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_16)
        bht_0_6 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_17)
        bht_0_7 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_18)
        bht_0_8 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_19)
        bht_0_9 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_20)
        bht_0_10 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_21)
        bht_0_11 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_22)
        bht_0_12 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_23)
        bht_0_13 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_24)
        bht_0_14 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_25)
        bht_0_15 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_26)
        bht_0_16 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_27)
        bht_0_17 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_28)
        bht_0_18 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_29)
        bht_0_19 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_30)
        bht_0_20 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_31)
        bht_0_21 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_32)
        bht_0_22 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_33)
        bht_0_23 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_34)
        bht_0_24 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_35)
        bht_0_25 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_36)
        bht_0_26 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_37)
        bht_0_27 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_38)
        bht_0_28 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_39)
        bht_0_29 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_40)
        bht_0_30 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_41)
        bht_0_31 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_42)
        bht_0_32 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_43)
        bht_0_33 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_44)
        bht_0_34 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_45)
        bht_0_35 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_46)
        bht_0_36 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_47)
        bht_0_37 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_48)
        bht_0_38 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_49)
        bht_0_39 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_50)
        bht_0_40 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_51)
        bht_0_41 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_52)
        bht_0_42 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_53)
        bht_0_43 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_54)
        bht_0_44 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_55)
        bht_0_45 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_56)
        bht_0_46 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_57)
        bht_0_47 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_58)
        bht_0_48 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_59)
        bht_0_49 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_60)
        bht_0_50 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_61)
        bht_0_51 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_62)
        bht_0_52 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_63)
        bht_0_53 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_64)
        bht_0_54 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_65)
        bht_0_55 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_66)
        bht_0_56 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_67)
        bht_0_57 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_68)
        bht_0_58 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_69)
        bht_0_59 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_70)
        bht_0_60 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_71)
        bht_0_61 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_72)
        bht_0_62 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & (&(io_pc_cmt[8:3])))
        bht_0_63 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_10)
        bht_1_0 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_11)
        bht_1_1 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_12)
        bht_1_2 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_13)
        bht_1_3 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_14)
        bht_1_4 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_15)
        bht_1_5 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_16)
        bht_1_6 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_17)
        bht_1_7 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_18)
        bht_1_8 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_19)
        bht_1_9 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_20)
        bht_1_10 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_21)
        bht_1_11 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_22)
        bht_1_12 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_23)
        bht_1_13 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_24)
        bht_1_14 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_25)
        bht_1_15 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_26)
        bht_1_16 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_27)
        bht_1_17 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_28)
        bht_1_18 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_29)
        bht_1_19 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_30)
        bht_1_20 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_31)
        bht_1_21 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_32)
        bht_1_22 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_33)
        bht_1_23 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_34)
        bht_1_24 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_35)
        bht_1_25 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_36)
        bht_1_26 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_37)
        bht_1_27 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_38)
        bht_1_28 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_39)
        bht_1_29 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_40)
        bht_1_30 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_41)
        bht_1_31 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_42)
        bht_1_32 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_43)
        bht_1_33 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_44)
        bht_1_34 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_45)
        bht_1_35 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_46)
        bht_1_36 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_47)
        bht_1_37 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_48)
        bht_1_38 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_49)
        bht_1_39 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_50)
        bht_1_40 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_51)
        bht_1_41 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_52)
        bht_1_42 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_53)
        bht_1_43 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_54)
        bht_1_44 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_55)
        bht_1_45 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_56)
        bht_1_46 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_57)
        bht_1_47 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_58)
        bht_1_48 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_59)
        bht_1_49 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_60)
        bht_1_50 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_61)
        bht_1_51 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_62)
        bht_1_52 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_63)
        bht_1_53 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_64)
        bht_1_54 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_65)
        bht_1_55 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_66)
        bht_1_56 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_67)
        bht_1_57 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_68)
        bht_1_58 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_69)
        bht_1_59 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_70)
        bht_1_60 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_71)
        bht_1_61 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & _GEN_72)
        bht_1_62 <= _bht_T_1;
      if (io_update_en & io_pc_cmt[2] & (&(io_pc_cmt[8:3])))
        bht_1_63 <= _bht_T_1;
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_74) begin
        if (io_real_jump)
          pht_0_0 <= _pht_T_1;
        else
          pht_0_0 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_75) begin
        if (io_real_jump)
          pht_0_1 <= _pht_T_1;
        else
          pht_0_1 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_76) begin
        if (io_real_jump)
          pht_0_2 <= _pht_T_1;
        else
          pht_0_2 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_77) begin
        if (io_real_jump)
          pht_0_3 <= _pht_T_1;
        else
          pht_0_3 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_78) begin
        if (io_real_jump)
          pht_0_4 <= _pht_T_1;
        else
          pht_0_4 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_79) begin
        if (io_real_jump)
          pht_0_5 <= _pht_T_1;
        else
          pht_0_5 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_80) begin
        if (io_real_jump)
          pht_0_6 <= _pht_T_1;
        else
          pht_0_6 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_81) begin
        if (io_real_jump)
          pht_0_7 <= _pht_T_1;
        else
          pht_0_7 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_82) begin
        if (io_real_jump)
          pht_0_8 <= _pht_T_1;
        else
          pht_0_8 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_83) begin
        if (io_real_jump)
          pht_0_9 <= _pht_T_1;
        else
          pht_0_9 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_84) begin
        if (io_real_jump)
          pht_0_10 <= _pht_T_1;
        else
          pht_0_10 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_85) begin
        if (io_real_jump)
          pht_0_11 <= _pht_T_1;
        else
          pht_0_11 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_86) begin
        if (io_real_jump)
          pht_0_12 <= _pht_T_1;
        else
          pht_0_12 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_87) begin
        if (io_real_jump)
          pht_0_13 <= _pht_T_1;
        else
          pht_0_13 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_88) begin
        if (io_real_jump)
          pht_0_14 <= _pht_T_1;
        else
          pht_0_14 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_89) begin
        if (io_real_jump)
          pht_0_15 <= _pht_T_1;
        else
          pht_0_15 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_90) begin
        if (io_real_jump)
          pht_0_16 <= _pht_T_1;
        else
          pht_0_16 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_91) begin
        if (io_real_jump)
          pht_0_17 <= _pht_T_1;
        else
          pht_0_17 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_92) begin
        if (io_real_jump)
          pht_0_18 <= _pht_T_1;
        else
          pht_0_18 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_93) begin
        if (io_real_jump)
          pht_0_19 <= _pht_T_1;
        else
          pht_0_19 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_94) begin
        if (io_real_jump)
          pht_0_20 <= _pht_T_1;
        else
          pht_0_20 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_95) begin
        if (io_real_jump)
          pht_0_21 <= _pht_T_1;
        else
          pht_0_21 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_96) begin
        if (io_real_jump)
          pht_0_22 <= _pht_T_1;
        else
          pht_0_22 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_97) begin
        if (io_real_jump)
          pht_0_23 <= _pht_T_1;
        else
          pht_0_23 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_98) begin
        if (io_real_jump)
          pht_0_24 <= _pht_T_1;
        else
          pht_0_24 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_99) begin
        if (io_real_jump)
          pht_0_25 <= _pht_T_1;
        else
          pht_0_25 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_100) begin
        if (io_real_jump)
          pht_0_26 <= _pht_T_1;
        else
          pht_0_26 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_101) begin
        if (io_real_jump)
          pht_0_27 <= _pht_T_1;
        else
          pht_0_27 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_102) begin
        if (io_real_jump)
          pht_0_28 <= _pht_T_1;
        else
          pht_0_28 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_103) begin
        if (io_real_jump)
          pht_0_29 <= _pht_T_1;
        else
          pht_0_29 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_104) begin
        if (io_real_jump)
          pht_0_30 <= _pht_T_1;
        else
          pht_0_30 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_105) begin
        if (io_real_jump)
          pht_0_31 <= _pht_T_1;
        else
          pht_0_31 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_106) begin
        if (io_real_jump)
          pht_0_32 <= _pht_T_1;
        else
          pht_0_32 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_107) begin
        if (io_real_jump)
          pht_0_33 <= _pht_T_1;
        else
          pht_0_33 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_108) begin
        if (io_real_jump)
          pht_0_34 <= _pht_T_1;
        else
          pht_0_34 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_109) begin
        if (io_real_jump)
          pht_0_35 <= _pht_T_1;
        else
          pht_0_35 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_110) begin
        if (io_real_jump)
          pht_0_36 <= _pht_T_1;
        else
          pht_0_36 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_111) begin
        if (io_real_jump)
          pht_0_37 <= _pht_T_1;
        else
          pht_0_37 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_112) begin
        if (io_real_jump)
          pht_0_38 <= _pht_T_1;
        else
          pht_0_38 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_113) begin
        if (io_real_jump)
          pht_0_39 <= _pht_T_1;
        else
          pht_0_39 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_114) begin
        if (io_real_jump)
          pht_0_40 <= _pht_T_1;
        else
          pht_0_40 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_115) begin
        if (io_real_jump)
          pht_0_41 <= _pht_T_1;
        else
          pht_0_41 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_116) begin
        if (io_real_jump)
          pht_0_42 <= _pht_T_1;
        else
          pht_0_42 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_117) begin
        if (io_real_jump)
          pht_0_43 <= _pht_T_1;
        else
          pht_0_43 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_118) begin
        if (io_real_jump)
          pht_0_44 <= _pht_T_1;
        else
          pht_0_44 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_119) begin
        if (io_real_jump)
          pht_0_45 <= _pht_T_1;
        else
          pht_0_45 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_120) begin
        if (io_real_jump)
          pht_0_46 <= _pht_T_1;
        else
          pht_0_46 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_121) begin
        if (io_real_jump)
          pht_0_47 <= _pht_T_1;
        else
          pht_0_47 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_122) begin
        if (io_real_jump)
          pht_0_48 <= _pht_T_1;
        else
          pht_0_48 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_123) begin
        if (io_real_jump)
          pht_0_49 <= _pht_T_1;
        else
          pht_0_49 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_124) begin
        if (io_real_jump)
          pht_0_50 <= _pht_T_1;
        else
          pht_0_50 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_125) begin
        if (io_real_jump)
          pht_0_51 <= _pht_T_1;
        else
          pht_0_51 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_126) begin
        if (io_real_jump)
          pht_0_52 <= _pht_T_1;
        else
          pht_0_52 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_127) begin
        if (io_real_jump)
          pht_0_53 <= _pht_T_1;
        else
          pht_0_53 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_128) begin
        if (io_real_jump)
          pht_0_54 <= _pht_T_1;
        else
          pht_0_54 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_129) begin
        if (io_real_jump)
          pht_0_55 <= _pht_T_1;
        else
          pht_0_55 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_130) begin
        if (io_real_jump)
          pht_0_56 <= _pht_T_1;
        else
          pht_0_56 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_131) begin
        if (io_real_jump)
          pht_0_57 <= _pht_T_1;
        else
          pht_0_57 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_132) begin
        if (io_real_jump)
          pht_0_58 <= _pht_T_1;
        else
          pht_0_58 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_133) begin
        if (io_real_jump)
          pht_0_59 <= _pht_T_1;
        else
          pht_0_59 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_134) begin
        if (io_real_jump)
          pht_0_60 <= _pht_T_1;
        else
          pht_0_60 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_135) begin
        if (io_real_jump)
          pht_0_61 <= _pht_T_1;
        else
          pht_0_61 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & _GEN_136) begin
        if (io_real_jump)
          pht_0_62 <= _pht_T_1;
        else
          pht_0_62 <= _pht_T_4;
      end
      if (io_update_en & ~(io_pc_cmt[2]) & (&pht_windex)) begin
        if (io_real_jump)
          pht_0_63 <= _pht_T_1;
        else
          pht_0_63 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_74) begin
        if (io_real_jump)
          pht_1_0 <= _pht_T_1;
        else
          pht_1_0 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_75) begin
        if (io_real_jump)
          pht_1_1 <= _pht_T_1;
        else
          pht_1_1 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_76) begin
        if (io_real_jump)
          pht_1_2 <= _pht_T_1;
        else
          pht_1_2 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_77) begin
        if (io_real_jump)
          pht_1_3 <= _pht_T_1;
        else
          pht_1_3 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_78) begin
        if (io_real_jump)
          pht_1_4 <= _pht_T_1;
        else
          pht_1_4 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_79) begin
        if (io_real_jump)
          pht_1_5 <= _pht_T_1;
        else
          pht_1_5 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_80) begin
        if (io_real_jump)
          pht_1_6 <= _pht_T_1;
        else
          pht_1_6 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_81) begin
        if (io_real_jump)
          pht_1_7 <= _pht_T_1;
        else
          pht_1_7 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_82) begin
        if (io_real_jump)
          pht_1_8 <= _pht_T_1;
        else
          pht_1_8 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_83) begin
        if (io_real_jump)
          pht_1_9 <= _pht_T_1;
        else
          pht_1_9 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_84) begin
        if (io_real_jump)
          pht_1_10 <= _pht_T_1;
        else
          pht_1_10 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_85) begin
        if (io_real_jump)
          pht_1_11 <= _pht_T_1;
        else
          pht_1_11 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_86) begin
        if (io_real_jump)
          pht_1_12 <= _pht_T_1;
        else
          pht_1_12 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_87) begin
        if (io_real_jump)
          pht_1_13 <= _pht_T_1;
        else
          pht_1_13 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_88) begin
        if (io_real_jump)
          pht_1_14 <= _pht_T_1;
        else
          pht_1_14 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_89) begin
        if (io_real_jump)
          pht_1_15 <= _pht_T_1;
        else
          pht_1_15 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_90) begin
        if (io_real_jump)
          pht_1_16 <= _pht_T_1;
        else
          pht_1_16 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_91) begin
        if (io_real_jump)
          pht_1_17 <= _pht_T_1;
        else
          pht_1_17 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_92) begin
        if (io_real_jump)
          pht_1_18 <= _pht_T_1;
        else
          pht_1_18 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_93) begin
        if (io_real_jump)
          pht_1_19 <= _pht_T_1;
        else
          pht_1_19 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_94) begin
        if (io_real_jump)
          pht_1_20 <= _pht_T_1;
        else
          pht_1_20 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_95) begin
        if (io_real_jump)
          pht_1_21 <= _pht_T_1;
        else
          pht_1_21 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_96) begin
        if (io_real_jump)
          pht_1_22 <= _pht_T_1;
        else
          pht_1_22 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_97) begin
        if (io_real_jump)
          pht_1_23 <= _pht_T_1;
        else
          pht_1_23 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_98) begin
        if (io_real_jump)
          pht_1_24 <= _pht_T_1;
        else
          pht_1_24 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_99) begin
        if (io_real_jump)
          pht_1_25 <= _pht_T_1;
        else
          pht_1_25 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_100) begin
        if (io_real_jump)
          pht_1_26 <= _pht_T_1;
        else
          pht_1_26 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_101) begin
        if (io_real_jump)
          pht_1_27 <= _pht_T_1;
        else
          pht_1_27 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_102) begin
        if (io_real_jump)
          pht_1_28 <= _pht_T_1;
        else
          pht_1_28 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_103) begin
        if (io_real_jump)
          pht_1_29 <= _pht_T_1;
        else
          pht_1_29 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_104) begin
        if (io_real_jump)
          pht_1_30 <= _pht_T_1;
        else
          pht_1_30 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_105) begin
        if (io_real_jump)
          pht_1_31 <= _pht_T_1;
        else
          pht_1_31 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_106) begin
        if (io_real_jump)
          pht_1_32 <= _pht_T_1;
        else
          pht_1_32 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_107) begin
        if (io_real_jump)
          pht_1_33 <= _pht_T_1;
        else
          pht_1_33 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_108) begin
        if (io_real_jump)
          pht_1_34 <= _pht_T_1;
        else
          pht_1_34 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_109) begin
        if (io_real_jump)
          pht_1_35 <= _pht_T_1;
        else
          pht_1_35 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_110) begin
        if (io_real_jump)
          pht_1_36 <= _pht_T_1;
        else
          pht_1_36 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_111) begin
        if (io_real_jump)
          pht_1_37 <= _pht_T_1;
        else
          pht_1_37 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_112) begin
        if (io_real_jump)
          pht_1_38 <= _pht_T_1;
        else
          pht_1_38 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_113) begin
        if (io_real_jump)
          pht_1_39 <= _pht_T_1;
        else
          pht_1_39 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_114) begin
        if (io_real_jump)
          pht_1_40 <= _pht_T_1;
        else
          pht_1_40 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_115) begin
        if (io_real_jump)
          pht_1_41 <= _pht_T_1;
        else
          pht_1_41 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_116) begin
        if (io_real_jump)
          pht_1_42 <= _pht_T_1;
        else
          pht_1_42 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_117) begin
        if (io_real_jump)
          pht_1_43 <= _pht_T_1;
        else
          pht_1_43 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_118) begin
        if (io_real_jump)
          pht_1_44 <= _pht_T_1;
        else
          pht_1_44 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_119) begin
        if (io_real_jump)
          pht_1_45 <= _pht_T_1;
        else
          pht_1_45 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_120) begin
        if (io_real_jump)
          pht_1_46 <= _pht_T_1;
        else
          pht_1_46 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_121) begin
        if (io_real_jump)
          pht_1_47 <= _pht_T_1;
        else
          pht_1_47 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_122) begin
        if (io_real_jump)
          pht_1_48 <= _pht_T_1;
        else
          pht_1_48 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_123) begin
        if (io_real_jump)
          pht_1_49 <= _pht_T_1;
        else
          pht_1_49 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_124) begin
        if (io_real_jump)
          pht_1_50 <= _pht_T_1;
        else
          pht_1_50 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_125) begin
        if (io_real_jump)
          pht_1_51 <= _pht_T_1;
        else
          pht_1_51 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_126) begin
        if (io_real_jump)
          pht_1_52 <= _pht_T_1;
        else
          pht_1_52 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_127) begin
        if (io_real_jump)
          pht_1_53 <= _pht_T_1;
        else
          pht_1_53 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_128) begin
        if (io_real_jump)
          pht_1_54 <= _pht_T_1;
        else
          pht_1_54 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_129) begin
        if (io_real_jump)
          pht_1_55 <= _pht_T_1;
        else
          pht_1_55 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_130) begin
        if (io_real_jump)
          pht_1_56 <= _pht_T_1;
        else
          pht_1_56 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_131) begin
        if (io_real_jump)
          pht_1_57 <= _pht_T_1;
        else
          pht_1_57 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_132) begin
        if (io_real_jump)
          pht_1_58 <= _pht_T_1;
        else
          pht_1_58 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_133) begin
        if (io_real_jump)
          pht_1_59 <= _pht_T_1;
        else
          pht_1_59 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_134) begin
        if (io_real_jump)
          pht_1_60 <= _pht_T_1;
        else
          pht_1_60 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_135) begin
        if (io_real_jump)
          pht_1_61 <= _pht_T_1;
        else
          pht_1_61 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & _GEN_136) begin
        if (io_real_jump)
          pht_1_62 <= _pht_T_1;
        else
          pht_1_62 <= _pht_T_4;
      end
      if (io_update_en & io_pc_cmt[2] & (&pht_windex)) begin
        if (io_real_jump)
          pht_1_63 <= _pht_T_1;
        else
          pht_1_63 <= _pht_T_4;
      end
      if (io_predict_fail) begin
        ras_0 <= io_ras_arch_0;
        ras_1 <= io_ras_arch_1;
        ras_2 <= io_ras_arch_2;
        ras_3 <= io_ras_arch_3;
        ras_4 <= io_ras_arch_4;
        ras_5 <= io_ras_arch_5;
        ras_6 <= io_ras_arch_6;
        ras_7 <= io_ras_arch_7;
        top <= io_top_arch;
      end
      else if (io_pd_pred_fix) begin
        if (io_pd_pred_fix_is_bl & _top_T == 3'h0)
          ras_0 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h1)
          ras_1 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h2)
          ras_2 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h3)
          ras_3 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h4)
          ras_4 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h5)
          ras_5 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & _top_T == 3'h6)
          ras_6 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl & (&_top_T))
          ras_7 <= io_pd_pc_plus_4;
        if (io_pd_pred_fix_is_bl)
          top <= _top_T;
      end
      else begin
        if (_GEN_7 & _top_T_2 == 3'h0)
          ras_0 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h1)
          ras_1 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h2)
          ras_2 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h3)
          ras_3 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h4)
          ras_4 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h5)
          ras_5 <= _ras_T_2;
        if (_GEN_7 & _top_T_2 == 3'h6)
          ras_6 <= _ras_T_2;
        if (_GEN_7 & (&_top_T_2))
          ras_7 <= _ras_T_2;
        if (_GEN_7)
          top <= _top_T_2;
        else if (_io_pred_npc_T & _GEN_6)
          top <= _top_T_4;
      end
    end
  end // always @(posedge)
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_addra = io_pc_cmt[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_addrb = io_npc_0[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_dina = {1'h1, io_pc_cmt[31:11]};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_wea =
    io_update_en & ~(io_pc_cmt[2]);
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(22)
  ) xilinx_simple_dual_port_1_clock_ram_read_first (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_1_addra = io_pc_cmt[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_1_addrb = io_npc_1[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_1_dina =
    {1'h1, io_pc_cmt[31:11]};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_1_wea =
    io_update_en & io_pc_cmt[2];
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(22)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_1 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_1_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_1_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_1_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_1_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_addra = io_pc_cmt[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb = io_npc_0[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_dina =
    {io_branch_target[31:2], io_br_type};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_wea =
    io_update_en & ~(io_pc_cmt[2]);
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(32)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_2 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_2_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_2_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_2_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_addra = io_pc_cmt[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb = io_npc_1[9:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_dina =
    {io_branch_target[31:2], io_br_type};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_wea =
    io_update_en & io_pc_cmt[2];
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(32)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_3 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_3_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_3_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_3_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb)
  );
  assign io_predict_jump_0 = io_pc_6[2] ? pred_hit_1 : pred_hit_0;
  assign io_predict_jump_1 = pred_hit_1;
  assign io_pred_npc = _io_pred_npc_T ? 32'(_GEN_5[_top_T_4] + 32'h4) : {_GEN_3, 2'h0};
  assign io_pred_valid_0 = io_pc_6[2] ? predict_valid_1 : pred_valid_hit_0;
  assign io_pred_valid_1 = predict_valid_1;
endmodule

