// Generated by CIRCT firtool-1.62.0
module SB(
  input         clock,
                reset,
  output        io_full,
  input  [31:0] io_addr_ex,
                io_st_data_ex,
  input  [4:0]  io_mem_type_ex,
  input         io_uncache_ex,
  input  [1:0]  io_is_store_num_cmt,
  output        io_st_cmt_valid,
  input         io_dcache_miss,
  output [31:0] io_st_addr_cmt,
                io_st_data_cmt,
  output [1:0]  io_st_wlen_cmt,
  output        io_is_uncache_cmt,
  input         io_flush,
  output [31:0] io_ld_data_mem,
  output        io_ld_hit_0,
                io_ld_hit_1,
                io_ld_hit_2,
                io_ld_hit_3,
  input         io_em_stall
);

  reg  [31:0]      sb_0_addr;
  reg  [31:0]      sb_0_data;
  reg  [3:0]       sb_0_wstrb;
  reg              sb_0_uncache;
  reg  [31:0]      sb_1_addr;
  reg  [31:0]      sb_1_data;
  reg  [3:0]       sb_1_wstrb;
  reg              sb_1_uncache;
  reg  [31:0]      sb_2_addr;
  reg  [31:0]      sb_2_data;
  reg  [3:0]       sb_2_wstrb;
  reg              sb_2_uncache;
  reg  [31:0]      sb_3_addr;
  reg  [31:0]      sb_3_data;
  reg  [3:0]       sb_3_wstrb;
  reg              sb_3_uncache;
  reg  [1:0]       head;
  reg  [1:0]       tail;
  reg  [2:0]       elem_num;
  reg              flush_buf;
  wire             full = elem_num == 3'h4 | flush_buf;
  reg  [2:0]       wait_to_cmt;
  wire [3:0][31:0] _GEN = {{sb_3_addr}, {sb_2_addr}, {sb_1_addr}, {sb_0_addr}};
  wire [3:0][31:0] _GEN_0 = {{sb_3_data}, {sb_2_data}, {sb_1_data}, {sb_0_data}};
  wire [3:0][3:0]  _GEN_1 = {{sb_3_wstrb}, {sb_2_wstrb}, {sb_1_wstrb}, {sb_0_wstrb}};
  wire [3:0]       _GEN_2 = _GEN_1[head];
  wire [3:0]       _GEN_3 =
    {{sb_3_uncache}, {sb_2_uncache}, {sb_1_uncache}, {sb_0_uncache}};
  wire [1:0]       _offset_T_5 = _GEN_2[1] ? 2'h1 : {1'h1, ~(_GEN_2[2])};
  wire [1:0]       offset = _GEN_2[0] ? 2'h0 : _offset_T_5;
  wire [2:0]       _io_st_wlen_cmt_T_9 =
    3'({1'h0, 2'({1'h0, _GEN_2[0]} + {1'h0, _GEN_2[1]})}
       + {1'h0, 2'({1'h0, _GEN_2[2]} + {1'h0, _GEN_2[3]})});
  reg  [31:0]      sb_order_reg_0_data;
  reg  [31:0]      sb_order_reg_1_data;
  reg  [31:0]      sb_order_reg_2_data;
  reg  [31:0]      sb_order_reg_3_data;
  reg  [3:0]       ld_hit_mask;
  reg  [3:0]       ld_hit_index;
  wire [31:0]      _hit_byte_T_4 = ld_hit_index[0] ? sb_order_reg_0_data : 32'h0;
  wire [31:0]      _hit_byte_T_5 = ld_hit_index[1] ? sb_order_reg_1_data : 32'h0;
  wire [31:0]      _hit_byte_T_6 = ld_hit_index[2] ? sb_order_reg_2_data : 32'h0;
  wire [31:0]      _hit_byte_T_7 = ld_hit_index[3] ? sb_order_reg_3_data : 32'h0;
  reg  [1:0]       hit_byte_r;
  wire [31:0]      hit_byte =
    (_hit_byte_T_4 | _hit_byte_T_5 | _hit_byte_T_6 | _hit_byte_T_7)
    >> {27'h0, hit_byte_r, 3'h0};
  reg              ld_hit_data_0_r;
  wire [7:0]       _ld_hit_data_0_T_1 = ld_hit_data_0_r ? hit_byte[7:0] : 8'h0;
  reg              io_ld_hit_0_r;
  reg  [3:0]       ld_hit_index_1;
  wire [31:0]      _hit_byte_T_18 = ld_hit_index_1[0] ? sb_order_reg_0_data : 32'h0;
  wire [31:0]      _hit_byte_T_19 = ld_hit_index_1[1] ? sb_order_reg_1_data : 32'h0;
  wire [31:0]      _hit_byte_T_20 = ld_hit_index_1[2] ? sb_order_reg_2_data : 32'h0;
  wire [31:0]      _hit_byte_T_21 = ld_hit_index_1[3] ? sb_order_reg_3_data : 32'h0;
  reg  [1:0]       hit_byte_r_1;
  wire [31:0]      hit_byte_1 =
    (_hit_byte_T_18 | _hit_byte_T_19 | _hit_byte_T_20 | _hit_byte_T_21)
    >> {27'h0, hit_byte_r_1, 3'h0};
  reg              ld_hit_data_1_r;
  wire [7:0]       _ld_hit_data_1_T_1 = ld_hit_data_1_r ? hit_byte_1[7:0] : 8'h0;
  reg              io_ld_hit_1_r;
  reg  [3:0]       ld_hit_index_2;
  wire [31:0]      _hit_byte_T_32 = ld_hit_index_2[0] ? sb_order_reg_0_data : 32'h0;
  wire [31:0]      _hit_byte_T_33 = ld_hit_index_2[1] ? sb_order_reg_1_data : 32'h0;
  wire [31:0]      _hit_byte_T_34 = ld_hit_index_2[2] ? sb_order_reg_2_data : 32'h0;
  wire [31:0]      _hit_byte_T_35 = ld_hit_index_2[3] ? sb_order_reg_3_data : 32'h0;
  reg  [1:0]       hit_byte_r_2;
  wire [31:0]      hit_byte_2 =
    (_hit_byte_T_32 | _hit_byte_T_33 | _hit_byte_T_34 | _hit_byte_T_35)
    >> {27'h0, hit_byte_r_2, 3'h0};
  reg              ld_hit_data_2_r;
  wire [7:0]       _ld_hit_data_2_T_1 = ld_hit_data_2_r ? hit_byte_2[7:0] : 8'h0;
  reg              io_ld_hit_2_r;
  reg  [3:0]       ld_hit_index_3;
  wire [31:0]      _hit_byte_T_46 = ld_hit_index_3[0] ? sb_order_reg_0_data : 32'h0;
  wire [31:0]      _hit_byte_T_47 = ld_hit_index_3[1] ? sb_order_reg_1_data : 32'h0;
  wire [31:0]      _hit_byte_T_48 = ld_hit_index_3[2] ? sb_order_reg_2_data : 32'h0;
  wire [31:0]      _hit_byte_T_49 = ld_hit_index_3[3] ? sb_order_reg_3_data : 32'h0;
  reg  [1:0]       hit_byte_r_3;
  wire [31:0]      hit_byte_3 =
    (_hit_byte_T_46 | _hit_byte_T_47 | _hit_byte_T_48 | _hit_byte_T_49)
    >> {27'h0, hit_byte_r_3, 3'h0};
  reg              ld_hit_data_3_r;
  wire [7:0]       _ld_hit_data_3_T_1 = ld_hit_data_3_r ? hit_byte_3[7:0] : 8'h0;
  reg              io_ld_hit_3_r;
  wire [1:0]       _start_T = 2'(head + wait_to_cmt[1:0]);
  wire [2:0]       _clear_num_T = 3'(elem_num - wait_to_cmt);
  wire [1:0]       clear_idx_1 = 2'(_start_T + 2'h1);
  wire             _GEN_4 =
    (|(_clear_num_T[2:1])) & clear_idx_1 == 2'h0 | (|_clear_num_T) & _start_T == 2'h0;
  wire             _GEN_5 =
    (|(_clear_num_T[2:1])) & clear_idx_1 == 2'h1 | (|_clear_num_T) & _start_T == 2'h1;
  wire             _GEN_6 =
    (|(_clear_num_T[2:1])) & clear_idx_1 == 2'h2 | (|_clear_num_T) & _start_T == 2'h2;
  wire             _GEN_7 =
    (|(_clear_num_T[2:1])) & (&clear_idx_1) | (|_clear_num_T) & (&_start_T);
  wire [1:0]       clear_idx_2 = 2'(_start_T - 2'h2);
  wire             _GEN_8 = _clear_num_T > 3'h2;
  wire             _GEN_9 = _GEN_8 & clear_idx_2 == 2'h0;
  wire             _GEN_10 = _GEN_8 & clear_idx_2 == 2'h1;
  wire             _GEN_11 = _GEN_8 & clear_idx_2 == 2'h2;
  wire             _GEN_12 = _GEN_8 & (&clear_idx_2);
  wire [1:0]       clear_idx_3 = 2'(_start_T - 2'h1);
  wire             _GEN_13 =
    _clear_num_T[2] ? clear_idx_3 == 2'h0 | _GEN_9 | _GEN_4 : _GEN_9 | _GEN_4;
  wire             _GEN_14 =
    _clear_num_T[2] ? clear_idx_3 == 2'h1 | _GEN_10 | _GEN_5 : _GEN_10 | _GEN_5;
  wire             _GEN_15 =
    _clear_num_T[2] ? clear_idx_3 == 2'h2 | _GEN_11 | _GEN_6 : _GEN_11 | _GEN_6;
  wire             _GEN_16 =
    _clear_num_T[2] ? (&clear_idx_3) | _GEN_12 | _GEN_7 : _GEN_12 | _GEN_7;
  wire [31:0]      _sb_addr_T_1 = {io_addr_ex[31:2], 2'h0};
  wire [62:0]      _sb_data_T_2 =
    {31'h0, io_st_data_ex} << {58'h0, io_addr_ex[1:0], 3'h0};
  wire [18:0]      _sb_wstrb_T_6 =
    {3'h0, 16'((16'h1 << (4'h1 << io_mem_type_ex[1:0])) - 16'h1)} << io_addr_ex[1:0];
  wire [3:0]       _GEN_17 = {2'h0, io_mem_type_ex[1:0]};
  wire [15:0]      _ld_mask_T_2 = 16'h1 << (4'h1 << _GEN_17);
  wire [3:0]       _ld_mask_T_3 = 4'(_ld_mask_T_2[3:0] - 4'h1);
  wire [1:0]       _sb_order_T_12 = 2'(tail - 2'h1);
  wire [1:0]       _sb_order_T_6 = 2'(tail - 2'h2);
  wire [1:0]       _sb_order_T_10 = 2'(tail + 2'h1);
  wire [3:0]       sb_order_3_wstrb = _GEN_1[tail];
  wire             ld_hit_temp_0 =
    (_GEN[_sb_order_T_12][31:2] ^ io_addr_ex[31:2]) == 30'h0;
  wire             ld_hit_temp_1 =
    (_GEN[_sb_order_T_6][31:2] ^ io_addr_ex[31:2]) == 30'h0;
  wire             ld_hit_temp_2 =
    (_GEN[_sb_order_T_10][31:2] ^ io_addr_ex[31:2]) == 30'h0;
  wire             ld_hit_temp_3 = (_GEN[tail][31:2] ^ io_addr_ex[31:2]) == 30'h0;
  wire [3:0]       _GEN_18 = {2'h0, io_addr_ex[1:0]};
  wire [3:0]       _ld_hit_T_1 = _GEN_1[_sb_order_T_12] >> _GEN_18;
  wire             ld_hit_0 = ld_hit_temp_0 & _ld_hit_T_1[0];
  wire [3:0]       _ld_hit_T_5 = _GEN_1[_sb_order_T_6] >> _GEN_18;
  wire             ld_hit_1 = ld_hit_temp_1 & _ld_hit_T_5[0];
  wire [3:0]       _ld_hit_T_9 = _GEN_1[_sb_order_T_10] >> _GEN_18;
  wire             ld_hit_2 = ld_hit_temp_2 & _ld_hit_T_9[0];
  wire [3:0]       _ld_hit_T_13 = sb_order_3_wstrb >> _GEN_18;
  wire             ld_hit_3 = ld_hit_temp_3 & _ld_hit_T_13[0];
  wire             ld_bit_hit =
    (|{ld_hit_3, ld_hit_2, ld_hit_1, ld_hit_0}) & _ld_mask_T_3[0];
  wire [1:0]       _addr_mem_T_7 = 2'(io_addr_ex[1:0] + 2'h1);
  wire [3:0]       _GEN_19 = {2'h0, _addr_mem_T_7};
  wire [3:0]       _ld_hit_T_17 = _GEN_1[_sb_order_T_12] >> _GEN_19;
  wire             ld_hit_1_0 = ld_hit_temp_0 & _ld_hit_T_17[0];
  wire [3:0]       _ld_hit_T_21 = _GEN_1[_sb_order_T_6] >> _GEN_19;
  wire             ld_hit_1_1 = ld_hit_temp_1 & _ld_hit_T_21[0];
  wire [3:0]       _ld_hit_T_25 = _GEN_1[_sb_order_T_10] >> _GEN_19;
  wire             ld_hit_1_2 = ld_hit_temp_2 & _ld_hit_T_25[0];
  wire [3:0]       _ld_hit_T_29 = sb_order_3_wstrb >> _GEN_19;
  wire             ld_hit_1_3 = ld_hit_temp_3 & _ld_hit_T_29[0];
  wire             ld_bit_hit_1 =
    (|{ld_hit_1_3, ld_hit_1_2, ld_hit_1_1, ld_hit_1_0}) & _ld_mask_T_3[1];
  wire [1:0]       _addr_mem_T_12 = 2'(io_addr_ex[1:0] - 2'h2);
  wire [3:0]       _GEN_20 = {2'h0, _addr_mem_T_12};
  wire [3:0]       _ld_hit_T_33 = _GEN_1[_sb_order_T_12] >> _GEN_20;
  wire             ld_hit_2_0 = ld_hit_temp_0 & _ld_hit_T_33[0];
  wire [3:0]       _ld_hit_T_37 = _GEN_1[_sb_order_T_6] >> _GEN_20;
  wire             ld_hit_2_1 = ld_hit_temp_1 & _ld_hit_T_37[0];
  wire [3:0]       _ld_hit_T_41 = _GEN_1[_sb_order_T_10] >> _GEN_20;
  wire             ld_hit_2_2 = ld_hit_temp_2 & _ld_hit_T_41[0];
  wire [3:0]       _ld_hit_T_45 = sb_order_3_wstrb >> _GEN_20;
  wire             ld_hit_2_3 = ld_hit_temp_3 & _ld_hit_T_45[0];
  wire             ld_bit_hit_2 =
    (|{ld_hit_2_3, ld_hit_2_2, ld_hit_2_1, ld_hit_2_0}) & _ld_mask_T_3[2];
  wire [1:0]       _addr_mem_T_17 = 2'(io_addr_ex[1:0] - 2'h1);
  wire [3:0]       _GEN_21 = {2'h0, _addr_mem_T_17};
  wire [3:0]       _ld_hit_T_49 = _GEN_1[_sb_order_T_12] >> _GEN_21;
  wire             ld_hit_3_0 = ld_hit_temp_0 & _ld_hit_T_49[0];
  wire [3:0]       _ld_hit_T_53 = _GEN_1[_sb_order_T_6] >> _GEN_21;
  wire             ld_hit_3_1 = ld_hit_temp_1 & _ld_hit_T_53[0];
  wire [3:0]       _ld_hit_T_57 = _GEN_1[_sb_order_T_10] >> _GEN_21;
  wire             ld_hit_3_2 = ld_hit_temp_2 & _ld_hit_T_57[0];
  wire [3:0]       _ld_hit_T_61 = sb_order_3_wstrb >> _GEN_21;
  wire             ld_hit_3_3 = ld_hit_temp_3 & _ld_hit_T_61[0];
  wire             ld_bit_hit_3 =
    (|{ld_hit_3_3, ld_hit_3_2, ld_hit_3_1, ld_hit_3_0}) & _ld_mask_T_3[3];
  wire [18:0]      _ld_hit_mask_T_3 = 19'hF << (4'h1 << _GEN_17);
  wire [3:0]       _ld_hit_index_T_6 = ld_hit_2 ? 4'h4 : {ld_hit_3, 3'h0};
  wire [3:0]       _ld_hit_index_T_7 = ld_hit_1 ? 4'h2 : _ld_hit_index_T_6;
  wire [3:0]       _ld_hit_index_T_16 = ld_hit_1_2 ? 4'h4 : {ld_hit_1_3, 3'h0};
  wire [3:0]       _ld_hit_index_T_17 = ld_hit_1_1 ? 4'h2 : _ld_hit_index_T_16;
  wire [3:0]       _ld_hit_index_T_26 = ld_hit_2_2 ? 4'h4 : {ld_hit_2_3, 3'h0};
  wire [3:0]       _ld_hit_index_T_27 = ld_hit_2_1 ? 4'h2 : _ld_hit_index_T_26;
  wire [3:0]       _ld_hit_index_T_36 = ld_hit_3_2 ? 4'h4 : {ld_hit_3_3, 3'h0};
  wire [3:0]       _ld_hit_index_T_37 = ld_hit_3_1 ? 4'h2 : _ld_hit_index_T_36;
  wire             _GEN_22 = ~flush_buf & io_mem_type_ex[4];
  wire             _GEN_23 = _GEN_22 & tail == 2'h0;
  wire             _GEN_24 = flush_buf | ~_GEN_23;
  wire             _GEN_25 = _GEN_22 & tail == 2'h1;
  wire             _GEN_26 = _GEN_22 & tail == 2'h2;
  wire             _GEN_27 = _GEN_22 & (&tail);
  always @(posedge clock) begin
    if (reset) begin
      sb_0_addr <= 32'h0;
      sb_0_data <= 32'h0;
      sb_0_wstrb <= 4'h0;
      sb_0_uncache <= 1'h0;
      sb_1_addr <= 32'h0;
      sb_1_data <= 32'h0;
      sb_1_wstrb <= 4'h0;
      sb_1_uncache <= 1'h0;
      sb_2_addr <= 32'h0;
      sb_2_data <= 32'h0;
      sb_2_wstrb <= 4'h0;
      sb_2_uncache <= 1'h0;
      sb_3_addr <= 32'h0;
      sb_3_data <= 32'h0;
      sb_3_wstrb <= 4'h0;
      sb_3_uncache <= 1'h0;
      head <= 2'h0;
      tail <= 2'h0;
      elem_num <= 3'h0;
      flush_buf <= 1'h0;
      wait_to_cmt <= 3'h0;
    end
    else begin
      if (_GEN_24) begin
      end
      else begin
        sb_0_addr <= _sb_addr_T_1;
        sb_0_data <= _sb_data_T_2[31:0];
      end
      if (flush_buf) begin
        if (_GEN_13)
          sb_0_wstrb <= 4'h0;
        if (_GEN_14)
          sb_1_wstrb <= 4'h0;
        if (_GEN_15)
          sb_2_wstrb <= 4'h0;
        if (_GEN_16)
          sb_3_wstrb <= 4'h0;
      end
      else begin
        if (_GEN_23)
          sb_0_wstrb <= _sb_wstrb_T_6[3:0];
        if (_GEN_25)
          sb_1_wstrb <= _sb_wstrb_T_6[3:0];
        if (_GEN_26)
          sb_2_wstrb <= _sb_wstrb_T_6[3:0];
        if (_GEN_27)
          sb_3_wstrb <= _sb_wstrb_T_6[3:0];
      end
      if (_GEN_24) begin
      end
      else
        sb_0_uncache <= io_uncache_ex;
      if (flush_buf | ~_GEN_25) begin
      end
      else begin
        sb_1_addr <= _sb_addr_T_1;
        sb_1_data <= _sb_data_T_2[31:0];
        sb_1_uncache <= io_uncache_ex;
      end
      if (flush_buf | ~_GEN_26) begin
      end
      else begin
        sb_2_addr <= _sb_addr_T_1;
        sb_2_data <= _sb_data_T_2[31:0];
        sb_2_uncache <= io_uncache_ex;
      end
      if (flush_buf | ~_GEN_27) begin
      end
      else begin
        sb_3_addr <= _sb_addr_T_1;
        sb_3_data <= _sb_data_T_2[31:0];
        sb_3_uncache <= io_uncache_ex;
      end
      head <= 2'(head + {1'h0, (|wait_to_cmt) & ~io_dcache_miss});
      if (flush_buf & ~(|wait_to_cmt))
        tail <= 2'(head + {1'h0, (|wait_to_cmt) & ~io_dcache_miss});
      else
        tail <= 2'(tail + {1'h0, io_mem_type_ex[4]});
      if (flush_buf & ~(|wait_to_cmt))
        elem_num <= 3'h0;
      else
        elem_num <=
          3'(3'(elem_num - {2'h0, (|wait_to_cmt) & ~io_dcache_miss})
             + {2'h0, io_mem_type_ex[4] & ~full});
      flush_buf <= io_flush | (|wait_to_cmt) & flush_buf;
      wait_to_cmt <=
        3'(3'(wait_to_cmt + {1'h0, io_is_store_num_cmt})
           - {2'h0, (|wait_to_cmt) & ~io_dcache_miss});
    end
    if (io_em_stall) begin
    end
    else begin
      sb_order_reg_0_data <= _GEN_0[_sb_order_T_12];
      sb_order_reg_1_data <= _GEN_0[_sb_order_T_6];
      sb_order_reg_2_data <= _GEN_0[_sb_order_T_10];
      sb_order_reg_3_data <= _GEN_0[tail];
      ld_hit_mask <= io_mem_type_ex[4] ? 4'hF : _ld_hit_mask_T_3[3:0];
      ld_hit_index <= ld_hit_0 ? 4'h1 : _ld_hit_index_T_7;
      hit_byte_r <= io_addr_ex[1:0];
      ld_hit_data_0_r <= ld_bit_hit;
      io_ld_hit_0_r <= ld_bit_hit;
      ld_hit_index_1 <= ld_hit_1_0 ? 4'h1 : _ld_hit_index_T_17;
      hit_byte_r_1 <= _addr_mem_T_7;
      ld_hit_data_1_r <= ld_bit_hit_1;
      io_ld_hit_1_r <= ld_bit_hit_1;
      ld_hit_index_2 <= ld_hit_2_0 ? 4'h1 : _ld_hit_index_T_27;
      hit_byte_r_2 <= _addr_mem_T_12;
      ld_hit_data_2_r <= ld_bit_hit_2;
      io_ld_hit_2_r <= ld_bit_hit_2;
      ld_hit_index_3 <= ld_hit_3_0 ? 4'h1 : _ld_hit_index_T_37;
      hit_byte_r_3 <= _addr_mem_T_17;
      ld_hit_data_3_r <= ld_bit_hit_3;
      io_ld_hit_3_r <= ld_bit_hit_3;
    end
  end // always @(posedge)
  assign io_full = full;
  assign io_st_cmt_valid = |wait_to_cmt;
  assign io_st_addr_cmt = 32'(_GEN[head] + {30'h0, offset});
  assign io_st_data_cmt = _GEN_0[head] >> {27'h0, offset, 3'h0};
  assign io_st_wlen_cmt = _io_st_wlen_cmt_T_9[2:1];
  assign io_is_uncache_cmt = _GEN_3[head];
  assign io_ld_data_mem =
    {_ld_hit_data_3_T_1, _ld_hit_data_2_T_1, _ld_hit_data_1_T_1, _ld_hit_data_0_T_1};
  assign io_ld_hit_0 = ld_hit_mask[0] | io_ld_hit_0_r;
  assign io_ld_hit_1 = ld_hit_mask[1] | io_ld_hit_1_r;
  assign io_ld_hit_2 = ld_hit_mask[2] | io_ld_hit_2_r;
  assign io_ld_hit_3 = ld_hit_mask[3] | io_ld_hit_3_r;
endmodule

