// Generated by CIRCT firtool-1.62.0
module Stable_Counter(
  input         clock,
                reset,
  output [63:0] io_value
);

  reg [63:0] counter;
  always @(posedge clock) begin
    if (reset)
      counter <= 64'h0;
    else
      counter <= 64'(counter + 64'h1);
  end // always @(posedge)
  assign io_value = counter;
endmodule

