// Generated by CIRCT firtool-1.62.0
module Unorder_Issue_Queue(
  input         clock,
                reset,
                io_insts_disp_index_0,
                io_insts_disp_valid_0,
                io_insts_disp_valid_1,
  input  [5:0]  io_insts_dispatch_0_prj,
                io_insts_dispatch_0_prk,
  input         io_insts_dispatch_0_rd_valid,
  input  [5:0]  io_insts_dispatch_0_prd,
  input  [31:0] io_insts_dispatch_0_imm,
  input  [4:0]  io_insts_dispatch_0_rob_index,
  input  [3:0]  io_insts_dispatch_0_alu_op,
  input         io_insts_dispatch_0_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_0_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_0_pc,
  input  [5:0]  io_insts_dispatch_1_prj,
                io_insts_dispatch_1_prk,
  input         io_insts_dispatch_1_rd_valid,
  input  [5:0]  io_insts_dispatch_1_prd,
  input  [31:0] io_insts_dispatch_1_imm,
  input  [4:0]  io_insts_dispatch_1_rob_index,
  input  [3:0]  io_insts_dispatch_1_alu_op,
  input         io_insts_dispatch_1_alu_rs1_sel,
  input  [1:0]  io_insts_dispatch_1_alu_rs2_sel,
  input  [31:0] io_insts_dispatch_1_pc,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prk_ready_0,
                io_prk_ready_1,
  input  [5:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
                io_ld_mem_prd,
  input         io_issue_ack_0,
                io_issue_ack_1,
                io_issue_ack_2,
                io_issue_ack_3,
                io_issue_ack_4,
                io_issue_ack_5,
  output [5:0]  io_insts_issue_0_inst_prj,
                io_insts_issue_0_inst_prk,
  output        io_insts_issue_0_inst_rd_valid,
  output [5:0]  io_insts_issue_0_inst_prd,
  output [31:0] io_insts_issue_0_inst_imm,
  output [4:0]  io_insts_issue_0_inst_rob_index,
  output [3:0]  io_insts_issue_0_inst_alu_op,
  output        io_insts_issue_0_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_0_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_0_inst_pc,
  output [5:0]  io_insts_issue_1_inst_prj,
                io_insts_issue_1_inst_prk,
  output        io_insts_issue_1_inst_rd_valid,
  output [5:0]  io_insts_issue_1_inst_prd,
  output [31:0] io_insts_issue_1_inst_imm,
  output [4:0]  io_insts_issue_1_inst_rob_index,
  output [3:0]  io_insts_issue_1_inst_alu_op,
  output        io_insts_issue_1_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_1_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_1_inst_pc,
  output [5:0]  io_insts_issue_2_inst_prj,
                io_insts_issue_2_inst_prk,
  output        io_insts_issue_2_inst_rd_valid,
  output [5:0]  io_insts_issue_2_inst_prd,
  output [31:0] io_insts_issue_2_inst_imm,
  output [4:0]  io_insts_issue_2_inst_rob_index,
  output [3:0]  io_insts_issue_2_inst_alu_op,
  output        io_insts_issue_2_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_2_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_2_inst_pc,
  output [5:0]  io_insts_issue_3_inst_prj,
                io_insts_issue_3_inst_prk,
  output        io_insts_issue_3_inst_rd_valid,
  output [5:0]  io_insts_issue_3_inst_prd,
  output [31:0] io_insts_issue_3_inst_imm,
  output [4:0]  io_insts_issue_3_inst_rob_index,
  output [3:0]  io_insts_issue_3_inst_alu_op,
  output        io_insts_issue_3_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_3_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_3_inst_pc,
  output [5:0]  io_insts_issue_4_inst_prj,
                io_insts_issue_4_inst_prk,
  output        io_insts_issue_4_inst_rd_valid,
  output [5:0]  io_insts_issue_4_inst_prd,
  output [31:0] io_insts_issue_4_inst_imm,
  output [4:0]  io_insts_issue_4_inst_rob_index,
  output [3:0]  io_insts_issue_4_inst_alu_op,
  output        io_insts_issue_4_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_4_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_4_inst_pc,
  output [5:0]  io_insts_issue_5_inst_prj,
                io_insts_issue_5_inst_prk,
  output        io_insts_issue_5_inst_rd_valid,
  output [5:0]  io_insts_issue_5_inst_prd,
  output [31:0] io_insts_issue_5_inst_imm,
  output [4:0]  io_insts_issue_5_inst_rob_index,
  output [3:0]  io_insts_issue_5_inst_alu_op,
  output        io_insts_issue_5_inst_alu_rs1_sel,
  output [1:0]  io_insts_issue_5_inst_alu_rs2_sel,
  output [31:0] io_insts_issue_5_inst_pc,
  output        io_issue_req_0,
                io_issue_req_1,
                io_issue_req_2,
                io_issue_req_3,
                io_issue_req_4,
                io_issue_req_5,
  output [3:0]  io_elem_num,
  output        io_full,
  input         io_stall,
                io_flush,
                io_dcache_miss
);

  reg  [5:0]  queue_0_inst_prj;
  reg  [5:0]  queue_0_inst_prk;
  reg         queue_0_inst_rd_valid;
  reg  [5:0]  queue_0_inst_prd;
  reg  [31:0] queue_0_inst_imm;
  reg  [4:0]  queue_0_inst_rob_index;
  reg  [3:0]  queue_0_inst_alu_op;
  reg         queue_0_inst_alu_rs1_sel;
  reg  [1:0]  queue_0_inst_alu_rs2_sel;
  reg  [31:0] queue_0_inst_pc;
  reg         queue_0_prj_waked;
  reg         queue_0_prk_waked;
  reg         queue_0_prj_wake_by_ld;
  reg         queue_0_prk_wake_by_ld;
  reg  [5:0]  queue_1_inst_prj;
  reg  [5:0]  queue_1_inst_prk;
  reg         queue_1_inst_rd_valid;
  reg  [5:0]  queue_1_inst_prd;
  reg  [31:0] queue_1_inst_imm;
  reg  [4:0]  queue_1_inst_rob_index;
  reg  [3:0]  queue_1_inst_alu_op;
  reg         queue_1_inst_alu_rs1_sel;
  reg  [1:0]  queue_1_inst_alu_rs2_sel;
  reg  [31:0] queue_1_inst_pc;
  reg         queue_1_prj_waked;
  reg         queue_1_prk_waked;
  reg         queue_1_prj_wake_by_ld;
  reg         queue_1_prk_wake_by_ld;
  reg  [5:0]  queue_2_inst_prj;
  reg  [5:0]  queue_2_inst_prk;
  reg         queue_2_inst_rd_valid;
  reg  [5:0]  queue_2_inst_prd;
  reg  [31:0] queue_2_inst_imm;
  reg  [4:0]  queue_2_inst_rob_index;
  reg  [3:0]  queue_2_inst_alu_op;
  reg         queue_2_inst_alu_rs1_sel;
  reg  [1:0]  queue_2_inst_alu_rs2_sel;
  reg  [31:0] queue_2_inst_pc;
  reg         queue_2_prj_waked;
  reg         queue_2_prk_waked;
  reg         queue_2_prj_wake_by_ld;
  reg         queue_2_prk_wake_by_ld;
  reg  [5:0]  queue_3_inst_prj;
  reg  [5:0]  queue_3_inst_prk;
  reg         queue_3_inst_rd_valid;
  reg  [5:0]  queue_3_inst_prd;
  reg  [31:0] queue_3_inst_imm;
  reg  [4:0]  queue_3_inst_rob_index;
  reg  [3:0]  queue_3_inst_alu_op;
  reg         queue_3_inst_alu_rs1_sel;
  reg  [1:0]  queue_3_inst_alu_rs2_sel;
  reg  [31:0] queue_3_inst_pc;
  reg         queue_3_prj_waked;
  reg         queue_3_prk_waked;
  reg         queue_3_prj_wake_by_ld;
  reg         queue_3_prk_wake_by_ld;
  reg  [5:0]  queue_4_inst_prj;
  reg  [5:0]  queue_4_inst_prk;
  reg         queue_4_inst_rd_valid;
  reg  [5:0]  queue_4_inst_prd;
  reg  [31:0] queue_4_inst_imm;
  reg  [4:0]  queue_4_inst_rob_index;
  reg  [3:0]  queue_4_inst_alu_op;
  reg         queue_4_inst_alu_rs1_sel;
  reg  [1:0]  queue_4_inst_alu_rs2_sel;
  reg  [31:0] queue_4_inst_pc;
  reg         queue_4_prj_waked;
  reg         queue_4_prk_waked;
  reg         queue_4_prj_wake_by_ld;
  reg         queue_4_prk_wake_by_ld;
  reg  [5:0]  queue_5_inst_prj;
  reg  [5:0]  queue_5_inst_prk;
  reg         queue_5_inst_rd_valid;
  reg  [5:0]  queue_5_inst_prd;
  reg  [31:0] queue_5_inst_imm;
  reg  [4:0]  queue_5_inst_rob_index;
  reg  [3:0]  queue_5_inst_alu_op;
  reg         queue_5_inst_alu_rs1_sel;
  reg  [1:0]  queue_5_inst_alu_rs2_sel;
  reg  [31:0] queue_5_inst_pc;
  reg         queue_5_prj_waked;
  reg         queue_5_prk_waked;
  reg         queue_5_prj_wake_by_ld;
  reg         queue_5_prk_wake_by_ld;
  reg  [3:0]  tail;
  reg  [5:0]  qmask;
  wire [1:0]  insert_num =
    2'({1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1});
  wire [1:0]  _tail_T = qmask[4] ? 2'h0 : insert_num;
  wire [3:0]  _tail_pop_T_2 =
    4'(tail
       - {3'h0,
          |{io_issue_ack_5,
            io_issue_ack_4,
            io_issue_ack_3,
            io_issue_ack_2,
            io_issue_ack_1,
            io_issue_ack_0}});
  wire [5:0]  _qmask_pop_T =
    {io_issue_ack_5,
     io_issue_ack_4,
     io_issue_ack_3,
     io_issue_ack_2,
     io_issue_ack_1,
     io_issue_ack_0};
  wire [5:0]  _qmask_pop_T_3 = {1'h0, qmask[5:1]};
  wire [5:0]  qmask_pop = (|_qmask_pop_T) ? _qmask_pop_T_3 : qmask;
  wire [4:0]  next_mask =
    ~(5'({io_issue_ack_4, io_issue_ack_3, io_issue_ack_2, io_issue_ack_1, io_issue_ack_0}
         - 5'h1));
  wire        _GEN = 1'(1'h0 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_0 = _GEN ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_1 = _GEN ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_1_inst_prj =
    next_mask[0] ? queue_1_inst_prj : queue_0_inst_prj;
  wire [5:0]  queue_next_inst_prj = qmask_pop[0] ? _queue_next_T_1_inst_prj : _GEN_0;
  wire [5:0]  _queue_next_T_1_inst_prk =
    next_mask[0] ? queue_1_inst_prk : queue_0_inst_prk;
  wire [5:0]  queue_next_inst_prk = qmask_pop[0] ? _queue_next_T_1_inst_prk : _GEN_1;
  wire [5:0]  _queue_0_prj_wake_by_ld_T = queue_next_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_0_prk_wake_by_ld_T = queue_next_inst_prk ^ io_wake_preg_3;
  wire        _GEN_2 = 1'(1'h1 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_3 = _GEN_2 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_4 = _GEN_2 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_3_inst_prj =
    next_mask[1] ? queue_2_inst_prj : queue_1_inst_prj;
  wire [5:0]  queue_next_1_inst_prj = qmask_pop[1] ? _queue_next_T_3_inst_prj : _GEN_3;
  wire [5:0]  _queue_next_T_3_inst_prk =
    next_mask[1] ? queue_2_inst_prk : queue_1_inst_prk;
  wire [5:0]  queue_next_1_inst_prk = qmask_pop[1] ? _queue_next_T_3_inst_prk : _GEN_4;
  wire [5:0]  _queue_1_prj_wake_by_ld_T = queue_next_1_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_1_prk_wake_by_ld_T = queue_next_1_inst_prk ^ io_wake_preg_3;
  wire        _GEN_5 = 1'(1'h0 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_6 = _GEN_5 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_7 = _GEN_5 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_5_inst_prj =
    next_mask[2] ? queue_3_inst_prj : queue_2_inst_prj;
  wire [5:0]  queue_next_2_inst_prj = qmask_pop[2] ? _queue_next_T_5_inst_prj : _GEN_6;
  wire [5:0]  _queue_next_T_5_inst_prk =
    next_mask[2] ? queue_3_inst_prk : queue_2_inst_prk;
  wire [5:0]  queue_next_2_inst_prk = qmask_pop[2] ? _queue_next_T_5_inst_prk : _GEN_7;
  wire [5:0]  _queue_2_prj_wake_by_ld_T = queue_next_2_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_2_prk_wake_by_ld_T = queue_next_2_inst_prk ^ io_wake_preg_3;
  wire        _GEN_8 = 1'(1'h1 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_9 = _GEN_8 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_10 = _GEN_8 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_7_inst_prj =
    next_mask[3] ? queue_4_inst_prj : queue_3_inst_prj;
  wire [5:0]  queue_next_3_inst_prj = qmask_pop[3] ? _queue_next_T_7_inst_prj : _GEN_9;
  wire [5:0]  _queue_next_T_7_inst_prk =
    next_mask[3] ? queue_4_inst_prk : queue_3_inst_prk;
  wire [5:0]  queue_next_3_inst_prk = qmask_pop[3] ? _queue_next_T_7_inst_prk : _GEN_10;
  wire [5:0]  _queue_3_prj_wake_by_ld_T = queue_next_3_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_3_prk_wake_by_ld_T = queue_next_3_inst_prk ^ io_wake_preg_3;
  wire        _GEN_11 = 1'(1'h0 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_12 = _GEN_11 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_13 = _GEN_11 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  _queue_next_T_9_inst_prj =
    next_mask[4] ? queue_5_inst_prj : queue_4_inst_prj;
  wire [5:0]  queue_next_4_inst_prj = qmask_pop[4] ? _queue_next_T_9_inst_prj : _GEN_12;
  wire [5:0]  _queue_next_T_9_inst_prk =
    next_mask[4] ? queue_5_inst_prk : queue_4_inst_prk;
  wire [5:0]  queue_next_4_inst_prk = qmask_pop[4] ? _queue_next_T_9_inst_prk : _GEN_13;
  wire [5:0]  _queue_4_prj_wake_by_ld_T = queue_next_4_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_4_prk_wake_by_ld_T = queue_next_4_inst_prk ^ io_wake_preg_3;
  wire        _GEN_14 = 1'(1'h1 - _tail_pop_T_2[0]) | io_insts_disp_index_0;
  wire [5:0]  _GEN_15 = _GEN_14 ? io_insts_dispatch_1_prj : io_insts_dispatch_0_prj;
  wire [5:0]  _GEN_16 = _GEN_14 ? io_insts_dispatch_1_prk : io_insts_dispatch_0_prk;
  wire [5:0]  queue_next_5_inst_prj = qmask_pop[5] ? queue_5_inst_prj : _GEN_15;
  wire [5:0]  queue_next_5_inst_prk = qmask_pop[5] ? queue_5_inst_prk : _GEN_16;
  wire [5:0]  _queue_5_prj_wake_by_ld_T = queue_next_5_inst_prj ^ io_wake_preg_3;
  wire [5:0]  _queue_5_prk_wake_by_ld_T = queue_next_5_inst_prk ^ io_wake_preg_3;
  wire        _GEN_17 = _GEN ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_1_prj_waked =
    next_mask[0] ? queue_1_prj_waked : queue_0_prj_waked;
  wire        queue_next_prj_waked = qmask_pop[0] ? _queue_next_T_1_prj_waked : _GEN_17;
  wire        _GEN_18 = _GEN ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_1_prk_waked =
    next_mask[0] ? queue_1_prk_waked : queue_0_prk_waked;
  wire        queue_next_prk_waked = qmask_pop[0] ? _queue_next_T_1_prk_waked : _GEN_18;
  wire        _queue_next_T_1_prj_wake_by_ld =
    next_mask[0] ? queue_1_prj_wake_by_ld : queue_0_prj_wake_by_ld;
  wire        queue_next_prj_wake_by_ld =
    qmask_pop[0]
      ? _queue_next_T_1_prj_wake_by_ld
      : (_GEN_0 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_1_prk_wake_by_ld =
    next_mask[0] ? queue_1_prk_wake_by_ld : queue_0_prk_wake_by_ld;
  wire        queue_next_prk_wake_by_ld =
    qmask_pop[0]
      ? _queue_next_T_1_prk_wake_by_ld
      : (_GEN_1 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _GEN_19 = _GEN_2 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_3_prj_waked =
    next_mask[1] ? queue_2_prj_waked : queue_1_prj_waked;
  wire        queue_next_1_prj_waked = qmask_pop[1] ? _queue_next_T_3_prj_waked : _GEN_19;
  wire        _GEN_20 = _GEN_2 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_3_prk_waked =
    next_mask[1] ? queue_2_prk_waked : queue_1_prk_waked;
  wire        queue_next_1_prk_waked = qmask_pop[1] ? _queue_next_T_3_prk_waked : _GEN_20;
  wire        _queue_next_T_3_prj_wake_by_ld =
    next_mask[1] ? queue_2_prj_wake_by_ld : queue_1_prj_wake_by_ld;
  wire        queue_next_1_prj_wake_by_ld =
    qmask_pop[1]
      ? _queue_next_T_3_prj_wake_by_ld
      : (_GEN_3 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_3_prk_wake_by_ld =
    next_mask[1] ? queue_2_prk_wake_by_ld : queue_1_prk_wake_by_ld;
  wire        queue_next_1_prk_wake_by_ld =
    qmask_pop[1]
      ? _queue_next_T_3_prk_wake_by_ld
      : (_GEN_4 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _GEN_21 = _GEN_5 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_5_prj_waked =
    next_mask[2] ? queue_3_prj_waked : queue_2_prj_waked;
  wire        queue_next_2_prj_waked = qmask_pop[2] ? _queue_next_T_5_prj_waked : _GEN_21;
  wire        _GEN_22 = _GEN_5 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_5_prk_waked =
    next_mask[2] ? queue_3_prk_waked : queue_2_prk_waked;
  wire        queue_next_2_prk_waked = qmask_pop[2] ? _queue_next_T_5_prk_waked : _GEN_22;
  wire        _queue_next_T_5_prj_wake_by_ld =
    next_mask[2] ? queue_3_prj_wake_by_ld : queue_2_prj_wake_by_ld;
  wire        queue_next_2_prj_wake_by_ld =
    qmask_pop[2]
      ? _queue_next_T_5_prj_wake_by_ld
      : (_GEN_6 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_5_prk_wake_by_ld =
    next_mask[2] ? queue_3_prk_wake_by_ld : queue_2_prk_wake_by_ld;
  wire        queue_next_2_prk_wake_by_ld =
    qmask_pop[2]
      ? _queue_next_T_5_prk_wake_by_ld
      : (_GEN_7 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _GEN_23 = _GEN_8 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_7_prj_waked =
    next_mask[3] ? queue_4_prj_waked : queue_3_prj_waked;
  wire        queue_next_3_prj_waked = qmask_pop[3] ? _queue_next_T_7_prj_waked : _GEN_23;
  wire        _GEN_24 = _GEN_8 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_7_prk_waked =
    next_mask[3] ? queue_4_prk_waked : queue_3_prk_waked;
  wire        queue_next_3_prk_waked = qmask_pop[3] ? _queue_next_T_7_prk_waked : _GEN_24;
  wire        _queue_next_T_7_prj_wake_by_ld =
    next_mask[3] ? queue_4_prj_wake_by_ld : queue_3_prj_wake_by_ld;
  wire        queue_next_3_prj_wake_by_ld =
    qmask_pop[3]
      ? _queue_next_T_7_prj_wake_by_ld
      : (_GEN_9 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_7_prk_wake_by_ld =
    next_mask[3] ? queue_4_prk_wake_by_ld : queue_3_prk_wake_by_ld;
  wire        queue_next_3_prk_wake_by_ld =
    qmask_pop[3]
      ? _queue_next_T_7_prk_wake_by_ld
      : (_GEN_10 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _GEN_25 = _GEN_11 ? io_prj_ready_1 : io_prj_ready_0;
  wire        _queue_next_T_9_prj_waked =
    next_mask[4] ? queue_5_prj_waked : queue_4_prj_waked;
  wire        queue_next_4_prj_waked = qmask_pop[4] ? _queue_next_T_9_prj_waked : _GEN_25;
  wire        _GEN_26 = _GEN_11 ? io_prk_ready_1 : io_prk_ready_0;
  wire        _queue_next_T_9_prk_waked =
    next_mask[4] ? queue_5_prk_waked : queue_4_prk_waked;
  wire        queue_next_4_prk_waked = qmask_pop[4] ? _queue_next_T_9_prk_waked : _GEN_26;
  wire        _queue_next_T_9_prj_wake_by_ld =
    next_mask[4] ? queue_5_prj_wake_by_ld : queue_4_prj_wake_by_ld;
  wire        queue_next_4_prj_wake_by_ld =
    qmask_pop[4]
      ? _queue_next_T_9_prj_wake_by_ld
      : (_GEN_12 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _queue_next_T_9_prk_wake_by_ld =
    next_mask[4] ? queue_5_prk_wake_by_ld : queue_4_prk_wake_by_ld;
  wire        queue_next_4_prk_wake_by_ld =
    qmask_pop[4]
      ? _queue_next_T_9_prk_wake_by_ld
      : (_GEN_13 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        _GEN_27 = _GEN_14 ? io_prj_ready_1 : io_prj_ready_0;
  wire        queue_next_5_prj_waked = qmask_pop[5] ? queue_5_prj_waked : _GEN_27;
  wire        _GEN_28 = _GEN_14 ? io_prk_ready_1 : io_prk_ready_0;
  wire        queue_next_5_prk_waked = qmask_pop[5] ? queue_5_prk_waked : _GEN_28;
  wire        queue_next_5_prj_wake_by_ld =
    qmask_pop[5]
      ? queue_5_prj_wake_by_ld
      : (_GEN_15 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  wire        queue_next_5_prk_wake_by_ld =
    qmask_pop[5]
      ? queue_5_prk_wake_by_ld
      : (_GEN_16 ^ io_ld_mem_prd) == 6'h0 & (|io_ld_mem_prd);
  always @(posedge clock) begin
    if (reset) begin
      queue_0_inst_prj <= 6'h0;
      queue_0_inst_prk <= 6'h0;
      queue_0_inst_rd_valid <= 1'h0;
      queue_0_inst_prd <= 6'h0;
      queue_0_inst_imm <= 32'h0;
      queue_0_inst_rob_index <= 5'h0;
      queue_0_inst_alu_op <= 4'h0;
      queue_0_inst_alu_rs1_sel <= 1'h0;
      queue_0_inst_alu_rs2_sel <= 2'h0;
      queue_0_inst_pc <= 32'h0;
      queue_0_prj_waked <= 1'h0;
      queue_0_prk_waked <= 1'h0;
      queue_0_prj_wake_by_ld <= 1'h0;
      queue_0_prk_wake_by_ld <= 1'h0;
      queue_1_inst_prj <= 6'h0;
      queue_1_inst_prk <= 6'h0;
      queue_1_inst_rd_valid <= 1'h0;
      queue_1_inst_prd <= 6'h0;
      queue_1_inst_imm <= 32'h0;
      queue_1_inst_rob_index <= 5'h0;
      queue_1_inst_alu_op <= 4'h0;
      queue_1_inst_alu_rs1_sel <= 1'h0;
      queue_1_inst_alu_rs2_sel <= 2'h0;
      queue_1_inst_pc <= 32'h0;
      queue_1_prj_waked <= 1'h0;
      queue_1_prk_waked <= 1'h0;
      queue_1_prj_wake_by_ld <= 1'h0;
      queue_1_prk_wake_by_ld <= 1'h0;
      queue_2_inst_prj <= 6'h0;
      queue_2_inst_prk <= 6'h0;
      queue_2_inst_rd_valid <= 1'h0;
      queue_2_inst_prd <= 6'h0;
      queue_2_inst_imm <= 32'h0;
      queue_2_inst_rob_index <= 5'h0;
      queue_2_inst_alu_op <= 4'h0;
      queue_2_inst_alu_rs1_sel <= 1'h0;
      queue_2_inst_alu_rs2_sel <= 2'h0;
      queue_2_inst_pc <= 32'h0;
      queue_2_prj_waked <= 1'h0;
      queue_2_prk_waked <= 1'h0;
      queue_2_prj_wake_by_ld <= 1'h0;
      queue_2_prk_wake_by_ld <= 1'h0;
      queue_3_inst_prj <= 6'h0;
      queue_3_inst_prk <= 6'h0;
      queue_3_inst_rd_valid <= 1'h0;
      queue_3_inst_prd <= 6'h0;
      queue_3_inst_imm <= 32'h0;
      queue_3_inst_rob_index <= 5'h0;
      queue_3_inst_alu_op <= 4'h0;
      queue_3_inst_alu_rs1_sel <= 1'h0;
      queue_3_inst_alu_rs2_sel <= 2'h0;
      queue_3_inst_pc <= 32'h0;
      queue_3_prj_waked <= 1'h0;
      queue_3_prk_waked <= 1'h0;
      queue_3_prj_wake_by_ld <= 1'h0;
      queue_3_prk_wake_by_ld <= 1'h0;
      queue_4_inst_prj <= 6'h0;
      queue_4_inst_prk <= 6'h0;
      queue_4_inst_rd_valid <= 1'h0;
      queue_4_inst_prd <= 6'h0;
      queue_4_inst_imm <= 32'h0;
      queue_4_inst_rob_index <= 5'h0;
      queue_4_inst_alu_op <= 4'h0;
      queue_4_inst_alu_rs1_sel <= 1'h0;
      queue_4_inst_alu_rs2_sel <= 2'h0;
      queue_4_inst_pc <= 32'h0;
      queue_4_prj_waked <= 1'h0;
      queue_4_prk_waked <= 1'h0;
      queue_4_prj_wake_by_ld <= 1'h0;
      queue_4_prk_wake_by_ld <= 1'h0;
      queue_5_inst_prj <= 6'h0;
      queue_5_inst_prk <= 6'h0;
      queue_5_inst_rd_valid <= 1'h0;
      queue_5_inst_prd <= 6'h0;
      queue_5_inst_imm <= 32'h0;
      queue_5_inst_rob_index <= 5'h0;
      queue_5_inst_alu_op <= 4'h0;
      queue_5_inst_alu_rs1_sel <= 1'h0;
      queue_5_inst_alu_rs2_sel <= 2'h0;
      queue_5_inst_pc <= 32'h0;
      queue_5_prj_waked <= 1'h0;
      queue_5_prk_waked <= 1'h0;
      queue_5_prj_wake_by_ld <= 1'h0;
      queue_5_prk_wake_by_ld <= 1'h0;
      tail <= 4'h0;
      qmask <= 6'h0;
    end
    else begin
      if (qmask_pop[0]) begin
        if (next_mask[0]) begin
          queue_0_inst_prj <= queue_1_inst_prj;
          queue_0_inst_prk <= queue_1_inst_prk;
          queue_0_inst_rd_valid <= queue_1_inst_rd_valid;
          queue_0_inst_prd <= queue_1_inst_prd;
          queue_0_inst_imm <= queue_1_inst_imm;
          queue_0_inst_rob_index <= queue_1_inst_rob_index;
          queue_0_inst_alu_op <= queue_1_inst_alu_op;
          queue_0_inst_alu_rs1_sel <= queue_1_inst_alu_rs1_sel;
          queue_0_inst_alu_rs2_sel <= queue_1_inst_alu_rs2_sel;
          queue_0_inst_pc <= queue_1_inst_pc;
        end
      end
      else begin
        queue_0_inst_prj <= _GEN_0;
        queue_0_inst_prk <= _GEN_1;
        queue_0_inst_rd_valid <=
          _GEN ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_0_inst_prd <= _GEN ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_0_inst_imm <= _GEN ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_0_inst_rob_index <=
          _GEN ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_0_inst_alu_op <=
          _GEN ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_0_inst_alu_rs1_sel <=
          _GEN ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_0_inst_alu_rs2_sel <=
          _GEN ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_0_inst_pc <= _GEN ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_0_prj_waked <=
        queue_next_prj_waked
        | (|{~(|_queue_0_prj_wake_by_ld_T),
             (queue_next_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_0_prk_waked <=
        queue_next_prk_waked
        | (|{~(|_queue_0_prk_wake_by_ld_T),
             (queue_next_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_0_prj_wake_by_ld <=
        ~(|_queue_0_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prj_wake_by_ld;
      queue_0_prk_wake_by_ld <=
        ~(|_queue_0_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_prk_wake_by_ld;
      if (qmask_pop[1]) begin
        if (next_mask[1]) begin
          queue_1_inst_prj <= queue_2_inst_prj;
          queue_1_inst_prk <= queue_2_inst_prk;
          queue_1_inst_rd_valid <= queue_2_inst_rd_valid;
          queue_1_inst_prd <= queue_2_inst_prd;
          queue_1_inst_imm <= queue_2_inst_imm;
          queue_1_inst_rob_index <= queue_2_inst_rob_index;
          queue_1_inst_alu_op <= queue_2_inst_alu_op;
          queue_1_inst_alu_rs1_sel <= queue_2_inst_alu_rs1_sel;
          queue_1_inst_alu_rs2_sel <= queue_2_inst_alu_rs2_sel;
          queue_1_inst_pc <= queue_2_inst_pc;
        end
      end
      else begin
        queue_1_inst_prj <= _GEN_3;
        queue_1_inst_prk <= _GEN_4;
        queue_1_inst_rd_valid <=
          _GEN_2 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_1_inst_prd <= _GEN_2 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_1_inst_imm <= _GEN_2 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_1_inst_rob_index <=
          _GEN_2 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_1_inst_alu_op <=
          _GEN_2 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_1_inst_alu_rs1_sel <=
          _GEN_2 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_1_inst_alu_rs2_sel <=
          _GEN_2 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_1_inst_pc <= _GEN_2 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_1_prj_waked <=
        queue_next_1_prj_waked
        | (|{~(|_queue_1_prj_wake_by_ld_T),
             (queue_next_1_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_1_prk_waked <=
        queue_next_1_prk_waked
        | (|{~(|_queue_1_prk_wake_by_ld_T),
             (queue_next_1_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_1_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_1_prj_wake_by_ld <=
        ~(|_queue_1_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prj_wake_by_ld;
      queue_1_prk_wake_by_ld <=
        ~(|_queue_1_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_1_prk_wake_by_ld;
      if (qmask_pop[2]) begin
        if (next_mask[2]) begin
          queue_2_inst_prj <= queue_3_inst_prj;
          queue_2_inst_prk <= queue_3_inst_prk;
          queue_2_inst_rd_valid <= queue_3_inst_rd_valid;
          queue_2_inst_prd <= queue_3_inst_prd;
          queue_2_inst_imm <= queue_3_inst_imm;
          queue_2_inst_rob_index <= queue_3_inst_rob_index;
          queue_2_inst_alu_op <= queue_3_inst_alu_op;
          queue_2_inst_alu_rs1_sel <= queue_3_inst_alu_rs1_sel;
          queue_2_inst_alu_rs2_sel <= queue_3_inst_alu_rs2_sel;
          queue_2_inst_pc <= queue_3_inst_pc;
        end
      end
      else begin
        queue_2_inst_prj <= _GEN_6;
        queue_2_inst_prk <= _GEN_7;
        queue_2_inst_rd_valid <=
          _GEN_5 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_2_inst_prd <= _GEN_5 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_2_inst_imm <= _GEN_5 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_2_inst_rob_index <=
          _GEN_5 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_2_inst_alu_op <=
          _GEN_5 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_2_inst_alu_rs1_sel <=
          _GEN_5 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_2_inst_alu_rs2_sel <=
          _GEN_5 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_2_inst_pc <= _GEN_5 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_2_prj_waked <=
        queue_next_2_prj_waked
        | (|{~(|_queue_2_prj_wake_by_ld_T),
             (queue_next_2_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_2_prk_waked <=
        queue_next_2_prk_waked
        | (|{~(|_queue_2_prk_wake_by_ld_T),
             (queue_next_2_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_2_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_2_prj_wake_by_ld <=
        ~(|_queue_2_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prj_wake_by_ld;
      queue_2_prk_wake_by_ld <=
        ~(|_queue_2_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_2_prk_wake_by_ld;
      if (qmask_pop[3]) begin
        if (next_mask[3]) begin
          queue_3_inst_prj <= queue_4_inst_prj;
          queue_3_inst_prk <= queue_4_inst_prk;
          queue_3_inst_rd_valid <= queue_4_inst_rd_valid;
          queue_3_inst_prd <= queue_4_inst_prd;
          queue_3_inst_imm <= queue_4_inst_imm;
          queue_3_inst_rob_index <= queue_4_inst_rob_index;
          queue_3_inst_alu_op <= queue_4_inst_alu_op;
          queue_3_inst_alu_rs1_sel <= queue_4_inst_alu_rs1_sel;
          queue_3_inst_alu_rs2_sel <= queue_4_inst_alu_rs2_sel;
          queue_3_inst_pc <= queue_4_inst_pc;
        end
      end
      else begin
        queue_3_inst_prj <= _GEN_9;
        queue_3_inst_prk <= _GEN_10;
        queue_3_inst_rd_valid <=
          _GEN_8 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_3_inst_prd <= _GEN_8 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_3_inst_imm <= _GEN_8 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_3_inst_rob_index <=
          _GEN_8 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_3_inst_alu_op <=
          _GEN_8 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_3_inst_alu_rs1_sel <=
          _GEN_8 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_3_inst_alu_rs2_sel <=
          _GEN_8 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_3_inst_pc <= _GEN_8 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_3_prj_waked <=
        queue_next_3_prj_waked
        | (|{~(|_queue_3_prj_wake_by_ld_T),
             (queue_next_3_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_3_prk_waked <=
        queue_next_3_prk_waked
        | (|{~(|_queue_3_prk_wake_by_ld_T),
             (queue_next_3_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_3_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_3_prj_wake_by_ld <=
        ~(|_queue_3_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prj_wake_by_ld;
      queue_3_prk_wake_by_ld <=
        ~(|_queue_3_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_3_prk_wake_by_ld;
      if (qmask_pop[4]) begin
        if (next_mask[4]) begin
          queue_4_inst_prj <= queue_5_inst_prj;
          queue_4_inst_prk <= queue_5_inst_prk;
          queue_4_inst_rd_valid <= queue_5_inst_rd_valid;
          queue_4_inst_prd <= queue_5_inst_prd;
          queue_4_inst_imm <= queue_5_inst_imm;
          queue_4_inst_rob_index <= queue_5_inst_rob_index;
          queue_4_inst_alu_op <= queue_5_inst_alu_op;
          queue_4_inst_alu_rs1_sel <= queue_5_inst_alu_rs1_sel;
          queue_4_inst_alu_rs2_sel <= queue_5_inst_alu_rs2_sel;
          queue_4_inst_pc <= queue_5_inst_pc;
        end
      end
      else begin
        queue_4_inst_prj <= _GEN_12;
        queue_4_inst_prk <= _GEN_13;
        queue_4_inst_rd_valid <=
          _GEN_11 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_4_inst_prd <= _GEN_11 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_4_inst_imm <= _GEN_11 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_4_inst_rob_index <=
          _GEN_11 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_4_inst_alu_op <=
          _GEN_11 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_4_inst_alu_rs1_sel <=
          _GEN_11 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_4_inst_alu_rs2_sel <=
          _GEN_11 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_4_inst_pc <= _GEN_11 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_4_prj_waked <=
        queue_next_4_prj_waked
        | (|{~(|_queue_4_prj_wake_by_ld_T),
             (queue_next_4_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_4_prk_waked <=
        queue_next_4_prk_waked
        | (|{~(|_queue_4_prk_wake_by_ld_T),
             (queue_next_4_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_4_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_4_prj_wake_by_ld <=
        ~(|_queue_4_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_4_prj_wake_by_ld;
      queue_4_prk_wake_by_ld <=
        ~(|_queue_4_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_4_prk_wake_by_ld;
      if (qmask_pop[5]) begin
      end
      else begin
        queue_5_inst_prj <= _GEN_15;
        queue_5_inst_prk <= _GEN_16;
        queue_5_inst_rd_valid <=
          _GEN_14 ? io_insts_dispatch_1_rd_valid : io_insts_dispatch_0_rd_valid;
        queue_5_inst_prd <= _GEN_14 ? io_insts_dispatch_1_prd : io_insts_dispatch_0_prd;
        queue_5_inst_imm <= _GEN_14 ? io_insts_dispatch_1_imm : io_insts_dispatch_0_imm;
        queue_5_inst_rob_index <=
          _GEN_14 ? io_insts_dispatch_1_rob_index : io_insts_dispatch_0_rob_index;
        queue_5_inst_alu_op <=
          _GEN_14 ? io_insts_dispatch_1_alu_op : io_insts_dispatch_0_alu_op;
        queue_5_inst_alu_rs1_sel <=
          _GEN_14 ? io_insts_dispatch_1_alu_rs1_sel : io_insts_dispatch_0_alu_rs1_sel;
        queue_5_inst_alu_rs2_sel <=
          _GEN_14 ? io_insts_dispatch_1_alu_rs2_sel : io_insts_dispatch_0_alu_rs2_sel;
        queue_5_inst_pc <= _GEN_14 ? io_insts_dispatch_1_pc : io_insts_dispatch_0_pc;
      end
      queue_5_prj_waked <=
        queue_next_5_prj_waked
        | (|{~(|_queue_5_prj_wake_by_ld_T),
             (queue_next_5_inst_prj ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prj ^ io_wake_preg_0) == 6'h0});
      queue_5_prk_waked <=
        queue_next_5_prk_waked
        | (|{~(|_queue_5_prk_wake_by_ld_T),
             (queue_next_5_inst_prk ^ io_wake_preg_2) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_1) == 6'h0,
             (queue_next_5_inst_prk ^ io_wake_preg_0) == 6'h0});
      queue_5_prj_wake_by_ld <=
        ~(|_queue_5_prj_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_5_prj_wake_by_ld;
      queue_5_prk_wake_by_ld <=
        ~(|_queue_5_prk_wake_by_ld_T) & (|io_wake_preg_3) | queue_next_5_prk_wake_by_ld;
      if (io_flush) begin
        tail <= 4'h0;
        qmask <= 6'h0;
      end
      else if (io_stall) begin
        tail <= _tail_pop_T_2;
        if (|_qmask_pop_T)
          qmask <= _qmask_pop_T_3;
      end
      else begin
        tail <= 4'(_tail_pop_T_2 + {2'h0, _tail_T});
        if (insert_num == 2'h2)
          qmask <= {qmask_pop[3:0], 2'h3};
        else if (insert_num == 2'h1)
          qmask <= {qmask_pop[4:0], 1'h1};
        else if (|_qmask_pop_T)
          qmask <= _qmask_pop_T_3;
      end
    end
  end // always @(posedge)
  assign io_insts_issue_0_inst_prj = queue_0_inst_prj;
  assign io_insts_issue_0_inst_prk = queue_0_inst_prk;
  assign io_insts_issue_0_inst_rd_valid = queue_0_inst_rd_valid;
  assign io_insts_issue_0_inst_prd = queue_0_inst_prd;
  assign io_insts_issue_0_inst_imm = queue_0_inst_imm;
  assign io_insts_issue_0_inst_rob_index = queue_0_inst_rob_index;
  assign io_insts_issue_0_inst_alu_op = queue_0_inst_alu_op;
  assign io_insts_issue_0_inst_alu_rs1_sel = queue_0_inst_alu_rs1_sel;
  assign io_insts_issue_0_inst_alu_rs2_sel = queue_0_inst_alu_rs2_sel;
  assign io_insts_issue_0_inst_pc = queue_0_inst_pc;
  assign io_insts_issue_1_inst_prj = queue_1_inst_prj;
  assign io_insts_issue_1_inst_prk = queue_1_inst_prk;
  assign io_insts_issue_1_inst_rd_valid = queue_1_inst_rd_valid;
  assign io_insts_issue_1_inst_prd = queue_1_inst_prd;
  assign io_insts_issue_1_inst_imm = queue_1_inst_imm;
  assign io_insts_issue_1_inst_rob_index = queue_1_inst_rob_index;
  assign io_insts_issue_1_inst_alu_op = queue_1_inst_alu_op;
  assign io_insts_issue_1_inst_alu_rs1_sel = queue_1_inst_alu_rs1_sel;
  assign io_insts_issue_1_inst_alu_rs2_sel = queue_1_inst_alu_rs2_sel;
  assign io_insts_issue_1_inst_pc = queue_1_inst_pc;
  assign io_insts_issue_2_inst_prj = queue_2_inst_prj;
  assign io_insts_issue_2_inst_prk = queue_2_inst_prk;
  assign io_insts_issue_2_inst_rd_valid = queue_2_inst_rd_valid;
  assign io_insts_issue_2_inst_prd = queue_2_inst_prd;
  assign io_insts_issue_2_inst_imm = queue_2_inst_imm;
  assign io_insts_issue_2_inst_rob_index = queue_2_inst_rob_index;
  assign io_insts_issue_2_inst_alu_op = queue_2_inst_alu_op;
  assign io_insts_issue_2_inst_alu_rs1_sel = queue_2_inst_alu_rs1_sel;
  assign io_insts_issue_2_inst_alu_rs2_sel = queue_2_inst_alu_rs2_sel;
  assign io_insts_issue_2_inst_pc = queue_2_inst_pc;
  assign io_insts_issue_3_inst_prj = queue_3_inst_prj;
  assign io_insts_issue_3_inst_prk = queue_3_inst_prk;
  assign io_insts_issue_3_inst_rd_valid = queue_3_inst_rd_valid;
  assign io_insts_issue_3_inst_prd = queue_3_inst_prd;
  assign io_insts_issue_3_inst_imm = queue_3_inst_imm;
  assign io_insts_issue_3_inst_rob_index = queue_3_inst_rob_index;
  assign io_insts_issue_3_inst_alu_op = queue_3_inst_alu_op;
  assign io_insts_issue_3_inst_alu_rs1_sel = queue_3_inst_alu_rs1_sel;
  assign io_insts_issue_3_inst_alu_rs2_sel = queue_3_inst_alu_rs2_sel;
  assign io_insts_issue_3_inst_pc = queue_3_inst_pc;
  assign io_insts_issue_4_inst_prj = queue_4_inst_prj;
  assign io_insts_issue_4_inst_prk = queue_4_inst_prk;
  assign io_insts_issue_4_inst_rd_valid = queue_4_inst_rd_valid;
  assign io_insts_issue_4_inst_prd = queue_4_inst_prd;
  assign io_insts_issue_4_inst_imm = queue_4_inst_imm;
  assign io_insts_issue_4_inst_rob_index = queue_4_inst_rob_index;
  assign io_insts_issue_4_inst_alu_op = queue_4_inst_alu_op;
  assign io_insts_issue_4_inst_alu_rs1_sel = queue_4_inst_alu_rs1_sel;
  assign io_insts_issue_4_inst_alu_rs2_sel = queue_4_inst_alu_rs2_sel;
  assign io_insts_issue_4_inst_pc = queue_4_inst_pc;
  assign io_insts_issue_5_inst_prj = queue_5_inst_prj;
  assign io_insts_issue_5_inst_prk = queue_5_inst_prk;
  assign io_insts_issue_5_inst_rd_valid = queue_5_inst_rd_valid;
  assign io_insts_issue_5_inst_prd = queue_5_inst_prd;
  assign io_insts_issue_5_inst_imm = queue_5_inst_imm;
  assign io_insts_issue_5_inst_rob_index = queue_5_inst_rob_index;
  assign io_insts_issue_5_inst_alu_op = queue_5_inst_alu_op;
  assign io_insts_issue_5_inst_alu_rs1_sel = queue_5_inst_alu_rs1_sel;
  assign io_insts_issue_5_inst_alu_rs2_sel = queue_5_inst_alu_rs2_sel;
  assign io_insts_issue_5_inst_pc = queue_5_inst_pc;
  assign io_issue_req_0 =
    qmask[0] & queue_0_prj_waked & queue_0_prk_waked
    & ~((queue_0_prj_wake_by_ld & (queue_0_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_0_prk_wake_by_ld & (queue_0_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_1 =
    qmask[1] & queue_1_prj_waked & queue_1_prk_waked
    & ~((queue_1_prj_wake_by_ld & (queue_1_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_1_prk_wake_by_ld & (queue_1_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_2 =
    qmask[2] & queue_2_prj_waked & queue_2_prk_waked
    & ~((queue_2_prj_wake_by_ld & (queue_2_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_2_prk_wake_by_ld & (queue_2_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_3 =
    qmask[3] & queue_3_prj_waked & queue_3_prk_waked
    & ~((queue_3_prj_wake_by_ld & (queue_3_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_3_prk_wake_by_ld & (queue_3_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_4 =
    qmask[4] & queue_4_prj_waked & queue_4_prk_waked
    & ~((queue_4_prj_wake_by_ld & (queue_4_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_4_prk_wake_by_ld & (queue_4_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_issue_req_5 =
    qmask[5] & queue_5_prj_waked & queue_5_prk_waked
    & ~((queue_5_prj_wake_by_ld & (queue_5_inst_prj ^ io_ld_mem_prd) == 6'h0
         | queue_5_prk_wake_by_ld & (queue_5_inst_prk ^ io_ld_mem_prd) == 6'h0)
        & io_dcache_miss);
  assign io_elem_num = tail;
  assign io_full = qmask[4];
endmodule

